In [1]:
import pandas as pd
import os
import numpy as np

# Constants

In [2]:
str_project = os.getcwd().split('\\')[4]
print(str_project)
str_task = os.getcwd().split('\\')[5]
print(str_task)
str_subtask = os.getcwd().split('\\')[6]
print(str_subtask)

str_dirname_output = './output'

06_ml_in_python
03_homecredit_default_risk_model
02_data_exploration

In [3]:
os.getcwd()

'M:\\Risk Management\\Bridger Hyde\\20240521_bridger_internship\\06_ml_in_python\\03_homecredit_default_risk_model\\02_data_exploration'

In [4]:
try:
    os.mkdir(str_dirname_output)
except FileExistsError:
    pass

# Explore CSV's

In [5]:
pd.set_option('display.max_rows', 500)

In [6]:
dfbureau = pd.read_csv('M:\\Risk Management\\Bridger Hyde\\20240521_bridger_internship\\06_ml_in_python\\03_homecredit_default_risk_model\\01_data_collection\\output\\bureau.csv')
dfbureau

,SK_ID_CURR,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY,MONTHS_BALANCE,STATUS
0,380361,5715448,Active,currency 1,-820,0,31069.0,NaN,NaN,0,67500.0,0.00,67500.00,0.0,Credit card,-183,0.0,-26,X
1,380361,5715449,Active,currency 1,-357,0,1119.0,NaN,NaN,0,45000.0,0.00,45000.00,0.0,Credit card,-130,2691.0,-11,X
2,380361,5715451,Closed,currency 1,-917,0,-187.0,-759.0,NaN,0,74439.0,0.00,0.00,0.0,Consumer credit,-748,0.0,-30,X
3,380361,5715452,Closed,currency 1,-993,0,31039.0,-831.0,NaN,0,315000.0,0.00,0.00,0.0,Credit card,-818,0.0,-32,X
4,380361,5715453,Closed,currency 1,-1146,0,681.0,-780.0,NaN,0,2025000.0,0.00,0.00,0.0,Consumer credit,-769,0.0,-37,X
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
774349,229054,5053730,Active,currency 1,-456,0,1372.0,NaN,0.0,0,67500.0,63530.46,3969.54,0.0,Credit card,-3,NaN,-14,X
774350,254479,5053734,Active,currency 1,-1571,0,986.0,NaN,NaN,0,142294.5,NaN,NaN,0.0,Consumer credit,-2,NaN,-51,0
774351,363575,5053740,Closed,currency 1,-1234,0,-503.0,-502.0,NaN,0,900000.0,0.00,0.00,0.0,Consumer credit,-461,58554.0,-40,X
774352,245498,5053747,Closed,currency 1,-2582,0,-2214.0,-2018.0,0.0,0,49495.5,0.00,0.00,0.0,Consumer credit,-2017,12600.0,-84,0
774353,407724,5053758,Closed,currency 1,-2423,0,-2150.0,-2175.0,NaN,0,21883.5,0.00,NaN,0.0,Consumer credit,-787,NaN,-79,X

In [7]:
print(dfbureau.describe())

          SK_ID_CURR  SK_ID_BUREAU    DAYS_CREDIT  CREDIT_DAY_OVERDUE  \
count  774354.000000  7.743540e+05  774354.000000       774354.000000
mean   278017.293464  6.023531e+06   -1118.831666            0.533727
std    102891.546382  5.010273e+05     774.611568           28.387156
min    100001.000000  5.001710e+06   -2922.000000            0.000000
25%    188739.000000  5.701775e+06   -1627.000000            0.000000
50%    277789.500000  6.061580e+06    -972.000000            0.000000
75%    367440.000000  6.430669e+06    -473.000000            0.000000
max    456255.000000  6.842888e+06       0.000000         2792.000000

       DAYS_CREDIT_ENDDATE  DAYS_ENDDATE_FACT  AMT_CREDIT_MAX_OVERDUE  \
count        723869.000000      490889.000000            2.347040e+05
mean            618.655037        -985.557709            4.144723e+03
std            5163.587845         695.174291            3.133638e+05
min          -42060.000000      -42023.000000            0.000000e+00
25%           -1092.000000       -1421.000000            0.000000e+00
50%            -294.000000        -874.000000            0.000000e+00
75%             506.000000        -410.000000            0.000000e+00
max           31131.000000           0.000000            1.159872e+08

       CNT_CREDIT_PROLONG  AMT_CREDIT_SUM  AMT_CREDIT_SUM_DEBT  \
count       774354.000000    7.743490e+05         6.620000e+05
mean             0.005430    3.697548e+05         1.447260e+05
std              0.089438    1.209776e+06         7.215658e+05
min              0.000000    0.000000e+00        -2.014753e+06
25%              0.000000    5.292495e+04         0.000000e+00
50%              0.000000    1.305000e+05         0.000000e+00
75%              0.000000    3.285000e+05         4.703850e+04
max              9.000000    5.850000e+08         1.701000e+08

       AMT_CREDIT_SUM_LIMIT  AMT_CREDIT_SUM_OVERDUE  DAYS_CREDIT_UPDATE  \
count          4.777910e+05            7.743540e+05       774354.000000
mean           5.492964e+03            2.083465e+01         -556.021587
std            4.249620e+04            2.646012e+03          635.018072
min           -5.864061e+05            0.000000e+00       -41947.000000
25%            0.000000e+00            0.000000e+00         -897.000000
50%            0.000000e+00            0.000000e+00         -344.000000
75%            0.000000e+00            0.000000e+00          -29.000000
max            4.500000e+06            1.125734e+06          372.000000

        AMT_ANNUITY  MONTHS_BALANCE
count  4.891360e+05   774354.000000
mean   1.570947e+04      -36.288669
std    3.259931e+05       25.449736
min    0.000000e+00      -96.000000
25%    0.000000e+00      -53.000000
50%    0.000000e+00      -31.000000
75%    1.350000e+04      -15.000000
max    1.184534e+08        0.000000

In [8]:
print(dfbureau.isnull().sum())

SK_ID_CURR                     0
SK_ID_BUREAU                   0
CREDIT_ACTIVE                  0
CREDIT_CURRENCY                0
DAYS_CREDIT                    0
CREDIT_DAY_OVERDUE             0
DAYS_CREDIT_ENDDATE        50485
DAYS_ENDDATE_FACT         283465
AMT_CREDIT_MAX_OVERDUE    539650
CNT_CREDIT_PROLONG             0
AMT_CREDIT_SUM                 5
AMT_CREDIT_SUM_DEBT       112354
AMT_CREDIT_SUM_LIMIT      296563
AMT_CREDIT_SUM_OVERDUE         0
CREDIT_TYPE                    0
DAYS_CREDIT_UPDATE             0
AMT_ANNUITY               285218
MONTHS_BALANCE                 0
STATUS                         0
dtype: int64

In [9]:
missing = dfbureau.isnull().mean() * 100
print(missing[missing > 0])

DAYS_CREDIT_ENDDATE        6.519628
DAYS_ENDDATE_FACT         36.606642
AMT_CREDIT_MAX_OVERDUE    69.690348
AMT_CREDIT_SUM             0.000646
AMT_CREDIT_SUM_DEBT       14.509385
AMT_CREDIT_SUM_LIMIT      38.298117
AMT_ANNUITY               36.833025
dtype: float64

In [10]:
# AMT CREDIT MAX OVERDUE 69% missing, (Meaning remaing NaN values are customers that dont have any credit overdue)
# DAYS ENDDATE FACT 36% missing, (Only for accounts that are closed in Loan Status)
# AMT CREDIT SUM LIMIT 38% missing, (Nan values mean no credit limit? does this mean unlimited or 0 credit at all)
# AMT CREDIT SUM DEBT 14% missing, (Nan values indicate that the customers have no debt on their credit) 
# AMT ANNUITY 36% missing, (Unsure)

# Explore Credit Card Csv

In [11]:
dfcredit = pd.read_csv('M:\\Risk Management\\Bridger Hyde\\20240521_bridger_internship\\06_ml_in_python\\03_homecredit_default_risk_model\\01_data_collection\\output\\creditcard.csv')
dfcredit

,SK_ID_PREV,SK_ID_CURR,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_POS_CURRENT,AMT_INST_MIN_REGULARITY,AMT_PAYMENT_CURRENT,AMT_PAYMENT_TOTAL_CURRENT,AMT_RECEIVABLE_PRINCIPAL,AMT_RECIVABLE,AMT_TOTAL_RECEIVABLE,CNT_DRAWINGS_ATM_CURRENT,CNT_DRAWINGS_CURRENT,CNT_DRAWINGS_OTHER_CURRENT,CNT_DRAWINGS_POS_CURRENT,CNT_INSTALMENT_MATURE_CUM,SK_DPD,SK_DPD_DEF
0,1000018,394447,374731.425,405000,27000.0,147394.980,120394.980,12970.440,27708.750,27708.750,361490.985,368012.925,368012.925,6.0,44,0.0,38.0,10.0,0,0
1,1000030,361282,447928.515,652500,4500.0,138059.505,133559.505,16625.790,43320.420,21263.580,443795.625,447483.015,447483.015,1.0,41,0.0,40.0,15.0,0,0
2,1000031,131335,838311.030,2394000,157500.0,463353.840,305853.840,42804.810,354519.090,354519.090,822446.055,833599.530,833599.530,4.0,21,0.0,17.0,59.0,0,0
3,1000035,436351,0.000,1125000,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0,0.0,0.0,0.0,0,0
4,1000077,181153,0.000,1035000,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0,0.0,0.0,0.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104302,2843476,197090,3604092.165,15345000,90000.0,90000.000,0.000,327159.135,329404.905,328513.500,3416069.475,3622657.320,3641557.320,2.0,2,0.0,0.0,3229.0,1428,330
104303,2843477,168439,141361.515,1350000,58500.0,58500.000,0.000,10345.860,81197.550,67410.000,132619.005,139800.735,139800.735,6.0,6,0.0,0.0,330.0,0,0
104304,2843478,424526,460026.450,1890000,90000.0,90000.000,0.000,40528.350,122021.550,109980.000,440196.615,458796.780,458796.780,4.0,4,0.0,0.0,845.0,0,0
104305,2843493,337804,887098.905,2295000,0.0,108257.400,108257.400,42307.920,73137.060,61986.735,850963.500,875772.270,875772.270,0.0,7,0.0,7.0,91.0,0,0
104306,2843496,425374,665605.215,9450000,220500.0,272679.075,52179.075,43855.065,304211.385,260356.320,652193.145,661377.465,661377.465,3.0,28,0.0,25.0,87.0,0,0

In [12]:
print(dfcredit.describe())

         SK_ID_PREV     SK_ID_CURR   AMT_BALANCE  AMT_CREDIT_LIMIT_ACTUAL  \
count  1.043070e+05  104307.000000  1.043070e+05             1.043070e+05
mean   1.905019e+06  278333.445358  2.146460e+06             5.662808e+06
std    5.364566e+05  102795.185159  3.258557e+06             5.211967e+06
min    1.000018e+06  100006.000000 -1.260000e+05             0.000000e+00
25%    1.431454e+06  189489.000000  0.000000e+00             1.395000e+06
50%    1.898308e+06  278593.000000  6.895300e+05             3.780000e+06
75%    2.371280e+06  367629.500000  2.948521e+06             9.000000e+06
max    2.843496e+06  456250.000000  2.998048e+07             3.285000e+07

       AMT_DRAWINGS_ATM_CURRENT  AMT_DRAWINGS_CURRENT  \
count              1.043070e+05          1.043070e+05
mean               1.766272e+05          2.736780e+05
std                2.918587e+05          4.540374e+05
min                0.000000e+00         -1.687500e+03
25%                0.000000e+00          0.000000e+00
50%                5.850000e+04          1.414935e+05
75%                2.385000e+05          3.599910e+05
max                8.384850e+06          3.029332e+07

       AMT_DRAWINGS_POS_CURRENT  AMT_INST_MIN_REGULARITY  AMT_PAYMENT_CURRENT  \
count              1.043070e+05             1.043070e+05         1.043070e+05
mean               8.796226e+04             1.199813e+05         3.028094e+05
std                3.140170e+05             1.800972e+05         4.784821e+05
min                0.000000e+00             0.000000e+00         0.000000e+00
25%                0.000000e+00             0.000000e+00         0.000000e+00
50%                0.000000e+00             3.691507e+04         1.381968e+05
75%                6.030216e+04             1.689901e+05         4.320000e+05
max                3.029332e+07             2.025557e+06         3.007314e+07

       AMT_PAYMENT_TOTAL_CURRENT  AMT_RECEIVABLE_PRINCIPAL  AMT_RECIVABLE  \
count               1.043070e+05              1.043070e+05   1.043070e+05
mean                2.794019e+05              2.060518e+06   2.138679e+06
std                 4.605046e+05              3.131405e+06   3.253757e+06
min                 0.000000e+00             -1.260000e+05  -1.726412e+05
25%                 0.000000e+00              0.000000e+00   0.000000e+00
50%                 1.172147e+05              6.615882e+05   6.813738e+05
75%                 3.898694e+05              2.824981e+06   2.935828e+06
max                 3.007314e+07              2.864113e+07   3.026941e+07

       AMT_TOTAL_RECEIVABLE  CNT_DRAWINGS_ATM_CURRENT  CNT_DRAWINGS_CURRENT  \
count          1.043070e+05             104307.000000         104307.000000
mean           2.139028e+06                  9.168618             25.887927
std            3.254430e+06                 14.949723             53.050057
min           -1.726412e+05                  0.000000              0.000000
25%            0.000000e+00                  0.000000              0.000000
50%            6.814822e+05                  3.000000              8.000000
75%            2.936074e+06                 13.000000             30.000000
max            3.046124e+07                390.000000           2298.000000

       CNT_DRAWINGS_OTHER_CURRENT  CNT_DRAWINGS_POS_CURRENT  \
count               104307.000000             104307.000000
mean                     0.142589                 16.576721
std                      0.864689                 50.037925
min                      0.000000                  0.000000
25%                      0.000000                  0.000000
50%                      0.000000                  0.000000
75%                      0.000000                  9.000000
max                     38.000000               2298.000000

       CNT_INSTALMENT_MATURE_CUM         SK_DPD     SK_DPD_DEF
count              104307.000000  104307.000000  104307.000000
mean                  705.784406     341.800445      12.209459
std                  1244.611395    3832.379909    1008.583519
min                     0.000000       0.000000       0.000000
25%                     0.000000       0.000000       0.000000
50%                    45.000000       0.000000       0.000000
75%                   703.000000       0.000000       0.000000
max                  7014.000000  150483.000000  150483.000000

In [13]:
print(dfcredit.isnull().sum())

SK_ID_PREV                    0
SK_ID_CURR                    0
AMT_BALANCE                   0
AMT_CREDIT_LIMIT_ACTUAL       0
AMT_DRAWINGS_ATM_CURRENT      0
AMT_DRAWINGS_CURRENT          0
AMT_DRAWINGS_POS_CURRENT      0
AMT_INST_MIN_REGULARITY       0
AMT_PAYMENT_CURRENT           0
AMT_PAYMENT_TOTAL_CURRENT     0
AMT_RECEIVABLE_PRINCIPAL      0
AMT_RECIVABLE                 0
AMT_TOTAL_RECEIVABLE          0
CNT_DRAWINGS_ATM_CURRENT      0
CNT_DRAWINGS_CURRENT          0
CNT_DRAWINGS_OTHER_CURRENT    0
CNT_DRAWINGS_POS_CURRENT      0
CNT_INSTALMENT_MATURE_CUM     0
SK_DPD                        0
SK_DPD_DEF                    0
dtype: int64

In [14]:
dftest = pd.read_csv('M:\\Risk Management\\Bridger Hyde\\20240521_bridger_internship\\06_ml_in_python\\03_homecredit_default_risk_model\\01_data_collection\\output\\test.csv')
dftest

,SK_ID_CURR,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100001,Cash loans,F,N,Y,0,135000.0,568800.0,20560.5,450000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
1,100005,Cash loans,M,N,Y,0,99000.0,222768.0,17370.0,180000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
2,100013,Cash loans,M,Y,Y,0,202500.0,663264.0,69777.0,630000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,4.0
3,100028,Cash loans,F,N,Y,2,315000.0,1575000.0,49018.5,1575000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
4,100038,Cash loans,M,Y,N,1,180000.0,625500.0,32067.0,625500.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48739,456221,Cash loans,F,N,Y,0,121500.0,412560.0,17473.5,270000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
48740,456222,Cash loans,F,N,N,2,157500.0,622413.0,31909.5,495000.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
48741,456223,Cash loans,F,Y,Y,1,202500.0,315000.0,33205.5,315000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,3.0,1.0
48742,456224,Cash loans,M,N,N,0,225000.0,450000.0,25128.0,450000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
48743,456250,Cash loans,F,Y,N,0,135000.0,312768.0,24709.5,270000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,4.0

In [15]:
print(dftest.describe())

          SK_ID_CURR  CNT_CHILDREN  AMT_INCOME_TOTAL    AMT_CREDIT  \
count   48744.000000  48744.000000      4.874400e+04  4.874400e+04
mean   277796.676350      0.397054      1.784318e+05  5.167404e+05
std    103169.547296      0.709047      1.015226e+05  3.653970e+05
min    100001.000000      0.000000      2.694150e+04  4.500000e+04
25%    188557.750000      0.000000      1.125000e+05  2.606400e+05
50%    277549.000000      0.000000      1.575000e+05  4.500000e+05
75%    367555.500000      1.000000      2.250000e+05  6.750000e+05
max    456250.000000     20.000000      4.410000e+06  2.245500e+06

         AMT_ANNUITY  AMT_GOODS_PRICE  REGION_POPULATION_RELATIVE  \
count   48720.000000     4.874400e+04                48744.000000
mean    29426.240209     4.626188e+05                    0.021226
std     16016.368315     3.367102e+05                    0.014428
min      2295.000000     4.500000e+04                    0.000253
25%     17973.000000     2.250000e+05                    0.010006
50%     26199.000000     3.960000e+05                    0.018850
75%     37390.500000     6.300000e+05                    0.028663
max    180576.000000     2.245500e+06                    0.072508

         DAYS_BIRTH  DAYS_EMPLOYED  DAYS_REGISTRATION  ...  FLAG_DOCUMENT_18  \
count  48744.000000   48744.000000       48744.000000  ...      48744.000000
mean  -16068.084605   67485.366322       -4967.652716  ...          0.001559
std     4325.900393  144348.507136        3552.612035  ...          0.039456
min   -25195.000000  -17463.000000      -23722.000000  ...          0.000000
25%   -19637.000000   -2910.000000       -7459.250000  ...          0.000000
50%   -15785.000000   -1293.000000       -4490.000000  ...          0.000000
75%   -12496.000000    -296.000000       -1901.000000  ...          0.000000
max    -7338.000000  365243.000000           0.000000  ...          1.000000

       FLAG_DOCUMENT_19  FLAG_DOCUMENT_20  FLAG_DOCUMENT_21  \
count           48744.0           48744.0           48744.0
mean                0.0               0.0               0.0
std                 0.0               0.0               0.0
min                 0.0               0.0               0.0
25%                 0.0               0.0               0.0
50%                 0.0               0.0               0.0
75%                 0.0               0.0               0.0
max                 0.0               0.0               0.0

       AMT_REQ_CREDIT_BUREAU_HOUR  AMT_REQ_CREDIT_BUREAU_DAY  \
count                42695.000000               42695.000000
mean                     0.002108                   0.001803
std                      0.046373                   0.046132
min                      0.000000                   0.000000
25%                      0.000000                   0.000000
50%                      0.000000                   0.000000
75%                      0.000000                   0.000000
max                      2.000000                   2.000000

       AMT_REQ_CREDIT_BUREAU_WEEK  AMT_REQ_CREDIT_BUREAU_MON  \
count                42695.000000               42695.000000
mean                     0.002787                   0.009299
std                      0.054037                   0.110924
min                      0.000000                   0.000000
25%                      0.000000                   0.000000
50%                      0.000000                   0.000000
75%                      0.000000                   0.000000
max                      2.000000                   6.000000

       AMT_REQ_CREDIT_BUREAU_QRT  AMT_REQ_CREDIT_BUREAU_YEAR
count               42695.000000                42695.000000
mean                    0.546902                    1.983769
std                     0.693305                    1.838873
min                     0.000000                    0.000000
25%                     0.000000                    0.000000
50%                     0.000000                    2.000000
75%                     1.000000                    3.000000
max                     7.000000                   17.000000

[8 rows x 105 columns]

In [16]:
print(dftest.isnull().sum())

SK_ID_CURR                          0
NAME_CONTRACT_TYPE                  0
CODE_GENDER                         0
FLAG_OWN_CAR                        0
FLAG_OWN_REALTY                     0
CNT_CHILDREN                        0
AMT_INCOME_TOTAL                    0
AMT_CREDIT                          0
AMT_ANNUITY                        24
AMT_GOODS_PRICE                     0
NAME_TYPE_SUITE                   911
NAME_INCOME_TYPE                    0
NAME_EDUCATION_TYPE                 0
NAME_FAMILY_STATUS                  0
NAME_HOUSING_TYPE                   0
REGION_POPULATION_RELATIVE          0
DAYS_BIRTH                          0
DAYS_EMPLOYED                       0
DAYS_REGISTRATION                   0
DAYS_ID_PUBLISH                     0
OWN_CAR_AGE                     32312
FLAG_MOBIL                          0
FLAG_EMP_PHONE                      0
FLAG_WORK_PHONE                     0
FLAG_CONT_MOBILE                    0
FLAG_PHONE                          0
FLAG_EMAIL                          0
OCCUPATION_TYPE                 15605
CNT_FAM_MEMBERS                     0
REGION_RATING_CLIENT                0
REGION_RATING_CLIENT_W_CITY         0
WEEKDAY_APPR_PROCESS_START          0
HOUR_APPR_PROCESS_START             0
REG_REGION_NOT_LIVE_REGION          0
REG_REGION_NOT_WORK_REGION          0
LIVE_REGION_NOT_WORK_REGION         0
REG_CITY_NOT_LIVE_CITY              0
REG_CITY_NOT_WORK_CITY              0
LIVE_CITY_NOT_WORK_CITY             0
ORGANIZATION_TYPE                   0
EXT_SOURCE_1                    20532
EXT_SOURCE_2                        8
EXT_SOURCE_3                     8668
APARTMENTS_AVG                  23887
BASEMENTAREA_AVG                27641
YEARS_BEGINEXPLUATATION_AVG     22856
YEARS_BUILD_AVG                 31818
COMMONAREA_AVG                  33495
ELEVATORS_AVG                   25189
ENTRANCES_AVG                   23579
FLOORSMAX_AVG                   23321
FLOORSMIN_AVG                   32466
LANDAREA_AVG                    28254
LIVINGAPARTMENTS_AVG            32780
LIVINGAREA_AVG                  23552
NONLIVINGAPARTMENTS_AVG         33347
NONLIVINGAREA_AVG               26084
APARTMENTS_MODE                 23887
BASEMENTAREA_MODE               27641
YEARS_BEGINEXPLUATATION_MODE    22856
YEARS_BUILD_MODE                31818
COMMONAREA_MODE                 33495
ELEVATORS_MODE                  25189
ENTRANCES_MODE                  23579
FLOORSMAX_MODE                  23321
FLOORSMIN_MODE                  32466
LANDAREA_MODE                   28254
LIVINGAPARTMENTS_MODE           32780
LIVINGAREA_MODE                 23552
NONLIVINGAPARTMENTS_MODE        33347
NONLIVINGAREA_MODE              26084
APARTMENTS_MEDI                 23887
BASEMENTAREA_MEDI               27641
YEARS_BEGINEXPLUATATION_MEDI    22856
YEARS_BUILD_MEDI                31818
COMMONAREA_MEDI                 33495
ELEVATORS_MEDI                  25189
ENTRANCES_MEDI                  23579
FLOORSMAX_MEDI                  23321
FLOORSMIN_MEDI                  32466
LANDAREA_MEDI                   28254
LIVINGAPARTMENTS_MEDI           32780
LIVINGAREA_MEDI                 23552
NONLIVINGAPARTMENTS_MEDI        33347
NONLIVINGAREA_MEDI              26084
FONDKAPREMONT_MODE              32797
HOUSETYPE_MODE                  23619
TOTALAREA_MODE                  22624
WALLSMATERIAL_MODE              23893
EMERGENCYSTATE_MODE             22209
OBS_30_CNT_SOCIAL_CIRCLE           29
DEF_30_CNT_SOCIAL_CIRCLE           29
OBS_60_CNT_SOCIAL_CIRCLE           29
DEF_60_CNT_SOCIAL_CIRCLE           29
DAYS_LAST_PHONE_CHANGE              0
FLAG_DOCUMENT_2                     0
FLAG_DOCUMENT_3                     0
FLAG_DOCUMENT_4                     0
FLAG_DOCUMENT_5                     0
FLAG_DOCUMENT_6                     0
FLAG_DOCUMENT_7                     0
FLAG_DOCUMENT_8                     0
FLAG_DOCUMENT_9                     0
FLAG_DOCUMENT_10                    0
FLAG_DOCUMENT_11                    0
FLAG_DOCUMENT_12                    0
FLAG_DOCUMENT_13                    0
FLAG_DOCUMENT_14                    0
FLAG_DOCUMENT_15                    0
FLAG_DOCUMENT_16                    0
FLAG_DOCUMENT_17                    0
FLAG_DOCUMENT_18                    0
FLAG_DOCUMENT_19                    0
FLAG_DOCUMENT_20                    0
FLAG_DOCUMENT_21                    0
AMT_REQ_CREDIT_BUREAU_HOUR       6049
AMT_REQ_CREDIT_BUREAU_DAY        6049
AMT_REQ_CREDIT_BUREAU_WEEK       6049
AMT_REQ_CREDIT_BUREAU_MON        6049
AMT_REQ_CREDIT_BUREAU_QRT        6049
AMT_REQ_CREDIT_BUREAU_YEAR       6049
dtype: int64

In [17]:
missing = dftest.isnull().mean() * 100
print(missing[missing > 0])

AMT_ANNUITY                      0.049237
NAME_TYPE_SUITE                  1.868948
OWN_CAR_AGE                     66.289184
OCCUPATION_TYPE                 32.014197
EXT_SOURCE_1                    42.122107
EXT_SOURCE_2                     0.016412
EXT_SOURCE_3                    17.782701
APARTMENTS_AVG                  49.005006
BASEMENTAREA_AVG                56.706466
YEARS_BEGINEXPLUATATION_AVG     46.889874
YEARS_BUILD_AVG                 65.275726
COMMONAREA_AVG                  68.716150
ELEVATORS_AVG                   51.676104
ENTRANCES_AVG                   48.373133
FLOORSMAX_AVG                   47.843837
FLOORSMIN_AVG                   66.605121
LANDAREA_AVG                    57.964057
LIVINGAPARTMENTS_AVG            67.249302
LIVINGAREA_AVG                  48.317742
NONLIVINGAPARTMENTS_AVG         68.412523
NONLIVINGAREA_AVG               53.512227
APARTMENTS_MODE                 49.005006
BASEMENTAREA_MODE               56.706466
YEARS_BEGINEXPLUATATION_MODE    46.889874
YEARS_BUILD_MODE                65.275726
COMMONAREA_MODE                 68.716150
ELEVATORS_MODE                  51.676104
ENTRANCES_MODE                  48.373133
FLOORSMAX_MODE                  47.843837
FLOORSMIN_MODE                  66.605121
LANDAREA_MODE                   57.964057
LIVINGAPARTMENTS_MODE           67.249302
LIVINGAREA_MODE                 48.317742
NONLIVINGAPARTMENTS_MODE        68.412523
NONLIVINGAREA_MODE              53.512227
APARTMENTS_MEDI                 49.005006
BASEMENTAREA_MEDI               56.706466
YEARS_BEGINEXPLUATATION_MEDI    46.889874
YEARS_BUILD_MEDI                65.275726
COMMONAREA_MEDI                 68.716150
ELEVATORS_MEDI                  51.676104
ENTRANCES_MEDI                  48.373133
FLOORSMAX_MEDI                  47.843837
FLOORSMIN_MEDI                  66.605121
LANDAREA_MEDI                   57.964057
LIVINGAPARTMENTS_MEDI           67.249302
LIVINGAREA_MEDI                 48.317742
NONLIVINGAPARTMENTS_MEDI        68.412523
NONLIVINGAREA_MEDI              53.512227
FONDKAPREMONT_MODE              67.284179
HOUSETYPE_MODE                  48.455194
TOTALAREA_MODE                  46.413918
WALLSMATERIAL_MODE              49.017315
EMERGENCYSTATE_MODE             45.562531
OBS_30_CNT_SOCIAL_CIRCLE         0.059495
DEF_30_CNT_SOCIAL_CIRCLE         0.059495
OBS_60_CNT_SOCIAL_CIRCLE         0.059495
DEF_60_CNT_SOCIAL_CIRCLE         0.059495
AMT_REQ_CREDIT_BUREAU_HOUR      12.409732
AMT_REQ_CREDIT_BUREAU_DAY       12.409732
AMT_REQ_CREDIT_BUREAU_WEEK      12.409732
AMT_REQ_CREDIT_BUREAU_MON       12.409732
AMT_REQ_CREDIT_BUREAU_QRT       12.409732
AMT_REQ_CREDIT_BUREAU_YEAR      12.409732
dtype: float64