In [1]:
import os
import pandas as pd
import numpy as np

/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/pandas/core/computation/expressions.py:21: UserWarning: Pandas requires version '2.8.0' or newer of 'numexpr' (version '2.7.3' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

### Functions

In [2]:
# get percent difference
def get_percent_difference(val1, val2):
    flt_diff = abs(val1 - val2)
    flt_mean = np.mean([val1, val2])
    prop_diff = flt_diff / flt_mean
    return prop_diff * 100

### Constants

In [3]:
str_dirname_output = './output'
str_variant = 'model6'

### Output directory

In [4]:
try:
    os.mkdir(str_dirname_output)
except:
    pass

### Variant directory

In [5]:
try:
    os.mkdir(f'{str_dirname_output}/{str_variant}')
except:
    pass

### Get descriptives from PD test data

In [6]:
str_filename = 'df_descriptives.csv'
str_local_path = f'../get_predictions/03_eda/output/{str_variant}/{str_filename}'
df_pd = pd.read_csv(str_local_path)

# add suffix
df_pd.columns = [f'{col}__pd' for col in df_pd.columns]

# rename
dict_rename = {
    'feature__pd': 'feature',
}
df_pd.rename(columns=dict_rename, inplace=True)

# show
df_pd

,feature,dtype__pd,propna__pd,min__pd,max__pd,range__pd,std__pd,mean__pd,median__pd,mode__pd,n_unique__pd,prop_unique__pd,prop_negative__pd,prop_min__pd,prop_max__pd,prop_zero__pd
0,dtmstampcreation__base,float64,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,1,0.000040,0.000000,1.000000,1.00000,1.000000
1,rev319__tu,float64,0.0,0.000000,123456.664572,123456.664572,5399.911390,1585.674466,0.000000,0.0,4243,0.170648,0.000000,0.523327,0.00004,0.523327
2,all253__tu,float64,0.0,-6.000000,298285.000000,298291.000000,3039.279999,248.900861,0.000000,0.0,1148,0.046171,0.311092,0.032296,0.00004,0.481017
3,all254__tu,float64,0.0,-6.000000,246985.000000,246991.000000,3303.205836,336.874638,0.000000,0.0,1527,0.061414,0.255590,0.032296,0.00008,0.493364
4,all255__tu,float64,0.0,-6.000000,225016.000000,225022.000000,3854.882001,476.256395,0.000000,0.0,2024,0.081403,0.190999,0.032296,0.00008,0.495938
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2497,at09s__tu,float64,0.0,-5.000000,59.000000,64.000000,3.633321,2.438184,1.000000,0.0,41,0.001649,0.032336,0.000040,0.00004,0.279360
2498,at12s__tu,float64,0.0,-4.000000,37.000000,41.000000,4.549695,1.483591,1.000000,-3.0,39,0.001569,0.316482,0.032296,0.00004,0.020471
2499,at20s__tu,float64,0.0,-5.000000,999.000000,1004.000000,75.366690,125.685328,122.000000,-4.0,485,0.019506,0.032336,0.000040,0.00008,0.000442
2500,at21s__tu,float64,0.0,-5.000000,999.000000,1004.000000,27.681321,21.058036,13.000000,2.0,214,0.008607,0.032336,0.000040,0.00008,0.011704
2501,yhat_pricing_lgd,float64,0.0,0.039544,0.713544,0.673999,0.081999,0.397236,0.401674,0.03954432580829409,24864,1.000000,0.000000,0.000040,0.00004,0.000000

### Get descriptives from parsed data

In [7]:
str_filename = 'df_descriptives.csv'
str_local_path = f'../../08_retro_scoring/07_analysis/02_eda/output/{str_variant}/{str_filename}'
df_parsed = pd.read_csv(str_local_path)

# add suffix
df_parsed.columns = [f'{col}__parse' for col in df_parsed.columns]

# rename
dict_rename = {
    'feature__parse': 'feature',
}
df_parsed.rename(columns=dict_rename, inplace=True)

# show
df_parsed

,feature,dtype__parse,propna__parse,min__parse,max__parse,range__parse,std__parse,mean__parse,median__parse,mode__parse,n_unique__parse,prop_unique__parse,prop_negative__parse,prop_min__parse,prop_max__parse,prop_zero__parse
0,uniqueid__app,int64,0.0,5.776705e+14,7.276222e+14,1.499517e+14,3.882217e+13,6.449815e+14,6.386993e+14,577670472533441,45742,1.000000,0.000000,0.000022,0.000022,0.000000
1,inst_trd__tu,float64,0.0,-6.000000e+00,1.500000e+02,1.560000e+02,9.380946e+00,8.043243e+00,5.000000e+00,1.0,104,0.002274,0.005159,0.005159,0.000022,0.076057
2,agg110__tu,float64,0.0,-6.000000e+00,9.044080e+05,9.044140e+05,3.198961e+04,1.659979e+04,4.364500e+03,-2.0,21932,0.479472,0.230882,0.005159,0.000022,0.038979
3,agg109__tu,float64,0.0,-6.000000e+00,9.045120e+05,9.045180e+05,3.206745e+04,1.664911e+04,4.497000e+03,-2.0,21949,0.479843,0.227297,0.005159,0.000022,0.038039
4,agg108__tu,float64,0.0,-6.000000e+00,8.762690e+05,8.762750e+05,3.217021e+04,1.668898e+04,4.456000e+03,-2.0,22010,0.481177,0.224957,0.005159,0.000022,0.039767
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016,lm31s__tu,float64,0.0,-4.000000e+00,1.000000e+00,5.000000e+00,2.554640e-01,-1.004329e+00,-1.000000e+00,-1.0,4,0.000087,0.992698,0.005159,0.003848,0.003454
2017,lm30s__tu,float64,0.0,-4.000000e+00,1.000000e+00,5.000000e+00,2.573876e-01,-1.004001e+00,-1.000000e+00,-1.0,4,0.000087,0.992698,0.005159,0.004176,0.003126
2018,lm29s__tu,float64,0.0,-5.000000e+00,2.590000e+02,2.640000e+02,4.747568e+00,-7.978007e-01,-1.000000e+00,-1.0,54,0.001181,0.995409,0.002711,0.000022,0.002121
2019,lm28s__tu,float64,0.0,-4.000000e+00,7.033400e+05,7.033440e+05,1.322711e+04,8.137508e+02,-1.000000e+00,-1.0,235,0.005138,0.992698,0.005159,0.000022,0.002121
2020,pricing_ecnl,float64,0.0,2.636560e-04,5.377501e-01,5.374864e-01,7.490214e-02,1.493829e-01,1.402552e-01,0.0002636560239825553,45742,1.000000,0.000000,0.000022,0.000022,0.000000

### Join

In [8]:
df = pd.merge(
    left=df_pd,
    right=df_parsed,
    on='feature',
    how='inner',
)

# show
df

,feature,dtype__pd,propna__pd,min__pd,max__pd,range__pd,std__pd,mean__pd,median__pd,mode__pd,...,std__parse,mean__parse,median__parse,mode__parse,n_unique__parse,prop_unique__parse,prop_negative__parse,prop_min__parse,prop_max__parse,prop_zero__parse
0,rev319__tu,float64,0.0,0.000000,123456.664572,123456.664572,5399.911390,1585.674466,0.000000,0.0,...,3588.736538,1138.150206,167.000000,0.0,8280,0.181015,0.000000,0.415942,0.000022,0.415942
1,all253__tu,float64,0.0,-6.000000,298285.000000,298291.000000,3039.279999,248.900861,0.000000,0.0,...,2631.055961,268.432753,0.000000,0.0,2472,0.054042,0.296948,0.005159,0.000022,0.397971
2,all254__tu,float64,0.0,-6.000000,246985.000000,246991.000000,3303.205836,336.874638,0.000000,0.0,...,3638.418119,372.484019,0.000000,0.0,2991,0.065388,0.247978,0.005159,0.000022,0.393927
3,all255__tu,float64,0.0,-6.000000,225016.000000,225022.000000,3854.882001,476.256395,0.000000,0.0,...,3152.564310,418.202068,0.000000,0.0,3319,0.072559,0.187618,0.005159,0.000022,0.385597
4,rev315__tu,float64,0.0,-6.000000,999.000000,1005.000000,12.438764,4.641168,-1.000000,-2.0,...,8.149967,5.038214,1.000000,-2.0,28,0.000612,0.413821,0.005159,0.033755,0.075642
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2002,at09s__tu,float64,0.0,-5.000000,59.000000,64.000000,3.633321,2.438184,1.000000,0.0,...,3.856264,3.279918,2.000000,0.0,44,0.000962,0.005159,0.005159,0.000044,0.226422
2003,at12s__tu,float64,0.0,-4.000000,37.000000,41.000000,4.549695,1.483591,1.000000,-3.0,...,5.107658,2.650671,2.000000,-3.0,48,0.001049,0.230117,0.005159,0.000022,0.009750
2004,at20s__tu,float64,0.0,-5.000000,999.000000,1004.000000,75.366690,125.685328,122.000000,-4.0,...,72.542771,117.060426,108.000000,84.0,511,0.011171,0.005159,0.005159,0.000044,0.002252
2005,at21s__tu,float64,0.0,-5.000000,999.000000,1004.000000,27.681321,21.058036,13.000000,2.0,...,26.233041,18.676031,9.000000,2.0,268,0.005859,0.005159,0.005159,0.000022,0.008614
2006,yhat_pricing_lgd,float64,0.0,0.039544,0.713544,0.673999,0.081999,0.397236,0.401674,0.03954432580829409,...,0.070660,0.410256,0.415018,0.011430799890491283,45742,1.000000,0.000000,0.000022,0.000022,0.000000

### Check means

In [9]:
%%time

df['mean_diff'] = df.apply(
    lambda x: get_percent_difference(
        val1=x['mean__pd'], 
        val2=x['mean__parse'],
    ),
    axis=1,
)

# make absolute value
df['mean_diff'] = df['mean_diff'].abs()

# sort
df.sort_values(by='mean_diff', ascending=False, inplace=True)

# list cols
list_cols = [
    'feature',
    'mean__pd',
    'mean__parse',
    'mean_diff',
]

# subset
df_tmp = df[list_cols].copy()

# save
str_filename = 'df_mean_diff.csv'
str_local_path = f'{str_dirname_output}/{str_variant}/{str_filename}'
df_tmp.to_csv(str_local_path)

# show
df_tmp

CPU times: user 52.8 ms, sys: 284 µs, total: 53 ms
Wall time: 52.3 ms

/tmp/ipykernel_9295/4078309835.py:5: RuntimeWarning: invalid value encountered in double_scalars
  prop_diff = flt_diff / flt_mean

         feature  mean__pd  mean__parse     mean_diff
418    re06s__tu -0.151142     0.153732  23546.154504
1746    cv17__tu -0.174590     0.161580   5168.028246
1661   hr20s__tu  0.611527    -0.565520   5116.808484
473    g405s__tu -0.380269     0.411897   5009.189833
1662   hr21s__tu  0.645190    -0.585807   4145.994644
...          ...       ...          ...           ...
1728  rvlr14__tu       NaN          NaN           NaN
1729  rvlr15__tu       NaN          NaN           NaN
1730  rvlr16__tu       NaN          NaN           NaN
1731  rvlr17__tu       NaN          NaN           NaN
1732  rvlr18__tu       NaN          NaN           NaN

[2007 rows x 4 columns]

### Get medians

In [10]:
%%time

df['median_diff'] = df.apply(
    lambda x: get_percent_difference(
        val1=x['median__pd'], 
        val2=x['median__parse'],
    ),
    axis=1,
)

# make absolute value
df['median_diff'] = df['median_diff'].abs()

# sort
df.sort_values(by='median_diff', ascending=False, inplace=True)

# list cols
list_cols = [
    'feature',
    'median__pd',
    'median__parse',
    'median_diff',
]

# subset
df_tmp = df[list_cols].copy()

# save
str_filename = 'df_median_diff.csv'
str_local_path = f'{str_dirname_output}/{str_variant}/{str_filename}'
df_tmp.to_csv(str_local_path)

# show
df_tmp

CPU times: user 49.3 ms, sys: 478 µs, total: 49.8 ms
Wall time: 49 ms

/tmp/ipykernel_9295/4078309835.py:5: RuntimeWarning: invalid value encountered in double_scalars
  prop_diff = flt_diff / flt_mean
/tmp/ipykernel_9295/4078309835.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  prop_diff = flt_diff / flt_mean

                       feature  median__pd  median__parse  median_diff
276                  rev51__tu        -1.0            1.0          inf
83                 revs905__tu        -1.0            1.0          inf
704   bankruptcytimenewest__ln         1.0           -1.0          inf
272                  rev11__tu        -1.0            1.0          inf
569                  jt41s__tu         1.0           -1.0          inf
...                        ...         ...            ...          ...
1728                rvlr14__tu         NaN            NaN          NaN
1729                rvlr15__tu         NaN            NaN          NaN
1730                rvlr16__tu         NaN            NaN          NaN
1731                rvlr17__tu         NaN            NaN          NaN
1732                rvlr18__tu         NaN            NaN          NaN

[2007 rows x 4 columns]