# Train, Valid, Test Split (ml.m5.12xlarge)

In [1]:
import os
import pandas as pd
import numpy as np
from tqdm import tqdm

/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/pandas/core/computation/expressions.py:21: UserWarning: Pandas requires version '2.8.0' or newer of 'numexpr' (version '2.7.3' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

### Functions

In [2]:
# denote df
def mark_df(flt_prop_row):
    if flt_prop_row <= 0.6:
        return 'train'
    elif flt_prop_row <= 0.8:
        return 'valid'
    else:
        return 'test'

### Constants

In [3]:
str_project = os.getcwd().split('/')[4].replace('_','-')
print(f'Project: {str_project}')
str_step = os.getcwd().split('/')[-1]
print(f'Step: {str_step}')
str_dirname_output = './output'

str_id = 'uniqueid'
str_datecol = 'applicationdate__app'
str_target = 'target'

list_cols_id = [
    str_id,
    str_datecol,
    str_target,
]

Project: 20231010-gen-xii
Step: 03_train_valid_test_split

### Output

In [4]:
try:
    os.mkdir(str_dirname_output)
except:
    pass

### Import data

In [5]:
%%time

# import
str_filename = 'df_raw.gzip'
str_uri = f's3://{str_project}/01_ad/01_data_prep/01_data_collection/output/{str_filename}'
# read from s3
df = pd.read_parquet(str_uri)
# replace
df.replace(['NaN','nan'], np.nan, inplace=True)

# show
df

CPU times: user 2min 48s, sys: 4min 57s, total: 7min 46s
Wall time: 51.2 s

,bitdebtor__base,dtmstampcreation__base,dtmapproved__base,dtmdeclined__base,dtmfunded__base,observationdate__base,analyticsmatchkey__base,decision_dte__base,booked__base,acct_typ_cde__base,...,us934d__tu,us934s__tu,us935b__tu,us935c__tu,us935d__tu,us935s__tu,score_bankcard__tu,score_cvpropensity__tu,finscore__tu,intscore__ln
0,0.0,20181103.0,20181103.0,NaN,NaN,201810.0,73140.0,2018-11-03,0.0,AU,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.0,20181103.0,NaN,20181103.0,NaN,201810.0,72817.0,2018-11-03,0.0,AU,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.0,20181103.0,NaN,20181103.0,NaN,201810.0,74494.0,2018-11-03,0.0,AU,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.0,20181030.0,NaN,20181030.0,NaN,201810.0,61357.0,2018-10-30,0.0,AU,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.0,20181031.0,20181031.0,NaN,NaN,201810.0,61417.0,2018-10-31,0.0,AU,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2100693,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,0.0,NaN,555.0,588.0
2100694,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,0.0,451.0,571.0,574.0
2100695,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,0.0,447.0,616.0,568.0
2100696,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,0.0,501.0,648.0,595.0
2100697,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,0.0,NaN,534.0,597.0

### Mark each row as train, valid, or test

In [6]:
%%time

# sort
df.sort_values(by=str_datecol, ascending=True, inplace=True)

# create column
int_nrows = df.shape[0]
df['int_row'] = [i for i in range(1, int_nrows + 1)]
# divide by n rows
df['flt_prop_row'] = df['int_row'] / int_nrows

# drop
df.drop('int_row', axis=1, inplace=True)

# mark the df
df['data_set'] = df['flt_prop_row'].apply(mark_df)

# show
df

CPU times: user 28.6 s, sys: 17.9 s, total: 46.5 s
Wall time: 43.5 s

,bitdebtor__base,dtmstampcreation__base,dtmapproved__base,dtmdeclined__base,dtmfunded__base,observationdate__base,analyticsmatchkey__base,decision_dte__base,booked__base,acct_typ_cde__base,...,us935b__tu,us935c__tu,us935d__tu,us935s__tu,score_bankcard__tu,score_cvpropensity__tu,finscore__tu,intscore__ln,flt_prop_row,data_set
578033,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.760323e-07,train
578463,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.520645e-07,train
578464,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.428097e-06,train
578465,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.904129e-06,train
578466,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.380161e-06,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61490,1.0,20191231.0,NaN,20191231.0,NaN,201910.0,866585.0,2019-12-31,0.0,AU,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.999981e-01,test
98385,1.0,20191231.0,NaN,20191231.0,NaN,201910.0,862293.0,2019-12-31,0.0,AU,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.999986e-01,test
98384,1.0,20191231.0,NaN,20191231.0,NaN,201910.0,937386.0,2019-12-31,0.0,AU,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.999990e-01,test
413531,1.0,20191231.0,NaN,20191231.0,NaN,201910.0,865161.0,2019-12-31,0.0,AU,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.999995e-01,test
560787,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AU,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000e+00,test

### Show value counts

In [7]:
ser_prop = pd.value_counts(df['data_set'], normalize=True)
print(ser_prop)

data_set
train    0.6
valid    0.2
test     0.2
Name: proportion, dtype: float64

/tmp/ipykernel_37772/1628931787.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  ser_prop = pd.value_counts(df['data_set'], normalize=True)

In [8]:
ser_freq = pd.value_counts(df['data_set'], normalize=False)
print(ser_freq)

data_set
train    1260418
valid     420140
test      420140
Name: count, dtype: int64

/tmp/ipykernel_37772/3389291447.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  ser_freq = pd.value_counts(df['data_set'], normalize=False)

### Write data frames

In [9]:
list_df = [
    'train',
    'valid',
    'test',
]
for str_df in tqdm (list_df):
    # subset
    df_tmp = df[df['data_set']==str_df].copy()
    
    # drop
    list_cols = [
        'flt_prop_row',
        'data_set',
    ]
    df_tmp.drop(list_cols, axis=1, inplace=True)
    
    # write to s3
    str_filename = f'df_{str_df}_raw.gzip'
    str_uri = f's3://{str_project}/01_ad/01_data_prep/{str_step}/{str_filename}'
    df_tmp.to_parquet(str_uri, compression='gzip')

100%|██████████| 3/3 [14:06<00:00, 282.11s/it]