In [1]:
import os
import pandas as pd
import functions as func
import numpy as np
from tqdm import tqdm
from pprint import pprint

/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/pandas/core/computation/expressions.py:21: UserWarning: Pandas requires version '2.8.0' or newer of 'numexpr' (version '2.7.3' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

### Constants

In [2]:
str_project = os.getcwd().split('/')[4].replace('_','-')
print(f'Project: {str_project}')
str_step = os.getcwd().split('/')[-1]
print(f'Step: {str_step}')
str_dirname_output = './output'

str_id = 'uniqueid'
str_datecol = 'applicationdate__app'
str_target = 'target'
flt_threshold = 0.80 # proportion missing in any data set

list_cols_id = [
    str_id,
    str_datecol,
    str_target,
]

Project: 20231010-gen-xii
Step: 02_name

### Output

In [3]:
try:
    os.mkdir(str_dirname_output)
except:
    pass

### Import column names

In [4]:
%%time

str_filename = 'df_descriptives_train.csv'
str_local_path = f'../../04_eda_pt_2/output/{str_filename}'
list_cols = list(pd.read_csv(str_local_path)['feature'])
# message
print(f'We will be reviewing {len(list_cols)} columns for leaks by name')
print('')

We will be reviewing 2485 columns for leaks by name

CPU times: user 7.68 ms, sys: 3.66 ms, total: 11.3 ms
Wall time: 13.2 ms

### List of Leaky Features by Name

In [5]:
%%time

# get id, date, score, fund columns
list_id_cols, list_date_cols, list_score_cols, list_fund_cols = func.check_columns(list_cols)

# combine lists
list_leaky_by_name = list_id_cols + list_date_cols + list_score_cols + list_fund_cols
# rm dups
list_leaky_by_name = list(dict.fromkeys(list_leaky_by_name))
# message
print('')
print(f'There are {len(list_leaky_by_name)} features with names suggesting they should be dropped')
for a, col in enumerate(list_leaky_by_name):
    print(f'{a+1} - {col}')

print('')

There are 23 columns containing the string "id"
1 - bigaccountid
2 - bigdebtorid
3 - acctid__tu
4 - partyid__tu
5 - permid__tu
6 - middlename__tu
7 - educationevidence__ln
8 - inputprovidedstate__ln
9 - inputprovidedfirstname__ln
10 - inputprovidedlastname__ln
11 - inputprovidedcity__ln
12 - inputprovidedzipcode__ln
13 - inputprovidedssn__ln
14 - inputprovideddateofbirth__ln
15 - inputprovidedphone__ln
16 - inputprovidedlexid__ln
17 - inputprovidedstreetaddress__ln
18 - bigdealertypeid__app
19 - bigdebtorid__app
20 - bigaccountid__app
21 - bigdebtorid__ln
22 - bigaccountid__ln
23 - bigdealerid__app

There are 27 columns containing the strings "date", "dtm", or "dte"
1 - dtmstampcreation__base
2 - dtmapproved__base
3 - dtmdeclined__base
4 - dtmfunded__base
5 - creditasofdate__tu
6 - gnrcrem_frsrpt_dte__base
7 - observationdate__base
8 - open_dte__base
9 - decision_dte__base
10 - observationdate__tu
11 - dtmstampcreation__tu
12 - dateofbirth__tu
13 - chargeoffdate__app
14 - defaultdate__app
15 - dtmfunded__tu
16 - dtmfunded__app
17 - fundeddate__app
18 - dtmapproved__tu
19 - approvaldate__app
20 - dtmapproved__app
21 - dtmdeclined__tu
22 - dtmdeclined__app
23 - tu_creditbureaudate__tu
24 - credit_as_of_date__tu
25 - inputprovideddateofbirth__ln
26 - ssndatelowissued__ln
27 - dtmstampcreation__app

There are 16 columns containing the string "score"
1 - score_cvpropensity__tu
2 - score_epd__tu
3 - score_newaccount__tu
4 - intscore__ln
5 - score_bankcard__tu
6 - score_cvauto__tu
7 - finscore__tu
8 - vantagescore3__tu
9 - vantagescore4__tu
10 - syntheticfraud_score__tu
11 - bankcard_score__ln
12 - crossindustry_score__ln
13 - crossindustry_score_name__ln
14 - telecommunications_score__ln
15 - short_term_lending_score__ln
16 - auto_score__ln

There are 5 columns containing the string "fund"
1 - dtmfunded__base
2 - dtmfunded__tu
3 - dtmfunded__app
4 - fundeddate__app
5 - bitfunded__app


There are 66 features with names suggesting they should be dropped
1 - bigaccountid
2 - bigdebtorid
3 - acctid__tu
4 - partyid__tu
5 - permid__tu
6 - middlename__tu
7 - educationevidence__ln
8 - inputprovidedstate__ln
9 - inputprovidedfirstname__ln
10 - inputprovidedlastname__ln
11 - inputprovidedcity__ln
12 - inputprovidedzipcode__ln
13 - inputprovidedssn__ln
14 - inputprovideddateofbirth__ln
15 - inputprovidedphone__ln
16 - inputprovidedlexid__ln
17 - inputprovidedstreetaddress__ln
18 - bigdealertypeid__app
19 - bigdebtorid__app
20 - bigaccountid__app
21 - bigdebtorid__ln
22 - bigaccountid__ln
23 - bigdealerid__app
24 - dtmstampcreation__base
25 - dtmapproved__base
26 - dtmdeclined__base
27 - dtmfunded__base
28 - creditasofdate__tu
29 - gnrcrem_frsrpt_dte__base
30 - observationdate__base
31 - open_dte__base
32 - decision_dte__base
33 - observationdate__tu
34 - dtmstampcreation__tu
35 - dateofbirth__tu
36 - chargeoffdate__app
37 - defaultdate__app
38 - dtmfunded__tu
39 - dtmfunded__app
40 - fundeddate__app
41 - dtmapproved__tu
42 - approvaldate__app
43 - dtmapproved__app
44 - dtmdeclined__tu
45 - dtmdeclined__app
46 - tu_creditbureaudate__tu
47 - credit_as_of_date__tu
48 - ssndatelowissued__ln
49 - dtmstampcreation__app
50 - score_cvpropensity__tu
51 - score_epd__tu
52 - score_newaccount__tu
53 - intscore__ln
54 - score_bankcard__tu
55 - score_cvauto__tu
56 - finscore__tu
57 - vantagescore3__tu
58 - vantagescore4__tu
59 - syntheticfraud_score__tu
60 - bankcard_score__ln
61 - crossindustry_score__ln
62 - crossindustry_score_name__ln
63 - telecommunications_score__ln
64 - short_term_lending_score__ln
65 - auto_score__ln
66 - bitfunded__app

CPU times: user 2.08 ms, sys: 0 ns, total: 2.08 ms
Wall time: 2.05 ms

In [6]:
# remove good cols in list_leaky_by_name
list_dont_drop = [
    'educationevidence__ln',
    'inputprovidedstate__ln',
    'inputprovidedfirstname__ln',
    'inputprovidedlastname__ln',
    'inputprovidedcity__ln',
    'inputprovidedzipcode__ln',
    'inputprovidedssn__ln',
    'inputprovideddateofbirth__ln',
    'inputprovidedphone__ln',
    'inputprovidedlexid__ln',
    'inputprovidedstreetaddress__ln',
    'bigdealertypeid__app',
    'auto_score__ln',
    # 2023-11-06
    'intscore__ln',
    'vantagescore4__tu',
]
list_leaky_by_name = [col for col in list_leaky_by_name if col not in list_dont_drop]

# message
print(f'There are {len(list_leaky_by_name)} features identified as leaky based off of their name')
for a, col in enumerate(list_leaky_by_name):
    print(f'{a+1} - {col}')

There are 51 features identified as leaky based off of their name
1 - bigaccountid
2 - bigdebtorid
3 - acctid__tu
4 - partyid__tu
5 - permid__tu
6 - middlename__tu
7 - bigdebtorid__app
8 - bigaccountid__app
9 - bigdebtorid__ln
10 - bigaccountid__ln
11 - bigdealerid__app
12 - dtmstampcreation__base
13 - dtmapproved__base
14 - dtmdeclined__base
15 - dtmfunded__base
16 - creditasofdate__tu
17 - gnrcrem_frsrpt_dte__base
18 - observationdate__base
19 - open_dte__base
20 - decision_dte__base
21 - observationdate__tu
22 - dtmstampcreation__tu
23 - dateofbirth__tu
24 - chargeoffdate__app
25 - defaultdate__app
26 - dtmfunded__tu
27 - dtmfunded__app
28 - fundeddate__app
29 - dtmapproved__tu
30 - approvaldate__app
31 - dtmapproved__app
32 - dtmdeclined__tu
33 - dtmdeclined__app
34 - tu_creditbureaudate__tu
35 - credit_as_of_date__tu
36 - ssndatelowissued__ln
37 - dtmstampcreation__app
38 - score_cvpropensity__tu
39 - score_epd__tu
40 - score_newaccount__tu
41 - score_bankcard__tu
42 - score_cvauto__tu
43 - finscore__tu
44 - vantagescore3__tu
45 - syntheticfraud_score__tu
46 - bankcard_score__ln
47 - crossindustry_score__ln
48 - crossindustry_score_name__ln
49 - telecommunications_score__ln
50 - short_term_lending_score__ln
51 - bitfunded__app

### List of Leaky Features Manually

In [7]:
# create list leaky manual 
list_leaky_manual = [
    # obviously bad
    'bitlhmgroup__app',
    'bitfunded__app',
    'dealerzip__app',
    'dealercity__app',
    'analyticsmatchkey__tu',
    'strzipcode__app',
    'bitapproved__app',
    'strcity__app',
    'fltapprovedapr_contract__app',
    'subjectage__ln',
    'applicationmonth__app',
    'applicationdayofweek__app',
    'applicationquarter__app',
    'fltapproveddebttoincome__app',
    'bitsystemdecline__app',
    'addrinputtaxyr__ln',
    'bitrolled__app',
    'addrcurrenttaxyr__ln',
    # probably bad
    'linkb011__tu',
    'fltacquisitionfee__app',
    'flttaxgrossreceipts__app',
    # 24 month time-series features
    'agg101__tu',
    'agg102__tu',
    'agg103__tu',
    'agg104__tu',
    'agg105__tu',
    'agg106__tu',
    'agg107__tu',
    'agg108__tu',
    'agg109__tu',
    'agg110__tu',
    'agg111__tu',
    'agg112__tu',
    'agg113__tu',
    'agg114__tu',
    'agg115__tu',
    'agg116__tu',
    'agg117__tu',
    'agg118__tu',
    'agg119__tu',
    'agg120__tu',
    'agg121__tu',
    'agg122__tu',
    'agg123__tu',
    'agg124__tu',
    'agg201__tu',
    'agg202__tu',
    'agg203__tu',
    'agg204__tu',
    'agg205__tu',
    'agg206__tu',
    'agg207__tu',
    'agg208__tu',
    'agg209__tu',
    'agg210__tu',
    'agg211__tu',
    'agg212__tu',
    'agg213__tu',
    'agg214__tu',
    'agg215__tu',
    'agg216__tu',
    'agg217__tu',
    'agg218__tu',
    'agg219__tu',
    'agg220__tu',
    'agg221__tu',
    'agg222__tu',
    'agg223__tu',
    'agg224__tu',
    'agg301__tu',
    'agg302__tu',
    'agg303__tu',
    'agg304__tu',
    'agg305__tu',
    'agg306__tu',
    'agg307__tu',
    'agg308__tu',
    'agg309__tu',
    'agg310__tu',
    'agg311__tu',
    'agg312__tu',
    'agg313__tu',
    'agg314__tu',
    'agg315__tu',
    'agg316__tu',
    'agg317__tu',
    'agg318__tu',
    'agg319__tu',
    'agg320__tu',
    'agg321__tu',
    'agg322__tu',
    'agg323__tu',
    'agg324__tu',
    'agg401__tu',
    'agg402__tu',
    'agg403__tu',
    'agg404__tu',
    'agg405__tu',
    'agg406__tu',
    'agg407__tu',
    'agg408__tu',
    'agg409__tu',
    'agg410__tu',
    'agg411__tu',
    'agg412__tu',
    'agg413__tu',
    'agg414__tu',
    'agg415__tu',
    'agg416__tu',
    'agg417__tu',
    'agg418__tu',
    'agg419__tu',
    'agg420__tu',
    'agg421__tu',
    'agg422__tu',
    'agg423__tu',
    'agg424__tu',
    'agg501__tu',
    'agg502__tu',
    'agg503__tu',
    'agg504__tu',
    'agg505__tu',
    'agg506__tu',
    'agg507__tu',
    'agg508__tu',
    'agg509__tu',
    'agg510__tu',
    'agg511__tu',
    'agg512__tu',
    'agg513__tu',
    'agg514__tu',
    'agg515__tu',
    'agg516__tu',
    'agg517__tu',
    'agg518__tu',
    'agg519__tu',
    'agg520__tu',
    'agg521__tu',
    'agg522__tu',
    'agg523__tu',
    'agg524__tu',
    'agg601__tu',
    'agg602__tu',
    'agg603__tu',
    'agg604__tu',
    'agg605__tu',
    'agg606__tu',
    'agg607__tu',
    'agg608__tu',
    'agg609__tu',
    'agg610__tu',
    'agg611__tu',
    'agg612__tu',
    'agg613__tu',
    'agg614__tu',
    'agg615__tu',
    'agg616__tu',
    'agg617__tu',
    'agg618__tu',
    'agg619__tu',
    'agg620__tu',
    'agg621__tu',
    'agg622__tu',
    'agg623__tu',
    'agg624__tu',
    'agg701__tu',
    'agg702__tu',
    'agg703__tu',
    'agg704__tu',
    'agg705__tu',
    'agg706__tu',
    'agg707__tu',
    'agg708__tu',
    'agg709__tu',
    'agg710__tu',
    'agg711__tu',
    'agg712__tu',
    'agg713__tu',
    'agg714__tu',
    'agg715__tu',
    'agg716__tu',
    'agg717__tu',
    'agg718__tu',
    'agg719__tu',
    'agg720__tu',
    'agg721__tu',
    'agg722__tu',
    'agg723__tu',
    'agg724__tu',
    'agg801__tu',
    'agg802__tu',
    'agg803__tu',
    'agg804__tu',
    'agg805__tu',
    'agg806__tu',
    'agg807__tu',
    'agg808__tu',
    'agg809__tu',
    'agg810__tu',
    'agg811__tu',
    'agg812__tu',
    'agg813__tu',
    'agg814__tu',
    'agg815__tu',
    'agg816__tu',
    'agg817__tu',
    'agg818__tu',
    'agg819__tu',
    'agg820__tu',
    'agg821__tu',
    'agg822__tu',
    'agg823__tu',
    'agg824__tu',
    'aggs101__tu',
    'aggs102__tu',
    'aggs103__tu',
    'aggs104__tu',
    'aggs105__tu',
    'aggs106__tu',
    'aggs107__tu',
    'aggs108__tu',
    'aggs109__tu',
    'aggs110__tu',
    'aggs111__tu',
    'aggs112__tu',
    'aggs113__tu',
    'aggs114__tu',
    'aggs115__tu',
    'aggs116__tu',
    'aggs117__tu',
    'aggs118__tu',
    'aggs119__tu',
    'aggs120__tu',
    'aggs121__tu',
    'aggs122__tu',
    'aggs123__tu',
    'aggs124__tu',
    'rets101__tu',
    'rets102__tu',
    'rets103__tu',
    'rets104__tu',
    'rets105__tu',
    'rets106__tu',
    'rets107__tu',
    'rets108__tu',
    'rets109__tu',
    'rets110__tu',
    'rets111__tu',
    'rets112__tu',
    'rets113__tu',
    'rets114__tu',
    'rets115__tu',
    'rets116__tu',
    'rets117__tu',
    'rets118__tu',
    'rets119__tu',
    'rets120__tu',
    'rets121__tu',
    'rets122__tu',
    'rets123__tu',
    'rets124__tu',
    'revs101__tu',
    'revs102__tu',
    'revs103__tu',
    'revs104__tu',
    'revs105__tu',
    'revs106__tu',
    'revs107__tu',
    'revs108__tu',
    'revs109__tu',
    'revs110__tu',
    'revs111__tu',
    'revs112__tu',
    'revs113__tu',
    'revs114__tu',
    'revs115__tu',
    'revs116__tu',
    'revs117__tu',
    'revs118__tu',
    'revs119__tu',
    'revs120__tu',
    'revs121__tu',
    'revs122__tu',
    'revs123__tu',
    'revs124__tu',
    # 2024-05-07
    'strvehicletype__app', # unavailable at time of application
]

In [8]:
# check if cols in dataset
list_leaky_manual = [col for col in list_leaky_manual if col in list_cols]
print(f'There are {len(list_leaky_manual)} features to remove manually')
for a, col in enumerate(list_leaky_manual):
    print(f'{a+1} - {col}')

There are 285 features to remove manually
1 - bitlhmgroup__app
2 - bitfunded__app
3 - dealerzip__app
4 - dealercity__app
5 - analyticsmatchkey__tu
6 - strzipcode__app
7 - bitapproved__app
8 - strcity__app
9 - fltapprovedapr_contract__app
10 - subjectage__ln
11 - applicationmonth__app
12 - applicationdayofweek__app
13 - applicationquarter__app
14 - fltapproveddebttoincome__app
15 - bitsystemdecline__app
16 - addrinputtaxyr__ln
17 - bitrolled__app
18 - addrcurrenttaxyr__ln
19 - linkb011__tu
20 - fltacquisitionfee__app
21 - flttaxgrossreceipts__app
22 - agg101__tu
23 - agg102__tu
24 - agg103__tu
25 - agg104__tu
26 - agg105__tu
27 - agg106__tu
28 - agg107__tu
29 - agg108__tu
30 - agg109__tu
31 - agg110__tu
32 - agg111__tu
33 - agg112__tu
34 - agg113__tu
35 - agg114__tu
36 - agg115__tu
37 - agg116__tu
38 - agg117__tu
39 - agg118__tu
40 - agg119__tu
41 - agg120__tu
42 - agg121__tu
43 - agg122__tu
44 - agg123__tu
45 - agg124__tu
46 - agg201__tu
47 - agg202__tu
48 - agg203__tu
49 - agg204__tu
50 - agg205__tu
51 - agg206__tu
52 - agg207__tu
53 - agg208__tu
54 - agg209__tu
55 - agg210__tu
56 - agg211__tu
57 - agg212__tu
58 - agg213__tu
59 - agg214__tu
60 - agg215__tu
61 - agg216__tu
62 - agg217__tu
63 - agg218__tu
64 - agg219__tu
65 - agg220__tu
66 - agg221__tu
67 - agg222__tu
68 - agg223__tu
69 - agg224__tu
70 - agg301__tu
71 - agg302__tu
72 - agg303__tu
73 - agg304__tu
74 - agg305__tu
75 - agg306__tu
76 - agg307__tu
77 - agg308__tu
78 - agg309__tu
79 - agg310__tu
80 - agg311__tu
81 - agg312__tu
82 - agg313__tu
83 - agg314__tu
84 - agg315__tu
85 - agg316__tu
86 - agg317__tu
87 - agg318__tu
88 - agg319__tu
89 - agg320__tu
90 - agg321__tu
91 - agg322__tu
92 - agg323__tu
93 - agg324__tu
94 - agg401__tu
95 - agg402__tu
96 - agg403__tu
97 - agg404__tu
98 - agg405__tu
99 - agg406__tu
100 - agg407__tu
101 - agg408__tu
102 - agg409__tu
103 - agg410__tu
104 - agg411__tu
105 - agg412__tu
106 - agg413__tu
107 - agg414__tu
108 - agg415__tu
109 - agg416__tu
110 - agg417__tu
111 - agg418__tu
112 - agg419__tu
113 - agg420__tu
114 - agg421__tu
115 - agg422__tu
116 - agg423__tu
117 - agg424__tu
118 - agg501__tu
119 - agg502__tu
120 - agg503__tu
121 - agg504__tu
122 - agg505__tu
123 - agg506__tu
124 - agg507__tu
125 - agg508__tu
126 - agg509__tu
127 - agg510__tu
128 - agg511__tu
129 - agg512__tu
130 - agg513__tu
131 - agg514__tu
132 - agg515__tu
133 - agg516__tu
134 - agg517__tu
135 - agg518__tu
136 - agg519__tu
137 - agg520__tu
138 - agg521__tu
139 - agg522__tu
140 - agg523__tu
141 - agg524__tu
142 - agg601__tu
143 - agg602__tu
144 - agg603__tu
145 - agg604__tu
146 - agg605__tu
147 - agg606__tu
148 - agg607__tu
149 - agg608__tu
150 - agg609__tu
151 - agg610__tu
152 - agg611__tu
153 - agg612__tu
154 - agg613__tu
155 - agg614__tu
156 - agg615__tu
157 - agg616__tu
158 - agg617__tu
159 - agg618__tu
160 - agg619__tu
161 - agg620__tu
162 - agg621__tu
163 - agg622__tu
164 - agg623__tu
165 - agg624__tu
166 - agg701__tu
167 - agg702__tu
168 - agg703__tu
169 - agg704__tu
170 - agg705__tu
171 - agg706__tu
172 - agg707__tu
173 - agg708__tu
174 - agg709__tu
175 - agg710__tu
176 - agg711__tu
177 - agg712__tu
178 - agg713__tu
179 - agg714__tu
180 - agg715__tu
181 - agg716__tu
182 - agg717__tu
183 - agg718__tu
184 - agg719__tu
185 - agg720__tu
186 - agg721__tu
187 - agg722__tu
188 - agg723__tu
189 - agg724__tu
190 - agg801__tu
191 - agg802__tu
192 - agg803__tu
193 - agg804__tu
194 - agg805__tu
195 - agg806__tu
196 - agg807__tu
197 - agg808__tu
198 - agg809__tu
199 - agg810__tu
200 - agg811__tu
201 - agg812__tu
202 - agg813__tu
203 - agg814__tu
204 - agg815__tu
205 - agg816__tu
206 - agg817__tu
207 - agg818__tu
208 - agg819__tu
209 - agg820__tu
210 - agg821__tu
211 - agg822__tu
212 - agg823__tu
213 - agg824__tu
214 - aggs101__tu
215 - aggs102__tu
216 - aggs103__tu
217 - aggs104__tu
218 - aggs105__tu
219 - aggs106__tu
220 - aggs107__tu
221 - aggs108__tu
222 - aggs109__tu
223 - aggs110__tu
224 - aggs111__tu
225 - aggs112__tu
226 - aggs113__tu
227 - aggs114__tu
228 - aggs115__tu
229 - aggs116__tu
230 - aggs117__tu
231 - aggs118__tu
232 - aggs119__tu
233 - aggs120__tu
234 - aggs121__tu
235 - aggs122__tu
236 - aggs123__tu
237 - aggs124__tu
238 - rets101__tu
239 - rets102__tu
240 - rets103__tu
241 - rets104__tu
242 - rets105__tu
243 - rets106__tu
244 - rets107__tu
245 - rets108__tu
246 - rets109__tu
247 - rets110__tu
248 - rets111__tu
249 - rets112__tu
250 - rets113__tu
251 - rets114__tu
252 - rets115__tu
253 - rets116__tu
254 - rets117__tu
255 - rets118__tu
256 - rets119__tu
257 - rets120__tu
258 - rets121__tu
259 - rets122__tu
260 - rets123__tu
261 - rets124__tu
262 - revs101__tu
263 - revs102__tu
264 - revs103__tu
265 - revs104__tu
266 - revs105__tu
267 - revs106__tu
268 - revs107__tu
269 - revs108__tu
270 - revs109__tu
271 - revs110__tu
272 - revs111__tu
273 - revs112__tu
274 - revs113__tu
275 - revs114__tu
276 - revs115__tu
277 - revs116__tu
278 - revs117__tu
279 - revs118__tu
280 - revs119__tu
281 - revs120__tu
282 - revs121__tu
283 - revs122__tu
284 - revs123__tu
285 - revs124__tu

### Combine All Leaky Features and Remove Duplicates

In [9]:
# combine lists
list_cols_all = list_leaky_by_name + list_leaky_manual
list_cols_all = list(dict.fromkeys(list_cols_all))

# make df
df = pd.DataFrame({'feature': list_cols_all})

# save
str_filename = 'df_cols_drop.csv'
str_local_path = f'{str_dirname_output}/{str_filename}'
df.to_csv(str_local_path, index=False)

# show
df

          feature
0    bigaccountid
1     bigdebtorid
2      acctid__tu
3     partyid__tu
4      permid__tu
..            ...
330   revs120__tu
331   revs121__tu
332   revs122__tu
333   revs123__tu
334   revs124__tu

[335 rows x 1 columns]

### Save ```df_no_leaks.csv```

In [10]:
# create list of cols to keep
list_cols_keep = [col for col in list_cols if col not in list_cols_all]
# extend
list_cols_keep.extend(list_cols_id)
# rm dups
list_cols_keep = list(dict.fromkeys(list_cols_keep))

# create df
df = pd.DataFrame({'feature': list_cols_keep})
# save
str_filename = 'df_cols_noleaks.csv'
str_local_path = f'{str_dirname_output}/{str_filename}'
df.to_csv(str_local_path, index=False)

# show
df

                                 feature
0                        bitdebtor__base
1                             bkc224__tu
2                             bkc222__tu
3                             bkc205__tu
4                             bkc204__tu
...                                  ...
2148    bitdealerapplicantsamestate__app
2149  fltinsuredunemploymentpremium__app
2150                            uniqueid
2151                applicationdate__app
2152                              target

[2153 rows x 1 columns]