In [1]:
import os
import pandas as pd
import numpy as np
import datetime as dt
import pickle
from tqdm import tqdm
import warnings

# silence
warnings.filterwarnings('ignore')

try:
    import optbinning
except:
    ! pip install optbinning

(CVXPY) Feb 18 09:40:56 PM: Encountered unexpected exception importing solver GLOP:
RuntimeError('Unrecognized new version of ortools (9.11.4210). Expected < 9.10.0. Please open a feature request on cvxpy to enable support for this version.')
(CVXPY) Feb 18 09:40:56 PM: Encountered unexpected exception importing solver PDLP:
RuntimeError('Unrecognized new version of ortools (9.11.4210). Expected < 9.10.0. Please open a feature request on cvxpy to enable support for this version.')

In [2]:
print(f'Latest run date: {dt.datetime.now()}')

Latest run date: 2025-02-18 21:40:56.595726

#### Constants

In [3]:
str_dirname_output = './output'

#### Output dir

In [4]:
try:
    os.mkdir(str_dirname_output)
except:
    pass

#### Indirect

In [5]:
# get features in model
str_filename = 'df_feat_imp.csv'
str_local_path = f'../09_60_in_720/02_model/output/{str_filename}'
df_feat_imp = pd.read_csv(str_local_path)
list_cols_in_model = list(df_feat_imp['feature'])
list_cols_in_model = [f'{col.split("_binned")[0]}' for col in list_cols_in_model]

# get bins
str_filename = 'dict_bins.pkl'
str_local_path = f'../10_60_in_720_test/02_model/output/{str_filename}'
dict_bins = pickle.load(open(str_local_path, 'rb'))

# show binning table
list_df = []
for key, val in tqdm(dict_bins.items()):
    if key in list_cols_in_model:
        df_bins = val.binning_table.build()
        list_df.append(df_bins)
        df_bins['Feature'] = key
    else:
        pass

# concat
df = pd.concat(list_df)

# get the aa dict
list_cols = [
    'feature',
    'reason',
    'description',
]
str_filename = 'df_aa.csv'
str_local_path = f'../09_60_in_720/06_parser/input/{str_filename}'
df_aa = pd.read_csv(str_local_path, usecols=list_cols)

# rename
dict_rename = {
    'feature': 'Feature',
    'reason': 'Reason',
    'description': 'Description',
}
df_aa.rename(columns=dict_rename, inplace=True)

# join
df = pd.merge(
    left=df,
    right=df_aa,
    on='Feature',
    how='left',
)

# reorder
list_cols = [
    'Feature',
    'Bin',
    'Count',
    'Count (%)',
    'Non-event',
    'Event',
    'Event rate',
    'WoE',
    'IV',
    'JS',
    'Reason',
    'Description',
]
df = df[list_cols].copy()

# save
str_filename = 'df_bins_indirect.csv'
str_local_path = f'{str_dirname_output}/{str_filename}'
df.to_csv(str_local_path, index=False)

# show
df

100%|██████████| 1119/1119 [00:00<00:00, 5920.65it/s]

,Feature,Bin,Count,Count (%),Non-event,Event,Event rate,WoE,IV,JS,Reason,Description
0,fltgrossmonthly__income_sum,"(-inf, 3469.72)",10494,0.419458,5110,5384,0.513055,-0.109167,0.005002,0.000625,Insufficient income,NaN
1,fltgrossmonthly__income_sum,"[3469.72, 3682.94)",1304,0.052122,639,665,0.509969,-0.096817,0.000489,0.000061,Insufficient income,NaN
2,fltgrossmonthly__income_sum,"[3682.94, 4098.88)",2486,0.099368,1261,1225,0.492759,-0.02797,0.000078,0.000010,Insufficient income,NaN
3,fltgrossmonthly__income_sum,"[4098.88, 4339.04)",1482,0.059237,777,705,0.475709,0.040308,0.000096,0.000012,Insufficient income,NaN
4,fltgrossmonthly__income_sum,"[4339.04, 5249.95)",3933,0.157207,2080,1853,0.471142,0.058628,0.000540,0.000067,Insufficient income,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
307,phoneinputproblems__ln,"(-inf, 3.50)",13801,0.551643,7208,6593,0.477719,0.032249,0.000573,0.000072,Unable to verify working phone number,Indicates problems associated with the input p...
308,phoneinputproblems__ln,"[3.50, inf)",11217,0.448357,5657,5560,0.495676,-0.039639,0.000705,0.000088,Unable to verify working phone number,Indicates problems associated with the input p...
309,phoneinputproblems__ln,Special,0,0.000000,0,0,0.000000,0.0,0.000000,0.000000,Unable to verify working phone number,Indicates problems associated with the input p...
310,phoneinputproblems__ln,Missing,0,0.000000,0,0,0.000000,0.0,0.000000,0.000000,Unable to verify working phone number,Indicates problems associated with the input p...
311,phoneinputproblems__ln,,25018,1.000000,12865,12153,0.485770,,0.001278,0.000160,Unable to verify working phone number,Indicates problems associated with the input p...

#### Direct

In [6]:
# get features in model
str_filename = 'df_feat_imp.csv'
str_local_path = f'../13_60_in_720_dl/02_model/output/{str_filename}'
df_feat_imp = pd.read_csv(str_local_path)
list_cols_in_model = list(df_feat_imp['feature'])
list_cols_in_model = [f'{col.split("_binned")[0]}' for col in list_cols_in_model]

# get bins
str_filename = 'dict_bins.pkl'
str_local_path = f'../14_60_in_720_dl_test/02_model/output/{str_filename}'
dict_bins = pickle.load(open(str_local_path, 'rb'))

# show binning table
list_df = []
for key, val in tqdm(dict_bins.items()):
    if key in list_cols_in_model:
        df_bins = val.binning_table.build()
        list_df.append(df_bins)
        df_bins['Feature'] = key
    else:
        pass

# concat
df = pd.concat(list_df)

# get the aa dict
list_cols = [
    'feature',
    'reason',
    'description',
]
str_filename = 'df_aa.csv'
str_local_path = f'../13_60_in_720_dl/06_parser/input/{str_filename}'
df_aa = pd.read_csv(str_local_path, usecols=list_cols)

# rename
dict_rename = {
    'feature': 'Feature',
    'reason': 'Reason',
    'description': 'Description',
}
df_aa.rename(columns=dict_rename, inplace=True)

# join
df = pd.merge(
    left=df,
    right=df_aa,
    on='Feature',
    how='left',
)

# reorder
list_cols = [
    'Feature',
    'Bin',
    'Count',
    'Count (%)',
    'Non-event',
    'Event',
    'Event rate',
    'WoE',
    'IV',
    'JS',
    'Reason',
    'Description',
]
df = df[list_cols].copy()

# save
str_filename = 'df_bins_direct.csv'
str_local_path = f'{str_dirname_output}/{str_filename}'
df.to_csv(str_local_path, index=False)

# show
df

100%|██████████| 982/982 [00:00<00:00, 6565.95it/s]

,Feature,Bin,Count,Count (%),Non-event,Event,Event rate,WoE,IV,JS,Reason,Description
0,fltgrossmonthly__income_sum,"(-inf, 3245.78)",8676,0.346790,6106,2570,0.296219,-0.112058,0.004463,0.000558,Insufficient income,NaN
1,fltgrossmonthly__income_sum,"[3245.78, 3776.51)",3660,0.146295,2594,1066,0.291257,-0.088137,0.001159,0.000145,Insufficient income,NaN
2,fltgrossmonthly__income_sum,"[3776.51, 4116.78)",2048,0.081861,1502,546,0.266602,0.03451,0.000097,0.000012,Insufficient income,NaN
3,fltgrossmonthly__income_sum,"[4116.78, 4880.04)",3880,0.155088,2852,1028,0.264948,0.042981,0.000284,0.000035,Insufficient income,NaN
4,fltgrossmonthly__income_sum,"[4880.04, 5280.58)",1529,0.061116,1127,402,0.262917,0.053438,0.000172,0.000022,Insufficient income,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
243,flt_wtd_avg_closed__tu_pmthx,"[0.39, 0.81)",2584,0.103286,1932,652,0.252322,0.108842,0.001193,0.000149,Derogatory Payments on Accounts,Weighted average of payment history string of ...
244,flt_wtd_avg_closed__tu_pmthx,"[0.81, inf)",6000,0.239827,4616,1384,0.230667,0.227126,0.011718,0.001462,Derogatory Payments on Accounts,Weighted average of payment history string of ...
245,flt_wtd_avg_closed__tu_pmthx,Special,0,0.000000,0,0,0.000000,0.0,0.000000,0.000000,Derogatory Payments on Accounts,Weighted average of payment history string of ...
246,flt_wtd_avg_closed__tu_pmthx,Missing,0,0.000000,0,0,0.000000,0.0,0.000000,0.000000,Derogatory Payments on Accounts,Weighted average of payment history string of ...
247,flt_wtd_avg_closed__tu_pmthx,,25018,1.000000,18178,6840,0.273403,,0.019721,0.002461,Derogatory Payments on Accounts,Weighted average of payment history string of ...