In [1]:
import pandas as pd
import os
import numpy as np

# Constants

In [2]:
str_project = os.getcwd().split('\\')[4]
print(str_project)
str_task = os.getcwd().split('\\')[5]
print(str_task)
str_subtask = os.getcwd().split('\\')[6]
print(str_subtask)

str_dirname_output = './output'

06_ml_in_python
03_homecredit_default_risk_model
01_data_collection

In [3]:
os.getcwd()

'M:\\Risk Management\\Bridger Hyde\\20240521_bridger_internship\\06_ml_in_python\\03_homecredit_default_risk_model\\01_data_collection'

In [4]:
try:
    os.mkdir(str_dirname_output)
except FileExistsError:
    pass

# Pull In CSV's

In [5]:
dftest = pd.read_csv('./input/application_test.csv')
dftest

,SK_ID_CURR,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100001,Cash loans,F,N,Y,0,135000.0,568800.0,20560.5,450000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
1,100005,Cash loans,M,N,Y,0,99000.0,222768.0,17370.0,180000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
2,100013,Cash loans,M,Y,Y,0,202500.0,663264.0,69777.0,630000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,4.0
3,100028,Cash loans,F,N,Y,2,315000.0,1575000.0,49018.5,1575000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
4,100038,Cash loans,M,Y,N,1,180000.0,625500.0,32067.0,625500.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48739,456221,Cash loans,F,N,Y,0,121500.0,412560.0,17473.5,270000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
48740,456222,Cash loans,F,N,N,2,157500.0,622413.0,31909.5,495000.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
48741,456223,Cash loans,F,Y,Y,1,202500.0,315000.0,33205.5,315000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,3.0,1.0
48742,456224,Cash loans,M,N,N,0,225000.0,450000.0,25128.0,450000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
48743,456250,Cash loans,F,Y,N,0,135000.0,312768.0,24709.5,270000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,4.0

In [6]:
dftrain = pd.read_csv('./input/application_train_full.csv')
dftrain

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307506,456251,0,Cash loans,M,N,N,0,157500.0,254700.0,27558.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307507,456252,0,Cash loans,F,N,Y,0,72000.0,269550.0,12001.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307508,456253,0,Cash loans,F,N,Y,0,153000.0,677664.0,29979.0,...,0,0,0,0,1.0,0.0,0.0,1.0,0.0,1.0
307509,456254,1,Cash loans,F,N,Y,0,171000.0,370107.0,20205.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
307510,456255,0,Cash loans,F,N,N,0,157500.0,675000.0,49117.5,...,0,0,0,0,0.0,0.0,0.0,2.0,0.0,1.0

In [7]:
dfbur = pd.read_csv('./input/bureau.csv')
dfbur

,SK_ID_CURR,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY
0,215354,5714462,Closed,currency 1,-497,0,-153.0,-153.0,NaN,0,91323.00,0.0,NaN,0.0,Consumer credit,-131,NaN
1,215354,5714463,Active,currency 1,-208,0,1075.0,NaN,NaN,0,225000.00,171342.0,NaN,0.0,Credit card,-20,NaN
2,215354,5714464,Active,currency 1,-203,0,528.0,NaN,NaN,0,464323.50,NaN,NaN,0.0,Consumer credit,-16,NaN
3,215354,5714465,Active,currency 1,-203,0,NaN,NaN,NaN,0,90000.00,NaN,NaN,0.0,Credit card,-16,NaN
4,215354,5714466,Active,currency 1,-629,0,1197.0,NaN,77674.5,0,2700000.00,NaN,NaN,0.0,Consumer credit,-21,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1716423,259355,5057750,Active,currency 1,-44,0,-30.0,NaN,0.0,0,11250.00,11250.0,0.0,0.0,Microloan,-19,NaN
1716424,100044,5057754,Closed,currency 1,-2648,0,-2433.0,-2493.0,5476.5,0,38130.84,0.0,0.0,0.0,Consumer credit,-2493,NaN
1716425,100044,5057762,Closed,currency 1,-1809,0,-1628.0,-970.0,NaN,0,15570.00,NaN,NaN,0.0,Consumer credit,-967,NaN
1716426,246829,5057770,Closed,currency 1,-1878,0,-1513.0,-1513.0,NaN,0,36000.00,0.0,0.0,0.0,Consumer credit,-1508,NaN
1716427,246829,5057778,Closed,currency 1,-463,0,NaN,-387.0,NaN,0,22500.00,0.0,NaN,0.0,Microloan,-387,NaN

In [8]:
dfburbal = pd.read_csv('./input/bureau_balance.csv')
dfburbal

          SK_ID_BUREAU  MONTHS_BALANCE STATUS
0              5715448               0      C
1              5715448              -1      C
2              5715448              -2      C
3              5715448              -3      C
4              5715448              -4      C
...                ...             ...    ...
27299920       5041336             -47      X
27299921       5041336             -48      X
27299922       5041336             -49      X
27299923       5041336             -50      X
27299924       5041336             -51      X

[27299925 rows x 3 columns]

# Get max bureau Balance

In [9]:
dfburmax = dfburbal.loc[dfburbal.groupby('SK_ID_BUREAU')['MONTHS_BALANCE'].idxmin()]
dfburmax = dfburmax.reset_index(drop=True)
dfburmax

        SK_ID_BUREAU  MONTHS_BALANCE STATUS
0            5001709             -96      X
1            5001710             -82      X
2            5001711              -3      0
3            5001712             -18      0
4            5001713             -21      X
...              ...             ...    ...
817390       6842884             -47      X
817391       6842885             -23      0
817392       6842886             -32      0
817393       6842887             -36      0
817394       6842888             -61      0

[817395 rows x 3 columns]

## merge bureau balance and bureau

In [44]:
dfbureau = pd.merge(dfbur, dfburmax, on='SK_ID_BUREAU', how='inner')
dfbureau

,SK_ID_CURR,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY,MONTHS_BALANCE,STATUS
0,380361,5715448,Active,currency 1,-820,0,31069.0,NaN,NaN,0,67500.0,0.00,67500.00,0.0,Credit card,-183,0.0,-26,X
1,380361,5715449,Active,currency 1,-357,0,1119.0,NaN,NaN,0,45000.0,0.00,45000.00,0.0,Credit card,-130,2691.0,-11,X
2,380361,5715451,Closed,currency 1,-917,0,-187.0,-759.0,NaN,0,74439.0,0.00,0.00,0.0,Consumer credit,-748,0.0,-30,X
3,380361,5715452,Closed,currency 1,-993,0,31039.0,-831.0,NaN,0,315000.0,0.00,0.00,0.0,Credit card,-818,0.0,-32,X
4,380361,5715453,Closed,currency 1,-1146,0,681.0,-780.0,NaN,0,2025000.0,0.00,0.00,0.0,Consumer credit,-769,0.0,-37,X
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
774349,229054,5053730,Active,currency 1,-456,0,1372.0,NaN,0.0,0,67500.0,63530.46,3969.54,0.0,Credit card,-3,NaN,-14,X
774350,254479,5053734,Active,currency 1,-1571,0,986.0,NaN,NaN,0,142294.5,NaN,NaN,0.0,Consumer credit,-2,NaN,-51,0
774351,363575,5053740,Closed,currency 1,-1234,0,-503.0,-502.0,NaN,0,900000.0,0.00,0.00,0.0,Consumer credit,-461,58554.0,-40,X
774352,245498,5053747,Closed,currency 1,-2582,0,-2214.0,-2018.0,0.0,0,49495.5,0.00,0.00,0.0,Consumer credit,-2017,12600.0,-84,0
774353,407724,5053758,Closed,currency 1,-2423,0,-2150.0,-2175.0,NaN,0,21883.5,0.00,NaN,0.0,Consumer credit,-787,NaN,-79,X

In [11]:
# export merged Bureau to csv
dfbureau.to_csv('./output/bureau.csv', index=False)

In [5]:
dfcreditcard = pd.read_csv('./input/credit_card_balance.csv')
dfcreditcard

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_OTHER_CURRENT,AMT_DRAWINGS_POS_CURRENT,AMT_INST_MIN_REGULARITY,...,AMT_RECIVABLE,AMT_TOTAL_RECEIVABLE,CNT_DRAWINGS_ATM_CURRENT,CNT_DRAWINGS_CURRENT,CNT_DRAWINGS_OTHER_CURRENT,CNT_DRAWINGS_POS_CURRENT,CNT_INSTALMENT_MATURE_CUM,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF
0,2562384,378907,-6,56.970,135000,0.0,877.5,0.0,877.5,1700.325,...,0.000,0.000,0.0,1,0.0,1.0,35.0,Active,0,0
1,2582071,363914,-1,63975.555,45000,2250.0,2250.0,0.0,0.0,2250.000,...,64875.555,64875.555,1.0,1,0.0,0.0,69.0,Active,0,0
2,1740877,371185,-7,31815.225,450000,0.0,0.0,0.0,0.0,2250.000,...,31460.085,31460.085,0.0,0,0.0,0.0,30.0,Active,0,0
3,1389973,337855,-4,236572.110,225000,2250.0,2250.0,0.0,0.0,11795.760,...,233048.970,233048.970,1.0,1,0.0,0.0,10.0,Active,0,0
4,1891521,126868,-1,453919.455,450000,0.0,11547.0,0.0,11547.0,22924.890,...,453919.455,453919.455,0.0,1,0.0,1.0,101.0,Active,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3840307,1036507,328243,-9,0.000,45000,NaN,0.0,NaN,NaN,0.000,...,0.000,0.000,NaN,0,NaN,NaN,0.0,Active,0,0
3840308,1714892,347207,-9,0.000,45000,0.0,0.0,0.0,0.0,0.000,...,0.000,0.000,0.0,0,0.0,0.0,23.0,Active,0,0
3840309,1302323,215757,-9,275784.975,585000,270000.0,270000.0,0.0,0.0,2250.000,...,273093.975,273093.975,2.0,2,0.0,0.0,18.0,Active,0,0
3840310,1624872,430337,-10,0.000,450000,NaN,0.0,NaN,NaN,0.000,...,0.000,0.000,NaN,0,NaN,NaN,0.0,Active,0,0
3840311,2411345,236760,-10,0.000,157500,0.0,0.0,0.0,0.0,0.000,...,0.000,0.000,0.0,0,0.0,0.0,21.0,Completed,0,0

# aggregate credit DF to save space

In [8]:
dfaggcredit = dfcreditcard.groupby(['SK_ID_PREV', 'SK_ID_CURR']).agg({
    'AMT_BALANCE': 'sum',  # Calculate the mean of 'value1'
    'AMT_CREDIT_LIMIT_ACTUAL': 'sum',
    'AMT_DRAWINGS_ATM_CURRENT': 'sum',# Calculate the sum of 'value2'
    'AMT_DRAWINGS_CURRENT': 'sum',
    'AMT_DRAWINGS_POS_CURRENT': 'sum',
    'AMT_INST_MIN_REGULARITY': 'sum',
    'AMT_PAYMENT_CURRENT': 'sum',
    'AMT_PAYMENT_TOTAL_CURRENT':'sum',
    'AMT_RECEIVABLE_PRINCIPAL':'sum',
    'AMT_RECIVABLE': 'sum',
    'AMT_TOTAL_RECEIVABLE': 'sum',
    'CNT_DRAWINGS_ATM_CURRENT': 'sum',
    'CNT_DRAWINGS_CURRENT': 'sum',
    'CNT_DRAWINGS_OTHER_CURRENT': 'sum',
    'CNT_DRAWINGS_POS_CURRENT': 'sum',
    'CNT_INSTALMENT_MATURE_CUM': 'sum',
    'SK_DPD':'sum',
    'SK_DPD_DEF':'sum'
}).reset_index()

dfaggcredit

,SK_ID_PREV,SK_ID_CURR,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_POS_CURRENT,AMT_INST_MIN_REGULARITY,AMT_PAYMENT_CURRENT,AMT_PAYMENT_TOTAL_CURRENT,AMT_RECEIVABLE_PRINCIPAL,AMT_RECIVABLE,AMT_TOTAL_RECEIVABLE,CNT_DRAWINGS_ATM_CURRENT,CNT_DRAWINGS_CURRENT,CNT_DRAWINGS_OTHER_CURRENT,CNT_DRAWINGS_POS_CURRENT,CNT_INSTALMENT_MATURE_CUM,SK_DPD,SK_DPD_DEF
0,1000018,394447,374731.425,405000,27000.0,147394.980,120394.980,12970.440,27708.750,27708.750,361490.985,368012.925,368012.925,6.0,44,0.0,38.0,10.0,0,0
1,1000030,361282,447928.515,652500,4500.0,138059.505,133559.505,16625.790,43320.420,21263.580,443795.625,447483.015,447483.015,1.0,41,0.0,40.0,15.0,0,0
2,1000031,131335,838311.030,2394000,157500.0,463353.840,305853.840,42804.810,354519.090,354519.090,822446.055,833599.530,833599.530,4.0,21,0.0,17.0,59.0,0,0
3,1000035,436351,0.000,1125000,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0,0.0,0.0,0.0,0,0
4,1000077,181153,0.000,1035000,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0,0.0,0.0,0.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104302,2843476,197090,3604092.165,15345000,90000.0,90000.000,0.000,327159.135,329404.905,328513.500,3416069.475,3622657.320,3641557.320,2.0,2,0.0,0.0,3229.0,1428,330
104303,2843477,168439,141361.515,1350000,58500.0,58500.000,0.000,10345.860,81197.550,67410.000,132619.005,139800.735,139800.735,6.0,6,0.0,0.0,330.0,0,0
104304,2843478,424526,460026.450,1890000,90000.0,90000.000,0.000,40528.350,122021.550,109980.000,440196.615,458796.780,458796.780,4.0,4,0.0,0.0,845.0,0,0
104305,2843493,337804,887098.905,2295000,0.0,108257.400,108257.400,42307.920,73137.060,61986.735,850963.500,875772.270,875772.270,0.0,7,0.0,7.0,91.0,0,0
104306,2843496,425374,665605.215,9450000,220500.0,272679.075,52179.075,43855.065,304211.385,260356.320,652193.145,661377.465,661377.465,3.0,28,0.0,25.0,87.0,0,0

In [12]:
#export aggregated credit card DF to csv
dfaggcredit.to_csv('./output/creditcard.csv', index=False)

# aggregate installment payments DF to save space

In [9]:
dfinstall = pd.read_csv('./input/installments_payments.csv')
dfinstall

,SK_ID_PREV,SK_ID_CURR,NUM_INSTALMENT_VERSION,NUM_INSTALMENT_NUMBER,DAYS_INSTALMENT,DAYS_ENTRY_PAYMENT,AMT_INSTALMENT,AMT_PAYMENT
0,1054186,161674,1.0,6,-1180.0,-1187.0,6948.360,6948.360
1,1330831,151639,0.0,34,-2156.0,-2156.0,1716.525,1716.525
2,2085231,193053,2.0,1,-63.0,-63.0,25425.000,25425.000
3,2452527,199697,1.0,3,-2418.0,-2426.0,24350.130,24350.130
4,2714724,167756,1.0,2,-1383.0,-1366.0,2165.040,2160.585
...,...,...,...,...,...,...,...,...
13605396,2186857,428057,0.0,66,-1624.0,NaN,67.500,NaN
13605397,1310347,414406,0.0,47,-1539.0,NaN,67.500,NaN
13605398,1308766,402199,0.0,43,-7.0,NaN,43737.435,NaN
13605399,1062206,409297,0.0,43,-1986.0,NaN,67.500,NaN
13605400,2448869,434321,1.0,19,-27.0,NaN,11504.250,NaN

In [11]:
dfagginstall = dfinstall.groupby(['SK_ID_PREV','SK_ID_CURR']).agg({
    'AMT_INSTALMENT':'sum',
    'AMT_PAYMENT':'sum'
}).reset_index()

dfagginstall['PAID_OFF'] = np.where(dfagginstall['AMT_PAYMENT'] >= dfagginstall['AMT_INSTALMENT'], 1, 0)
dfagginstall

        SK_ID_PREV  SK_ID_CURR  AMT_INSTALMENT  AMT_PAYMENT  PAID_OFF
0          1000001      158271       68443.425    68443.425         1
1          1000002      101962       37235.565    37235.565         1
2          1000003      252457       14854.050    14854.050         1
3          1000004      260094       33523.155    33523.155         1
4          1000005      176456      161735.310   147021.705         0
...            ...         ...             ...          ...       ...
997747     2843495      260963      797530.185   797530.185         1
997748     2843496      425374      312334.605   304333.155         0
997749     2843497      451578      183503.700   183503.700         1
997750     2843498      393881      414321.435   414321.435         1
997751     2843499      314148      578082.240   578082.240         1

[997752 rows x 5 columns]

In [13]:
# expoert installments aggregate DF to csv
dfagginstall.to_csv('./output/installments.csv', index=False)

In [16]:
dfpos = pd.read_csv('./input/POS_CASH_balance.csv')
dfpos

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,CNT_INSTALMENT,CNT_INSTALMENT_FUTURE,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF
0,1803195,182943,-31,48.0,45.0,Active,0,0
1,1715348,367990,-33,36.0,35.0,Active,0,0
2,1784872,397406,-32,12.0,9.0,Active,0,0
3,1903291,269225,-35,48.0,42.0,Active,0,0
4,2341044,334279,-35,36.0,35.0,Active,0,0
...,...,...,...,...,...,...,...,...
10001353,2448283,226558,-20,6.0,0.0,Active,843,0
10001354,1717234,141565,-19,12.0,0.0,Active,602,0
10001355,1283126,315695,-21,10.0,0.0,Active,609,0
10001356,1082516,450255,-22,12.0,0.0,Active,614,0
10001357,1259607,174278,-52,16.0,0.0,Completed,0,0

In [18]:
dfposagg = dfpos.groupby(['SK_ID_PREV','SK_ID_CURR']).agg({
    'CNT_INSTALMENT':'sum',
    'CNT_INSTALMENT_FUTURE':'sum',
    'SK_DPD':'sum',
    'SK_DPD_DEF':'sum'
}).reset_index()
dfposagg

,SK_ID_PREV,SK_ID_CURR,CNT_INSTALMENT,CNT_INSTALMENT_FUTURE,SK_DPD,SK_DPD_DEF
0,1000001,158271,26.0,23.0,0,0
1,1000002,101962,26.0,10.0,0,0
2,1000003,252457,48.0,42.0,0,0
3,1000004,260094,77.0,49.0,0,0
4,1000005,176456,110.0,55.0,0,0
...,...,...,...,...,...,...
936320,2843494,292375,98.0,95.0,0,0
936321,2843495,260963,427.0,399.0,0,0
936322,2843497,451578,504.0,294.0,0,0
936323,2843498,393881,192.0,170.0,0,0
936324,2843499,314148,560.0,502.0,0,0

In [19]:
dfposagg.to_csv('./output/pos.csv', index=False)

In [21]:
dfprev = pd.read_csv('./input/previous_application.csv')
dfprev

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,...,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
0,2030495,271877,Consumer loans,1730.430,17145.0,17145.0,0.0,17145.0,SATURDAY,15,...,Connectivity,12.0,middle,POS mobile with interest,365243.0,-42.0,300.0,-42.0,-37.0,0.0
1,2802425,108129,Cash loans,25188.615,607500.0,679671.0,NaN,607500.0,THURSDAY,11,...,XNA,36.0,low_action,Cash X-Sell: low,365243.0,-134.0,916.0,365243.0,365243.0,1.0
2,2523466,122040,Cash loans,15060.735,112500.0,136444.5,NaN,112500.0,TUESDAY,11,...,XNA,12.0,high,Cash X-Sell: high,365243.0,-271.0,59.0,365243.0,365243.0,1.0
3,2819243,176158,Cash loans,47041.335,450000.0,470790.0,NaN,450000.0,MONDAY,7,...,XNA,12.0,middle,Cash X-Sell: middle,365243.0,-482.0,-152.0,-182.0,-177.0,1.0
4,1784265,202054,Cash loans,31924.395,337500.0,404055.0,NaN,337500.0,THURSDAY,9,...,XNA,24.0,high,Cash Street: high,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1670209,2300464,352015,Consumer loans,14704.290,267295.5,311400.0,0.0,267295.5,WEDNESDAY,12,...,Furniture,30.0,low_normal,POS industry with interest,365243.0,-508.0,362.0,-358.0,-351.0,0.0
1670210,2357031,334635,Consumer loans,6622.020,87750.0,64291.5,29250.0,87750.0,TUESDAY,15,...,Furniture,12.0,middle,POS industry with interest,365243.0,-1604.0,-1274.0,-1304.0,-1297.0,0.0
1670211,2659632,249544,Consumer loans,11520.855,105237.0,102523.5,10525.5,105237.0,MONDAY,12,...,Consumer electronics,10.0,low_normal,POS household with interest,365243.0,-1457.0,-1187.0,-1187.0,-1181.0,0.0
1670212,2785582,400317,Cash loans,18821.520,180000.0,191880.0,NaN,180000.0,WEDNESDAY,9,...,XNA,12.0,low_normal,Cash X-Sell: low,365243.0,-1155.0,-825.0,-825.0,-817.0,1.0
1670213,2418762,261212,Cash loans,16431.300,360000.0,360000.0,NaN,360000.0,SUNDAY,10,...,XNA,48.0,middle,Cash X-Sell: middle,365243.0,-1163.0,247.0,-443.0,-423.0,0.0

In [27]:
dfprev.to_csv('./output/prev.csv',index=False)

In [28]:
dftrain.to_csv('./output/train.csv',index=False)
dftest.to_csv('./output/test.csv', index=False)