In [1]:
import os
import pandas as pd
import boto3
from tqdm import tqdm
import datetime as dt

In [2]:
print(f'Last run date: {dt.datetime.today()}')

Last run date: 2024-07-01 16:30:14.241536

#### constants

In [3]:
# project
str_project = os.getcwd().split('/')[4].replace('_','-')
print(f'Project: {str_project}')
# task
str_task = os.getcwd().split('/')[5]
print(f'Task: {str_task}')

Project: 20240423-gen-xii-payload-parsing
Task: 04_concat_results

#### get names of files in s3 bucket

In [5]:
# init
cls_client = boto3.client('s3')

# prefix
str_prefix = '03_step_function/parsed'

# list the files
dict_response = cls_client.list_objects_v2(Bucket=str_project, Prefix=str_prefix)

# get contents
list_dict_contents = dict_response['Contents']

# get the filenames
list_str_files = [dict_contents['Key'] for dict_contents in list_dict_contents]

# get only gzip
list_str_files = [str_file for str_file in list_str_files if '.gzip' in str_file]
print(f'There are {len(list_str_files)} parsed files:')
for a, str_file in enumerate(list_str_files):
    print(f'{a+1} - {str_file}')

There are 230 parsed files:
1 - 03_step_function/parsed/X_raw_1.gzip
2 - 03_step_function/parsed/X_raw_10.gzip
3 - 03_step_function/parsed/X_raw_100.gzip
4 - 03_step_function/parsed/X_raw_101.gzip
5 - 03_step_function/parsed/X_raw_102.gzip
6 - 03_step_function/parsed/X_raw_103.gzip
7 - 03_step_function/parsed/X_raw_104.gzip
8 - 03_step_function/parsed/X_raw_105.gzip
9 - 03_step_function/parsed/X_raw_106.gzip
10 - 03_step_function/parsed/X_raw_107.gzip
11 - 03_step_function/parsed/X_raw_108.gzip
12 - 03_step_function/parsed/X_raw_109.gzip
13 - 03_step_function/parsed/X_raw_11.gzip
14 - 03_step_function/parsed/X_raw_110.gzip
15 - 03_step_function/parsed/X_raw_111.gzip
16 - 03_step_function/parsed/X_raw_112.gzip
17 - 03_step_function/parsed/X_raw_113.gzip
18 - 03_step_function/parsed/X_raw_114.gzip
19 - 03_step_function/parsed/X_raw_115.gzip
20 - 03_step_function/parsed/X_raw_116.gzip
21 - 03_step_function/parsed/X_raw_117.gzip
22 - 03_step_function/parsed/X_raw_118.gzip
23 - 03_step_function/parsed/X_raw_119.gzip
24 - 03_step_function/parsed/X_raw_12.gzip
25 - 03_step_function/parsed/X_raw_120.gzip
26 - 03_step_function/parsed/X_raw_121.gzip
27 - 03_step_function/parsed/X_raw_122.gzip
28 - 03_step_function/parsed/X_raw_123.gzip
29 - 03_step_function/parsed/X_raw_124.gzip
30 - 03_step_function/parsed/X_raw_125.gzip
31 - 03_step_function/parsed/X_raw_126.gzip
32 - 03_step_function/parsed/X_raw_127.gzip
33 - 03_step_function/parsed/X_raw_128.gzip
34 - 03_step_function/parsed/X_raw_129.gzip
35 - 03_step_function/parsed/X_raw_13.gzip
36 - 03_step_function/parsed/X_raw_130.gzip
37 - 03_step_function/parsed/X_raw_131.gzip
38 - 03_step_function/parsed/X_raw_132.gzip
39 - 03_step_function/parsed/X_raw_133.gzip
40 - 03_step_function/parsed/X_raw_134.gzip
41 - 03_step_function/parsed/X_raw_135.gzip
42 - 03_step_function/parsed/X_raw_136.gzip
43 - 03_step_function/parsed/X_raw_137.gzip
44 - 03_step_function/parsed/X_raw_138.gzip
45 - 03_step_function/parsed/X_raw_139.gzip
46 - 03_step_function/parsed/X_raw_14.gzip
47 - 03_step_function/parsed/X_raw_140.gzip
48 - 03_step_function/parsed/X_raw_141.gzip
49 - 03_step_function/parsed/X_raw_142.gzip
50 - 03_step_function/parsed/X_raw_143.gzip
51 - 03_step_function/parsed/X_raw_144.gzip
52 - 03_step_function/parsed/X_raw_145.gzip
53 - 03_step_function/parsed/X_raw_146.gzip
54 - 03_step_function/parsed/X_raw_147.gzip
55 - 03_step_function/parsed/X_raw_148.gzip
56 - 03_step_function/parsed/X_raw_149.gzip
57 - 03_step_function/parsed/X_raw_15.gzip
58 - 03_step_function/parsed/X_raw_150.gzip
59 - 03_step_function/parsed/X_raw_151.gzip
60 - 03_step_function/parsed/X_raw_152.gzip
61 - 03_step_function/parsed/X_raw_153.gzip
62 - 03_step_function/parsed/X_raw_154.gzip
63 - 03_step_function/parsed/X_raw_155.gzip
64 - 03_step_function/parsed/X_raw_156.gzip
65 - 03_step_function/parsed/X_raw_157.gzip
66 - 03_step_function/parsed/X_raw_158.gzip
67 - 03_step_function/parsed/X_raw_159.gzip
68 - 03_step_function/parsed/X_raw_16.gzip
69 - 03_step_function/parsed/X_raw_160.gzip
70 - 03_step_function/parsed/X_raw_161.gzip
71 - 03_step_function/parsed/X_raw_162.gzip
72 - 03_step_function/parsed/X_raw_163.gzip
73 - 03_step_function/parsed/X_raw_164.gzip
74 - 03_step_function/parsed/X_raw_165.gzip
75 - 03_step_function/parsed/X_raw_166.gzip
76 - 03_step_function/parsed/X_raw_167.gzip
77 - 03_step_function/parsed/X_raw_168.gzip
78 - 03_step_function/parsed/X_raw_169.gzip
79 - 03_step_function/parsed/X_raw_17.gzip
80 - 03_step_function/parsed/X_raw_170.gzip
81 - 03_step_function/parsed/X_raw_171.gzip
82 - 03_step_function/parsed/X_raw_172.gzip
83 - 03_step_function/parsed/X_raw_173.gzip
84 - 03_step_function/parsed/X_raw_174.gzip
85 - 03_step_function/parsed/X_raw_175.gzip
86 - 03_step_function/parsed/X_raw_176.gzip
87 - 03_step_function/parsed/X_raw_177.gzip
88 - 03_step_function/parsed/X_raw_178.gzip
89 - 03_step_function/parsed/X_raw_179.gzip
90 - 03_step_function/parsed/X_raw_18.gzip
91 - 03_step_function/parsed/X_raw_180.gzip
92 - 03_step_function/parsed/X_raw_181.gzip
93 - 03_step_function/parsed/X_raw_182.gzip
94 - 03_step_function/parsed/X_raw_183.gzip
95 - 03_step_function/parsed/X_raw_184.gzip
96 - 03_step_function/parsed/X_raw_185.gzip
97 - 03_step_function/parsed/X_raw_186.gzip
98 - 03_step_function/parsed/X_raw_187.gzip
99 - 03_step_function/parsed/X_raw_188.gzip
100 - 03_step_function/parsed/X_raw_189.gzip
101 - 03_step_function/parsed/X_raw_19.gzip
102 - 03_step_function/parsed/X_raw_190.gzip
103 - 03_step_function/parsed/X_raw_191.gzip
104 - 03_step_function/parsed/X_raw_192.gzip
105 - 03_step_function/parsed/X_raw_193.gzip
106 - 03_step_function/parsed/X_raw_194.gzip
107 - 03_step_function/parsed/X_raw_195.gzip
108 - 03_step_function/parsed/X_raw_196.gzip
109 - 03_step_function/parsed/X_raw_197.gzip
110 - 03_step_function/parsed/X_raw_198.gzip
111 - 03_step_function/parsed/X_raw_199.gzip
112 - 03_step_function/parsed/X_raw_2.gzip
113 - 03_step_function/parsed/X_raw_20.gzip
114 - 03_step_function/parsed/X_raw_200.gzip
115 - 03_step_function/parsed/X_raw_201.gzip
116 - 03_step_function/parsed/X_raw_202.gzip
117 - 03_step_function/parsed/X_raw_203.gzip
118 - 03_step_function/parsed/X_raw_204.gzip
119 - 03_step_function/parsed/X_raw_205.gzip
120 - 03_step_function/parsed/X_raw_206.gzip
121 - 03_step_function/parsed/X_raw_207.gzip
122 - 03_step_function/parsed/X_raw_208.gzip
123 - 03_step_function/parsed/X_raw_209.gzip
124 - 03_step_function/parsed/X_raw_21.gzip
125 - 03_step_function/parsed/X_raw_210.gzip
126 - 03_step_function/parsed/X_raw_211.gzip
127 - 03_step_function/parsed/X_raw_212.gzip
128 - 03_step_function/parsed/X_raw_213.gzip
129 - 03_step_function/parsed/X_raw_214.gzip
130 - 03_step_function/parsed/X_raw_215.gzip
131 - 03_step_function/parsed/X_raw_216.gzip
132 - 03_step_function/parsed/X_raw_217.gzip
133 - 03_step_function/parsed/X_raw_218.gzip
134 - 03_step_function/parsed/X_raw_219.gzip
135 - 03_step_function/parsed/X_raw_22.gzip
136 - 03_step_function/parsed/X_raw_220.gzip
137 - 03_step_function/parsed/X_raw_221.gzip
138 - 03_step_function/parsed/X_raw_222.gzip
139 - 03_step_function/parsed/X_raw_223.gzip
140 - 03_step_function/parsed/X_raw_224.gzip
141 - 03_step_function/parsed/X_raw_225.gzip
142 - 03_step_function/parsed/X_raw_226.gzip
143 - 03_step_function/parsed/X_raw_227.gzip
144 - 03_step_function/parsed/X_raw_228.gzip
145 - 03_step_function/parsed/X_raw_229.gzip
146 - 03_step_function/parsed/X_raw_23.gzip
147 - 03_step_function/parsed/X_raw_230.gzip
148 - 03_step_function/parsed/X_raw_24.gzip
149 - 03_step_function/parsed/X_raw_25.gzip
150 - 03_step_function/parsed/X_raw_26.gzip
151 - 03_step_function/parsed/X_raw_27.gzip
152 - 03_step_function/parsed/X_raw_28.gzip
153 - 03_step_function/parsed/X_raw_29.gzip
154 - 03_step_function/parsed/X_raw_3.gzip
155 - 03_step_function/parsed/X_raw_30.gzip
156 - 03_step_function/parsed/X_raw_31.gzip
157 - 03_step_function/parsed/X_raw_32.gzip
158 - 03_step_function/parsed/X_raw_33.gzip
159 - 03_step_function/parsed/X_raw_34.gzip
160 - 03_step_function/parsed/X_raw_35.gzip
161 - 03_step_function/parsed/X_raw_36.gzip
162 - 03_step_function/parsed/X_raw_37.gzip
163 - 03_step_function/parsed/X_raw_38.gzip
164 - 03_step_function/parsed/X_raw_39.gzip
165 - 03_step_function/parsed/X_raw_4.gzip
166 - 03_step_function/parsed/X_raw_40.gzip
167 - 03_step_function/parsed/X_raw_41.gzip
168 - 03_step_function/parsed/X_raw_42.gzip
169 - 03_step_function/parsed/X_raw_43.gzip
170 - 03_step_function/parsed/X_raw_44.gzip
171 - 03_step_function/parsed/X_raw_45.gzip
172 - 03_step_function/parsed/X_raw_46.gzip
173 - 03_step_function/parsed/X_raw_47.gzip
174 - 03_step_function/parsed/X_raw_48.gzip
175 - 03_step_function/parsed/X_raw_49.gzip
176 - 03_step_function/parsed/X_raw_5.gzip
177 - 03_step_function/parsed/X_raw_50.gzip
178 - 03_step_function/parsed/X_raw_51.gzip
179 - 03_step_function/parsed/X_raw_52.gzip
180 - 03_step_function/parsed/X_raw_53.gzip
181 - 03_step_function/parsed/X_raw_54.gzip
182 - 03_step_function/parsed/X_raw_55.gzip
183 - 03_step_function/parsed/X_raw_56.gzip
184 - 03_step_function/parsed/X_raw_57.gzip
185 - 03_step_function/parsed/X_raw_58.gzip
186 - 03_step_function/parsed/X_raw_59.gzip
187 - 03_step_function/parsed/X_raw_6.gzip
188 - 03_step_function/parsed/X_raw_60.gzip
189 - 03_step_function/parsed/X_raw_61.gzip
190 - 03_step_function/parsed/X_raw_62.gzip
191 - 03_step_function/parsed/X_raw_63.gzip
192 - 03_step_function/parsed/X_raw_64.gzip
193 - 03_step_function/parsed/X_raw_65.gzip
194 - 03_step_function/parsed/X_raw_66.gzip
195 - 03_step_function/parsed/X_raw_67.gzip
196 - 03_step_function/parsed/X_raw_68.gzip
197 - 03_step_function/parsed/X_raw_69.gzip
198 - 03_step_function/parsed/X_raw_7.gzip
199 - 03_step_function/parsed/X_raw_70.gzip
200 - 03_step_function/parsed/X_raw_71.gzip
201 - 03_step_function/parsed/X_raw_72.gzip
202 - 03_step_function/parsed/X_raw_73.gzip
203 - 03_step_function/parsed/X_raw_74.gzip
204 - 03_step_function/parsed/X_raw_75.gzip
205 - 03_step_function/parsed/X_raw_76.gzip
206 - 03_step_function/parsed/X_raw_77.gzip
207 - 03_step_function/parsed/X_raw_78.gzip
208 - 03_step_function/parsed/X_raw_79.gzip
209 - 03_step_function/parsed/X_raw_8.gzip
210 - 03_step_function/parsed/X_raw_80.gzip
211 - 03_step_function/parsed/X_raw_81.gzip
212 - 03_step_function/parsed/X_raw_82.gzip
213 - 03_step_function/parsed/X_raw_83.gzip
214 - 03_step_function/parsed/X_raw_84.gzip
215 - 03_step_function/parsed/X_raw_85.gzip
216 - 03_step_function/parsed/X_raw_86.gzip
217 - 03_step_function/parsed/X_raw_87.gzip
218 - 03_step_function/parsed/X_raw_88.gzip
219 - 03_step_function/parsed/X_raw_89.gzip
220 - 03_step_function/parsed/X_raw_9.gzip
221 - 03_step_function/parsed/X_raw_90.gzip
222 - 03_step_function/parsed/X_raw_91.gzip
223 - 03_step_function/parsed/X_raw_92.gzip
224 - 03_step_function/parsed/X_raw_93.gzip
225 - 03_step_function/parsed/X_raw_94.gzip
226 - 03_step_function/parsed/X_raw_95.gzip
227 - 03_step_function/parsed/X_raw_96.gzip
228 - 03_step_function/parsed/X_raw_97.gzip
229 - 03_step_function/parsed/X_raw_98.gzip
230 - 03_step_function/parsed/X_raw_99.gzip

#### Concatenate files

In [6]:
%%time

list_df = []
for str_file in tqdm(list_str_files):
    # read
    str_uri = f's3://{str_project}/{str_file}'
    df = pd.read_parquet(str_uri)
    # append
    list_df.append(df)
# concat
df = pd.concat(list_df)
# save memory
del list_df

# show
df

100%|██████████| 230/230 [01:29<00:00,  2.56it/s]

CPU times: user 1min 4s, sys: 18.9 s, total: 1min 23s
Wall time: 1min 35s

,uniqueid__app,bigaccountid__app,bigdebtorid__app,bitdebtor__app,bigstatusid__app,strcity__app,strname__app,strzipcode__app,applicationdate__app,bitapproved__app,...,strvehicletype__app,bitgap__app,dealerstampcreation__app,RunningNetLoss,bitTarget24Months,target,bigAccountId,dtmFunded,BITDEBTOR,tu_was_empty__tu
6507952__primary__20221222,0__0__20221222,6507952,NaN,1,11,WAKARUSA,Indiana,46573,NaN,False,...,NaN,NaN,NaN,NaN,NaN,NaN,6507952,2023-01-03,1,NaN
6514953__primary__20221227,0__0__20221227,6514953,NaN,1,11,PHOENIX,Arizona,85016,NaN,False,...,NaN,NaN,NaN,NaN,NaN,NaN,6514953,2023-01-05,1,NaN
6523250__primary__20221231,0__0__20221231,6523250,NaN,1,11,CHICAGO,Illinois,60805,NaN,False,...,NaN,NaN,NaN,NaN,NaN,NaN,6523250,2023-01-10,1,NaN
6505279__primary__20221220,0__0__20221220,6505279,NaN,1,11,Slippery Rock,Pennsylvania,16057,NaN,False,...,NaN,NaN,NaN,NaN,NaN,NaN,6505279,2023-01-12,1,NaN
6491983__primary__20221213,0__0__20221213,6491983,NaN,1,11,DETROIT,Michigan,48213,NaN,False,...,NaN,NaN,NaN,NaN,NaN,NaN,6491983,2023-01-17,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7351323__primary__20231116,0__0__20231116,7351323,NaN,1,9,Burke,Virginia,22015,NaN,False,...,NaN,NaN,NaN,NaN,NaN,NaN,7351323,2023-11-30,1,NaN
7357885__primary__20231118,0__0__20231118,7357885,NaN,1,5,San Diego,California,92119,NaN,False,...,NaN,NaN,NaN,NaN,NaN,NaN,7357885,2023-12-04,1,NaN
7365253__primary__20231122,0__0__20231122,7365253,NaN,1,1,CUMBERLAND,Maryland,21502,NaN,False,...,NaN,NaN,NaN,NaN,NaN,NaN,7365253,2023-12-08,1,NaN
7333795__primary__20231114,0__0__20231114,7333795,NaN,1,1,BRAYMER,Missouri,64624,NaN,False,...,NaN,NaN,NaN,NaN,NaN,NaN,7333795,2023-12-20,1,NaN
7333795__secondary__20231114,0__0__20231114,7333795,NaN,0,1,BRAYMER,Missouri,64624,NaN,False,...,NaN,NaN,NaN,NaN,NaN,NaN,7333795,2023-12-20,0,NaN

In [7]:
list_cols_ = [col for col in list(df.columns) if '__ln' in col]
list_cols_

['uniqueid__ln',
 'biglnriskviewattributesv5id__ln',
 'bigaccountid__ln',
 'bigdebtorid__ln',
 'biglnriskviewscoreid__ln',
 'bitinvalid__ln',
 'dtmstampcreation__ln',
 'attribute_index__ln',
 'inputprovidedfirstname__ln',
 'inputprovidedlastname__ln',
 'inputprovidedstreetaddress__ln',
 'inputprovidedcity__ln',
 'inputprovidedstate__ln',
 'inputprovidedzipcode__ln',
 'inputprovidedssn__ln',
 'inputprovideddateofbirth__ln',
 'inputprovidedphone__ln',
 'inputprovidedlexid__ln',
 'subjectrecordtimeoldest__ln',
 'subjectrecordtimenewest__ln',
 'subjectnewestrecord12month__ln',
 'subjectactivityindex03month__ln',
 'subjectactivityindex06month__ln',
 'subjectactivityindex12month__ln',
 'subjectage__ln',
 'subjectdeceased__ln',
 'subjectssncount__ln',
 'subjectstabilityindex__ln',
 'subjectstabilityprimaryfactor__ln',
 'subjectabilityindex__ln',
 'subjectabilityprimaryfactor__ln',
 'subjectwillingnessindex__ln',
 'subjectwillingnessprimaryfactor__ln',
 'confirmationsubjectfound__ln',
 'confirmationinputname__ln',
 'confirmationinputdob__ln',
 'confirmationinputssn__ln',
 'confirmationinputaddress__ln',
 'sourcenonderogprofileindex__ln',
 'sourcenonderogcount__ln',
 'sourcenonderogcount03month__ln',
 'sourcenonderogcount06month__ln',
 'sourcenonderogcount12month__ln',
 'sourcecredheadertimeoldest__ln',
 'sourcecredheadertimenewest__ln',
 'sourcevoterregistration__ln',
 'educationattendance__ln',
 'educationevidence__ln',
 'educationprogramattended__ln',
 'educationinstitutionprivate__ln',
 'educationinstitutionrating__ln',
 'profliccount__ln',
 'proflictypecategory__ln',
 'businessassociation__ln',
 'businessassociationindex__ln',
 'businessassociationtimeoldest__ln',
 'businesstitleleadership__ln',
 'assetindex__ln',
 'assetindexprimaryfactor__ln',
 'assetownership__ln',
 'assetprop__ln',
 'assetpropindex__ln',
 'assetpropevercount__ln',
 'assetpropcurrentcount__ln',
 'assetpropcurrenttaxtotal__ln',
 'assetproppurchasecount12month__ln',
 'assetproppurchasetimeoldest__ln',
 'assetproppurchasetimenewest__ln',
 'assetpropnewestmortgagetype__ln',
 'assetpropeversoldcount__ln',
 'assetpropsoldcount12month__ln',
 'assetpropsaletimeoldest__ln',
 'assetpropsaletimenewest__ln',
 'assetpropnewestsaleprice__ln',
 'assetpropsalepurchaseratio__ln',
 'assetpersonal__ln',
 'assetpersonalcount__ln',
 'purchaseactivityindex__ln',
 'purchaseactivitycount__ln',
 'purchaseactivitydollartotal__ln',
 'derogseverityindex__ln',
 'derogcount__ln',
 'derogcount12month__ln',
 'derogtimenewest__ln',
 'criminalfelonycount__ln',
 'criminalfelonycount12month__ln',
 'criminalfelonytimenewest__ln',
 'criminalnonfelonycount__ln',
 'criminalnonfelonycount12month__ln',
 'criminalnonfelonytimenewest__ln',
 'evictioncount__ln',
 'evictioncount12month__ln',
 'evictiontimenewest__ln',
 'lienjudgmentseverityindex__ln',
 'lienjudgmentcount__ln',
 'lienjudgmentcount12month__ln',
 'lienjudgmentsmallclaimscount__ln',
 'lienjudgmentcourtcount__ln',
 'lienjudgmenttaxcount__ln',
 'lienjudgmentforeclosurecount__ln',
 'lienjudgmentothercount__ln',
 'lienjudgmenttimenewest__ln',
 'lienjudgmentdollartotal__ln',
 'bankruptcycount__ln',
 'bankruptcycount24month__ln',
 'bankruptcytimenewest__ln',
 'bankruptcychapter__ln',
 'bankruptcystatus__ln',
 'bankruptcydismissed24month__ln',
 'shorttermloanrequest__ln',
 'shorttermloanrequest12month__ln',
 'shorttermloanrequest24month__ln',
 'inquiryauto12month__ln',
 'inquirybanking12month__ln',
 'inquirytelcom12month__ln',
 'inquirynonshortterm12month__ln',
 'inquiryshortterm12month__ln',
 'inquirycollections12month__ln',
 'ssnsubjectcount__ln',
 'ssndeceased__ln',
 'ssndatelowissued__ln',
 'ssnproblems__ln',
 'addronfilecount__ln',
 'addronfilecorrectional__ln',
 'addronfilecollege__ln',
 'addronfilehighrisk__ln',
 'addrinputtimeoldest__ln',
 'addrinputtimenewest__ln',
 'addrinputlengthofres__ln',
 'addrinputsubjectcount__ln',
 'addrinputmatchindex__ln',
 'addrinputsubjectowned__ln',
 'addrinputdeedmailing__ln',
 'addrinputownershipindex__ln',
 'addrinputphoneservice__ln',
 'addrinputphonecount__ln',
 'addrinputdwelltype__ln',
 'addrinputdwelltypeindex__ln',
 'addrinputdelivery__ln',
 'addrinputtimelastsale__ln',
 'addrinputlastsaleprice__ln',
 'addrinputtaxvalue__ln',
 'addrinputtaxyr__ln',
 'addrinputtaxmarketvalue__ln',
 'addrinputavmvalue__ln',
 'addrinputavmvalue12month__ln',
 'addrinputavmratio12monthprior__ln',
 'addrinputavmvalue60month__ln',
 'addrinputavmratio60monthprior__ln',
 'addrinputcountyratio__ln',
 'addrinputtractratio__ln',
 'addrinputblockratio__ln',
 'addrinputproblems__ln',
 'addrcurrenttimeoldest__ln',
 'addrcurrenttimenewest__ln',
 'addrcurrentlengthofres__ln',
 'addrcurrentsubjectowned__ln',
 'addrcurrentdeedmailing__ln',
 'addrcurrentownershipindex__ln',
 'addrcurrentphoneservice__ln',
 'addrcurrentdwelltype__ln',
 'addrcurrentdwelltypeindex__ln',
 'addrcurrenttimelastsale__ln',
 'addrcurrentlastsalesprice__ln',
 'addrcurrenttaxvalue__ln',
 'addrcurrenttaxyr__ln',
 'addrcurrenttaxmarketvalue__ln',
 'addrcurrentavmvalue__ln',
 'addrcurrentavmvalue12month__ln',
 'addrcurrentavmratio12monthprior__ln',
 'addrcurrentavmvalue60month__ln',
 'addrcurrentavmratio60monthprior__ln',
 'addrcurrentcountyratio__ln',
 'addrcurrenttractratio__ln',
 'addrcurrentblockratio__ln',
 'addrcurrentcorrectional__ln',
 'addrprevioustimeoldest__ln',
 'addrprevioustimenewest__ln',
 'addrpreviouslengthofres__ln',
 'addrprevioussubjectowned__ln',
 'addrpreviousownershipindex__ln',
 'addrpreviousdwelltype__ln',
 'addrpreviousdwelltypeindex__ln',
 'addrpreviouscorrectional__ln',
 'addrstabilityindex__ln',
 'addrchangecount03month__ln',
 'addrchangecount06month__ln',
 'addrchangecount12month__ln',
 'addrchangecount24month__ln',
 'addrchangecount60month__ln',
 'addrlastmovetaxratiodiff__ln',
 'addrlastmoveecontrajectory__ln',
 'addrlastmoveecontrajectoryindex__ln',
 'phoneinputproblems__ln',
 'phoneinputsubjectcount__ln',
 'phoneinputmobile__ln',
 'alertregulatorycondition__ln',
 'analyticsmatchkey__ln',
 'auto_score__ln',
 'auto_reason1__ln',
 'auto_reason2__ln',
 'auto_reason3__ln',
 'auto_reason4__ln',
 'auto_reason5__ln',
 'bankcard_score__ln',
 'bankcard_reason1__ln',
 'bankcard_reason2__ln',
 'bankcard_reason3__ln',
 'bankcard_reason4__ln',
 'bankcard_reason5__ln',
 'short_term_lending_score__ln',
 'short_term_lending_reason1__ln',
 'short_term_lending_reason2__ln',
 'short_term_lending_reason3__ln',
 'short_term_lending_reason4__ln',
 'short_term_lending_reason5__ln',
 'telecommunications_score__ln',
 'telecommunications_reason1__ln',
 'telecommunications_reason2__ln',
 'telecommunications_reason3__ln',
 'telecommunications_reason4__ln',
 'telecommunications_reason5__ln',
 'crossindustry_index__ln',
 'crossindustry_score_name__ln',
 'crossindustry_score__ln',
 'crossindustry_reason1__ln',
 'crossindustry_reason2__ln',
 'crossindustry_reason3__ln',
 'crossindustry_reason4__ln',
 'crossindustry_reason5__ln',
 'alert1__ln',
 'alert2__ln',
 'alert3__ln',
 'alert4__ln',
 'alert5__ln',
 'alert6__ln',
 'alert7__ln',
 'alert8__ln',
 'alert9__ln',
 'alert10__ln',
 'intscore__ln']

In [8]:
df_tmp = df[list_cols_]
df_tmp.head(10)

,uniqueid__ln,biglnriskviewattributesv5id__ln,bigaccountid__ln,bigdebtorid__ln,biglnriskviewscoreid__ln,bitinvalid__ln,dtmstampcreation__ln,attribute_index__ln,inputprovidedfirstname__ln,inputprovidedlastname__ln,...,alert2__ln,alert3__ln,alert4__ln,alert5__ln,alert6__ln,alert7__ln,alert8__ln,alert9__ln,alert10__ln,intscore__ln
6507952__primary__20221222,"6507952,8129537",0,6507952,8129537,0,False,2022-12-22T10:08:57,NaN,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6514953__primary__20221227,"6514953,8138048",0,6514953,8138048,0,False,2022-12-27T19:12:51,NaN,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6523250__primary__20221231,"6523250,8148207",0,6523250,8148207,0,False,2022-12-31T14:50:24,NaN,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6505279__primary__20221220,"6505279,8126294",0,6505279,8126294,0,False,2022-12-20T15:03:08,NaN,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6491983__primary__20221213,"6491983,8109984",0,6491983,8109984,0,False,2022-12-13T10:45:17,NaN,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6551440__primary__20230116,"6551440,8182749",0,6551440,8182749,0,False,2023-01-16T13:57:19,NaN,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6527403__primary__20230103,"6527403,8153295",0,6527403,8153295,0,False,2023-01-03T17:30:56,NaN,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6561720__primary__20230121,"6561720,8195257",0,6561720,8195257,0,False,2023-01-21T10:58:27,NaN,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6561546__primary__20230121,"6561546,8195030",0,6561546,8195030,0,False,2023-01-21T10:30:47,NaN,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6551216__primary__20230116,"6551216,8182472",0,6551216,8182472,0,False,2023-01-16T12:59:53,NaN,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df.purchaseactivityindex__ln.value_counts()

purchaseactivityindex__ln
 0.0    26954
-1.0       73
Name: count, dtype: int64

#### Write to s3

In [10]:
%%time

# convert to string
for col in df.columns:
    if df[col].dtype not in ['int64', 'float64']:
        df[col] = df[col].astype(str)

str_filename = 'df_X_raw.gzip'
str_uri = f's3://{str_project}/{str_task}/{str_filename}'
df.to_parquet(str_uri, compression='gzip')

CPU times: user 8.6 s, sys: 25.3 ms, total: 8.62 s
Wall time: 8.71 s