In [1]:
import os
import pandas as pd
import numpy as np
import datetime as dt
import pickle

In [2]:
print(f'Last run date: {dt.datetime.now()}')

Last run date: 2025-02-18 21:40:12.794064

#### Constants

In [3]:
str_dirname_output = './output'

#### Make output directory

In [4]:
try:
    os.mkdir(str_dirname_output)
except:
    pass

#### Indirect

In [5]:
# get feature importance
str_filename = 'df_feat_imp.csv'
str_local_path = f'../09_60_in_720/02_model/output/{str_filename}'
df = pd.read_csv(str_local_path)

# get imputation dictionary
str_filename = 'dict_impute.pkl'
str_local_path = f'../10_60_in_720_test/02_model/output/{str_filename}'
dict_impute = pickle.load(open(str_local_path, 'rb'))

# add suffix
dict_impute = {f'{key}_binned': val for key, val in dict_impute.items()}

# map
df['imputation'] = df['feature'].map(dict_impute)

# rm suffix
df['feature'] = df['feature'].apply(
    lambda x: x.split('_binned')[0],
)

# reorder
list_cols = [
    'feature',
    'importance',
    'importance_abs',
    'imputation',
    'description',
]
df = df[list_cols].copy()

# save
str_filename = 'df_imputations_indirect.csv'
str_local_path = f'{str_dirname_output}/{str_filename}'
df.to_csv(str_local_path, index=False)

# show
df

,feature,importance,importance_abs,imputation,description
0,fltgrossmonthly__income_sum,-0.011405,0.011405,0.000000,NaN
1,miles_odometer__app,0.009920,0.009920,60518.520780,NaN
2,au20s__tu,-0.009259,0.009259,1.000000,Months since oldest auto trade opened
3,rtl_trd__tu,-0.008708,0.008708,0.000000,Number of retail trades
4,ENG-loan_to_value,0.008026,0.008026,1.273484,NaN
5,rev322__tu,-0.006039,0.006039,0.000000,Min Total Open-to-Buy for Revolving accounts o...
6,balmag01__tu,-0.005165,0.005165,600.000000,Non-mortgage balance magnitude algorithm over ...
7,g232s__tu,0.004912,0.004912,383.000000,Number of inquiries (includes duplicates)
8,g002s__tu,0.004893,0.004893,33.000000,Number of 60 days past due ratings in past 12 ...
9,linkt003__tu,-0.004751,0.004751,5.000000,Number of non-military non-corroborated addres...
10,inquirybanking12month__ln,0.004483,0.004483,1.000000,Indicates subject has one or more LexisNexis b...
11,all235__tu,-0.003952,0.003952,0.000000,Aggregate Excess Payment for All accounts over...
12,cv15__tu,-0.003812,0.003812,35.000000,Number of deduped auto inquiries
13,derogseverityindex__ln,-0.003061,0.003061,5.000000,Index indicating severity of derogatory record...
14,cv13__tu,-0.002990,0.002990,100.000000,Percentage of trades ever delinquent
15,ENG-wtd_avg,-0.002942,0.002942,0.000000,NaN
16,subjectabilityindex__ln,-0.002893,0.002893,1.000000,Modeled risk index indicating the subject's ab...
17,g407s__tu,0.002663,0.002663,24.000000,Number of deduped finance inquiries
18,ENG-franchise,0.002544,0.002544,0.000000,NaN
19,phoneinputproblems__ln,-0.002522,0.002522,6.000000,Indicates problems associated with the input p...
20,at24s__tu,-0.002251,0.002251,0.000000,Number of currently open and satisfactory trad...
21,jt20s__tu,-0.002242,0.002242,1.000000,Months since oldest joint trade opened
22,rp01s__tu,-0.002021,0.002021,4.000000,Number of repossession trades
23,sourcenonderogcount12month__ln,0.001987,0.001987,0.000000,Total non-derogatory source types on file for ...
24,in21s__tu,0.001910,0.001910,0.000000,Months since most recent installment trade opened
25,ENG-bk,-0.001906,0.001906,0.000000,NaN
26,bc97a__tu,0.001727,0.001727,0.000000,Total open to buy of open credit cards verifie...
27,addrprevioustimenewest__ln,-0.001587,0.001587,1.000000,Time (in months) since the subject was most re...
28,trv01__tu,-0.001426,0.001426,1.000000,Number of months since overlimit on a bankcard
29,s068b__tu,0.001389,0.001389,18.000000,Number of non-medical third party collections
30,in34s__tu,-0.001125,0.001125,536.000000,Utilization for open installment trades verifi...
31,addronfilecount__ln,0.001080,0.001080,40.000000,Total number of addresses found on file in sub...
32,linka053__tu,-0.001066,0.001066,0.000000,Number of days since the first (oldest) checki...
33,fi101s__tu,-0.000670,0.000670,291954.000000,Total balance of all finance installment trade...
34,fi36s__tu,0.000577,0.000577,0.000000,Months since most recent finance installment d...
35,linkf098__tu,-0.000544,0.000544,0.000000,Number of satisfactory trades
36,linka006__tu,-0.000502,0.000502,162.000000,Number of total inquiries in the last 3 years....
37,fi25s__tu,-0.000501,0.000501,0.000000,Number of currently open and satisfactory fina...
38,addrinputsubjectcount__ln,-0.000408,0.000408,83.000000,Total number of unique subjects on file curren...
39,linka025__tu,0.000403,0.000403,9.000000,Number of other inquiries in the last 3 years....
40,g251c__tu,-0.000334,0.000334,51.000000,Number of 60 days past due or worse items in t...
41,inquiryshortterm12month__ln,0.000331,0.000331,1.000000,Indicates subject has one or more LexisNexis p...
42,g095s__tu,0.000280,0.000280,0.000000,Months since most recent public record
43,s209a__tu,0.000218,0.000218,0.000000,Months since most recent non-medical third par...
44,inquirynonshortterm12month__ln,-0.000088,0.000088,1.000000,Indicates subject has one or more LexisNexis c...

#### Direct

In [6]:
# get feature importance
str_filename = 'df_feat_imp.csv'
str_local_path = f'../13_60_in_720_dl/02_model/output/{str_filename}'
df = pd.read_csv(str_local_path)

# get imputation dictionary
str_filename = 'dict_impute.pkl'
str_local_path = f'../14_60_in_720_dl_test/02_model/output/{str_filename}'
dict_impute = pickle.load(open(str_local_path, 'rb'))

# add suffix
dict_impute = {f'{key}_binned': val for key, val in dict_impute.items()}

# map
df['imputation'] = df['feature'].map(dict_impute)

# rm suffix
df['feature'] = df['feature'].apply(
    lambda x: x.split('_binned')[0],
)

# reorder
list_cols = [
    'feature',
    'importance',
    'importance_abs',
    'imputation',
    'description',
]
df = df[list_cols].copy()

# save
str_filename = 'df_imputations_direct.csv'
str_local_path = f'{str_dirname_output}/{str_filename}'
df.to_csv(str_local_path, index=False)

# show
df

,feature,importance,importance_abs,imputation,description
0,linkt001__tu,-0.018050,0.018050,19.000000,Number of non-military addresses in last 7 years
1,au20s__tu,-0.016539,0.016539,1.000000,Months since oldest auto trade opened
2,rtl_trd__tu,-0.012721,0.012721,0.000000,Number of retail trades
3,rev326__tu,-0.012705,0.012705,0.000000,Average Total Open-to-Buy for Revolving accoun...
4,br109s__tu,-0.011817,0.011817,11.000000,Number of bank revolving trades with past due ...
5,miles_odometer__app,0.011778,0.011778,60518.520780,NaN
6,fltgrossmonthly__income_sum,-0.010692,0.010692,0.000000,NaN
7,balmag01__tu,-0.009710,0.009710,600.000000,Non-mortgage balance magnitude algorithm over ...
8,ENG-loan_to_value,0.007732,0.007732,1.273484,NaN
9,int_n_months_open__tu_pmthx,-0.006530,0.006530,0.000000,NaN
10,rp01s__tu,-0.005521,0.005521,4.000000,Number of repossession trades
11,jt20s__tu,-0.005161,0.005161,1.000000,Months since oldest joint trade opened
12,trv10__tu,-0.004991,0.004991,0.000000,Number of months non-mortgage balance decrease...
13,trv13__tu,-0.004962,0.004962,0.000000,Number of revolving high credit increases YOY
14,cv15__tu,-0.004517,0.004517,35.000000,Number of deduped auto inquiries
15,linkt003__tu,-0.004005,0.004005,5.000000,Number of non-military non-corroborated addres...
16,g002s__tu,0.003729,0.003729,33.000000,Number of 60 days past due ratings in past 12 ...
17,flt_wtd_avg_closed__tu_pmthx,-0.002997,0.002997,0.000000,NaN
18,co01s__tu,0.002987,0.002987,43.000000,Number of charged-off trades
19,g407s__tu,0.002769,0.002769,24.000000,Number of deduped finance inquiries
20,g232s__tu,0.002478,0.002478,383.000000,Number of inquiries (includes duplicates)
21,linkf098__tu,-0.002359,0.002359,0.000000,Number of satisfactory trades
22,st20s__tu,-0.002084,0.002084,1.000000,Months since oldest student loan trade opened
23,per235__tu,-0.001795,0.001795,0.000000,Aggregate Excess Payment for Personal Loan acc...
24,linka006__tu,-0.001470,0.001470,162.000000,Number of total inquiries in the last 3 years....
25,in30s__tu,-0.001339,0.001339,100.000000,Percentage of open installment trades > 50% of...
26,linka003__tu,0.001130,0.001130,9.000000,Number of other inquiries in the last 2 years....
27,fi25s__tu,-0.000792,0.000792,0.000000,Number of currently open and satisfactory fina...
28,in21s__tu,-0.000642,0.000642,0.000000,Months since most recent installment trade opened
29,fi36s__tu,-0.000541,0.000541,0.000000,Months since most recent finance installment d...
30,aut252__tu,-0.000354,0.000354,0.000000,Average Aggregate Excess Payment for Auto acco...
31,s068b__tu,0.000292,0.000292,18.000000,Number of non-medical third party collections
32,flt_wtd_avg_open__tu_pmthx,-0.000242,0.000242,0.000000,NaN