## Imports

In [1]:
import os
import pandas as pd
import numpy as np

## Constants

In [8]:
str_project = os.getcwd().split('\\')[5]
print(f'Project: {str_project}')
str_task = os.getcwd().split('\\')[6]
print(f'Task: {str_task}')
str_subtask = os.getcwd().split('\\')[7]
print(f'Subtask: {str_subtask}')

str_dirname_output = './output'

Project: 06_ml_in_python
Task: 01_home_credit_model
Subtask: 01_data_collection

## Output Dir

In [9]:
#make an output for the train, valid, test files
try:
    os.mkdir(str_dirname_output)
except FileExistsError:
    pass

## Read train.csv

In [24]:
str_filename = 'train.csv'
str_local_path = f'./input/{str_filename}'
df = pd.read_csv(str_local_path)
df.head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,396902,0,Cash loans,F,Y,Y,0,121500,835380,40320.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,4.0
1,112096,0,Cash loans,F,N,Y,0,202500,516069,26478.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,6.0
2,285821,1,Cash loans,M,Y,Y,1,180000,284400,22469.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
3,376901,0,Cash loans,F,N,Y,0,90000,265536,13685.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
4,325138,0,Cash loans,F,Y,Y,0,94500,755190,30078.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

## Sort the Df

In [37]:
#sort by id, ascending such that model is trained on the first 60% of accounts
df_tmp = df.sort_values(by=['SK_ID_CURR'], ascending=True)
#insert a row number column such that we can split the df into 60-20-20 based on total rows
df_tmp.insert(0, 'RowNum', np.arange(df_tmp.shape[0]))
#show
df_tmp.head()

,RowNum,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
98228,0,100006,0,Cash loans,F,N,Y,0,135000,312683,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
30798,1,100007,0,Cash loans,M,N,Y,0,121500,513000,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
92156,2,100008,0,Cash loans,M,N,Y,0,99000,490496,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
120170,3,100009,0,Cash loans,F,Y,Y,1,171000,1560726,...,0,0,0,0,0.0,0.0,0.0,1.0,1.0,2.0
101877,4,100012,0,Revolving loans,M,N,Y,0,135000,405000,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [36]:
df_tmp.shape

(125000, 123)

## Split Df into Train, Valid, Test

### Training

In [40]:
df_training = df_tmp.query('0 <= RowNum < 75000')
df_training.tail()

,RowNum,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
108007,74995,313992,0,Cash loans,M,N,N,0,112500,291915,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
5683,74996,313997,0,Cash loans,F,N,Y,0,67500,305222,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
111682,74997,313998,0,Cash loans,F,Y,Y,0,315000,1822500,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
76159,74998,314001,0,Cash loans,F,N,Y,0,108000,323195,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
9490,74999,314002,0,Cash loans,F,N,N,0,90000,170640,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0

In [41]:
df_training.shape

(75000, 123)

### Validation

In [42]:
df_validation = df_tmp.query('75000 <= RowNum < 100000')
df_validation.tail()

,RowNum,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
91894,99995,385070,0,Cash loans,F,N,N,0,180000,755190,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
41734,99996,385072,1,Cash loans,F,N,Y,0,225000,408780,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
36916,99997,385073,1,Cash loans,M,Y,Y,0,157500,450000,...,0,0,0,0,0.0,0.0,0.0,1.0,1.0,1.0
37683,99998,385074,0,Cash loans,F,N,Y,1,180000,195543,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,2.0
42639,99999,385078,0,Cash loans,F,N,Y,2,67500,225000,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,0.0

In [43]:
df_validation.shape

(25000, 123)

### Testing

In [45]:
df_testing = df_tmp.query('RowNum >= 100000')
df_testing.tail()

,RowNum,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
32679,124995,456247,0,Cash loans,F,N,Y,0,112500,345510,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,2.0
97336,124996,456248,0,Cash loans,F,N,Y,0,153000,331920,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
26087,124997,456251,0,Cash loans,M,N,N,0,157500,254700,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
98229,124998,456254,1,Cash loans,F,N,Y,0,171000,370107,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
11148,124999,456255,0,Cash loans,F,N,N,0,157500,675000,...,0,0,0,0,0.0,0.0,0.0,2.0,0.0,1.0

In [46]:
df_testing.shape

(25000, 123)

## Output Df's as CSV

### Training

In [48]:
str_filename = 'df_training.csv'
str_local_path = f'{str_dirname_output}/{str_filename}'
df_training.to_csv(str_local_path, index=False)

### Validation

In [49]:
str_filename = 'df_validation.csv'
str_local_path = f'{str_dirname_output}/{str_filename}'
df_validation.to_csv(str_local_path, index=False)

### Testing

In [51]:
str_filename = 'df_testing.csv'
str_local_path = f'{str_dirname_output}/{str_filename}'
df_testing.to_csv(str_local_path, index=False)