In [1]:
import pandas as pd
import os
import numpy as np

# Constants

In [2]:
str_project = os.getcwd().split('\\')[4]
print(f'Project: {str_project}')
str_task = os.getcwd().split('\\')[5]
print(f'Task: {str_task}')
str_subtask = os.getcwd().split('\\')[6]
print(f'Subtask: {str_subtask}')

str_dirname_output = './output'

Project: 06_ml_in_python
Task: 02_application_test_model
Subtask: 03_data_preprocessing

In [3]:
os.getcwd()

'M:\\Risk Management\\Bridger Hyde\\20240521_bridger_internship\\06_ml_in_python\\02_application_test_model\\03_data_preprocessing'

In [4]:
try:
    os.mkdir(str_dirname_output)
except FileExistsError:
    pass

# pull in both CSVs

In [5]:
df_train = pd.read_csv('M:\\Risk Management\\Bridger Hyde\\20240521_bridger_internship\\06_ml_in_python\\02_application_test_model\\02_data_exploration\\output\\application_training.csv')
df_train

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307506,456251,0,Cash loans,M,N,N,0,157500.0,254700.0,27558.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307507,456252,0,Cash loans,F,N,Y,0,72000.0,269550.0,12001.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307508,456253,0,Cash loans,F,N,Y,0,153000.0,677664.0,29979.0,...,0,0,0,0,1.0,0.0,0.0,1.0,0.0,1.0
307509,456254,1,Cash loans,F,N,Y,0,171000.0,370107.0,20205.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
307510,456255,0,Cash loans,F,N,N,0,157500.0,675000.0,49117.5,...,0,0,0,0,0.0,0.0,0.0,2.0,0.0,1.0

In [6]:
df_test = pd.read_csv('M:\\Risk Management\\Bridger Hyde\\20240521_bridger_internship\\06_ml_in_python\\02_application_test_model\\01_data_collection\\output\\application_test.csv')
df_test

,SK_ID_CURR,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100001,Cash loans,F,N,Y,0,135000.0,568800.0,20560.5,450000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
1,100005,Cash loans,M,N,Y,0,99000.0,222768.0,17370.0,180000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
2,100013,Cash loans,M,Y,Y,0,202500.0,663264.0,69777.0,630000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,4.0
3,100028,Cash loans,F,N,Y,2,315000.0,1575000.0,49018.5,1575000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
4,100038,Cash loans,M,Y,N,1,180000.0,625500.0,32067.0,625500.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48739,456221,Cash loans,F,N,Y,0,121500.0,412560.0,17473.5,270000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
48740,456222,Cash loans,F,N,N,2,157500.0,622413.0,31909.5,495000.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
48741,456223,Cash loans,F,Y,Y,1,202500.0,315000.0,33205.5,315000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,3.0,1.0
48742,456224,Cash loans,M,N,N,0,225000.0,450000.0,25128.0,450000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
48743,456250,Cash loans,F,Y,N,0,135000.0,312768.0,24709.5,270000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,4.0

In [7]:
df_valid = pd.read_csv('M:\\Risk Management\\Bridger Hyde\\20240521_bridger_internship\\06_ml_in_python\\02_application_test_model\\02_data_exploration\\output\\validset.csv')
df_valid

,rownum,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,93750,421122,0,Revolving loans,F,N,Y,1,90000.0,247500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
1,93751,281021,0,Revolving loans,F,N,N,0,180000.0,225000.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,2.0
2,93752,298762,0,Cash loans,F,N,Y,0,135000.0,373311.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,93753,322213,0,Revolving loans,F,N,Y,1,103500.0,270000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
4,93754,181313,0,Cash loans,F,N,Y,0,202500.0,679671.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31245,124995,217133,0,Revolving loans,M,Y,Y,0,54000.0,157500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
31246,124996,169482,0,Cash loans,F,N,N,0,180000.0,661500.0,...,0,0,0,0,0.0,0.0,0.0,2.0,0.0,2.0
31247,124997,333982,0,Cash loans,F,N,Y,0,90000.0,239850.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
31248,124998,249620,0,Revolving loans,M,N,Y,0,76500.0,180000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,0.0
31249,124999,320235,0,Cash loans,M,Y,N,0,81000.0,306000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

In [47]:
# examine text columns for outliers
text_columns = df_train.select_dtypes(include=['category','object'])

count_results = {}
# go through columns getting value countes for each value
for column in text_columns.columns:
    value_counts = text_columns[column].value_counts()
    count_results[column] = value_counts
    
# prints out value counts for each column for each value
for column, counts in count_results.items():
    print(f"Counts for coulmn: {column}")
    for value, count in counts.items():
        print(f"{value}: {count}")
    print("\n" + "--"*40 + "\n")

Counts for coulmn: NAME_CONTRACT_TYPE
Cash loans: 278232
Revolving loans: 29279

--------------------------------------------------------------------------------

Counts for coulmn: CODE_GENDER
F: 202448
M: 105059
XNA: 4

--------------------------------------------------------------------------------

Counts for coulmn: FLAG_OWN_CAR
N: 202924
Y: 104587

--------------------------------------------------------------------------------

Counts for coulmn: FLAG_OWN_REALTY
Y: 213312
N: 94199

--------------------------------------------------------------------------------

Counts for coulmn: NAME_TYPE_SUITE
Unaccompanied: 248526
Family: 40149
Spouse, partner: 11370
Children: 3267
Other_B: 1770
Other_A: 866
Group of people: 271

--------------------------------------------------------------------------------

Counts for coulmn: NAME_INCOME_TYPE
Working: 158774
Commercial associate: 71617
Pensioner: 55362
State servant: 21703
Unemployed: 22
Student: 18
Businessman: 10
Maternity leave: 5

--------------------------------------------------------------------------------

Counts for coulmn: NAME_EDUCATION_TYPE
Secondary / secondary special: 218391
Higher education: 74863
Incomplete higher: 10277
Lower secondary: 3816
Academic degree: 164

--------------------------------------------------------------------------------

Counts for coulmn: NAME_FAMILY_STATUS
Married: 196432
Single / not married: 45444
Civil marriage: 29775
Separated: 19770
Widow: 16088
Unknown: 2

--------------------------------------------------------------------------------

Counts for coulmn: NAME_HOUSING_TYPE
House / apartment: 272868
With parents: 14840
Municipal apartment: 11183
Rented apartment: 4881
Office apartment: 2617
Co-op apartment: 1122

--------------------------------------------------------------------------------

Counts for coulmn: OCCUPATION_TYPE
Laborers: 55186
Sales staff: 32102
Core staff: 27570
Managers: 21371
Drivers: 18603
High skill tech staff: 11380
Accountants: 9813
Medicine staff: 8537
Security staff: 6721
Cooking staff: 5946
Cleaning staff: 4653
Private service staff: 2652
Low-skill Laborers: 2093
Waiters/barmen staff: 1348
Secretaries: 1305
Realty agents: 751
HR staff: 563
IT staff: 526

--------------------------------------------------------------------------------

Counts for coulmn: WEEKDAY_APPR_PROCESS_START
TUESDAY: 53901
WEDNESDAY: 51934
MONDAY: 50714
THURSDAY: 50591
FRIDAY: 50338
SATURDAY: 33852
SUNDAY: 16181

--------------------------------------------------------------------------------

Counts for coulmn: ORGANIZATION_TYPE
Business Entity Type 3: 67992
XNA: 55374
Self-employed: 38412
Other: 16683
Medicine: 11193
Business Entity Type 2: 10553
Government: 10404
School: 8893
Trade: type 7: 7831
Kindergarten: 6880
Construction: 6721
Business Entity Type 1: 5984
Transport: type 4: 5398
Trade: type 3: 3492
Industry: type 9: 3368
Industry: type 3: 3278
Security: 3247
Housing: 2958
Industry: type 11: 2704
Military: 2634
Bank: 2507
Agriculture: 2454
Police: 2341
Transport: type 2: 2204
Postal: 2157
Security Ministries: 1974
Trade: type 2: 1900
Restaurant: 1811
Services: 1575
University: 1327
Industry: type 7: 1307
Transport: type 3: 1187
Industry: type 1: 1039
Hotel: 966
Electricity: 950
Industry: type 4: 877
Trade: type 6: 631
Industry: type 5: 599
Insurance: 597
Telecom: 577
Emergency: 560
Industry: type 2: 458
Advertising: 429
Realtor: 396
Culture: 379
Industry: type 12: 369
Trade: type 1: 348
Mobile: 317
Legal Services: 305
Cleaning: 260
Transport: type 1: 201
Industry: type 6: 112
Industry: type 10: 109
Religion: 85
Industry: type 13: 67
Trade: type 4: 64
Trade: type 5: 49
Industry: type 8: 24

--------------------------------------------------------------------------------

Counts for coulmn: FONDKAPREMONT_MODE
reg oper account: 73830
reg oper spec account: 12080
not specified: 5687
org spec account: 5619

--------------------------------------------------------------------------------

Counts for coulmn: HOUSETYPE_MODE
block of flats: 150503
specific housing: 1499
terraced house: 1212

--------------------------------------------------------------------------------

Counts for coulmn: WALLSMATERIAL_MODE
Panel: 66040
Stone, brick: 64815
Block: 9253
Wooden: 5362
Mixed: 2296
Monolithic: 1779
Others: 1625

--------------------------------------------------------------------------------

Counts for coulmn: EMERGENCYSTATE_MODE
No: 159428
Yes: 2328

--------------------------------------------------------------------------------

In [48]:
# changes outlier GENDER code to Majority 
df_train.loc[df_train['CODE_GENDER'] == 'XNA', 'CODE_GENDER'] = 'F'

In [10]:
# search the dataframes for columns that are missing values and show it as a %
missing = df_train.isnull().mean() * 100
print(missing[missing > 0])
# removes columns that are missing over 65 % of values (changes to 75%)
cols_to_remove = missing[missing > 75].index
print(cols_to_remove)
# drop columns 
df_train_clean = df_train.drop(columns=cols_to_remove)
df_train_clean.shape

AMT_ANNUITY                    0.003902
AMT_GOODS_PRICE                0.090403
NAME_TYPE_SUITE                0.420148
OWN_CAR_AGE                   65.990810
OCCUPATION_TYPE               31.345545
                                ...
AMT_REQ_CREDIT_BUREAU_DAY     13.501631
AMT_REQ_CREDIT_BUREAU_WEEK    13.501631
AMT_REQ_CREDIT_BUREAU_MON     13.501631
AMT_REQ_CREDIT_BUREAU_QRT     13.501631
AMT_REQ_CREDIT_BUREAU_YEAR    13.501631
Length: 67, dtype: float64
Index([], dtype='object')

(307511, 122)

In [14]:
# Duplicate column drop on test set
df_test_clean = df_test.drop(columns=cols_to_remove)
# show shape of dataset (has 1 less columns due to missing target col)
df_test_clean.shape

#df_valid_clean = df_valid.drop(columns=cols_to_remove)
#df_valid_clean.shape

(48744, 121)

In [15]:
df_valid_clean = df_valid.drop(columns=cols_to_remove)
df_valid_clean.shape

(31250, 106)

In [51]:
# Search Numerical columns for outliers in training set
def find_outliers(df_train_clean, threshold=4):
    outliers = {}
    
    for col in df_train_clean.select_dtypes(include=[np.number]).columns:
        mean = df_train_clean[col].mean()
        std = df_train_clean[col].std()
        upper_bound = mean + threshold * std
        lower_bound = mean - threshold * std
        
        outliers[col] = df_train_clean[(df_train_clean[col] > upper_bound) | (df_train_clean[col] < lower_bound)][col]
    
    return outliers

outliers = find_outliers(df_train_clean, threshold=4)

for col, outlier_values in outliers.items():
    print(f"Outliers in columns {col}:")
    print(outlier_values)

Outliers in columns SK_ID_CURR:
Series([], Name: SK_ID_CURR, dtype: int64)
Outliers in columns TARGET:
Series([], Name: TARGET, dtype: int64)
Outliers in columns CNT_CHILDREN:
1133      4
1721      4
2348      4
2666      4
3079      7
         ..
305112    7
306244    4
306297    4
306888    5
307293    4
Name: CNT_CHILDREN, Length: 555, dtype: int64
Outliers in columns AMT_INCOME_TOTAL:
1723      1935000.0
3371      1350000.0
4603      1350000.0
8314      1350000.0
10222     2250000.0
            ...
298082    2475000.0
300468    1575000.0
304477    2025000.0
305577    1215000.0
306028    1350000.0
Name: AMT_INCOME_TOTAL, Length: 230, dtype: float64
Outliers in columns AMT_CREDIT:
189       2250000.0
341       2250000.0
485       2286211.5
1243      2254500.0
1446      2250000.0
            ...
305834    2466954.0
306102    2517300.0
306497    2463840.0
306882    2250000.0
307214    2290743.0
Name: AMT_CREDIT, Length: 1049, dtype: float64
Outliers in columns AMT_ANNUITY:
60         86989.5
485       116266.5
1446      116505.0
1530      107356.5
1633       96174.0
            ...
305671    112779.0
305889     93838.5
305952     98770.5
306352     98379.0
307002    166572.0
Name: AMT_ANNUITY, Length: 1212, dtype: float64
Outliers in columns AMT_GOODS_PRICE:
189       2250000.0
341       2250000.0
485       2182500.0
1243      2254500.0
1446      2250000.0
            ...
305834    2205000.0
306102    2250000.0
306497    2250000.0
306882    2250000.0
307214    2047500.0
Name: AMT_GOODS_PRICE, Length: 1083, dtype: float64
Outliers in columns REGION_POPULATION_RELATIVE:
Series([], Name: REGION_POPULATION_RELATIVE, dtype: float64)
Outliers in columns DAYS_BIRTH:
Series([], Name: DAYS_BIRTH, dtype: int64)
Outliers in columns DAYS_EMPLOYED:
Series([], Name: DAYS_EMPLOYED, dtype: int64)
Outliers in columns DAYS_REGISTRATION:
2680     -20981.0
20555    -19344.0
21990    -21244.0
27531    -20452.0
33939    -20447.0
34343    -19244.0
41442    -21249.0
43581    -19488.0
44824    -22392.0
45121    -20571.0
50148    -19706.0
68403    -20838.0
74685    -19636.0
75227    -20560.0
93123    -20516.0
94098    -22113.0
95342    -21887.0
99788    -19159.0
118360   -19207.0
119165   -19463.0
129516   -20840.0
136858   -19660.0
147595   -20569.0
151533   -22701.0
151696   -19152.0
153731   -21865.0
161470   -20701.0
163628   -23738.0
174336   -19579.0
189491   -20136.0
194676   -20841.0
210943   -22858.0
212205   -19504.0
212224   -19424.0
213929   -20741.0
221818   -20096.0
234093   -24672.0
249436   -23416.0
256131   -19134.0
259119   -19985.0
261446   -19695.0
269250   -20623.0
269381   -19513.0
278457   -19265.0
282370   -21146.0
289176   -22928.0
289957   -19370.0
295688   -19795.0
298429   -22442.0
299743   -20514.0
301029   -19170.0
303945   -19183.0
Name: DAYS_REGISTRATION, dtype: float64
Outliers in columns DAYS_ID_PUBLISH:
Series([], Name: DAYS_ID_PUBLISH, dtype: int64)
Outliers in columns OWN_CAR_AGE:
85        65.0
134       65.0
237       64.0
272       65.0
369       64.0
          ...
306946    64.0
307029    64.0
307076    64.0
307132    65.0
307234    64.0
Name: OWN_CAR_AGE, Length: 3339, dtype: float64
Outliers in columns FLAG_MOBIL:
15709    0
Name: FLAG_MOBIL, dtype: int64
Outliers in columns FLAG_EMP_PHONE:
Series([], Name: FLAG_EMP_PHONE, dtype: int64)
Outliers in columns FLAG_WORK_PHONE:
Series([], Name: FLAG_WORK_PHONE, dtype: int64)
Outliers in columns FLAG_CONT_MOBILE:
50        0
109       0
114       0
1433      0
1816      0
         ..
305248    0
305451    0
305894    0
306477    0
306912    0
Name: FLAG_CONT_MOBILE, Length: 574, dtype: int64
Outliers in columns FLAG_PHONE:
Series([], Name: FLAG_PHONE, dtype: int64)
Outliers in columns FLAG_EMAIL:
28        1
30        1
55        1
61        1
85        1
         ..
307427    1
307484    1
307500    1
307503    1
307508    1
Name: FLAG_EMAIL, Length: 17442, dtype: int64
Outliers in columns CNT_FAM_MEMBERS:
1133      6.0
1721      6.0
2348      6.0
2666      6.0
3079      9.0
         ...
305112    8.0
306244    6.0
306297    6.0
306888    7.0
307293    6.0
Name: CNT_FAM_MEMBERS, Length: 529, dtype: float64
Outliers in columns REGION_RATING_CLIENT:
Series([], Name: REGION_RATING_CLIENT, dtype: int64)
Outliers in columns REGION_RATING_CLIENT_W_CITY:
Series([], Name: REGION_RATING_CLIENT_W_CITY, dtype: int64)
Outliers in columns HOUR_APPR_PROCESS_START:
Series([], Name: HOUR_APPR_PROCESS_START, dtype: int64)
Outliers in columns REG_REGION_NOT_LIVE_REGION:
84        1
115       1
138       1
204       1
225       1
         ..
307126    1
307187    1
307225    1
307233    1
307485    1
Name: REG_REGION_NOT_LIVE_REGION, Length: 4657, dtype: int64
Outliers in columns REG_REGION_NOT_WORK_REGION:
28        1
41        1
58        1
110       1
115       1
         ..
307320    1
307378    1
307425    1
307454    1
307485    1
Name: REG_REGION_NOT_WORK_REGION, Length: 15612, dtype: int64
Outliers in columns LIVE_REGION_NOT_WORK_REGION:
28        1
41        1
58        1
110       1
133       1
         ..
307281    1
307320    1
307378    1
307425    1
307454    1
Name: LIVE_REGION_NOT_WORK_REGION, Length: 12503, dtype: int64
Outliers in columns REG_CITY_NOT_LIVE_CITY:
Series([], Name: REG_CITY_NOT_LIVE_CITY, dtype: int64)
Outliers in columns REG_CITY_NOT_WORK_CITY:
Series([], Name: REG_CITY_NOT_WORK_CITY, dtype: int64)
Outliers in columns LIVE_CITY_NOT_WORK_CITY:
Series([], Name: LIVE_CITY_NOT_WORK_CITY, dtype: int64)
Outliers in columns EXT_SOURCE_1:
Series([], Name: EXT_SOURCE_1, dtype: float64)
Outliers in columns EXT_SOURCE_2:
Series([], Name: EXT_SOURCE_2, dtype: float64)
Outliers in columns EXT_SOURCE_3:
Series([], Name: EXT_SOURCE_3, dtype: float64)
Outliers in columns APARTMENTS_AVG:
152       0.5845
544       0.6639
1119      1.0000
1312      0.6304
1394      0.7119
           ...
306858    0.5866
307004    1.0000
307313    0.9557
307339    0.7103
307476    0.5928
Name: APARTMENTS_AVG, Length: 1456, dtype: float64
Outliers in columns BASEMENTAREA_AVG:
98        0.4212
152       0.4570
551       0.4294
1008      0.4526
1241      0.8182
           ...
306354    0.4962
306771    0.6360
306858    0.5271
307313    0.8165
307339    0.4981
Name: BASEMENTAREA_AVG, Length: 1042, dtype: float64
Outliers in columns YEARS_BEGINEXPLUATATION_AVG:
77        0.6508
261       0.4933
1736      0.3224
1885      0.6538
2276      0.4953
           ...
304738    0.4918
305101    0.3169
306337    0.0000
306597    0.0000
307292    0.3294
Name: YEARS_BEGINEXPLUATATION_AVG, Length: 683, dtype: float64
Outliers in columns YEARS_BUILD_AVG:
59        0.1160
478       0.0276
2432      0.2792
2664      0.0000
3143      0.2316
           ...
305914    0.0000
306133    0.2316
306828    0.0000
307259    0.1636
307438    0.2520
Name: YEARS_BUILD_AVG, Length: 455, dtype: float64
Outliers in columns COMMONAREA_AVG:
255       0.4682
852       0.6260
858       0.6849
1394      0.3827
1545      0.3761
           ...
306325    0.4414
306858    0.4605
307004    0.4053
307135    0.8050
307476    0.5046
Name: COMMONAREA_AVG, Length: 1102, dtype: float64
Outliers in columns ELEVATORS_AVG:
51        0.88
116       0.68
551       0.64
852       0.64
1241      0.72
          ...
306179    0.72
306206    1.00
306858    0.88
307135    0.96
307476    0.64
Name: ELEVATORS_AVG, Length: 1356, dtype: float64
Outliers in columns ENTRANCES_AVG:
551       0.5517
901       0.6207
1011      0.6897
1158      0.5517
1241      0.6207
           ...
306354    1.0000
306408    0.8966
307313    1.0000
307438    0.6552
307476    0.5517
Name: ENTRANCES_AVG, Length: 1406, dtype: float64
Outliers in columns FLOORSMAX_AVG:
152       0.9167
189       0.9583
410       1.0000
932       0.8750
1404      0.9583
           ...
306862    0.8333
307022    0.8333
307024    0.8750
307135    0.8750
307165    0.8750
Name: FLOORSMAX_AVG, Length: 583, dtype: float64
Outliers in columns FLOORSMIN_AVG:
1586      1.0000
2936      0.9583
3052      1.0000
4254      0.9167
5957      0.9167
           ...
305761    0.8917
306771    1.0000
307024    0.9167
307135    0.9167
307165    0.9167
Name: FLOORSMIN_AVG, Length: 285, dtype: float64
Outliers in columns LANDAREA_AVG:
51        0.3977
161       0.4101
445       0.4228
532       0.8004
625       0.3995
           ...
306571    0.4211
306602    0.4957
306894    1.0000
307195    1.0000
307313    0.9130
Name: LANDAREA_AVG, Length: 1117, dtype: float64
Outliers in columns LIVINGAPARTMENTS_AVG:
1394      0.5707
1658      0.6918
2181      0.8338
2218      0.5632
2845      0.4976
           ...
306179    0.5102
306679    0.5010
307004    0.9153
307339    0.5791
307476    0.4825
Name: LIVINGAPARTMENTS_AVG, Length: 863, dtype: float64
Outliers in columns LIVINGAREA_AVG:
51        0.5878
152       0.7187
189       0.6651
544       0.7641
551       0.6078
           ...
307313    0.8549
307339    0.6302
307440    0.6005
307476    0.6080
307508    0.9279
Name: LIVINGAREA_AVG, Length: 1543, dtype: float64
Outliers in columns NONLIVINGAPARTMENTS_AVG:
103       0.2780
152       0.2201
1195      0.2625
1831      0.7452
2181      1.0000
           ...
306020    1.0000
306072    0.2278
306178    0.3977
307195    0.3166
307301    0.3089
Name: NONLIVINGAPARTMENTS_AVG, Length: 600, dtype: float64
Outliers in columns NONLIVINGAREA_AVG:
116       0.5209
152       0.7729
189       0.3558
247       0.3146
544       0.6811
           ...
306892    0.3359
307192    0.3108
307280    0.4839
307384    1.0000
307438    0.3882
Name: NONLIVINGAREA_AVG, Length: 1495, dtype: float64
Outliers in columns APARTMENTS_MODE:
152       0.5956
544       0.6765
1008      0.5578
1119      1.0000
1538      0.5546
           ...
306858    0.5977
307004    1.0000
307313    0.9737
307339    0.7237
307476    0.6040
Name: APARTMENTS_MODE, Length: 1488, dtype: float64
Outliers in columns BASEMENTAREA_MODE:
98        0.4371
152       0.4742
551       0.4456
1008      0.4697
1241      0.8491
           ...
306354    0.5149
306771    0.5461
306858    0.5470
307313    0.8474
307339    0.5169
Name: BASEMENTAREA_MODE, Length: 1041, dtype: float64
Outliers in columns YEARS_BEGINEXPLUATATION_MODE:
77        0.0000
261       0.0000
1736      0.0005
1885      0.0005
2276      0.0005
           ...
304738    0.0005
305101    0.0005
306337    0.0005
306597    0.0005
307292    0.0005
Name: YEARS_BEGINEXPLUATATION_MODE, Length: 679, dtype: float64
Outliers in columns YEARS_BUILD_MODE:
59        0.0000
478       0.0657
2432      0.3074
2664      0.0000
3143      0.2617
           ...
305914    0.0000
306133    0.2617
306828    0.0000
307259    0.1964
307438    0.2813
Name: YEARS_BUILD_MODE, Length: 443, dtype: float64
Outliers in columns COMMONAREA_MODE:
152       0.3500
255       0.4724
852       0.6317
858       0.6912
1566      0.3474
           ...
306325    0.4455
306858    0.4647
307004    0.4090
307135    0.8123
307476    0.5092
Name: COMMONAREA_MODE, Length: 1073, dtype: float64
Outliers in columns ELEVATORS_MODE:
51        0.8862
116       0.6848
152       0.6042
551       0.6445
852       0.6445
           ...
306179    0.7250
306206    1.0000
306858    0.8862
307135    0.9667
307476    0.6445
Name: ELEVATORS_MODE, Length: 1517, dtype: float64
Outliers in columns ENTRANCES_MODE:
551       0.5517
901       0.6207
1011      0.6897
1158      0.5517
1241      0.6207
           ...
306354    1.0000
306408    0.8966
307313    1.0000
307438    0.6552
307476    0.5517
Name: ENTRANCES_MODE, Length: 1396, dtype: float64
Outliers in columns FLOORSMAX_MODE:
152       0.9167
189       0.9583
410       1.0000
932       0.8750
1404      0.9583
           ...
305761    0.9583
306771    1.0000
307024    0.8750
307135    0.8750
307165    0.8750
Name: FLOORSMAX_MODE, Length: 547, dtype: float64
Outliers in columns FLOORSMIN_MODE:
1586      1.0000
2936      0.9583
3052      1.0000
4254      0.9167
5957      0.9167
           ...
305761    1.0000
306771    1.0000
307024    0.9167
307135    0.9167
307165    0.9167
Name: FLOORSMIN_MODE, Length: 298, dtype: float64
Outliers in columns LANDAREA_MODE:
51        0.4067
161       0.4195
445       0.4324
532       0.8187
625       0.4086
           ...
306571    0.4307
306602    0.7233
306894    1.0000
307195    1.0000
307313    0.9338
Name: LANDAREA_MODE, Length: 1148, dtype: float64
Outliers in columns LIVINGAPARTMENTS_MODE:
1705      0.5051
2181      0.9109
2218      0.6152
2727      0.5096
2730      0.5032
           ...
306679    0.5473
306858    0.5133
307004    1.0000
307339    0.6327
307476    0.5271
Name: LIVINGAPARTMENTS_MODE, Length: 887, dtype: float64
Outliers in columns LIVINGAREA_MODE:
51        0.6124
116       0.5582
152       0.7488
189       0.6930
544       0.7961
           ...
307313    0.8907
307339    0.6566
307440    0.6257
307476    0.6335
307508    0.9667
Name: LIVINGAREA_MODE, Length: 1607, dtype: float64
Outliers in columns NONLIVINGAPARTMENTS_MODE:
120       0.1946
152       0.2218
1195      0.2646
1241      0.1984
1831      0.7510
           ...
306020    1.0000
306072    0.2296
306178    0.4008
307195    0.3191
307301    0.3113
Name: NONLIVINGAPARTMENTS_MODE, Length: 555, dtype: float64
Outliers in columns NONLIVINGAREA_MODE:
116       0.5514
152       0.8183
189       0.3767
247       0.3330
544       0.7211
           ...
306892    0.3556
307192    0.3291
307280    0.5123
307384    1.0000
307438    0.4109
Name: NONLIVINGAREA_MODE, Length: 1491, dtype: float64
Outliers in columns APARTMENTS_MEDI:
152       0.5902
544       0.6703
1119      1.0000
1312      0.6365
1394      0.7188
           ...
306858    0.5923
307004    1.0000
307313    0.9649
307339    0.7172
307476    0.5985
Name: APARTMENTS_MEDI, Length: 1470, dtype: float64
Outliers in columns BASEMENTAREA_MEDI:
98        0.4212
152       0.4570
551       0.4294
1008      0.4526
1241      0.8182
           ...
306354    0.4962
306771    0.6077
306858    0.5271
307313    0.8165
307339    0.4981
Name: BASEMENTAREA_MEDI, Length: 1048, dtype: float64
Outliers in columns YEARS_BEGINEXPLUATATION_MEDI:
261       0.4933
1736      0.0000
2276      0.4953
2544      0.0000
3456      0.4973
           ...
304738    0.4918
305101    0.0000
306337    0.0000
306597    0.0000
307292    0.0000
Name: YEARS_BEGINEXPLUATATION_MEDI, Length: 652, dtype: float64
Outliers in columns YEARS_BUILD_MEDI:
59        0.0000
478       0.0406
2432      0.2888
2664      0.0000
3143      0.2419
           ...
305914    0.0000
306133    0.2419
306828    0.0000
307259    0.1748
307438    0.2620
Name: YEARS_BUILD_MEDI, Length: 451, dtype: float64
Outliers in columns COMMONAREA_MEDI:
255       0.4711
852       0.6299
858       0.6892
1394      0.3851
1545      0.3785
           ...
306325    0.4442
306858    0.4634
307004    0.4079
307135    0.8101
307476    0.5078
Name: COMMONAREA_MEDI, Length: 1097, dtype: float64
Outliers in columns ELEVATORS_MEDI:
51        0.88
116       0.68
551       0.64
852       0.64
1241      0.72
          ...
306179    0.72
306206    1.00
306858    0.88
307135    0.96
307476    0.64
Name: ELEVATORS_MEDI, Length: 1366, dtype: float64
Outliers in columns ENTRANCES_MEDI:
551       0.5517
901       0.6207
1011      0.6897
1158      0.5517
1241      0.6207
           ...
306354    1.0000
306408    0.8966
307313    1.0000
307438    0.6552
307476    0.5517
Name: ENTRANCES_MEDI, Length: 1406, dtype: float64
Outliers in columns FLOORSMAX_MEDI:
152       0.9167
189       0.9583
410       1.0000
932       0.8750
1404      0.9583
           ...
306862    0.8333
307022    0.8333
307024    0.8750
307135    0.8750
307165    0.8750
Name: FLOORSMAX_MEDI, Length: 597, dtype: float64
Outliers in columns FLOORSMIN_MEDI:
1586      1.0000
2936      0.9583
3052      1.0000
4254      0.9167
5957      0.9167
           ...
305761    1.0000
306771    1.0000
307024    0.9167
307135    0.9167
307165    0.9167
Name: FLOORSMIN_MEDI, Length: 296, dtype: float64
Outliers in columns LANDAREA_MEDI:
51        0.4046
161       0.4173
445       0.4301
532       0.8144
625       0.4065
           ...
306571    0.4284
306602    0.7194
306894    1.0000
307195    1.0000
307313    0.9289
Name: LANDAREA_MEDI, Length: 1134, dtype: float64
Outliers in columns LIVINGAPARTMENTS_MEDI:
1394      0.5806
1658      0.7037
2181      0.8482
2218      0.5729
2845      0.5062
           ...
306679    0.5096
306858    0.4780
307004    0.9312
307339    0.5892
307476    0.4908
Name: LIVINGAPARTMENTS_MEDI, Length: 887, dtype: float64
Outliers in columns LIVINGAREA_MEDI:
51        0.5983
152       0.7317
189       0.6771
544       0.7778
551       0.6187
           ...
307313    0.8703
307339    0.6416
307440    0.6113
307476    0.6189
307508    0.9445
Name: LIVINGAREA_MEDI, Length: 1538, dtype: float64
Outliers in columns NONLIVINGAPARTMENTS_MEDI:
103       0.2601
152       0.2213
1195      0.2640
1831      0.7492
2181      1.0000
           ...
306020    1.0000
306072    0.2290
306178    0.3998
307195    0.3183
307301    0.3106
Name: NONLIVINGAPARTMENTS_MEDI, Length: 598, dtype: float64
Outliers in columns NONLIVINGAREA_MEDI:
116       0.5318
152       0.7892
189       0.3633
247       0.3212
544       0.6954
           ...
306892    0.3429
307192    0.3174
307280    0.4941
307384    1.0000
307438    0.3963
Name: NONLIVINGAREA_MEDI, Length: 1489, dtype: float64
Outliers in columns TOTALAREA_MODE:
116       0.7010
152       0.7334
189       0.6216
323       0.6093
544       0.7628
           ...
307135    0.6886
307195    1.0000
307313    0.9468
307339    0.5470
307508    0.7970
Name: TOTALAREA_MODE, Length: 1503, dtype: float64
Outliers in columns OBS_30_CNT_SOCIAL_CIRCLE:
117       12.0
334       13.0
504       12.0
561       14.0
670       13.0
          ...
306984    15.0
306999    12.0
307165    14.0
307252    13.0
307428    12.0
Name: OBS_30_CNT_SOCIAL_CIRCLE, Length: 1930, dtype: float64
Outliers in columns DEF_30_CNT_SOCIAL_CIRCLE:
0         2.0
99        2.0
102       2.0
123       2.0
192       2.0
         ...
307380    3.0
307407    2.0
307416    2.0
307469    2.0
307503    3.0
Name: DEF_30_CNT_SOCIAL_CIRCLE, Length: 6838, dtype: float64
Outliers in columns OBS_60_CNT_SOCIAL_CIRCLE:
117       12.0
334       13.0
504       12.0
516       11.0
523       11.0
          ...
307252    13.0
307277    11.0
307428    12.0
307469    11.0
307494    11.0
Name: OBS_60_CNT_SOCIAL_CIRCLE, Length: 2691, dtype: float64
Outliers in columns DEF_60_CNT_SOCIAL_CIRCLE:
0         2.0
102       2.0
192       2.0
428       2.0
488       2.0
         ...
307264    3.0
307331    2.0
307380    2.0
307416    2.0
307503    2.0
Name: DEF_60_CNT_SOCIAL_CIRCLE, Length: 3928, dtype: float64
Outliers in columns DAYS_LAST_PHONE_CHANGE:
191568   -4292.0
Name: DAYS_LAST_PHONE_CHANGE, dtype: float64
Outliers in columns FLAG_DOCUMENT_2:
23923     1
33976     1
79252     1
87010     1
98999     1
109258    1
186302    1
187327    1
240334    1
247300    1
252170    1
282657    1
294910    1
Name: FLAG_DOCUMENT_2, dtype: int64
Outliers in columns FLAG_DOCUMENT_3:
Series([], Name: FLAG_DOCUMENT_3, dtype: int64)
Outliers in columns FLAG_DOCUMENT_4:
5896      1
6928      1
14306     1
18890     1
18978     1
29787     1
34485     1
44210     1
47434     1
58520     1
68590     1
71182     1
71348     1
99378     1
106895    1
119245    1
125017    1
129294    1
179741    1
222201    1
236631    1
254119    1
271220    1
285948    1
305368    1
Name: FLAG_DOCUMENT_4, dtype: int64
Outliers in columns FLAG_DOCUMENT_5:
270       1
292       1
300       1
319       1
320       1
         ..
307162    1
307211    1
307234    1
307250    1
307490    1
Name: FLAG_DOCUMENT_5, Length: 4648, dtype: int64
Outliers in columns FLAG_DOCUMENT_6:
Series([], Name: FLAG_DOCUMENT_6, dtype: int64)
Outliers in columns FLAG_DOCUMENT_7:
12795     1
13291     1
22698     1
25384     1
25782     1
26398     1
26954     1
40571     1
42764     1
46342     1
48949     1
50042     1
64519     1
70661     1
72902     1
76285     1
87095     1
90425     1

In [52]:
# adjust for outliers within the Numerical columns
df_train.loc[df_train['AMT_INCOME_TOTAL'] == 117000000, 'AMT_INCOME_TOTAL'] = 1170000

In [53]:
# setting numerical columns and categorical columns to variables
numcolstrain = df_train_clean.select_dtypes(include=['float64','int64']).columns
catcolstrain = df_train_clean.select_dtypes(include=['object']).columns

numcolstest = df_test_clean.select_dtypes(include=['float64','int64']).columns
catcolstest = df_test_clean.select_dtypes(include=['object']).columns

# filling missing values with 0 and unknown (future imputing done at a later time MODE was best results)
#df_train_clean[numcolstrain] = df_train_clean[numcolstrain].fillna(df_train_clean[numcolstrain].mean())
df_train_clean[numcolstrain] = df_train_clean[numcolstrain].fillna(0)
df_train_clean[catcolstrain] = df_train_clean[catcolstrain].fillna('Unknown')

#df_test_clean[numcolstest] = df_test_clean[numcolstest].fillna(df_test_clean[numcolstest].mean())
df_test_clean[numcolstest] = df_test_clean[numcolstest].fillna(0)
df_test_clean[catcolstest] = df_test_clean[catcolstest].fillna('Unknown')

# Export Cleaned CSVs

In [54]:
df_train_clean.to_csv('./output/trainingset.csv', index=False)

In [55]:
df_test_clean.to_csv('./output/testset.csv', index=False)