In [1]:
import os
import pandas as pd
import numpy as np
import json
from parse_payload import *
from tqdm import tqdm

### Functions

In [2]:
# read file
def read_file(str_local_path):
    try:
        dict_json_request = json.load(open(str_local_path))['request']
    except KeyError:
        dict_json_request = json.load(open(str_local_path))
    return dict_json_request

### Constants

In [3]:
str_dirname_input = './input'

### Parse first payload

In [4]:
# import first payload
str_filename_1 = 'request_7908440_1.json'
str_local_path = f'{str_dirname_input}/{str_filename_1}'
dict_request = read_file(str_local_path)
# init
cls_parser = PayloadToDataFrame()
# get data
df_1 = cls_parser.get_data(dict_request=dict_request)
# show
df_1

,uniqueid__app,bigaccountid__app,bigdebtorid__app,bitdebtor__app,dealerstate__app,strdealershiptrackertype__app,strname__app,bitdealertrack__app,intopenbktype__app,pti__app,...,linka084__tu,linka085__tu,linka073__tu,linka074__tu,linka075__tu,linka076__tu,linka077__tu,linka078__tu,linka079__tu,linka083__tu
0,790844097988571,7908440,9798857,1,Ohio,Franchise,Ohio,False,7,0,...,99999.0,99999.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### Parse second payload

In [5]:
# import first payload
str_filename_2 = 'request_7908440_15.json'
str_local_path = f'{str_dirname_input}/{str_filename_2}'
dict_request = read_file(str_local_path)
# init
cls_parser = PayloadToDataFrame()
# get data
df_2 = cls_parser.get_data(dict_request=dict_request)
# show
df_2

,uniqueid__app,bigaccountid__app,bigdebtorid__app,bitdebtor__app,dealerstate__app,strdealershiptrackertype__app,strname__app,bitdealertrack__app,intopenbktype__app,pti__app,...,linka084__tu,linka085__tu,linka073__tu,linka074__tu,linka075__tu,linka076__tu,linka077__tu,linka078__tu,linka079__tu,linka083__tu
0,790844097988571,7908440,9798857,1,Ohio,Franchise,Ohio,False,7,0.0889,...,99999.0,99999.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### Check where the columns arent equal

In [6]:
# get the columns in both dfs
list_cols = list(df_1.columns) + list(df_2.columns)
list_cols = list(dict.fromkeys(list_cols))
int_n_cols = len(list_cols)
print(f'There are {int_n_cols} unique features')

There are 1725 unique features

In [7]:
list_cols_mismatch = []
for col in tqdm(list_cols):
    if not df_1[col].equals(df_2[col]):
        list_cols_mismatch.append(col)
    else:
        pass
# get n cols
int_n_cols = len(list_cols_mismatch)
print(f'There are {int_n_cols} mismatching columns')

100%|██████████| 1725/1725 [00:00<00:00, 12491.91it/s]

There are 6 mismatching columns

### Show

In [8]:
# subset
df_1_mismatch = df_1[list_cols_mismatch].copy()
df_2_mismatch = df_2[list_cols_mismatch].copy()

In [9]:
# show df_1
df_1_mismatch

,pti__app,bitgap__app,miles_odometer__app,payment__app,amtfinanced__app,fltgrossmonthly__income_sum
0,0,False,38123,400,22410,6500

In [10]:
# show df_2
df_2_mismatch

,pti__app,bitgap__app,miles_odometer__app,payment__app,amtfinanced__app,fltgrossmonthly__income_sum
0,0.0889,True,38138,654.05,26924.58,7349.68