In [1]:
import os
import pandas as pd
import numpy as np
from datetime import datetime
from tqdm import tqdm
import catboost as cb

In [2]:
dtm_today = datetime.today()
print(f'Latest run date: {dtm_today}')

Latest run date: 2025-02-28 18:27:25.553061

#### Functions

In [3]:
def get_catboost_feat_importance(cls_model_inference, pool_eval):
    df_tmp = cls_model_inference.get_feature_importance(
        data=pool_eval,
        type='LossFunctionChange',
        prettified=True,
    )
    df_tmp.columns = ['feature', 'importance']
    df_tmp.sort_values(by='importance', ascending=False, inplace=True)
    return df_tmp

#### Constants

In [4]:
str_project = os.getcwd().split('/')[4].replace('_','-')
print(f'Project: {str_project}')

str_task = os.getcwd().split('/')[5]
print(f'Task: {str_task}')

str_dirname_output = './output'

str_target = 'Early_Pay_Delinquency_60_720_Flag'

Project: 20241112-simple-model-test
Task: ad_hoc

#### Output dir

In [5]:
try:
    os.mkdir(str_dirname_output)
except:
    pass

#### Import data

In [6]:
list_str_df = [
    'train',
    'test',
    'holdout',
]
list_df = []
for str_df in tqdm(list_str_df):
    str_filename = f'df_{str_df}.gzip'
    str_uri = f's3://{str_project}/09_60_in_720/01_data_split/df_{str_df}.gzip'
    df = pd.read_parquet(str_uri)
    list_df.append(df)
df = pd.concat(list_df)
del list_df
# show
df

100%|██████████| 3/3 [00:02<00:00,  1.15it/s]

,accountid,request_datetime,response_model_name,file_key,bitdebtor,bitdebtor__app,dealerstate__app,strdealershiptrackertype__app,strname__app,bitdealertrack__app,...,ENG-perfect_payment_hx_open,ENG-perfect_payment_hx_closed,ENG-bk_x_wtd_avg,request_month,row,prop_row,data_set,train,test,holdout
0,5702434,2021-07-26 16:29:29.3903686,Gen10,deprecated/03_pull_payloads_tbldove/df_request...,1,1,Iowa,Franchise,Iowa,True,...,0,0,0.616667,2021-07-01,1,0.000024,train,1,0,0
1,5714239,2021-07-26 16:39:34.1121025,Gen10,deprecated/03_pull_payloads_tbldove/df_request...,1,1,Utah,Franchise,Utah,True,...,0,0,NaN,2021-07-01,2,0.000048,train,1,0,0
2,5713063,2021-07-26 16:48:39.3211104,Gen10,deprecated/03_pull_payloads_tbldove/df_request...,1,1,Illinois,Franchise,Illinois,True,...,0,0,NaN,2021-07-01,3,0.000072,train,1,0,0
3,5713732,2021-07-27 09:02:35.3300974,Gen10,deprecated/03_pull_payloads_tbldove/df_request...,1,1,Michigan,Independent,Michigan,False,...,0,1,0.000000,2021-07-01,4,0.000096,train,1,0,0
4,5715634,2021-07-27 09:18:12.2190097,Gen10,deprecated/03_pull_payloads_tbldove/df_request...,1,1,Arizona,Franchise,Arizona,False,...,0,1,0.000000,2021-07-01,5,0.000120,train,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41693,6453589,2022-11-30 23:45:32+00:00,PRESTIGE-GENXI,01_pull_payloads/df_requests_2022-11-30.gzip,1,1,Michigan,Franchise,Michigan,False,...,0,1,0.000000,2022-11-01,41694,0.999904,holdout,0,0,1
41694,6418453,2022-11-30 23:48:36+00:00,PRESTIGE-GENXI,01_pull_payloads/df_requests_2022-11-30.gzip,1,1,Michigan,Independent,Michigan,False,...,0,0,0.000000,2022-11-01,41695,0.999928,holdout,0,0,1
41695,6411914,2022-11-30 23:53:12+00:00,PRESTIGE-GENXI,01_pull_payloads/df_requests_2022-11-30.gzip,1,1,Washington,Independent,Washington,True,...,0,0,NaN,2022-11-01,41696,0.999952,holdout,0,0,1
41696,6434554,2022-11-30 23:57:04+00:00,PRESTIGE-GENXI,01_pull_payloads/df_requests_2022-11-30.gzip,1,1,Michigan,Franchise,Michigan,False,...,0,0,0.137374,2022-11-01,41697,0.999976,holdout,0,0,1
41697,6447867,2022-11-30 23:58:56+00:00,PRESTIGE-GENXI,01_pull_payloads/df_requests_2022-11-30.gzip,1,1,South Carolina,Independent,South Carolina,True,...,0,1,0.000000,2022-11-01,41698,1.000000,holdout,0,0,1

#### Impute ENG-wtd_avg

In [7]:
df['ENG-wtd_avg'] = df['ENG-wtd_avg'].fillna(0)
# subset
df = df[df['ENG-wtd_avg'] < 0.5].copy()
# show
df

,accountid,request_datetime,response_model_name,file_key,bitdebtor,bitdebtor__app,dealerstate__app,strdealershiptrackertype__app,strname__app,bitdealertrack__app,...,ENG-perfect_payment_hx_open,ENG-perfect_payment_hx_closed,ENG-bk_x_wtd_avg,request_month,row,prop_row,data_set,train,test,holdout
1,5714239,2021-07-26 16:39:34.1121025,Gen10,deprecated/03_pull_payloads_tbldove/df_request...,1,1,Utah,Franchise,Utah,True,...,0,0,NaN,2021-07-01,2,0.000048,train,1,0,0
2,5713063,2021-07-26 16:48:39.3211104,Gen10,deprecated/03_pull_payloads_tbldove/df_request...,1,1,Illinois,Franchise,Illinois,True,...,0,0,NaN,2021-07-01,3,0.000072,train,1,0,0
8,5709029,2021-07-27 09:42:40.7808217,Gen10,deprecated/03_pull_payloads_tbldove/df_request...,1,1,Missouri,Franchise,Missouri,False,...,0,0,NaN,2021-07-01,9,0.000216,train,1,0,0
9,5709609,2021-07-27 09:47:57.8551698,Gen10,deprecated/03_pull_payloads_tbldove/df_request...,0,0,Indiana,Franchise,Indiana,True,...,0,0,0.000000,2021-07-01,11,0.000264,train,1,0,0
12,5710164,2021-07-27 10:14:00.4561057,Gen10,deprecated/03_pull_payloads_tbldove/df_request...,1,1,Ohio,Independent,Ohio,False,...,0,0,NaN,2021-07-01,12,0.000288,train,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41692,6450520,2022-11-30 23:33:56+00:00,PRESTIGE-GENXI,01_pull_payloads/df_requests_2022-11-30.gzip,1,1,Illinois,Franchise,Wisconsin,True,...,0,0,0.416667,2022-11-01,41693,0.999880,holdout,0,0,1
41693,6453589,2022-11-30 23:45:32+00:00,PRESTIGE-GENXI,01_pull_payloads/df_requests_2022-11-30.gzip,1,1,Michigan,Franchise,Michigan,False,...,0,1,0.000000,2022-11-01,41694,0.999904,holdout,0,0,1
41694,6418453,2022-11-30 23:48:36+00:00,PRESTIGE-GENXI,01_pull_payloads/df_requests_2022-11-30.gzip,1,1,Michigan,Independent,Michigan,False,...,0,0,0.000000,2022-11-01,41695,0.999928,holdout,0,0,1
41695,6411914,2022-11-30 23:53:12+00:00,PRESTIGE-GENXI,01_pull_payloads/df_requests_2022-11-30.gzip,1,1,Washington,Independent,Washington,True,...,0,0,NaN,2022-11-01,41696,0.999952,holdout,0,0,1
41696,6434554,2022-11-30 23:57:04+00:00,PRESTIGE-GENXI,01_pull_payloads/df_requests_2022-11-30.gzip,1,1,Michigan,Franchise,Michigan,False,...,0,0,0.137374,2022-11-01,41697,0.999976,holdout,0,0,1

#### Get features

In [8]:
# rm target
list_cols_model = [col for col in df.columns if col != str_target]
# rm non-numeric
list_cols_object = [col for col in list_cols_model if df[col].dtype not in ['int64','float64']]
list_cols_model = [col for col in df.columns if col not in list_cols_object]
# rm tags
list_cols_model = [col for col in list_cols_model if 'tag' not in col.lower()]
# rm flag
list_cols_model = [col for col in list_cols_model if 'flag' not in col.lower()]
# rm loss
list_cols_model = [col for col in list_cols_model if 'loss' not in col.lower()]
# rm cols to ignore
list_cols_ignore = [
    'data_set',
    'sum',
    'accountid',
    'bigdebtorid__app',
    'days_on_books',
    'bigdebtorid__ln',
    'bigaccountid__ln',
    'strzipcode__app',
    'bitdefault__app',
    'dti__app',
    'pti__app',
    'prop_row',
    'fltapproveddebttoincome__app',
    'fltapprovedapr_contract__app',
    'fltacquisitionfee__app',
    'row',
    'payment__app',
]
list_cols_model = [col for col in list_cols_model if col not in list_cols_ignore]

#### Fit model

In [9]:
# get train and test
df_train = df[df['data_set'] == 'train'].copy()
df_test = df[df['data_set'] == 'test'].copy()

# pool data
pool_train = cb.Pool(
    df_train[list_cols_model].copy(), 
    df_train[str_target], 
)
# pool
pool_valid = cb.Pool(
    df_test[list_cols_model].copy(), 
    df_test[str_target], 
)
# init class
cls_model_inference = cb.CatBoostClassifier(
    task_type='CPU',
    nan_mode='Min',
    random_state=42,
    eval_metric='AUC',
    iterations=100,
    learning_rate=None,
    class_weights=None,
    depth=None,
)
# fit
cls_model_inference.fit(
    pool_train,
    eval_set=[pool_valid],
    verbose=True,
    use_best_model=True,
    early_stopping_rounds=10, 
)

Learning rate set to 0.1637
0:	test: 0.5749964	best: 0.5749964 (0)	total: 84ms	remaining: 8.32s
1:	test: 0.5855460	best: 0.5855460 (1)	total: 111ms	remaining: 5.43s
2:	test: 0.5967104	best: 0.5967104 (2)	total: 136ms	remaining: 4.4s
3:	test: 0.6012653	best: 0.6012653 (3)	total: 161ms	remaining: 3.87s
4:	test: 0.6017204	best: 0.6017204 (4)	total: 186ms	remaining: 3.54s
5:	test: 0.6048700	best: 0.6048700 (5)	total: 212ms	remaining: 3.33s
6:	test: 0.6147031	best: 0.6147031 (6)	total: 239ms	remaining: 3.17s
7:	test: 0.6167581	best: 0.6167581 (7)	total: 264ms	remaining: 3.03s
8:	test: 0.6185413	best: 0.6185413 (8)	total: 290ms	remaining: 2.94s
9:	test: 0.6188220	best: 0.6188220 (9)	total: 316ms	remaining: 2.84s
10:	test: 0.6221149	best: 0.6221149 (10)	total: 342ms	remaining: 2.76s
11:	test: 0.6250063	best: 0.6250063 (11)	total: 368ms	remaining: 2.7s
12:	test: 0.6260483	best: 0.6260483 (12)	total: 393ms	remaining: 2.63s
13:	test: 0.6269323	best: 0.6269323 (13)	total: 420ms	remaining: 2.58s
14:	test: 0.6277329	best: 0.6277329 (14)	total: 446ms	remaining: 2.53s
15:	test: 0.6312531	best: 0.6312531 (15)	total: 471ms	remaining: 2.47s
16:	test: 0.6344603	best: 0.6344603 (16)	total: 497ms	remaining: 2.43s
17:	test: 0.6357978	best: 0.6357978 (17)	total: 523ms	remaining: 2.38s
18:	test: 0.6366404	best: 0.6366404 (18)	total: 547ms	remaining: 2.33s
19:	test: 0.6369042	best: 0.6369042 (19)	total: 574ms	remaining: 2.3s
20:	test: 0.6371484	best: 0.6371484 (20)	total: 600ms	remaining: 2.26s
21:	test: 0.6375489	best: 0.6375489 (21)	total: 627ms	remaining: 2.22s
22:	test: 0.6390233	best: 0.6390233 (22)	total: 654ms	remaining: 2.19s
23:	test: 0.6407878	best: 0.6407878 (23)	total: 680ms	remaining: 2.15s
24:	test: 0.6422668	best: 0.6422668 (24)	total: 708ms	remaining: 2.12s
25:	test: 0.6421794	best: 0.6422668 (24)	total: 733ms	remaining: 2.09s
26:	test: 0.6437914	best: 0.6437914 (26)	total: 759ms	remaining: 2.05s
27:	test: 0.6449803	best: 0.6449803 (27)	total: 784ms	remaining: 2.02s
28:	test: 0.6458954	best: 0.6458954 (28)	total: 811ms	remaining: 1.99s
29:	test: 0.6464444	best: 0.6464444 (29)	total: 837ms	remaining: 1.95s
30:	test: 0.6450081	best: 0.6464444 (29)	total: 863ms	remaining: 1.92s
31:	test: 0.6450006	best: 0.6464444 (29)	total: 889ms	remaining: 1.89s
32:	test: 0.6458886	best: 0.6464444 (29)	total: 916ms	remaining: 1.86s
33:	test: 0.6468273	best: 0.6468273 (33)	total: 942ms	remaining: 1.83s
34:	test: 0.6474860	best: 0.6474860 (34)	total: 968ms	remaining: 1.8s
35:	test: 0.6481781	best: 0.6481781 (35)	total: 994ms	remaining: 1.77s
36:	test: 0.6483775	best: 0.6483775 (36)	total: 1.02s	remaining: 1.74s
37:	test: 0.6485090	best: 0.6485090 (37)	total: 1.05s	remaining: 1.71s
38:	test: 0.6487688	best: 0.6487688 (38)	total: 1.07s	remaining: 1.68s
39:	test: 0.6483422	best: 0.6487688 (38)	total: 1.1s	remaining: 1.65s
40:	test: 0.6490795	best: 0.6490795 (40)	total: 1.13s	remaining: 1.62s
41:	test: 0.6496078	best: 0.6496078 (41)	total: 1.15s	remaining: 1.59s
42:	test: 0.6504610	best: 0.6504610 (42)	total: 1.18s	remaining: 1.56s
43:	test: 0.6505243	best: 0.6505243 (43)	total: 1.2s	remaining: 1.53s
44:	test: 0.6506899	best: 0.6506899 (44)	total: 1.23s	remaining: 1.5s
45:	test: 0.6504876	best: 0.6506899 (44)	total: 1.26s	remaining: 1.48s
46:	test: 0.6503268	best: 0.6506899 (44)	total: 1.28s	remaining: 1.45s
47:	test: 0.6512894	best: 0.6512894 (47)	total: 1.31s	remaining: 1.42s
48:	test: 0.6504424	best: 0.6512894 (47)	total: 1.34s	remaining: 1.39s
49:	test: 0.6510128	best: 0.6512894 (47)	total: 1.36s	remaining: 1.36s
50:	test: 0.6515243	best: 0.6515243 (50)	total: 1.39s	remaining: 1.33s
51:	test: 0.6513924	best: 0.6515243 (50)	total: 1.42s	remaining: 1.31s
52:	test: 0.6521424	best: 0.6521424 (52)	total: 1.44s	remaining: 1.28s
53:	test: 0.6530496	best: 0.6530496 (53)	total: 1.47s	remaining: 1.25s
54:	test: 0.6527201	best: 0.6530496 (53)	total: 1.5s	remaining: 1.22s
55:	test: 0.6523678	best: 0.6530496 (53)	total: 1.52s	remaining: 1.2s
56:	test: 0.6528568	best: 0.6530496 (53)	total: 1.55s	remaining: 1.17s
57:	test: 0.6530470	best: 0.6530496 (53)	total: 1.57s	remaining: 1.14s
58:	test: 0.6535064	best: 0.6535064 (58)	total: 1.6s	remaining: 1.11s
59:	test: 0.6539427	best: 0.6539427 (59)	total: 1.63s	remaining: 1.08s
60:	test: 0.6538611	best: 0.6539427 (59)	total: 1.65s	remaining: 1.06s
61:	test: 0.6544218	best: 0.6544218 (61)	total: 1.68s	remaining: 1.03s
62:	test: 0.6542985	best: 0.6544218 (61)	total: 1.71s	remaining: 1s
63:	test: 0.6533240	best: 0.6544218 (61)	total: 1.73s	remaining: 974ms
64:	test: 0.6537927	best: 0.6544218 (61)	total: 1.76s	remaining: 947ms
65:	test: 0.6539328	best: 0.6544218 (61)	total: 1.78s	remaining: 919ms
66:	test: 0.6539502	best: 0.6544218 (61)	total: 1.81s	remaining: 892ms
67:	test: 0.6539484	best: 0.6544218 (61)	total: 1.84s	remaining: 864ms
68:	test: 0.6532014	best: 0.6544218 (61)	total: 1.86s	remaining: 837ms
69:	test: 0.6534325	best: 0.6544218 (61)	total: 1.89s	remaining: 810ms
70:	test: 0.6530942	best: 0.6544218 (61)	total: 1.92s	remaining: 784ms
71:	test: 0.6529766	best: 0.6544218 (61)	total: 1.95s	remaining: 757ms
Stopped by overfitting detector  (10 iterations wait)

bestTest = 0.6544217813
bestIteration = 61

Shrink model to first 62 iterations.

#### Get feature importance

In [10]:
# get importance
df_tmp = get_catboost_feat_importance(
    cls_model_inference=cls_model_inference,
    pool_eval=pool_valid,
)

#### Map description

In [11]:
# get the data dict
df_data_dict = pd.read_csv('data_dictionary.csv')
dict_map = dict(zip(df_data_dict['feature_name'], df_data_dict['Description']))
df_tmp['description'] = df_tmp['feature'].map(dict_map)

# save
str_filename = 'df_feat_imp.csv'
str_local_path = f'{str_dirname_output}/{str_filename}'
df_tmp.to_csv(str_local_path, index=False)

# show
df_tmp

,feature,importance,description
0,linka006__tu,0.001259,Number of total inquiries in the last 3 years....
1,fltadvance__app,0.000886,NaN
2,bi09s__tu,0.000811,Number of bank installment trades opened in pa...
3,balmag01__tu,0.000663,Non-mortgage balance magnitude algorithm over ...
4,au20s__tu,0.000636,Months since oldest auto trade opened
...,...,...,...
2642,g228s__tu,-0.000185,Number of 90 or more days past due trades (cur...
2643,agg613__tu,-0.000227,Aggregate bankcard credit line for month 13
2644,addrprevioustimeoldest__ln,-0.000241,Time (in months) since the subject was first r...
2645,cv05__tu,-0.000348,Months since most recent non-medical third par...
2646,fltallowance__app,-0.000438,Allowance