In [1]:
import pandas as pd
import os

# Constants

In [2]:
str_project = os.getcwd().split('\\')[4]
print(f'Project: {str_project}')
str_task = os.getcwd().split('\\')[5]
print(f'Task: {str_task}')
str_subtask = os.getcwd().split('\\')[6]
print(f'Subtask: {str_subtask}')

str_dirname_output = './output'

Project: 06_ml_in_python
Task: 01_home_credit_model
Subtask: 01_data_collection

In [3]:
os.getcwd()

'M:\\Risk Management\\Bridger Hyde\\20240521_bridger_internship\\06_ml_in_python\\01_home_credit_model\\01_data_collection'

In [4]:
try:
    os.mkdir(str_dirname_output)
except FileExistsError:
    pass

# Pull In Training CSV

In [5]:
df = pd.read_csv('./input/train.csv')
df

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,396902,0,Cash loans,F,Y,Y,0,121500,835380,40320.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,4.0
1,112096,0,Cash loans,F,N,Y,0,202500,516069,26478.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,6.0
2,285821,1,Cash loans,M,Y,Y,1,180000,284400,22469.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
3,376901,0,Cash loans,F,N,Y,0,90000,265536,13685.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
4,325138,0,Cash loans,F,Y,Y,0,94500,755190,30078.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124995,217133,0,Revolving loans,M,Y,Y,0,54000,157500,7875.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
124996,169482,0,Cash loans,F,N,N,0,180000,661500,17577.0,...,0,0,0,0,0.0,0.0,0.0,2.0,0.0,2.0
124997,333982,0,Cash loans,F,N,Y,0,90000,239850,24705.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
124998,249620,0,Revolving loans,M,N,Y,0,76500,180000,9000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,0.0
124999,320235,0,Cash loans,M,Y,N,0,81000,306000,24305.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
# insert row numbers for easy splitting
rownum = range(len(df))
df.insert(0, 'rownum', rownum)
df.head()

,rownum,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,0,396902,0,Cash loans,F,Y,Y,0,121500,835380,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,4.0
1,1,112096,0,Cash loans,F,N,Y,0,202500,516069,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,6.0
2,2,285821,1,Cash loans,M,Y,Y,1,180000,284400,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
3,3,376901,0,Cash loans,F,N,Y,0,90000,265536,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
4,4,325138,0,Cash loans,F,Y,Y,0,94500,755190,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

# Export Data For Analysis

In [10]:
df.to_csv('./output/training.csv', index=False)