In [4]:
!pip install pyodbc

Collecting pyodbc
  Downloading pyodbc-5.1.0-cp312-cp312-win_amd64.whl.metadata (2.8 kB)
Downloading pyodbc-5.1.0-cp312-cp312-win_amd64.whl (69 kB)
   ---------------------------------------- 0.0/69.3 kB ? eta -:--:--
   ----- ---------------------------------- 10.2/69.3 kB ? eta -:--:--
   ----- ---------------------------------- 10.2/69.3 kB ? eta -:--:--
   ----------------------- ---------------- 41.0/69.3 kB 393.8 kB/s eta 0:00:01
   ---------------------------------------- 69.3/69.3 kB 541.5 kB/s eta 0:00:00
Installing collected packages: pyodbc
Successfully installed pyodbc-5.1.0

In [5]:
import pandas as pd
import pyodbc
import os

#### read sql in code

In [6]:
# Use """ to designate SQL query as a string
str_query = """
SELECT 
bigAccountId,
FundingMonth,
LoanStatus,
strTier,
DebtorState
FROM electra.riskdb.analytics.tbltempstaticpool
WHERE LoanStatus = 'C' AND DebtorState IN ('CA', 'AZ')
ORDER BY FundingMonth desc
"""

In [7]:
# establish SQL connection
conn = pyodbc.connect(
    'Driver={SQL Server};'
    'Server=electra;'
    'Database=pfsdb;'
    'Trusted_Connection=yes;'
)

data = pd.read_sql_query(
    sql=str_query,
    con=conn,
)


# close the connection 
conn.close()

# how variables work
# conn.close() == pyodbc.close()

C:\Users\bhyde\AppData\Local\Temp\ipykernel_16948\3484695457.py:9: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data = pd.read_sql_query(

In [8]:
# show data
# data

# show the head (begining) or tail(end)
data.head(5)

   bigAccountId FundingMonth LoanStatus strTier DebtorState
0       7353387   2023-11-01          C      A1          CA
1       7308436   2023-11-01          C       C          AZ
2       7150512   2023-10-01          C       C          AZ
3       7079158   2023-09-01          C       A          CA
4       7066350   2023-09-01          C       B          AZ

#### Read in SQL from sql script already written

In [10]:
# find our sql query, label it as str_query
#str_query = open('../../02_sql/01_sql_practice/sql_for_python.sql', 'r').read()
#os.listdir()
str_query = open('./sql/SQLQuery1.sql', 'r').read()
print(str_query)

SELECT *
FROM electra.riskdb.analytics.tbltempstaticpool
WHERE dtmfunded > '2020';

In [11]:
# establish SQL connection
conn = pyodbc.connect(
    'Driver={SQL Server};'
    'Server=electra;'
    'Database=pfsdb;'
    'Trusted_Connection=yes;'
)

data = pd.read_sql_query(
    sql=str_query,
    con=conn,
)


# close the connection
conn.close()

C:\Users\bhyde\AppData\Local\Temp\ipykernel_16948\1868007509.py:9: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data = pd.read_sql_query(

In [12]:
data.head(5)

,bigAccountId,FundingMonth,LoanStatus,CreditorProgramInitial,strTier,intOpenBKType,Portfolio,DebtorState,ContractDate,BookingDate,...,mnyManheim,ManheimToNADA,RiskByFinanced,PTIbyAmtFinanced,DTIbyAmtFinanced,bitSystemApproval,SegmentedScorebyFinanced,bitEncore,DealerType,intVehicleClass
0,7470760,2024-01-01,A,P,B,NaN,E,MO,2024-01-05 00:00:00,2024-01-24,...,NaN,None,None,1888.031992,6574.221552,True,None,None,Franchise,3
1,7472014,2024-01-01,A,P,A1,NaN,E,OR,2024-01-13 00:00:00,2024-01-24,...,NaN,None,None,2744.780939,6848.388939,True,None,None,Franchise,2
2,7473634,2024-01-01,A,P,A1,7.0,E,KY,2024-01-06 00:00:00,2024-01-12,...,NaN,None,None,3742.091139,10049.147375,True,None,None,Franchise,3
3,7476525,2024-01-01,A,P,B,7.0,E,IL,2024-01-18 00:00:00,2024-01-24,...,NaN,None,None,3022.181068,7005.851720,True,None,None,Franchise,1
4,7479545,2024-01-01,A,P,C,NaN,E,NM,2024-01-10 17:34:14,2024-01-30,...,NaN,None,None,3200.682916,9801.575585,True,None,None,Franchise,3

#### Create output directory to store output files

In [14]:
# to see whhat kind of error type we get 
os.mkdir('output')

FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'output'

In [15]:
# try and except block
# try some code, you know there will be exception/error, so do something else
try: 
    os.mkdir('output')
except FileExistsError:
    pass

In [16]:
data.to_csv('./output/python_data.csv', index=False)