In [1]:
import pandas as pd
import os
import matplotlib.pyplot as plt
import pyodbc
import numpy as np
import pickle

In [2]:
class GetData:
    def __init__(self):
        pass
    def read_sql_script(self, str_local_path):
        str_query = open(str_local_path, 'r').read()
        # save to object
        self.str_query = str_query
        # return object
        return self
    def pull_data_from_sql(self, conn, bool_close_conn=True):
        df = pd.read_sql_query(
            sql=self.str_query,
            con=conn,
        )
        if bool_close_conn:
            conn.close()
        else:
            pass
        return df

In [7]:
# initialize class To create df_check
cls_get_data = GetData()

#read query
str_filename = 'GenScoresTable2024Flask.sql'
str_local_path = f'./sql/{str_filename}'
cls_get_data.read_sql_script(
    str_local_path=str_local_path,
)
# pull data
conn = pyodbc.connect(
    'Driver={SQL Server};'
    'Server=electra;'
    'Database=pfsdb;'
    'Trusted_connection=yes;'
)
df_check = cls_get_data.pull_data_from_sql(
    conn=conn,
    bool_close_conn=True,
)
df_check

C:\Users\bhyde\AppData\Local\Temp\ipykernel_14056\3525508220.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(

,bigAccountId,DebtorState,bigDealerId,dtmStampCreation,dtmFunded,intTerm,intOpenBKType,strTier,AmtFinanced,OriginalInterestRate,MaxFico,Gen 11,Gen 12,Gen
0,7148408,MI,2222,2023-10-02 10:46:59.683,2024-01-10,72,13.0,A,28369.14,19.74,542.0,0.055039,0.126122,Gen11
1,7171803,MI,5948,2023-10-07 10:48:33.760,2024-01-22,72,7.0,B,23322.44,25.00,519.0,0.139163,0.311783,Gen11
2,7221580,IN,6703,2023-10-16 09:32:06.757,2024-02-02,60,13.0,A1,21807.24,18.00,580.0,0.009565,0.025141,Gen11
3,7228265,PA,6159,2023-10-18 14:25:13.170,2024-02-07,72,NaN,B,13281.06,26.74,574.0,0.120231,0.241734,Gen11
4,7254327,VA,929,2023-10-20 15:26:45.807,2024-01-16,72,13.0,A,24286.22,19.99,537.0,0.040068,0.029945,Gen11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10007,7918936,MD,2408,2024-06-08 08:52:30.010,2024-06-10,72,NaN,B,17976.03,25.37,627.0,0.120553,0.174345,Gen11
10008,7920157,OR,7207,2024-06-08 12:27:30.660,2024-06-10,72,NaN,B,18539.47,21.99,568.0,0.095689,0.190004,Gen11
10009,7920202,IN,5189,2024-06-08 12:35:45.430,2024-06-10,66,NaN,B,22553.62,25.00,629.0,0.077278,0.347628,Gen11
10010,7921132,MO,6806,2024-06-08 15:37:37.353,2024-06-10,72,NaN,B,27093.43,26.41,590.0,0.114264,0.410253,Gen11
10011,7921273,IN,6816,2024-06-08 16:15:41.427,2024-06-10,66,NaN,D,13067.93,25.00,595.0,0.178079,0.799698,Gen11

In [8]:
dfstatetier = df_check[['DebtorState','strTier']]
dfstatetier

      DebtorState strTier
0              MI       A
1              MI       B
2              IN      A1
3              PA       B
4              VA       A
...           ...     ...
10007          MD       B
10008          OR       B
10009          IN       B
10010          MO       B
10011          IN       D

[10012 rows x 2 columns]

In [25]:
dfg = dfstatetier.groupby(by=['strTier']).agg('sum', 'sum')
dfg

Empty DataFrame
Columns: []
Index: [A, A1, B, C, D, Gold, Platinum]

In [27]:
# initialize class To create df_check
cls_get_data = GetData()

#read query
str_filename = 'StateTiersStackedBar.sql'
str_local_path = f'./sql/{str_filename}'
cls_get_data.read_sql_script(
    str_local_path=str_local_path,
)
# pull data
conn = pyodbc.connect(
    'Driver={SQL Server};'
    'Server=electra;'
    'Database=pfsdb;'
    'Trusted_connection=yes;'
)
dfstackedbar = cls_get_data.pull_data_from_sql(
    conn=conn,
    bool_close_conn=True,
)
dfstackedbar

C:\Users\bhyde\AppData\Local\Temp\ipykernel_14056\3525508220.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(

     NumberOfTiers State Tier
0                2    LA    A
1                2    SD    C
2               41    AL    D
3                7    IA   A1
4              667    IL    B
..             ...   ...  ...
205             31    WA   A1
206              2    DE    C
207             16    MN    A
208            141    TN    B
209             15    SC    A

[210 rows x 3 columns]

In [28]:
str_root = os.getcwd().split('\\')[0]
print(str_root)

str_risk = os.getcwd().split('\\')[1]
print(str_risk)

str_user = os.getcwd().split('\\')[2]
print(str_user)

str_project = os.getcwd().split('\\')[3]
print(f'Project: {str_project}')

str_task = os.getcwd().split('\\')[4]
print(f'Task: {str_task}')

str_subtask = os.getcwd().split('\\')[5]
print(f'Subtask: {str_subtask}')

M:
Risk Management
Bridger Hyde
Project: 20240521_bridger_internship
Task: 03_python
Subtask: 01_jupyter_practice

In [29]:
dfstackedbar.to_parquet(f'{str_root}/{str_risk}/{str_user}/{str_project}/04_flask/static/home/dfstackedbar.gzip')