In [1]:
import os
import pandas as pd
import numpy as np
from tqdm import tqdm

try:
    import catboost as cb
except:
    ! pip install catboost
    import catboost as cb

#### Functions

In [2]:
def get_catboost_feat_importance(cls_model_inference, pool_eval):
    df_tmp = cls_model_inference.get_feature_importance(
        data=pool_eval,
        type='LossFunctionChange',
        prettified=True,
    )
    df_tmp.columns = ['feature', 'importance']
    df_tmp.sort_values(by='importance', ascending=False, inplace=True)
    return df_tmp

#### Constants

In [3]:
str_project = os.getcwd().split('/')[4].replace('_','-')
print(f'Project: {str_project}')

str_task = os.getcwd().split('/')[5]
print(f'Task: {str_task}')

str_dirname_output = './output'

str_target = 'has_inst_tag'

list_str_inst = [
    # from ben: 2025-02-21
    'CURRENT',
    'SELF',
    # key words
    'CHIME-STRIDE',
    'CHIMEFINAL',
    # from dustin: 2025-02-24
    'SELF FIN',
    'SELF/LEAD',
    'SELFINC/LEAD',
    'SBNASELFLNDR',
    'SBNA SELF',
    'CHIME',
    'CLEO',
    'CLEO AI',
    'VARO',
    'ATLAS',
    'ATLCAPBKSELF',
    'POSSIBLE',
    'POSSIBLE FIN',
    'KIKOFF',
    'SUPER.COM',
    'STEP',
    'STEP MOBILE',
    'BRIGHT',
    'BRIGHT BLDR',
    'FIG TECH INC',
    'SELF/RENT',
    'SELFBILLSE',
    'PROGRESSRES',
    'FLEX',
    'FLEXFINANCE',
]

Project: 20250221-credit-builder-analysis
Task: 04_credit_builder_feats

#### Output dir

In [4]:
try:
    os.mkdir(str_dirname_output)
except:
    pass

#### Import data

In [5]:
str_filename = 'df.gzip'
str_uri = f's3://20241112-simple-model-test/08_prep_data/{str_filename}'
df = pd.read_parquet(
    str_uri,
)
# sort
df.sort_values(by='request_datetime', ascending=True, inplace=True)
df

,accountid,request_datetime,response_model_name,file_key,bitdebtor,bitdebtor__app,dealerstate__app,strdealershiptrackertype__app,strname__app,bitdealertrack__app,...,ENG-franchise,ENG-has_codebtor,ENG-vehicle_age,ENG-payment_to_income,ENG-loan_to_value,ENG-bk,ENG-perfect_payment_hx,ENG-perfect_payment_hx_open,ENG-perfect_payment_hx_closed,ENG-bk_x_wtd_avg
0,5702434,2021-07-26 16:29:29.3903686,Gen10,deprecated/03_pull_payloads_tbldove/df_request...,1,1,Iowa,Franchise,Iowa,True,...,1,0,7,NaN,1.311220,1,0,0,0,0.616667
1,5714239,2021-07-26 16:39:34.1121025,Gen10,deprecated/03_pull_payloads_tbldove/df_request...,1,1,Utah,Franchise,Utah,True,...,1,0,5,NaN,1.432368,0,0,0,0,NaN
2,5713063,2021-07-26 16:48:39.3211104,Gen10,deprecated/03_pull_payloads_tbldove/df_request...,1,1,Illinois,Franchise,Illinois,True,...,1,0,4,NaN,1.587073,1,0,0,0,NaN
3,5713732,2021-07-27 09:02:35.3300974,Gen10,deprecated/03_pull_payloads_tbldove/df_request...,1,1,Michigan,Independent,Michigan,False,...,0,0,2,NaN,1.081881,0,1,0,1,0.000000
4,5715634,2021-07-27 09:18:12.2190097,Gen10,deprecated/03_pull_payloads_tbldove/df_request...,1,1,Arizona,Franchise,Arizona,False,...,1,0,4,NaN,1.371350,0,1,0,1,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94472,8420588,2024-11-26 06:16:16+00:00,PRESTIGE-GEN-XII,01_pull_payloads/df_requests_2024-11-25.gzip,1,1,North Carolina,Independent,North Carolina,True,...,0,0,4,NaN,1.280957,0,0,0,0,0.000000
94473,8401043,2024-11-26 06:21:44+00:00,PRESTIGE-GEN-XII,01_pull_payloads/df_requests_2024-11-25.gzip,1,1,Nevada,Franchise,Nevada,True,...,1,0,0,NaN,1.198869,1,0,0,0,0.367073
94474,8414683,2024-11-26 06:25:09+00:00,PRESTIGE-GEN-XII,01_pull_payloads/df_requests_2024-11-25.gzip,1,1,Virginia,Franchise,Virginia,False,...,1,0,3,NaN,1.313231,0,0,0,0,NaN
94475,8359085,2024-11-26 06:32:28+00:00,PRESTIGE-GEN-XII,01_pull_payloads/df_requests_2024-11-25.gzip,1,1,Alabama,Franchise,Alabama,True,...,1,0,3,NaN,0.991586,1,0,0,0,0.006585
94476,8418357,2024-11-26 06:54:45+00:00,PRESTIGE-GEN-XII,01_pull_payloads/df_requests_2024-11-25.gzip,1,1,Maryland,Independent,Maryland,False,...,0,0,3,0.094662,1.139095,0,0,0,0,0.000000

#### Create target

In [6]:
df['list_institutions'] = df['str_institution__tu_pmthx'].apply(
    lambda x: eval(x.replace('nan','None')),
)
df['list_institutions'] = df['list_institutions'].apply(
    lambda x: [] if x is None else x,
)

list_str_col_new = []
for str_inst in tqdm(list_str_inst):
    str_col_new = f'{str_inst}_tag'
    df[str_col_new] = df['list_institutions'].apply(
        lambda x: 1 if str_inst in x else 0,
    )
    list_str_col_new.append(str_col_new)

df['sum'] = df[list_str_col_new].sum(axis=1)
df['has_inst_tag'] = df['sum'].apply(
    lambda x: 1 if x > 0 else 0,
)
flt_mn = df['has_inst_tag'].mean()
print(f'Proportion has tag: {flt_mn:0.4f}')
# show
#df

100%|██████████| 29/29 [00:01<00:00, 20.18it/s]

Proportion has tag: 0.2053

#### Mark train/test

In [7]:
df['row'] = list(range(0, df.shape[0]))
df['prop_row'] = df['row'] / df.shape[0]
df['data_set'] = df['prop_row'].apply(
    lambda x: 'train' if x <= 0.8 else 'test',
)
df.drop(['row','prop_row'], axis=1, inplace=True)

#### List cols model

In [8]:
# rm target
list_cols_model = [col for col in df.columns if col != str_target]
# rm non-numeric
list_cols_object = [col for col in list_cols_model if df[col].dtype not in ['int64','float64']]
list_cols_model = [col for col in df.columns if col not in list_cols_object]
# rm tags
list_cols_model = [col for col in list_cols_model if 'tag' not in col.lower()]
# rm flag
list_cols_model = [col for col in list_cols_model if 'flag' not in col.lower()]
# rm loss
list_cols_model = [col for col in list_cols_model if 'loss' not in col.lower()]
# rm cols to ignore
list_cols_ignore = [
    'data_set',
    'sum',
    'accountid',
    'bigdebtorid__app',
    'days_on_books',
    'bigdebtorid__ln',
    'bigaccountid__ln',
    'strzipcode__app',
    'bitdefault__app',
    'dti__app',
    'pti__app',
    'prop_row',
    'fltapproveddebttoincome__app',
    'fltapprovedapr_contract__app',
    'fltacquisitionfee__app',
    'row',
    'payment__app',
]
list_cols_model = [col for col in list_cols_model if col not in list_cols_ignore]

#### Catboost model

In [9]:
# get train and test
df_train = df[df['data_set'] == 'train'].copy()
df_test = df[df['data_set'] == 'test'].copy()

# pool data
pool_train = cb.Pool(
    df_train[list_cols_model].copy(), 
    df_train[str_target], 
)
# pool
pool_valid = cb.Pool(
    df_test[list_cols_model].copy(), 
    df_test[str_target], 
)
# init class
cls_model_inference = cb.CatBoostClassifier(
    task_type='CPU',
    nan_mode='Min',
    random_state=42,
    eval_metric='AUC',
    iterations=100,
    learning_rate=None,
    class_weights=None,
    depth=None,
)
# fit
cls_model_inference.fit(
    pool_train,
    eval_set=[pool_valid],
    verbose=True,
    use_best_model=True,
    early_stopping_rounds=10, 
)

Learning rate set to 0.251118
0:	test: 0.8320961	best: 0.8320961 (0)	total: 95.4ms	remaining: 9.44s
1:	test: 0.8631967	best: 0.8631967 (1)	total: 138ms	remaining: 6.75s
2:	test: 0.8673892	best: 0.8673892 (2)	total: 179ms	remaining: 5.78s
3:	test: 0.8774530	best: 0.8774530 (3)	total: 223ms	remaining: 5.36s
4:	test: 0.8872382	best: 0.8872382 (4)	total: 265ms	remaining: 5.03s
5:	test: 0.8951279	best: 0.8951279 (5)	total: 306ms	remaining: 4.79s
6:	test: 0.8978682	best: 0.8978682 (6)	total: 352ms	remaining: 4.68s
7:	test: 0.9043988	best: 0.9043988 (7)	total: 396ms	remaining: 4.55s
8:	test: 0.9044213	best: 0.9044213 (8)	total: 441ms	remaining: 4.46s
9:	test: 0.9052144	best: 0.9052144 (9)	total: 484ms	remaining: 4.36s
10:	test: 0.9076813	best: 0.9076813 (10)	total: 527ms	remaining: 4.26s
11:	test: 0.9094192	best: 0.9094192 (11)	total: 566ms	remaining: 4.15s
12:	test: 0.9098600	best: 0.9098600 (12)	total: 610ms	remaining: 4.08s
13:	test: 0.9114035	best: 0.9114035 (13)	total: 652ms	remaining: 4s
14:	test: 0.9127198	best: 0.9127198 (14)	total: 692ms	remaining: 3.92s
15:	test: 0.9146921	best: 0.9146921 (15)	total: 733ms	remaining: 3.85s
16:	test: 0.9146754	best: 0.9146921 (15)	total: 773ms	remaining: 3.77s
17:	test: 0.9154986	best: 0.9154986 (17)	total: 816ms	remaining: 3.72s
18:	test: 0.9163261	best: 0.9163261 (18)	total: 854ms	remaining: 3.64s
19:	test: 0.9173398	best: 0.9173398 (19)	total: 895ms	remaining: 3.58s
20:	test: 0.9180381	best: 0.9180381 (20)	total: 938ms	remaining: 3.53s
21:	test: 0.9188964	best: 0.9188964 (21)	total: 977ms	remaining: 3.46s
22:	test: 0.9208404	best: 0.9208404 (22)	total: 1.02s	remaining: 3.42s
23:	test: 0.9204397	best: 0.9208404 (22)	total: 1.06s	remaining: 3.35s
24:	test: 0.9211385	best: 0.9211385 (24)	total: 1.1s	remaining: 3.31s
25:	test: 0.9216336	best: 0.9216336 (25)	total: 1.14s	remaining: 3.26s
26:	test: 0.9222340	best: 0.9222340 (26)	total: 1.18s	remaining: 3.2s
27:	test: 0.9228897	best: 0.9228897 (27)	total: 1.23s	remaining: 3.15s
28:	test: 0.9230292	best: 0.9230292 (28)	total: 1.27s	remaining: 3.1s
29:	test: 0.9232866	best: 0.9232866 (29)	total: 1.31s	remaining: 3.05s
30:	test: 0.9236686	best: 0.9236686 (30)	total: 1.35s	remaining: 3s
31:	test: 0.9241267	best: 0.9241267 (31)	total: 1.39s	remaining: 2.95s
32:	test: 0.9245743	best: 0.9245743 (32)	total: 1.43s	remaining: 2.9s
33:	test: 0.9267079	best: 0.9267079 (33)	total: 1.47s	remaining: 2.85s
34:	test: 0.9271065	best: 0.9271065 (34)	total: 1.51s	remaining: 2.8s
35:	test: 0.9274469	best: 0.9274469 (35)	total: 1.55s	remaining: 2.75s
36:	test: 0.9279543	best: 0.9279543 (36)	total: 1.59s	remaining: 2.71s
37:	test: 0.9279430	best: 0.9279543 (36)	total: 1.63s	remaining: 2.66s
38:	test: 0.9281402	best: 0.9281402 (38)	total: 1.67s	remaining: 2.61s
39:	test: 0.9282759	best: 0.9282759 (39)	total: 1.71s	remaining: 2.56s
40:	test: 0.9283620	best: 0.9283620 (40)	total: 1.75s	remaining: 2.52s
41:	test: 0.9284555	best: 0.9284555 (41)	total: 1.79s	remaining: 2.47s
42:	test: 0.9288332	best: 0.9288332 (42)	total: 1.83s	remaining: 2.43s
43:	test: 0.9291623	best: 0.9291623 (43)	total: 1.87s	remaining: 2.38s
44:	test: 0.9298427	best: 0.9298427 (44)	total: 1.91s	remaining: 2.33s
45:	test: 0.9300738	best: 0.9300738 (45)	total: 1.95s	remaining: 2.29s
46:	test: 0.9304958	best: 0.9304958 (46)	total: 1.99s	remaining: 2.24s
47:	test: 0.9309345	best: 0.9309345 (47)	total: 2.03s	remaining: 2.2s
48:	test: 0.9312477	best: 0.9312477 (48)	total: 2.07s	remaining: 2.15s
49:	test: 0.9315772	best: 0.9315772 (49)	total: 2.1s	remaining: 2.1s
50:	test: 0.9323574	best: 0.9323574 (50)	total: 2.15s	remaining: 2.06s
51:	test: 0.9325767	best: 0.9325767 (51)	total: 2.19s	remaining: 2.02s
52:	test: 0.9325874	best: 0.9325874 (52)	total: 2.23s	remaining: 1.98s
53:	test: 0.9325757	best: 0.9325874 (52)	total: 2.26s	remaining: 1.93s
54:	test: 0.9329526	best: 0.9329526 (54)	total: 2.3s	remaining: 1.88s
55:	test: 0.9328641	best: 0.9329526 (54)	total: 2.34s	remaining: 1.84s
56:	test: 0.9329146	best: 0.9329526 (54)	total: 2.38s	remaining: 1.8s
57:	test: 0.9330607	best: 0.9330607 (57)	total: 2.42s	remaining: 1.75s
58:	test: 0.9328803	best: 0.9330607 (57)	total: 2.46s	remaining: 1.71s
59:	test: 0.9331265	best: 0.9331265 (59)	total: 2.5s	remaining: 1.67s
60:	test: 0.9330412	best: 0.9331265 (59)	total: 2.54s	remaining: 1.62s
61:	test: 0.9330456	best: 0.9331265 (59)	total: 2.57s	remaining: 1.57s
62:	test: 0.9334514	best: 0.9334514 (62)	total: 2.61s	remaining: 1.53s
63:	test: 0.9334282	best: 0.9334514 (62)	total: 2.65s	remaining: 1.49s
64:	test: 0.9336702	best: 0.9336702 (64)	total: 2.69s	remaining: 1.45s
65:	test: 0.9339906	best: 0.9339906 (65)	total: 2.73s	remaining: 1.41s
66:	test: 0.9341809	best: 0.9341809 (66)	total: 2.77s	remaining: 1.36s
67:	test: 0.9351079	best: 0.9351079 (67)	total: 2.81s	remaining: 1.32s
68:	test: 0.9350740	best: 0.9351079 (67)	total: 2.85s	remaining: 1.28s
69:	test: 0.9352874	best: 0.9352874 (69)	total: 2.88s	remaining: 1.24s
70:	test: 0.9352020	best: 0.9352874 (69)	total: 2.93s	remaining: 1.2s
71:	test: 0.9353141	best: 0.9353141 (71)	total: 2.96s	remaining: 1.15s
72:	test: 0.9353772	best: 0.9353772 (72)	total: 3s	remaining: 1.11s
73:	test: 0.9353772	best: 0.9353772 (72)	total: 3.03s	remaining: 1.07s
74:	test: 0.9363650	best: 0.9363650 (74)	total: 3.08s	remaining: 1.03s
75:	test: 0.9364554	best: 0.9364554 (75)	total: 3.12s	remaining: 985ms
76:	test: 0.9365275	best: 0.9365275 (76)	total: 3.15s	remaining: 943ms
77:	test: 0.9365128	best: 0.9365275 (76)	total: 3.19s	remaining: 901ms
78:	test: 0.9365200	best: 0.9365275 (76)	total: 3.23s	remaining: 858ms
79:	test: 0.9365034	best: 0.9365275 (76)	total: 3.26s	remaining: 816ms
80:	test: 0.9368005	best: 0.9368005 (80)	total: 3.31s	remaining: 775ms
81:	test: 0.9368187	best: 0.9368187 (81)	total: 3.35s	remaining: 735ms
82:	test: 0.9368209	best: 0.9368209 (82)	total: 3.38s	remaining: 692ms
83:	test: 0.9367805	best: 0.9368209 (82)	total: 3.42s	remaining: 651ms
84:	test: 0.9367701	best: 0.9368209 (82)	total: 3.45s	remaining: 609ms
85:	test: 0.9367250	best: 0.9368209 (82)	total: 3.49s	remaining: 568ms
86:	test: 0.9367202	best: 0.9368209 (82)	total: 3.52s	remaining: 526ms
87:	test: 0.9367883	best: 0.9368209 (82)	total: 3.56s	remaining: 485ms
88:	test: 0.9367884	best: 0.9368209 (82)	total: 3.59s	remaining: 444ms
89:	test: 0.9369002	best: 0.9369002 (89)	total: 3.63s	remaining: 403ms
90:	test: 0.9368865	best: 0.9369002 (89)	total: 3.67s	remaining: 363ms
91:	test: 0.9368738	best: 0.9369002 (89)	total: 3.7s	remaining: 322ms
92:	test: 0.9370368	best: 0.9370368 (92)	total: 3.74s	remaining: 282ms
93:	test: 0.9370353	best: 0.9370368 (92)	total: 3.78s	remaining: 241ms
94:	test: 0.9370054	best: 0.9370368 (92)	total: 3.81s	remaining: 201ms
95:	test: 0.9375173	best: 0.9375173 (95)	total: 3.85s	remaining: 161ms
96:	test: 0.9375172	best: 0.9375173 (95)	total: 3.89s	remaining: 120ms
97:	test: 0.9376207	best: 0.9376207 (97)	total: 3.93s	remaining: 80.1ms
98:	test: 0.9376651	best: 0.9376651 (98)	total: 3.96s	remaining: 40ms
99:	test: 0.9376210	best: 0.9376651 (98)	total: 4s	remaining: 0us

bestTest = 0.9376650641
bestIteration = 98

Shrink model to first 99 iterations.

#### Get feat importance

In [10]:
# get importance
df_tmp = get_catboost_feat_importance(
    cls_model_inference=cls_model_inference,
    pool_eval=pool_valid,
)

#### Map description

In [11]:
# get the data dict
df_data_dict = pd.read_csv('data_dictionary.csv')
dict_map = dict(zip(df_data_dict['feature_name'], df_data_dict['Description']))
df_tmp['description'] = df_tmp['feature'].map(dict_map)

# save
str_filename = 'df_feat_imp.csv'
str_local_path = f'{str_dirname_output}/{str_filename}'
df_tmp.to_csv(str_local_path, index=False)

# show
df_tmp

,feature,importance,description
0,g201a__tu,0.047056,Total open to buy of open trades verified in p...
1,g202a__tu,0.046828,Total open to buy of open trades verified in p...
2,agg401__tu,0.009668,Aggregate non-mortgage actual payment for month 1
3,trd__tu,0.009136,Number of trades
4,at30s__tu,0.008314,Percentage of open trades > 50% of credit line...
...,...,...,...
2639,rev326__tu,-0.003888,Average Total Open-to-Buy for Revolving accoun...
2640,re102s__tu,-0.004340,Average credit line of open revolving trades v...
2641,rev316__tu,-0.004620,Max Total Open-to-Buy for Revolving accounts o...
2642,paymnt07__tu,-0.004996,Ratio of actual to minimum payment for non-mor...
2643,rev317__tu,-0.007356,Max Total Open-to-Buy for Revolving accounts o...

#### Pivot

In [12]:
dict_agg = {col: 'mean' for col in df_tmp['feature']}
df_tmp = df.groupby(by=str_target, as_index=False).agg(dict_agg)
dict_map = {
    0: 'No',
    1: 'Yes',
}
df_tmp[str_target] = df_tmp[str_target].map(dict_map)
df_tmp

,has_inst_tag,g201a__tu,g202a__tu,agg401__tu,trd__tu,at30s__tu,s043s__tu,bi20s__tu,at03s__tu,paymnt10__tu,...,rev319__tu,at28a__tu,bi09s__tu,fr28s__tu,bc03s__tu,rev326__tu,re102s__tu,rev316__tu,paymnt07__tu,rev317__tu
0,No,1111.498473,1136.729417,520.589708,12.679400,78.844259,1.903134,98.661719,3.808096,4.693961,...,2255.679028,39022.936641,0.405812,1591.416447,1.902057,1046.542635,1201.454551,1426.515380,2.444777,1572.174615
1,Yes,1835.005791,1861.210154,704.027129,15.777829,60.154504,1.268843,62.417808,4.795341,6.119892,...,1919.110120,28149.845777,0.822669,1241.409495,1.910659,1018.481951,1013.560430,1457.112833,2.678118,1543.586905

#### Transpose

In [13]:
df_tmp_t = df_tmp.set_index(str_target).T
# show
df_tmp_t

has_inst_tag           No          Yes
g201a__tu     1111.498473  1835.005791
g202a__tu     1136.729417  1861.210154
agg401__tu     520.589708   704.027129
trd__tu         12.679400    15.777829
at30s__tu       78.844259    60.154504
...                   ...          ...
rev326__tu    1046.542635  1018.481951
re102s__tu    1201.454551  1013.560430
rev316__tu    1426.515380  1457.112833
paymnt07__tu     2.444777     2.678118
rev317__tu    1572.174615  1543.586905

[2644 rows x 2 columns]

#### Map description

In [14]:
# get the data dict
df_data_dict = pd.read_csv('data_dictionary.csv')
dict_map = dict(zip(df_data_dict['feature_name'], df_data_dict['Description']))
df_tmp_t['tmp'] = df_tmp_t.index
df_tmp_t['description'] = df_tmp_t['tmp'].map(dict_map)
df_tmp_t.drop('tmp', axis=1, inplace=True)
# show
df_tmp_t

has_inst_tag,No,Yes,description
g201a__tu,1111.498473,1835.005791,Total open to buy of open trades verified in p...
g202a__tu,1136.729417,1861.210154,Total open to buy of open trades verified in p...
agg401__tu,520.589708,704.027129,Aggregate non-mortgage actual payment for month 1
trd__tu,12.679400,15.777829,Number of trades
at30s__tu,78.844259,60.154504,Percentage of open trades > 50% of credit line...
...,...,...,...
rev326__tu,1046.542635,1018.481951,Average Total Open-to-Buy for Revolving accoun...
re102s__tu,1201.454551,1013.560430,Average credit line of open revolving trades v...
rev316__tu,1426.515380,1457.112833,Max Total Open-to-Buy for Revolving accounts o...
paymnt07__tu,2.444777,2.678118,Ratio of actual to minimum payment for non-mor...
rev317__tu,1572.174615,1543.586905,Max Total Open-to-Buy for Revolving accounts o...

#### Save

In [15]:
str_filename = 'df_feat_imp.csv'
str_local_path = f'{str_dirname_output}/{str_filename}'
df_tmp_t.to_csv(str_local_path, index=True)