In [1]:
import os
import pandas as pd
import numpy as np
import boto3
import time
import datetime as dt

In [2]:
print(f'Latest run date: {dt.datetime.today()}')

Latest run date: 2024-03-07 21:30:57.343284

### Constants

In [3]:
str_project = '20231010-gen-xii'
str_dirname_output = './output'
#str_variant = 'model3'

### Output directory

In [4]:
try:
    os.mkdir(str_dirname_output)
except:
    pass

### Import data

In [5]:
str_filename = 'df.gzip'
str_uri = f's3://{str_project}/08_retro_scoring/06_create_df/{str_filename}'
df = pd.read_parquet(str_uri)
# replace
df.replace(['NaN','nan'], np.nan, inplace=True)

# show
df

,uniqueid__app_x,bigstatusid__app,strcity__app,strname__app,strzipcode__app,bitapproved__app,bitsystemdecline__app,approvaldate__app,bitfunded__app,fundeddate__app,...,fltdowncash__app,fltapproveddowntotal__app,payment__app,dti__app,pti__app,bitservicecontract__app,fltadvance__app,strvehicletype__app,bitgap__app,dealerstampcreation__app
0,0__0__20210120,14.0,Stanley,Virginia,22851,False,0.0,NaN,False,NaN,...,0.0,0.00,412.34,0.307483,0.103700,0,1.149789,suv,1,2011-06-30 10:15:42.320
1,0__0__20210120,14.0,Austin,Texas,78727,False,0.0,NaN,False,NaN,...,250.0,105.06,638.00,0.233488,0.132294,0,1.100576,suv,0,2012-10-19 15:20:30.163
2,0__0__20210122,14.0,STOCKTON,California,95207,False,0.0,NaN,False,NaN,...,1000.0,1000.00,629.99,0.340494,0.140493,0,1.051327,suv,1,2020-07-06 17:09:57.383
3,0__0__20210123,14.0,Mount Orab,Ohio,45154,False,0.0,NaN,False,NaN,...,0.0,0.00,398.95,0.481666,0.070066,0,1.143705,auto,0,2016-11-16 16:28:03.170
4,0__0__20210123,14.0,Mount Orab,Ohio,45154,False,0.0,NaN,False,NaN,...,0.0,0.00,398.95,0.481666,0.070066,0,1.143705,auto,0,2016-11-16 16:28:03.170
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71184,0__0__20231109,5.0,FOREST HILL,Texas,76119,False,0.0,NaN,False,NaN,...,0.0,0.00,511.77,0.449811,0.122139,0,1.349948,suv,0,2008-02-20 11:14:02.013
71185,0__0__20231120,5.0,CHICAGO,Illinois,60629,False,0.0,NaN,False,NaN,...,1000.0,500.00,450.63,0.350022,0.150022,0,1.149932,suv,0,2013-05-08 08:47:59.997
71186,0__0__20231107,1.0,PIKESVILLE,Maryland,21208,False,0.0,NaN,False,NaN,...,500.0,1000.00,727.74,0.385896,0.058485,1,0.838573,suv,0,2023-05-03 15:53:03.583
71187,0__0__20231117,5.0,Saginaw,Michigan,48601,False,0.0,NaN,False,NaN,...,0.0,0.00,587.21,0.453596,0.128596,0,1.121384,suv,1,2017-07-26 16:22:04.930
71188,0__0__20231024,1.0,Detroit,Michigan,48223,False,0.0,NaN,False,NaN,...,1000.0,0.00,351.67,0.525074,0.100417,0,1.119593,auto,1,2019-08-02 11:24:11.380

### Date range

In [6]:
dtm_min = df['dtmFunded'].min()
dtm_max = df['dtmFunded'].max()
print(f'Min date: {dtm_min}')
print(f'Max date: {dtm_max}')

Min date: 2021-01-25 00:00:00
Max date: 2024-03-04 00:00:00

### Get the features in the models

In [7]:
# list_cols = []
# for str_model in ['01_ad','02_pricing_pd','03_pricing_lgd']:
#     str_filename = 'df_cols_in_model.csv'
#     str_uri = f's3://{str_project}/{str_model}/02_model/{str_variant}/02_model/01_lambda_get_starting_feats/{str_filename}'
#     list_cols_model = list(pd.read_csv(str_uri)['feature'])
#     list_cols += list_cols_model

# # rm dups
# list_cols = list(dict.fromkeys(list_cols))
# print(f'There are {len(list_cols)} features in all models')

### Application

In [8]:
# app
list_cols_raw_app_suffix = [col for col in df.columns if '__app' in col]
print(f'There are {len(list_cols_raw_app_suffix)} app features')
for a, col in enumerate(list_cols_raw_app_suffix):
    print(f'{a+1} - {col}')

There are 93 app features
1 - uniqueid__app_x
2 - bigstatusid__app
3 - strcity__app
4 - strname__app
5 - strzipcode__app
6 - bitapproved__app
7 - bitsystemdecline__app
8 - approvaldate__app
9 - bitfunded__app
10 - fundeddate__app
11 - dtmapproved__app
12 - dtmdeclined__app
13 - defaultdate__app
14 - chargeoffdate__app
15 - defaultamount__app
16 - chargeoffamount__app
17 - applicationmonth__app
18 - applicationquarter__app
19 - applicationdayofweek__app
20 - bigdealerid__app
21 - bitrolled__app
22 - bigdealertypeid__app
23 - dealerstate__app
24 - bitlhmgroup__app
25 - dealercity__app
26 - dealerzip__app
27 - bitdealerapplicantsamestate__app
28 - bitdealerapplicantsamecity__app
29 - bitdealerapplicantsamezip__app
30 - strdealershiptrackertype__app
31 - inttype__app
32 - fltacquisitionfee__app
33 - fltaddfee__app
34 - fltallowance__app
35 - fltamountfinanced__app
36 - fltapprovedapr_contract__app
37 - fltapproveddebttoincome__app
38 - fltapprovedloantovalue__app
39 - fltapprovedpayment__app
40 - fltapprovedpricewholesale__app
41 - fltapprovedservicecontract__app
42 - fltdocumentfee__app
43 - fltgapinsurance__app
44 - fltinsureddisabilityamount__app
45 - fltinsureddisabilitypremium__app
46 - fltinsuredlifeamount__app
47 - fltinsuredlifepremium__app
48 - fltinsuredunemploymentamount__app
49 - fltinsuredunemploymentpremium__app
50 - fltlicensefee__app
51 - fltservicecontract__app
52 - flttaxgrossreceipts__app
53 - inttermbump__app
54 - bitdealertrack__app
55 - bitrouteone__app
56 - intservicecontractterm__app
57 - intservicecontractmileage__app
58 - intservicecontractmileageaddon__app
59 - bitmaintenanceagreement__app
60 - fltmaintenanceagreement__app
61 - bittrade__app
62 - bigmileage_odometer__app
63 - vehiclemodel__app
64 - fltpriceselling__app
65 - vehiclepricewholesale__app
66 - fltstatesalestax__app
67 - uniqueid__app_y
68 - bigaccountid__app
69 - bigdebtorid__app
70 - bitdebtor__app
71 - applicationdate__app
72 - dtmfunded__app
73 - bitdefault__app
74 - monthonbooks__app
75 - runningnetloss__app
76 - amtfinanced__app
77 - intopenbktype__app
78 - intterm__app
79 - vehicleyear__app
80 - bitnew__app
81 - vehiclemake__app
82 - miles_odometer__app
83 - bookvalue__app
84 - fltdowncash__app
85 - fltapproveddowntotal__app
86 - payment__app
87 - dti__app
88 - pti__app
89 - bitservicecontract__app
90 - fltadvance__app
91 - strvehicletype__app
92 - bitgap__app
93 - dealerstampcreation__app

In [9]:
# # app
# list_cols_raw_app_suffix = [col for col in list_cols if '__app' in col]
# # rm ENG
# list_cols_raw_app_suffix = [col for col in list_cols_raw_app_suffix if 'ENG-' not in col]
# # forced feats
# list_cols_force = [
#     'applicationdate__app', 
#     'payment__app', 
#     'amtfinanced__app',
#     'bookvalue__app',
#     'vehicleyear__app', # for vehicle age
#     'dealerstampcreation__app', # for dealership age
#     'intterm__app',
#     'fltapproveddowntotal__app', # for counter offers
# ]
# list_cols_raw_app_suffix = list_cols_raw_app_suffix + list_cols_force
# # rm dups
# list_cols_raw_app_suffix = list(dict.fromkeys(list_cols_raw_app_suffix))

# print(f'There are {len(list_cols_raw_app_suffix)} application features')
# for a, col in enumerate(list_cols_raw_app_suffix):
#     print(f'{a+1} - {col}')

In [10]:
# see nan
ser_isnull = df[list_cols_raw_app_suffix].isnull().mean()
df_isnull_app = pd.DataFrame({
    'feature': list(ser_isnull.index),
    'propna': list(ser_isnull.values),
})
df_isnull_app.sort_values(by='propna', ascending=False, inplace=True)

# save
str_filename = 'df_isnull_app.csv'
str_local_path = f'{str_dirname_output}/{str_filename}'
df_isnull_app.to_csv(str_local_path, index=False)

# show
df_isnull_app

                         feature  propna
12              defaultdate__app     1.0
14            defaultamount__app     1.0
65         fltstatesalestax__app     1.0
64    vehiclepricewholesale__app     1.0
63          fltpriceselling__app     1.0
..                           ...     ...
53           bitdealertrack__app     0.0
54              bitrouteone__app     0.0
58  bitmaintenanceagreement__app     0.0
66               uniqueid__app_y     0.0
92      dealerstampcreation__app     0.0

[93 rows x 2 columns]

### Income

In [11]:
list_cols_income = [col for col in df.columns if '__income' in col]
print(f'There are {len(list_cols_income)} income columns')

There are 2 income columns

In [12]:
# see nan
ser_isnull = df[list_cols_income].isnull().mean()
df_isnull_income = pd.DataFrame({
    'feature': list(ser_isnull.index),
    'propna': list(ser_isnull.values),
})
df_isnull_income.sort_values(by='propna', ascending=False, inplace=True)

# save
str_filename = 'df_isnull_income.csv'
str_local_path = f'{str_dirname_output}/{str_filename}'
df_isnull_income.to_csv(str_local_path, index=False)

# show
df_isnull_income

                         feature    propna
0    fltgrossmonthly__income_sum  0.001096
1  fltgrossmonthly__income_count  0.001096

### LN

In [13]:
# ln
list_cols_raw_ln_suffix = [col for col in df.columns if '__ln' in col]
print(f'There are {len(list_cols_raw_ln_suffix)} LN features')
for a, col in enumerate(list_cols_raw_ln_suffix):
    print(f'{a+1} - {col}')

There are 242 LN features
1 - uniqueid__ln
2 - biglnriskviewattributesv5id__ln
3 - bigaccountid__ln
4 - bigdebtorid__ln
5 - biglnriskviewscoreid__ln
6 - bitinvalid__ln
7 - dtmstampcreation__ln
8 - attribute_index__ln
9 - inputprovidedfirstname__ln
10 - inputprovidedlastname__ln
11 - inputprovidedstreetaddress__ln
12 - inputprovidedcity__ln
13 - inputprovidedstate__ln
14 - inputprovidedzipcode__ln
15 - inputprovidedssn__ln
16 - inputprovideddateofbirth__ln
17 - inputprovidedphone__ln
18 - inputprovidedlexid__ln
19 - subjectrecordtimeoldest__ln
20 - subjectrecordtimenewest__ln
21 - subjectnewestrecord12month__ln
22 - subjectactivityindex03month__ln
23 - subjectactivityindex06month__ln
24 - subjectactivityindex12month__ln
25 - subjectage__ln
26 - subjectdeceased__ln
27 - subjectssncount__ln
28 - subjectstabilityindex__ln
29 - subjectstabilityprimaryfactor__ln
30 - subjectabilityindex__ln
31 - subjectabilityprimaryfactor__ln
32 - subjectwillingnessindex__ln
33 - subjectwillingnessprimaryfactor__ln
34 - confirmationsubjectfound__ln
35 - confirmationinputname__ln
36 - confirmationinputdob__ln
37 - confirmationinputssn__ln
38 - confirmationinputaddress__ln
39 - sourcenonderogprofileindex__ln
40 - sourcenonderogcount__ln
41 - sourcenonderogcount03month__ln
42 - sourcenonderogcount06month__ln
43 - sourcenonderogcount12month__ln
44 - sourcecredheadertimeoldest__ln
45 - sourcecredheadertimenewest__ln
46 - sourcevoterregistration__ln
47 - educationattendance__ln
48 - educationevidence__ln
49 - educationprogramattended__ln
50 - educationinstitutionprivate__ln
51 - educationinstitutionrating__ln
52 - profliccount__ln
53 - proflictypecategory__ln
54 - businessassociation__ln
55 - businessassociationindex__ln
56 - businessassociationtimeoldest__ln
57 - businesstitleleadership__ln
58 - assetindex__ln
59 - assetindexprimaryfactor__ln
60 - assetownership__ln
61 - assetprop__ln
62 - assetpropindex__ln
63 - assetpropevercount__ln
64 - assetpropcurrentcount__ln
65 - assetpropcurrenttaxtotal__ln
66 - assetproppurchasecount12month__ln
67 - assetproppurchasetimeoldest__ln
68 - assetproppurchasetimenewest__ln
69 - assetpropnewestmortgagetype__ln
70 - assetpropeversoldcount__ln
71 - assetpropsoldcount12month__ln
72 - assetpropsaletimeoldest__ln
73 - assetpropsaletimenewest__ln
74 - assetpropnewestsaleprice__ln
75 - assetpropsalepurchaseratio__ln
76 - assetpersonal__ln
77 - assetpersonalcount__ln
78 - purchaseactivityindex__ln
79 - purchaseactivitycount__ln
80 - purchaseactivitydollartotal__ln
81 - derogseverityindex__ln
82 - derogcount__ln
83 - derogcount12month__ln
84 - derogtimenewest__ln
85 - criminalfelonycount__ln
86 - criminalfelonycount12month__ln
87 - criminalfelonytimenewest__ln
88 - criminalnonfelonycount__ln
89 - criminalnonfelonycount12month__ln
90 - criminalnonfelonytimenewest__ln
91 - evictioncount__ln
92 - evictioncount12month__ln
93 - evictiontimenewest__ln
94 - lienjudgmentseverityindex__ln
95 - lienjudgmentcount__ln
96 - lienjudgmentcount12month__ln
97 - lienjudgmentsmallclaimscount__ln
98 - lienjudgmentcourtcount__ln
99 - lienjudgmenttaxcount__ln
100 - lienjudgmentforeclosurecount__ln
101 - lienjudgmentothercount__ln
102 - lienjudgmenttimenewest__ln
103 - lienjudgmentdollartotal__ln
104 - bankruptcycount__ln
105 - bankruptcycount24month__ln
106 - bankruptcytimenewest__ln
107 - bankruptcychapter__ln
108 - bankruptcystatus__ln
109 - bankruptcydismissed24month__ln
110 - shorttermloanrequest__ln
111 - shorttermloanrequest12month__ln
112 - shorttermloanrequest24month__ln
113 - inquiryauto12month__ln
114 - inquirybanking12month__ln
115 - inquirytelcom12month__ln
116 - inquirynonshortterm12month__ln
117 - inquiryshortterm12month__ln
118 - inquirycollections12month__ln
119 - ssnsubjectcount__ln
120 - ssndeceased__ln
121 - ssndatelowissued__ln
122 - ssnproblems__ln
123 - addronfilecount__ln
124 - addronfilecorrectional__ln
125 - addronfilecollege__ln
126 - addronfilehighrisk__ln
127 - addrinputtimeoldest__ln
128 - addrinputtimenewest__ln
129 - addrinputlengthofres__ln
130 - addrinputsubjectcount__ln
131 - addrinputmatchindex__ln
132 - addrinputsubjectowned__ln
133 - addrinputdeedmailing__ln
134 - addrinputownershipindex__ln
135 - addrinputphoneservice__ln
136 - addrinputphonecount__ln
137 - addrinputdwelltype__ln
138 - addrinputdwelltypeindex__ln
139 - addrinputdelivery__ln
140 - addrinputtimelastsale__ln
141 - addrinputlastsaleprice__ln
142 - addrinputtaxvalue__ln
143 - addrinputtaxyr__ln
144 - addrinputtaxmarketvalue__ln
145 - addrinputavmvalue__ln
146 - addrinputavmvalue12month__ln
147 - addrinputavmratio12monthprior__ln
148 - addrinputavmvalue60month__ln
149 - addrinputavmratio60monthprior__ln
150 - addrinputcountyratio__ln
151 - addrinputtractratio__ln
152 - addrinputblockratio__ln
153 - addrinputproblems__ln
154 - addrcurrenttimeoldest__ln
155 - addrcurrenttimenewest__ln
156 - addrcurrentlengthofres__ln
157 - addrcurrentsubjectowned__ln
158 - addrcurrentdeedmailing__ln
159 - addrcurrentownershipindex__ln
160 - addrcurrentphoneservice__ln
161 - addrcurrentdwelltype__ln
162 - addrcurrentdwelltypeindex__ln
163 - addrcurrenttimelastsale__ln
164 - addrcurrentlastsalesprice__ln
165 - addrcurrenttaxvalue__ln
166 - addrcurrenttaxyr__ln
167 - addrcurrenttaxmarketvalue__ln
168 - addrcurrentavmvalue__ln
169 - addrcurrentavmvalue12month__ln
170 - addrcurrentavmratio12monthprior__ln
171 - addrcurrentavmvalue60month__ln
172 - addrcurrentavmratio60monthprior__ln
173 - addrcurrentcountyratio__ln
174 - addrcurrenttractratio__ln
175 - addrcurrentblockratio__ln
176 - addrcurrentcorrectional__ln
177 - addrprevioustimeoldest__ln
178 - addrprevioustimenewest__ln
179 - addrpreviouslengthofres__ln
180 - addrprevioussubjectowned__ln
181 - addrpreviousownershipindex__ln
182 - addrpreviousdwelltype__ln
183 - addrpreviousdwelltypeindex__ln
184 - addrpreviouscorrectional__ln
185 - addrstabilityindex__ln
186 - addrchangecount03month__ln
187 - addrchangecount06month__ln
188 - addrchangecount12month__ln
189 - addrchangecount24month__ln
190 - addrchangecount60month__ln
191 - addrlastmovetaxratiodiff__ln
192 - addrlastmoveecontrajectory__ln
193 - addrlastmoveecontrajectoryindex__ln
194 - phoneinputproblems__ln
195 - phoneinputsubjectcount__ln
196 - phoneinputmobile__ln
197 - alertregulatorycondition__ln
198 - analyticsmatchkey__ln
199 - auto_score__ln
200 - auto_reason1__ln
201 - auto_reason2__ln
202 - auto_reason3__ln
203 - auto_reason4__ln
204 - auto_reason5__ln
205 - bankcard_score__ln
206 - bankcard_reason1__ln
207 - bankcard_reason2__ln
208 - bankcard_reason3__ln
209 - bankcard_reason4__ln
210 - bankcard_reason5__ln
211 - short_term_lending_score__ln
212 - short_term_lending_reason1__ln
213 - short_term_lending_reason2__ln
214 - short_term_lending_reason3__ln
215 - short_term_lending_reason4__ln
216 - short_term_lending_reason5__ln
217 - telecommunications_score__ln
218 - telecommunications_reason1__ln
219 - telecommunications_reason2__ln
220 - telecommunications_reason3__ln
221 - telecommunications_reason4__ln
222 - telecommunications_reason5__ln
223 - crossindustry_index__ln
224 - crossindustry_score_name__ln
225 - crossindustry_score__ln
226 - crossindustry_reason1__ln
227 - crossindustry_reason2__ln
228 - crossindustry_reason3__ln
229 - crossindustry_reason4__ln
230 - crossindustry_reason5__ln
231 - alert1__ln
232 - alert2__ln
233 - alert3__ln
234 - alert4__ln
235 - alert5__ln
236 - alert6__ln
237 - alert7__ln
238 - alert8__ln
239 - alert9__ln
240 - alert10__ln
241 - intscore__ln
242 - ln_was_empty__ln

In [14]:
# # ln
# list_cols_raw_ln_suffix = [col for col in list_cols if '__ln' in col]
# print(f'There are {len(list_cols_raw_ln_suffix)} LN features')
# for a, col in enumerate(list_cols_raw_ln_suffix):
#     print(f'{a+1} - {col}')

In [15]:
# see nan
ser_isnull = df[list_cols_raw_ln_suffix].isnull().mean()
df_isnull_ln = pd.DataFrame({
    'feature': list(ser_isnull.index),
    'propna': list(ser_isnull.values),
})
df_isnull_ln.sort_values(by='propna', ascending=False, inplace=True)

# save
str_filename = 'df_isnull_ln.csv'
str_local_path = f'{str_dirname_output}/{str_filename}'
df_isnull_ln.to_csv(str_local_path, index=False)

# show
df_isnull_ln

                             feature   propna
241                 ln_was_empty__ln  1.00000
208             bankcard_reason4__ln  1.00000
217   telecommunications_reason1__ln  1.00000
216     telecommunications_score__ln  1.00000
215   short_term_lending_reason5__ln  1.00000
..                               ...      ...
5                     bitinvalid__ln  0.00007
4           biglnriskviewscoreid__ln  0.00007
3                    bigdebtorid__ln  0.00007
2                   bigaccountid__ln  0.00007
1    biglnriskviewattributesv5id__ln  0.00007

[242 rows x 2 columns]

### TU

In [16]:
# tu
list_cols_raw_tu_suffix = [col for col in df.columns if '__tu' in col]
print(f'There are {len(list_cols_raw_tu_suffix)} TU features')

There are 2146 TU features

In [17]:
# # tu
# list_cols_raw_tu_suffix = [col for col in list_cols if '__tu' in col]
# print(f'There are {len(list_cols_raw_tu_suffix)} TU features')

In [18]:
# see nan
ser_isnull = df[list_cols_raw_tu_suffix].isnull().mean()
df_isnull_tu = pd.DataFrame({
    'feature': list(ser_isnull.index),
    'propna': list(ser_isnull.values),
})
df_isnull_tu.sort_values(by='propna', ascending=False, inplace=True)

# save
str_filename = 'df_isnull_tu.csv'
str_local_path = f'{str_dirname_output}/{str_filename}'
df_isnull_tu.to_csv(str_local_path, index=False)

# show
df_isnull_tu

               feature    propna
2145  tu_was_empty__tu  1.000000
1938        au921b__tu  1.000000
1650          p03h__tu  1.000000
1651      linkahit__tu  1.000000
1652      linkbhit__tu  1.000000
...                ...       ...
703         rvlr73__tu  0.000379
702         rvlr72__tu  0.000379
701         rvlr71__tu  0.000379
700         rvlr70__tu  0.000379
1073        ret112__tu  0.000379

[2146 rows x 2 columns]