In [2]:
import os
import pandas as pd
import numpy as np
import pickle
import boto3
import json
import math
import datetime as dt
from tqdm import tqdm
from io import StringIO
import warnings
warnings.filterwarnings('ignore')

#### Constants

In [9]:
# project
str_project = os.getcwd().split('/')[4].replace('_','-')
print(f'Project: {str_project}')
# task
str_task = os.getcwd().split('/')[5]
print(f'Task: {str_task}')
# sub task
str_subtask = os.getcwd().split('/')[6]
print(f'Task: {str_subtask}')
# output
str_dirname_output = './output'
int_n_requests_per_lambda = 30

Project: 20240423-gen-xii-payload-parsing
Task: 02_lambda_function
Task: 01_create_parser

#### Make output

In [3]:
try:
    os.mkdir(str_dirname_output)
except:
    pass

#### Write functions.py

In [4]:
%%writefile functions.py

import pandas as pd
from io import StringIO
import numpy as np
import datetime as dt
import xml.etree.ElementTree as ET

# helper for get data
def get_data_helper(dict_json_request):
    # get rows
    list_dict_data = dict_json_request['rows']
    # get id and tables
    list_unique_id = []
    dict_list_tables = {}
    for dict_data in list_dict_data:
        # get unique_id
        unique_id = dict_data['row_id']
        list_unique_id.append(unique_id)
        # assign tables
        dict_list_tables[unique_id] = dict_data['sources']
    # return
    return list_unique_id, dict_list_tables

# get application table
def get_application_table(str_values, unique_id, dict_list_errors):
    # convert str_values to a df
    X = pd.read_csv(
        StringIO(str_values), 
        delimiter=',', 
    )
    # if X is empty
    if X.empty:
        # append error
        dict_list_errors[unique_id].append('Missing Application Table')
        # create a single row df filled with NaN
        list_cols = [
            'app_was_empty',
        ]
        X = pd.DataFrame({col: np.nan for col in list_cols}, index=[0])
        # set date to today
        X['applicationdate'] = dt.datetime.today()
    else:
        # lower
        X.columns = [col.lower() for col in X.columns]
    # add suffix to end of column names
    X.columns = [f'{col}__app' for col in X.columns]
    # set index to unique id
    X.index = [unique_id]
    # return
    return X, dict_list_errors

# get income table
def get_income_table(str_values, unique_id, dict_list_errors):
    # list of columns for income
    list_cols = [
        'bitinvalid',
        'bituse',
        'fltgrossmonthly',
    ]
    # list of cols after aggregation
    list_cols_agg = [
        'fltgrossmonthly__income_sum',
        'fltgrossmonthly__income_count',
    ]
    # convert str_values to a df
    X = pd.read_csv(
        StringIO(str_values), 
        delimiter=',', 
    )
    # if X is empty
    if X.empty:
        # append error
        dict_list_errors[unique_id].append('Missing Income Table')
        X = pd.DataFrame({col: np.nan for col in list_cols_agg}, index=[0])
    else:
        # lower
        X.columns = [col.lower() for col in X.columns]
        # rm T/F
        X_tmp = X * 1
        # filter rows
        X_tmp = X_tmp[X_tmp['bitinvalid']==0] # False
        X_tmp = X_tmp[X_tmp['bituse']==1] # True
        # aggregate
        X = pd.DataFrame()
        X['fltgrossmonthly__income_sum'] = [np.sum(X_tmp['fltgrossmonthly'])]
        X['fltgrossmonthly__income_count'] = [X_tmp.shape[0]]
    # set index to unique id
    X.index = [unique_id]
    # return
    return X, dict_list_errors

# get ln table
def get_lexis_nexis_table(str_values, unique_id, dict_list_errors):
    # read str_values to a df
    X = pd.read_csv(
        StringIO(str_values), 
        delimiter=',', 
    )
    # if empty
    if X.empty:
        # append error
        dict_list_errors[unique_id].append('Missing Lexis Nexis Table')
        # create row with NaN
        list_cols = [
            'ln_was_empty',
        ]
        X = pd.DataFrame({col: np.nan for col in list_cols}, index=[0])
    else:
        # lower
        X.columns = [col.lower() for col in X.columns]
    # add suffix to end of column names
    X.columns = [f'{col}__ln' for col in X.columns]
    # set index to unique id
    X.index = [unique_id]
    # return
    return X, dict_list_errors

# define helper to convert to proper dtype
def helper_convert_dtype(str_col_value):
    # try converting to integer
    try:
        str_col_value = int(str_col_value)
    except:
        # try converting to float
        try:
            str_col_value = float(str_col_value)
        # leave as string
        except:
            pass
    # return
    return str_col_value

# define helper to parse tuxml
def helper_parse_tuxml(str_values):
    # get root
    root = ET.fromstring(str_values)
    # empty dict
    dict_tuxml = {}
    # iterate through child branches
    for child in root.iter(tag='{http://www.transunion.com/namespace}characteristic'):
        # get col name
        str_col_name = child.find('{http://www.transunion.com/namespace}id').text.lower()
        # get col val
        try:
            str_col_value = helper_convert_dtype(str_col_value=child.find('{http://www.transunion.com/namespace}value').text)
        # if its nonetype
        except AttributeError:
            str_col_value = np.nan
        # assign
        dict_tuxml[str_col_name] = str_col_value
    # convert dtype and return df
    return pd.DataFrame(dict_tuxml, index=[0])

# get tu table
def get_transunion_table(str_values, unique_id, dict_list_errors):
    # parse xml
    X = helper_parse_tuxml(
        str_values=str_values, 
    )
    # if empty
    if X.empty:
        # append error
        dict_list_errors[unique_id].append('Missing TU Table')
        list_cols = [
            'tu_was_empty',
        ]
        # create row with NaN
        X = pd.DataFrame({col: np.nan for col in list_cols}, index=[0])
    else:
        pass
    # add suffix to end of column names
    X.columns = [f'{col}__tu' for col in X.columns]
    # set index to unique id
    X.index = [unique_id]
    # return
    return X, dict_list_errors

Overwriting functions.py

#### Write api.py

In [5]:
%%writefile api.py

from functions import *
import time

# define class
class ParsePayload:
    # init
    def __init__(self, list_cols_raw_all):
        self.str_datecol = 'applicationdate'
        self.dict_output = {}
        self.list_cols_raw_all = list_cols_raw_all
    # get data
    def get_data(self, dict_json_request):
        # start time
        time_start = time.perf_counter()

        # use helper
        list_unique_id, dict_list_tables = get_data_helper(
            dict_json_request=dict_json_request,
        )

        # save to object now for uniformity later
        self.dict_output['list_unique_id'] = list_unique_id

        # flt_sec
        flt_sec = time.perf_counter() - time_start
        # print
        print(f'{self.dict_output["list_unique_id"]}: Get Data: {flt_sec:0.5f} sec.')

        # save to object
        self.dict_json_request = dict_json_request
        # save to dict_output
        self.dict_output['flt_sec_get_data'] = flt_sec
        self.dict_output['dict_list_tables'] = dict_list_tables
        # return object
        return self
    # parse data
    def parse_data(self):
        # start time
        time_start = time.perf_counter()

        # empty dict
        dict_list_x = {}
        # another empty dict
        dict_list_errors = {}
        # iterate through unique ids
        for unique_id in self.dict_output['list_unique_id']:
            # put empty list in dict errors
            dict_list_errors[unique_id] = []
            # empty list
            dict_list_x[unique_id] = []
            # get tables
            list_dict_tables = self.dict_output['dict_list_tables'][unique_id]
            # iterate through tables
            for dict_table in list_dict_tables:
                # get str_values
                str_values = dict_table['values']
                # Application table
                if dict_table['name'] == 'Application':
                    # get application table
                    X, dict_list_errors = get_application_table(
                        str_values=str_values, 
                        unique_id=unique_id, 
                        dict_list_errors=dict_list_errors,
                    )
                    dict_list_x[unique_id].append(X)
                # Income table
                elif dict_table['name'] == 'Incomes':
                    # get income table
                    X, dict_list_errors = get_income_table(
                        str_values=str_values, 
                        unique_id=unique_id, 
                        dict_list_errors=dict_list_errors,
                    )
                    dict_list_x[unique_id].append(X)
                # LexisNexis
                elif dict_table['name'] == 'Lexis Nexis Risk View 5':
                    # get ln table
                    X, dict_list_errors = get_lexis_nexis_table(
                        str_values=str_values,
                        unique_id=unique_id, 
                        dict_list_errors=dict_list_errors,
                    )
                    dict_list_x[unique_id].append(X)
                # TU
                elif dict_table['name'] == 'TUXML':
                    # get tu table
                    X, dict_list_errors = get_transunion_table(
                        str_values=str_values,
                        unique_id=unique_id, 
                        dict_list_errors=dict_list_errors,
                    )
                    dict_list_x[unique_id].append(X)
                else:
                    pass

        # flt_sec
        flt_sec = time.perf_counter() - time_start
        # print
        print(f'{self.dict_output["list_unique_id"]}: Parse Data: {flt_sec:0.5f} sec.')

        # save to dict_output
        self.dict_output['flt_sec_parse_data'] = flt_sec
        self.dict_output['dict_list_x'] = dict_list_x
        self.dict_output['dict_list_errors'] = dict_list_errors
        # return object
        return self
    # create X
    def create_x(self):
        # start time
        time_start = time.perf_counter()

        # empty list
        list_x_cbind = []
        # concatenate cols of df in each list
        for list_x in self.dict_output['dict_list_x'].values():
            # concatenate
            x_cbind = pd.concat(list_x, axis=1)
            # append
            list_x_cbind.append(x_cbind)
        # concatenate rows
        X = pd.concat(list_x_cbind, axis=0)
        
        # ensure there is a field for every feature
        for col in self.list_cols_raw_all:
            if col not in list(X.columns):
                X[col] = np.nan

        # flt_sec
        flt_sec = time.perf_counter() - time_start
        # print()
        print(f'{self.dict_output["list_unique_id"]}: Create X: {flt_sec:0.5f} sec.')

        # save to dict_output
        self.dict_output['flt_sec_create_x'] = flt_sec
        self.dict_output['X_raw'] = X
        # return object
        return self

Overwriting api.py

#### Get features from raw data

In [6]:
%%time

str_filename = 'df_test_raw.gzip'
str_uri = f's3://20231010-gen-xii/03_pricing_lgd/01_data_prep/03_train_valid_test_split/{str_filename}'
list_cols_raw_all = list(pd.read_parquet(str_uri).columns)
# rm base
list_cols_raw_all = [col for col in list_cols_raw_all if '__base' not in col]
# income
list_cols_ignore = [
    'fltgrossmonthly__income_min',
    'fltgrossmonthly__income_max',
    'fltgrossmonthly__income_median',
    'fltgrossmonthly__income_mean',
    'fltgrossmonthly__income_std',
]
list_cols_raw_all = [col for col in list_cols_raw_all if col not in list_cols_ignore]
print(f'There are {len(list_cols_raw_all)} total raw features')

There are 2466 total raw features
CPU times: user 604 ms, sys: 733 ms, total: 1.34 s
Wall time: 3.24 s

#### Initialize class

In [7]:
from api import ParsePayload

cls_parser = ParsePayload(
    list_cols_raw_all=list_cols_raw_all,
)

#### Save

In [8]:
str_filename = 'cls_parser.pkl'
str_local_path = f'{str_dirname_output}/{str_filename}'
pickle.dump(cls_parser, open(str_local_path, 'wb'))

#### Test to see if parser would behave the way we expect it to

In [9]:
df = pd.read_csv('./output/df_requests_subset.csv')
df

,bigAccountId,dtmFunded,strRequest
0,5714239,2021-07-26,"{""request_id"":""588761"",""rows"":[{""row_id"":""5714..."
1,5709609,2021-07-27,"{""request_id"":""589163"",""rows"":[{""row_id"":""5709..."
2,5718633,2021-07-27,"{""request_id"":""589402"",""rows"":[{""row_id"":""5718..."
3,5704668,2021-07-27,"{""request_id"":""590811"",""rows"":[{""row_id"":""5704..."
4,5712452,2021-07-27,"{""request_id"":""592777"",""rows"":[{""row_id"":""5712..."
...,...,...,...
95,5716645,2021-08-02,"{""request_id"":""593192"",""rows"":[{""row_id"":""5716..."
96,5706152,2021-08-02,"{""request_id"":""593948"",""rows"":[{""row_id"":""5706..."
97,5713490,2021-08-02,"{""request_id"":""596309"",""rows"":[{""row_id"":""5713..."
98,5721262,2021-08-02,"{""request_id"":""593996"",""rows"":[{""row_id"":""5721..."
99,5713619,2021-08-02,"{""request_id"":""590494"",""rows"":[{""row_id"":""5713..."

In [10]:
# keep only the most recent payload
df.drop_duplicates(
    subset=['bigAccountId'],
    keep='last',
    inplace=True,
)
# show
df

,bigAccountId,dtmFunded,strRequest
0,5714239,2021-07-26,"{""request_id"":""588761"",""rows"":[{""row_id"":""5714..."
1,5709609,2021-07-27,"{""request_id"":""589163"",""rows"":[{""row_id"":""5709..."
2,5718633,2021-07-27,"{""request_id"":""589402"",""rows"":[{""row_id"":""5718..."
3,5704668,2021-07-27,"{""request_id"":""590811"",""rows"":[{""row_id"":""5704..."
4,5712452,2021-07-27,"{""request_id"":""592777"",""rows"":[{""row_id"":""5712..."
...,...,...,...
95,5716645,2021-08-02,"{""request_id"":""593192"",""rows"":[{""row_id"":""5716..."
96,5706152,2021-08-02,"{""request_id"":""593948"",""rows"":[{""row_id"":""5706..."
97,5713490,2021-08-02,"{""request_id"":""596309"",""rows"":[{""row_id"":""5713..."
98,5721262,2021-08-02,"{""request_id"":""593996"",""rows"":[{""row_id"":""5721..."
99,5713619,2021-08-02,"{""request_id"":""590494"",""rows"":[{""row_id"":""5713..."

In [11]:
# sort
df.sort_values(by='dtmFunded', ascending=True, inplace=True)

# show
df

,bigAccountId,dtmFunded,strRequest
0,5714239,2021-07-26,"{""request_id"":""588761"",""rows"":[{""row_id"":""5714..."
16,5711466,2021-07-27,"{""request_id"":""589516"",""rows"":[{""row_id"":""5711..."
15,5702106,2021-07-27,"{""request_id"":""589491"",""rows"":[{""row_id"":""5702..."
14,5708876,2021-07-27,"{""request_id"":""589591"",""rows"":[{""row_id"":""5708..."
13,5708693,2021-07-27,"{""request_id"":""589143"",""rows"":[{""row_id"":""5708..."
...,...,...,...
94,5720091,2021-08-02,"{""request_id"":""592645"",""rows"":[{""row_id"":""5720..."
95,5716645,2021-08-02,"{""request_id"":""593192"",""rows"":[{""row_id"":""5716..."
96,5706152,2021-08-02,"{""request_id"":""593948"",""rows"":[{""row_id"":""5706..."
97,5713490,2021-08-02,"{""request_id"":""596309"",""rows"":[{""row_id"":""5713..."
99,5713619,2021-08-02,"{""request_id"":""590494"",""rows"":[{""row_id"":""5713..."

In [12]:
# get min and max dates
dtm_min = df['dtmFunded'].min()
dtm_max = df['dtmFunded'].max()
print(f'Min date: {dtm_min}; Max date: {dtm_max}')

Min date: 2021-07-26; Max date: 2021-08-02

In [13]:
# get nrows
int_nrows = df.shape[0]

# divide by int_n_requests_per_lambda
int_n_lambdas = math.ceil(int_nrows / int_n_requests_per_lambda)
print(f'There will be {int_n_lambdas} lambdas')

There will be 4 lambdas

In [14]:
# create list to assign as new column
list_rows = list(np.tile(np.arange(1, int_n_lambdas+1), int_n_requests_per_lambda))
print(f'Length: {len(list_rows)}')
# make sure its the same length as df
list_rows = list_rows[:int_nrows]
print(f'Length: {len(list_rows)}')
# assign
df['rows'] = list_rows
# show
df

Length: 120
Length: 100

,bigAccountId,dtmFunded,strRequest,rows
0,5714239,2021-07-26,"{""request_id"":""588761"",""rows"":[{""row_id"":""5714...",1
16,5711466,2021-07-27,"{""request_id"":""589516"",""rows"":[{""row_id"":""5711...",2
15,5702106,2021-07-27,"{""request_id"":""589491"",""rows"":[{""row_id"":""5702...",3
14,5708876,2021-07-27,"{""request_id"":""589591"",""rows"":[{""row_id"":""5708...",4
13,5708693,2021-07-27,"{""request_id"":""589143"",""rows"":[{""row_id"":""5708...",1
...,...,...,...,...
94,5720091,2021-08-02,"{""request_id"":""592645"",""rows"":[{""row_id"":""5720...",4
95,5716645,2021-08-02,"{""request_id"":""593192"",""rows"":[{""row_id"":""5716...",1
96,5706152,2021-08-02,"{""request_id"":""593948"",""rows"":[{""row_id"":""5706...",2
97,5713490,2021-08-02,"{""request_id"":""596309"",""rows"":[{""row_id"":""5713...",3
99,5713619,2021-08-02,"{""request_id"":""590494"",""rows"":[{""row_id"":""5713...",4

In [15]:
df_ = df.iloc[0].strRequest
df_

'{"request_id":"588761","rows":[{"row_id":"5714239__7176826__20210720","sources":[{"name":"Application","version":1.0,"format":"csv","values":"UniqueID,bigAccountId,bigDebtorId,bitDebtor,strCity,strName,strZipCode,ApplicationDate,bitApproved,bitSystemDecline,ApprovalDate,bitFunded,FundedDate,dtmStampCreation,dtmApproved,dtmDeclined,dtmFunded,defaultDate,ChargeOffDate,defaultAmount,chargeoffamount,ApplicationMonth,ApplicationQuarter,ApplicationDayofWeek,bigDealerID,bitRolled,bigDealerTypeId,DealerState,bitLHMGroup,DealerCity,DealerZip,bitDealerApplicantSameState,bitDealerApplicantSameCity,bitDealerApplicantSameZip,strDealershipTrackerType,intType,fltAcquisitionFee,fltAddFee,fltAllowance,fltAmountFinanced,fltApprovedAPR_contract,fltApprovedDebtToIncome,fltApprovedDownTotal,fltApprovedLoanToValue,fltApprovedPayment,fltApprovedPriceWholesale,fltApprovedServiceContract,fltDocumentFee,fltDownCash,fltGapInsurance,fltInsuredDisabilityAmount,fltInsuredDisabilityPremium,fltInsuredLifeAmount,fltInsuredLifePremium,fltInsuredUnemploymentAmount,fltInsuredUnemploymentPremium,fltLicenseFee,fltServiceContract,fltTaxGrossReceipts,intTerm,intTermBump,bitDealerTrack,bitRouteOne,bitServiceContract,intServiceContractTerm,intServiceContractMileage,intServiceContractMileageAddOn,bitMaintenanceAgreement,fltMaintenanceAgreement,bitTrade\\r\\n5714239__7176826__20210720,5714239,7176826,1,W VALLEY CITY,Utah,84119,,True,,,False,,,,,,,,,,7,3,Tuesday,5761,False,1,Utah,False,WEST VALLEY,84120,1,0,0,Franchise,,499,0,0,24771.37,19.99,36.32,1000,142.37,598.14,17294,0,399,1000,895,0,0,0,0,0,0,229.25,3999,1666.12,72,6,True,False,True,60,129442,0,True,0,\\r\\n"},{"name":"Incomes","version":1.0,"format":"csv","values":"UniqueID,bigAccountId,bigDebtorId,bigIncomeId,bigIncomeTypeId,bitCurrent,bitEmployment,bitFullTime,bitInvalid,bitPulledFromBureau,bitSelfEmployed,bitUse,bitVerified,dtmEnd,dtmStampCreation,dtmStart,dtmVerified,fltGrossMonthly,intMonths,intWeeklyHour,intYears,strComment,strCommentVerification,strEmployerAddress,strEmployerBusiness,strEmployerContact,strEmployerName,strOccupation,strPhone,strPhoneDepartment,strPhoneFax,strPhonePersonnel,strPosition,strSource,strSpokeTo,strType,strWageType,dtmDateOnPayStub,flt401kLoanPayment,fltChildSupport,fltGarnish,bigEmployeeId_verified,bitBrokerage,bigDealerContactId_createdBy,bitW2,bit1099,strFrequency,bitRequirePOI,strPhoneExt,strDepartmentExt,strPersonnelExt,strDepartment,strWeekly,strEveryOther,strMonthly,strPayDays,dtmIncomeVerified,bigEmployeeId_verifiedAmount,fltYTDPaystub,fltGrossPaystub,fltBasePaystub,fltRatePaystub,bitIncomeVerified,bitIncomeVerifiedCollections\\r\\n5714239__7176826__20210720,5714239,7176826,10295018,2,True,True,True,False,False,False,True,True,,2021-07-20T17:06:37,2004-03-24T00:00:00,2021-07-26T13:52:27,5809.68,4,40,17,\\"TWN -CURRENT 7/23/2021 - Active\\n\\nCust/Co name listed: yes /Deducts:401kl#1 $141.52, loan#2 $188.28, #3 $102.26 /Annual/semi-annual pay removed: no /Income being used: ytd $5809.68 Job time:  17 yr  /Misc\\",,,,,PACIFIC SUPPLY,DRIVER CLASS A,8014846136,,,,TWN -CURRENT 7/23/2021 - Active,,TWN -CURRENT 7/23/2021 - Active,,Hourly,2021-07-04T00:00:00,,,,1931,False,,False,False,BiWeekly,True,,,,,,,,,2021-07-21T10:50:52,419,35613.34,2270.06,,25.02,True,\\r\\n"},{"name":"Debts","version":1.0,"format":"csv","values":"UniqueID,bigAccountId,bigDebtorId,bigDebtId,bigDebtTypeId,bigEmployeeId_createdBy,bitCurrent,bitInvalid,bitPulledFromBureau,bitUse,bitVerified,dtmStampCreation,dtmStart,dtmVerified,fltBalanceCurrent,fltBalanceOriginal,fltMonthlyPayment,strComment,strCreditor,strPaymentMethod,strType,bigIncomeId_withheldFrom,bitBrokerage,bigDebtorContactId_createdBy,bigDealerContactId_createdBy,bigCreditMergeResultId\\r\\n5714239__7176826__20210720,5714239,7176826,32142053,21,,True,False,False,True,False,2021-07-20T17:06:37,,,0,0,900,,,,RENT FACTOR,,False,,,\\r\\n5714239__7176826__20210720,5714239,7176826,32142054,9,1,True,False,True,True,False,2021-07-20T17:06:46,2021-05-29T00:00:00,,839,1000,180,,MTN AMER CU,,installment,,False,,,-1\\r\\n5714239__7176826__20210720,5714239,7176826,32143661,12,419,True,False,False,True,False,2021-07-21T10:51:33,,,,,141.52,Chalese Turnbow | poi,401k loan#1,,401k Loan Payment,,,,,\\r\\n5714239__7176826__20210720,5714239,7176826,32143669,12,419,True,False,False,True,False,2021-07-21T10:51:49,,,,,188.28,Chalese Turnbow | poi,\\"401kloan#2 \\",,401k Loan Payment,,,,,\\r\\n5714239__7176826__20210720,5714239,7176826,32143672,12,419,True,False,False,True,False,2021-07-21T10:52:12,,,,,102.26,Chalese Turnbow | poi,\\"401k loan #3 \\",,401k Loan Payment,,,,,\\r\\n"},{"name":"Lexis Nexis Risk View 5","version":1.0,"format":"csv","values":"UniqueID,bigLNRiskViewAttributesV5id,bigAccountId,bigDebtorId,bigLNRiskViewScoreId,bitInvalid,dtmStampCreation,attribute_index,inputprovidedfirstname,inputprovidedlastname,inputprovidedstreetaddress,inputprovidedcity,inputprovidedstate,inputprovidedzipcode,inputprovidedssn,inputprovideddateofbirth,inputprovidedphone,inputprovidedlexid,subjectrecordtimeoldest,subjectrecordtimenewest,subjectnewestrecord12month,subjectactivityindex03month,subjectactivityindex06month,subjectactivityindex12month,subjectage,subjectdeceased,subjectssncount,subjectstabilityindex,subjectstabilityprimaryfactor,subjectabilityindex,subjectabilityprimaryfactor,subjectwillingnessindex,subjectwillingnessprimaryfactor,confirmationsubjectfound,confirmationinputname,confirmationinputdob,confirmationinputssn,confirmationinputaddress,sourcenonderogprofileindex,sourcenonderogcount,sourcenonderogcount03month,sourcenonderogcount06month,sourcenonderogcount12month,sourcecredheadertimeoldest,sourcecredheadertimenewest,sourcevoterregistration,educationattendance,educationevidence,educationprogramattended,educationinstitutionprivate,educationinstitutionrating,profliccount,proflictypecategory,businessassociation,businessassociationindex,businessassociationtimeoldest,businesstitleleadership,assetindex,assetindexprimaryfactor,assetownership,assetprop,assetpropindex,assetpropevercount,assetpropcurrentcount,assetpropcurrenttaxtotal,assetproppurchasecount12month,assetproppurchasetimeoldest,assetproppurchasetimenewest,assetpropnewestmortgagetype,assetpropeversoldcount,assetpropsoldcount12month,assetpropsaletimeoldest,assetpropsaletimenewest,assetpropnewestsaleprice,assetpropsalepurchaseratio,assetpersonal,assetpersonalcount,purchaseactivityindex,purchaseactivitycount,purchaseactivitydollartotal,derogseverityindex,derogcount,derogcount12month,derogtimenewest,criminalfelonycount,criminalfelonycount12month,criminalfelonytimenewest,criminalnonfelonycount,criminalnonfelonycount12month,criminalnonfelonytimenewest,evictioncount,evictioncount12month,evictiontimenewest,lienjudgmentseverityindex,lienjudgmentcount,lienjudgmentcount12month,lienjudgmentsmallclaimscount,lienjudgmentcourtcount,lienjudgmenttaxcount,lienjudgmentforeclosurecount,lienjudgmentothercount,lienjudgmenttimenewest,lienjudgmentdollartotal,bankruptcycount,bankruptcycount24month,bankruptcytimenewest,bankruptcychapter,bankruptcystatus,bankruptcydismissed24month,shorttermloanrequest,shorttermloanrequest12month,shorttermloanrequest24month,inquiryauto12month,inquirybanking12month,inquirytelcom12month,inquirynonshortterm12month,inquiryshortterm12month,inquirycollections12month,ssnsubjectcount,ssndeceased,ssndatelowissued,ssnproblems,addronfilecount,addronfilecorrectional,addronfilecollege,addronfilehighrisk,addrinputtimeoldest,addrinputtimenewest,addrinputlengthofres,addrinputsubjectcount,addrinputmatchindex,addrinputsubjectowned,addrinputdeedmailing,addrinputownershipindex,addrinputphoneservice,addrinputphonecount,addrinputdwelltype,addrinputdwelltypeindex,addrinputdelivery,addrinputtimelastsale,addrinputlastsaleprice,addrinputtaxvalue,addrinputtaxyr,addrinputtaxmarketvalue,addrinputavmvalue,addrinputavmvalue12month,addrinputavmratio12monthprior,addrinputavmvalue60month,addrinputavmratio60monthprior,addrinputcountyratio,addrinputtractratio,addrinputblockratio,addrinputproblems,addrcurrenttimeoldest,addrcurrenttimenewest,addrcurrentlengthofres,addrcurrentsubjectowned,addrcurrentdeedmailing,addrcurrentownershipindex,addrcurrentphoneservice,addrcurrentdwelltype,addrcurrentdwelltypeindex,addrcurrenttimelastsale,addrcurrentlastsalesprice,addrcurrenttaxvalue,addrcurrenttaxyr,addrcurrenttaxmarketvalue,addrcurrentavmvalue,addrcurrentavmvalue12month,addrcurrentavmratio12monthprior,addrcurrentavmvalue60month,addrcurrentavmratio60monthprior,addrcurrentcountyratio,addrcurrenttractratio,addrcurrentblockratio,addrcurrentcorrectional,addrprevioustimeoldest,addrprevioustimenewest,addrpreviouslengthofres,addrprevioussubjectowned,addrpreviousownershipindex,addrpreviousdwelltype,addrpreviousdwelltypeindex,addrpreviouscorrectional,addrstabilityindex,addrchangecount03month,addrchangecount06month,addrchangecount12month,addrchangecount24month,addrchangecount60month,addrlastmovetaxratiodiff,addrlastmoveecontrajectory,addrlastmoveecontrajectoryindex,phoneinputproblems,phoneinputsubjectcount,phoneinputmobile,alertregulatorycondition\\r\\n\\"5714239,7176826\\",0,5714239,7176826,0,False,2021-07-20T17:06:40,,1,1,1,1,1,1,3,7,1,0,276,1,1,4,4,3,43,0,1,4,L78,1,D34,1,D34,1,3,7,3,1,6,3,1,1,2,276,1,1,0,0,0,-1,0,0,-1,0,0,-1,-1,3,A47,0,0,0,0,0,-1,0,-1,-1,-1,0,0,-1,-1,-1,0,0,0,0,-1,-1,3,5,0,12,0,0,-1,1,0,29,0,0,-1,4,3,0,0,2,1,0,0,12,4265,1,0,89,1,-1,0,0,0,0,0,0,0,0,0,0,1,0,19780101,0,10,0,0,0,50,1,49,1,2,0,0,3,0,0,S,3,-1,-1,-1,0,-1,0,-1,-1,-1,-1,-1,0,0,0,0,50,1,49,0,0,3,0,S,3,-1,-1,0,-1,0,-1,-1,-1,-1,-1,0,0,0,0,87,1,86,-1,5,H,1,0,4,0,0,0,0,1,-1,4,2,0,0,0,2\\r\\n"},{"name":"TUXML","version":1.0,"format":"xml","values":"<?xml version=\\"1.0\\" encoding=\\"UTF-8\\"?><creditBureau xmlns=\\"http://www.transunion.com/namespace\\" xmlns:xsi=\\"http://www.w3.org/2001/XMLSchema-instance\\"><document>response</document><version>2.8</version><transactionControl><userRefNumber>7176826</userRefNumber><subscriber><industryCode>F</industryCode><memberCode>6339359</memberCode><inquirySubscriberPrefixCode>2924</inquirySubscriberPrefixCode></subscriber><options><country>us</country><language>en</language></options><tracking><transactionTimeStamp>2021-07-20T18:06:43.797-05:00</transactionTimeStamp></tracking></transactionControl><product><code>07000</code><subject><number>1</number><subjectRecord><fileNumber>01</fileNumber><fileSummary><fileHitIndicator>regularHit</fileHitIndicator><ssnMatchIndicator>exact</ssnMatchIndicator><consumerStatementIndicator>false</consumerStatementIndicator><market>29</market><submarket>UT</submarket><creditDataStatus><suppressed>false</suppressed><doNotPromote><indicator>false</indicator></doNotPromote><freeze><indicator>false</indicator></freeze><minor>false</minor><disputed>false</disputed></creditDataStatus><inFileSinceDate estimatedDay=\\"false\\" estimatedMonth=\\"false\\" estimatedCentury=\\"false\\" estimatedYear=\\"false\\">1998-01-01</inFileSinceDate></fileSummary><indicative><name source=\\"file\\"><person><first>MONICO</first><middle>J</middle><last>VALDEZ</last></person></name><name source=\\"file\\"><qualifier>alsoKnownAs</qualifier><person><unparsed>VALDEZ,JOE,M</unparsed></person></name><address source=\\"file\\"><status>current</status><qualifier>personal</qualifier><street><number>3244</number><name>ORIOLE</name><type>WAY</type></street><location><city>SALT LAKE CITY</city><state>UT</state><zipCode>841193134</zipCode></location><dateReported estimatedDay=\\"false\\" estimatedMonth=\\"false\\" estimatedCentury=\\"false\\" estimatedYear=\\"false\\">2007-03-20</dateReported></address><address source=\\"file\\"><status>previous</status><qualifier>personal</qualifier><street><number>1914</number><name>4805</name><preDirectional>W</preDirectional><postDirectional>S</postDirectional></street><location><city>TAYLORSVILLE</city><state>UT</state><zipCode>84118</zipCode></location><dateReported estimatedDay=\\"false\\" estimatedMonth=\\"false\\" estimatedCentury=\\"false\\" estimatedYear=\\"false\\">2005-10-31</dateReported></address><address source=\\"file\\"><status>secondPrevious</status><qualifier>personal</qualifier><street><number>2534</number><name>LESTER</name><preDirectional>S</preDirectional><type>ST</type></street><location><city>WEST VALLEY CITY</city><state>UT</state><zipCode>841192166</zipCode></location><dateReported estimatedDay=\\"false\\" estimatedMonth=\\"false\\" estimatedCentury=\\"false\\" estimatedYear=\\"false\\">2016-11-11</dateReported></address><socialSecurity source=\\"file\\"><number>529232188</number></socialSecurity><dateOfBirth estimatedDay=\\"false\\" estimatedMonth=\\"false\\" estimatedCentury=\\"false\\" estimatedYear=\\"false\\" source=\\"file\\">1977-12-24</dateOfBirth><employment source=\\"file\\"><employer><unparsed>PACIFIC SUPPLY</unparsed></employer><occupation>DRIVER</occupation><dateHired estimatedDay=\\"false\\" estimatedMonth=\\"false\\" estimatedCentury=\\"false\\" estimatedYear=\\"false\\">2003-06-01</dateHired><address source=\\"file\\"><status>current</status><qualifier>employment</qualifier><location><city>SALT LAKE CITY</city><state>UT</state><zipCode>84105</zipCode></location><dateReported estimatedDay=\\"false\\" estimatedMonth=\\"false\\" estimatedCentury=\\"false\\" estimatedYear=\\"false\\">2016-12-20</dateReported></address><dateOnFileSince estimatedDay=\\"false\\" estimatedMonth=\\"false\\" estimatedCentury=\\"false\\" estimatedYear=\\"false\\">2016-12-20</dateOnFileSince><dateEffective estimatedDay=\\"false\\" estimatedMonth=\\"false\\" estimatedCentury=\\"false\\" estimatedYear=\\"false\\">2009-10-16</dateEffective></employment><employment source=\\"file\\"><employer><unparsed>BLUE BEACON TRUCK WASH</unparsed></employer><dateOnFileSince estimatedDay=\\"false\\" estimatedMonth=\\"false\\" estimatedCentury=\\"false\\" estimatedYear=\\"false\\">2000-02-01</dateOnFileSince></employment></indicative><custom><credit><trade><subscriber><industryCode>Q</industryCode><memberCode>0957T001</memberCode><name><unparsed>MTN AMER CU</unparsed></name></subscriber><portfolioType>installment</portfolioType><accountNumber>108823380601</accountNumber><ECOADesignator>individual</ECOADesignator><dateOpened estimatedDay=\\"false\\" estimatedMonth=\\"false\\" estimatedCentury=\\"false\\" estimatedYear=\\"false\\">2021-05-29</dateOpened><dateEffective estimatedDay=\\"false\\" estimatedMonth=\\"false\\" estimatedCentury=\\"false\\" estimatedYear=\\"false\\">2021-07-01</dateEffective><currentBalance>000000839</currentBalance><highCredit>000001000</highCredit><accountRating>01</accountRating><terms><paymentFrequency>monthly</paymentFrequency><paymentScheduleMonthCount>006</paymentScheduleMonthCount><scheduledMonthlyPayment>000000180</scheduledMonthlyPayment></terms><account><type>US</type></account><pastDue>000000000</pastDue><paymentHistory><paymentPattern><startDate estimatedDay=\\"false\\" estimatedMonth=\\"false\\" estimatedCentury=\\"false\\" estimatedYear=\\"false\\">2021-06-01</startDate><text>1</text></paymentPattern><historicalCounters><monthsReviewedCount>01</monthsReviewedCount><late30DaysTotal>00</late30DaysTotal><late60DaysTotal>00</late60DaysTotal><late90DaysTotal>00</late90DaysTotal></historicalCounters></paymentHistory><mostRecentPayment><date estimatedDay=\\"false\\" estimatedMonth=\\"false\\" estimatedCentury=\\"false\\" estimatedYear=\\"false\\">2021-06-25</date></mostRecentPayment><updateMethod>automated</updateMethod></trade><trade><subscriber><industryCode>Q</industryCode><memberCode>0957T001</memberCode><name><unparsed>MTN AMER CU</unparsed></name></subscriber><portfolioType>installment</portfolioType><accountNumber>108823380600</accountNumber><ECOADesignator>individual</ECOADesignator><dateOpened estimatedDay=\\"false\\" estimatedMonth=\\"false\\" estimatedCentury=\\"false\\" estimatedYear=\\"false\\">2020-05-02</dateOpened><dateEffective estimatedDay=\\"false\\" estimatedMonth=\\"false\\" estimatedCentury=\\"false\\" estimatedYear=\\"false\\">2020-10-02</dateEffective><dateClosed estimatedDay=\\"false\\" estimatedMonth=\\"false\\" estimatedCentury=\\"false\\" estimatedYear=\\"false\\">2020-10-02</dateClosed><closedIndicator>normal</closedIndicator><currentBalance>000000000</currentBalance><highCredit>000001000</highCredit><accountRating>01</accountRating><remark><code>CLO</code><type>ratingHistory</type></remark><terms><paymentFrequency>monthly</paymentFrequency><paymentScheduleMonthCount>006</paymentScheduleMonthCount></terms><account><type>US</type></account><pastDue>000000000</pastDue><paymentHistory><paymentPattern><startDate estimatedDay=\\"false\\" estimatedMonth=\\"false\\" estimatedCentury=\\"false\\" estimatedYear=\\"false\\">2020-09-02</startDate><text>1111</text></paymentPattern><historicalCounters><monthsReviewedCount>04</monthsReviewedCount><late30DaysTotal>00</late30DaysTotal><late60DaysTotal>00</late60DaysTotal><late90DaysTotal>00</late90DaysTotal></historicalCounters></paymentHistory><mostRecentPayment><date estimatedDay=\\"false\\" estimatedMonth=\\"false\\" estimatedCentury=\\"false\\" estimatedYear=\\"false\\">2020-10-02</date></mostRecentPayment><updateMethod>automated</updateMethod></trade><trade><subscriber><industryCode>F</industryCode><memberCode>025FY016</memberCode><name><unparsed>MID CITY FIN</unparsed></name></subscriber><portfolioType>installment</portfolioType><accountNumber>GMUX5710</accountNumber><ECOADesignator>individual</ECOADesignator><dateOpened estimatedDay=\\"false\\" estimatedMonth=\\"false\\" estimatedCentury=\\"false\\" estimatedYear=\\"false\\">2012-03-15</dateOpened><dateEffective estimatedDay=\\"false\\" estimatedMonth=\\"false\\" estimatedCentury=\\"false\\" estimatedYear=\\"false\\">2012-03-30</dateEffective><highCredit>000002000</highCredit><accountRating>01</accountRating><terms><paymentFrequency>monthly</paymentFrequency><paymentScheduleMonthCount>018</paymentScheduleMonthCount><scheduledMonthlyPayment>000000118</scheduledMonthlyPayment></terms><account><type>SE</type></account><paymentHistory><paymentPattern><startDate estimatedDay=\\"false\\" estimatedMonth=\\"false\\" estimatedCentury=\\"false\\" estimatedYear=\\"false\\">2012-02-29</startDate><text>1111111111111YY11Y11111111Y1111111</text></paymentPattern><historicalCounters><monthsReviewedCount>34</monthsReviewedCount><late30DaysTotal>00</late30DaysTotal><late60DaysTotal>00</late60DaysTotal><late90DaysTotal>00</late90DaysTotal></historicalCounters></paymentHistory><mostRecentPayment><date estimatedDay=\\"false\\" estimatedMonth=\\"false\\" estimatedCentury=\\"false\\" estimatedYear=\\"false\\">2012-03-30</date></mostRecentPayment><updateMethod>automated</updateMethod></trade><collection><subscriber><industryCode>Y</industryCode><memberCode>022PC001</memberCode><name><unparsed>MTN LAND COL</unparsed></name></subscriber><portfolioType>open</portfolioType><accountNumber>130429103276341</accountNumber><ECOADesignator>individual</ECOADesignator><account><type>AG</type></account><dateOpened estimatedDay=\\"false\\" estimatedMonth=\\"false\\" estimatedCentury=\\"false\\" estimatedYear=\\"false\\">2020-05-06</dateOpened><dateEffective estimatedDay=\\"false\\" estimatedMonth=\\"false\\" estimatedCentury=\\"false\\" estimatedYear=\\"false\\">2021-07-15</dateEffective><currentBalance>000000266</currentBalance><original><creditGrantor><unparsed>MEDICAL</unparsed></creditGrantor><creditorClassification>medicalOrHealthCare</creditorClassification><balance>000000238</balance></original><pastDue>000000266</pastDue><accountRating>9B</accountRating><remark><code>CLA</code><type>ratingHistory</type></remark><updateMethod>automated</updateMethod></collection><collection><subscriber><industryCode>Y</industryCode><memberCode>02834001</memberCode><name><unparsed>I C SYSTEM</unparsed></name></subscriber><portfolioType>open</portfolioType><accountNumber>100694922</accountNumber><ECOADesignator>individual</ECOADesignator><account><type>AG</type></account><dateOpened estimatedDay=\\"false\\" estima

#### df_idx.csv - not utilized here

In [16]:
list_rows = list(df['rows'].value_counts().index)
df_idx = pd.DataFrame({'row': list_rows})
df_idx.sort_values(by='row', ascending=True, inplace=True)

# save
str_filename = 'df_idx.csv'
df_idx.to_csv(f'{str_dirname_output}/{str_filename}', index=False)

# show
df_idx

   row
0    1
1    2
2    3
3    4

In [17]:
# parse (get income, LN, and TU)
print('Parsing requests...')
list_X_raw = []
for a, str_request in enumerate(df['strRequest']):
    # get bigAccountId
    int_bigaccountid = df['bigAccountId'].iloc[a]
    # get dtmFunded
    dtm_funded = df['dtmFunded'].iloc[a]
    
    # convert string request to dict
    dict_json_request = json.loads(str_request)
    # get data
    cls_parser.get_data(dict_json_request)
    # parse data
    cls_parser.parse_data()
    # create X
    cls_parser.create_x()
    # get X_raw
    X_raw = cls_parser.dict_output['X_raw']
        
    # assign
    X_raw['bigAccountId'] = int_bigaccountid
    X_raw['dtmFunded'] = dtm_funded
    # get nrows
    int_nrows = X_raw.shape[0]
    if int_nrows == 1:
        X_raw['BITDEBTOR'] = 1
    else:
        X_raw['BITDEBTOR'] = [1,0]
        
    # append
    list_X_raw.append(X_raw)
    
# concat
print('Concatenating raw data...')
X_raw = pd.concat(list_X_raw)
    
# save memeory
del list_X_raw
    
# write to s3 as parquet
print('Writing raw data to s3...')
# set nonnumeric to string
for col in X_raw.columns:
    # if not numeric
    if X_raw[col].dtype not in ['int64', 'float64']:
        # set as string
        X_raw[col] = X_raw[col].astype(str)
    else:
        pass

Parsing requests...
['5714239__7176826__20210720']: Get Data: 0.00000 sec.
['5714239__7176826__20210720']: Parse Data: 0.03457 sec.
['5714239__7176826__20210720']: Create X: 0.55109 sec.
['5711466__7173427__20210717']: Get Data: 0.00000 sec.
['5711466__7173427__20210717']: Parse Data: 0.03036 sec.
['5711466__7173427__20210717']: Create X: 0.59362 sec.
['5702106__7162085__20210707']: Get Data: 0.00000 sec.
['5702106__7162085__20210707']: Parse Data: 0.02926 sec.
['5702106__7162085__20210707']: Create X: 0.58711 sec.
['5708876__7170291__20210714']: Get Data: 0.00000 sec.
['5708876__7170291__20210714']: Parse Data: 0.03349 sec.
['5708876__7170291__20210714']: Create X: 0.51120 sec.
['5708693__7170066__20210714']: Get Data: 0.00000 sec.
['5708693__7170066__20210714']: Parse Data: 0.02927 sec.
['5708693__7170066__20210714']: Create X: 0.58711 sec.
['5712734__7174995__20210719']: Get Data: 0.00000 sec.
['5712734__7174995__20210719']: Parse Data: 0.03282 sec.
['5712734__7174995__20210719']: Create X: 0.51017 sec.
['5718002__7181410__20210724']: Get Data: 0.00000 sec.
['5718002__7181410__20210724']: Parse Data: 0.03250 sec.
['5718002__7181410__20210724']: Create X: 0.50953 sec.
['5704330__7164758__20210709', '5704330__7164759__20210709']: Get Data: 0.00000 sec.
['5704330__7164758__20210709', '5704330__7164759__20210709']: Parse Data: 0.09991 sec.
['5704330__7164758__20210709', '5704330__7164759__20210709']: Create X: 0.53236 sec.
['5717801__7181161__20210724']: Get Data: 0.00000 sec.
['5717801__7181161__20210724']: Parse Data: 0.03035 sec.
['5717801__7181161__20210724']: Create X: 0.58653 sec.
['5717887__7181269__20210724']: Get Data: 0.00000 sec.
['5717887__7181269__20210724']: Parse Data: 0.03039 sec.
['5717887__7181269__20210724']: Create X: 0.58488 sec.
['5695635__7154118__20210629', '5695635__7154119__20210629']: Get Data: 0.00000 sec.
['5695635__7154118__20210629', '5695635__7154119__20210629']: Parse Data: 0.06004 sec.
['5695635__7154118__20210629', '5695635__7154119__20210629']: Create X: 0.60319 sec.
['5709029__7170475__20210715']: Get Data: 0.00000 sec.
['5709029__7170475__20210715']: Parse Data: 0.03282 sec.
['5709029__7170475__20210715']: Create X: 0.51099 sec.
['5712452__7174658__20210719']: Get Data: 0.00000 sec.
['5712452__7174658__20210719']: Parse Data: 0.03330 sec.
['5712452__7174658__20210719']: Create X: 0.50828 sec.
['5704668__7165190__20210709']: Get Data: 0.00000 sec.
['5704668__7165190__20210709']: Parse Data: 0.03054 sec.
['5704668__7165190__20210709']: Create X: 0.62671 sec.
['5718633__7182210__20210724']: Get Data: 0.00000 sec.
['5718633__7182210__20210724']: Parse Data: 0.03382 sec.
['5718633__7182210__20210724']: Create X: 0.50982 sec.
['5709609__7171175__20210715', '5709609__7171176__20210715']: Get Data: 0.00000 sec.
['5709609__7171175__20210715', '5709609__7171176__20210715']: Parse Data: 0.06469 sec.
['5709609__7171175__20210715', '5709609__7171176__20210715']: Create X: 0.53264 sec.
['5715154__7177937__20210721']: Get Data: 0.00000 sec.
['5715154__7177937__20210721']: Parse Data: 0.03069 sec.
['5715154__7177937__20210721']: Create X: 0.58718 sec.
['5705936__7166739__20210711']: Get Data: 0.00000 sec.
['5705936__7166739__20210711']: Parse Data: 0.03448 sec.
['5705936__7166739__20210711']: Create X: 0.51144 sec.
['5716285__7179318__20210722']: Get Data: 0.00000 sec.
['5716285__7179318__20210722']: Parse Data: 0.03207 sec.
['5716285__7179318__20210722']: Create X: 0.51002 sec.
['5718084__7181511__20210724']: Get Data: 0.00000 sec.
['5718084__7181511__20210724']: Parse Data: 0.03408 sec.
['5718084__7181511__20210724']: Create X: 0.51062 sec.
['5718738__7182345__20210725']: Get Data: 0.00000 sec.
['5718738__7182345__20210725']: Parse Data: 0.07736 sec.
['5718738__7182345__20210725']: Create X: 0.51248 sec.
['5718748__7182360__20210725']: Get Data: 0.00000 sec.
['5718748__7182360__20210725']: Parse Data: 0.03280 sec.
['5718748__7182360__20210725']: Create X: 0.50958 sec.
['5712487__7174699__20210719']: Get Data: 0.00000 sec.
['5712487__7174699__20210719']: Parse Data: 0.03410 sec.
['5712487__7174699__20210719']: Create X: 0.51085 sec.
['5714558__7177204__20210721']: Get Data: 0.00000 sec.
['5714558__7177204__20210721']: Parse Data: 0.03243 sec.
['5714558__7177204__20210721']: Create X: 0.51058 sec.
['5715159__7177943__20210721']: Get Data: 0.00000 sec.
['5715159__7177943__20210721']: Parse Data: 0.03316 sec.
['5715159__7177943__20210721']: Create X: 0.51314 sec.
['5712692__7174945__20210719', '5712692__7174946__20210719']: Get Data: 0.00000 sec.
['5712692__7174945__20210719', '5712692__7174946__20210719']: Parse Data: 0.06737 sec.
['5712692__7174945__20210719', '5712692__7174946__20210719']: Create X: 0.53297 sec.
['5708631__7169992__20210714']: Get Data: 0.00000 sec.
['5708631__7169992__20210714']: Parse Data: 0.08393 sec.
['5708631__7169992__20210714']: Create X: 0.51174 sec.
['5714208__7176784__20210720']: Get Data: 0.00000 sec.
['5714208__7176784__20210720']: Parse Data: 0.03110 sec.
['5714208__7176784__20210720']: Create X: 0.59195 sec.
['5707024__7168045__20210712']: Get Data: 0.00000 sec.
['5707024__7168045__20210712']: Parse Data: 0.03411 sec.
['5707024__7168045__20210712']: Create X: 0.50982 sec.
['5717504__7180796__20210724']: Get Data: 0.00000 sec.
['5717504__7180796__20210724']: Parse Data: 0.03279 sec.
['5717504__7180796__20210724']: Create X: 0.51244 sec.
['5710886__7172715__20210716', '5710886__7172716__20210716']: Get Data: 0.00000 sec.
['5710886__7172715__20210716', '5710886__7172716__20210716']: Parse Data: 0.06537 sec.
['5710886__7172715__20210716', '5710886__7172716__20210716']: Create X: 0.53370 sec.
['5710164__7171838__20210716', '5710164__7171839__20210716']: Get Data: 0.00000 sec.
['5710164__7171838__20210716', '5710164__7171839__20210716']: Parse Data: 0.11951 sec.
['5710164__7171838__20210716', '5710164__7171839__20210716']: Create X: 0.53192 sec.
['5718939__7182599__20210726']: Get Data: 0.00000 sec.
['5718939__7182599__20210726']: Parse Data: 0.03319 sec.
['5718939__7182599__20210726']: Create X: 0.51270 sec.
['5715634__7178525__20210722']: Get Data: 0.00000 sec.
['5715634__7178525__20210722']: Parse Data: 0.02908 sec.
['5715634__7178525__20210722']: Create X: 0.58664 sec.
['5710028__7171680__20210716']: Get Data: 0.00000 sec.
['5710028__7171680__20210716']: Parse Data: 0.03292 sec.
['5710028__7171680__20210716']: Create X: 0.51063 sec.
['5717667__7180995__20210724']: Get Data: 0.00000 sec.
['5717667__7180995__20210724']: Parse Data: 0.03315 sec.
['5717667__7180995__20210724']: Create X: 0.50808 sec.
['5720041__7183948__20210727']: Get Data: 0.00000 sec.
['5720041__7183948__20210727']: Parse Data: 0.03364 sec.
['5720041__7183948__20210727']: Create X: 0.50948 sec.
['5709814__7171427__20210715']: Get Data: 0.00000 sec.
['5709814__7171427__20210715']: Parse Data: 0.02961 sec.
['5709814__7171427__20210715']: Create X: 0.58522 sec.
['5706920__7167913__20210712']: Get Data: 0.00000 sec.
['5706920__7167913__20210712']: Parse Data: 0.03021 sec.
['5706920__7167913__20210712']: Create X: 0.58669 sec.
['5712267__7174438__20210718']: Get Data: 0.00000 sec.
['5712267__7174438__20210718']: Parse Data: 0.03246 sec.
['5712267__7174438__20210718']: Create X: 0.51000 sec.
['5719069__7182759__20210726']: Get Data: 0.00000 sec.
['5719069__7182759__20210726']: Parse Data: 0.09419 sec.
['5719069__7182759__20210726']: Create X: 0.51242 sec.
['5706170__7167016__20210712']: Get Data: 0.00000 sec.
['5706170__7167016__20210712']: Parse Data: 0.03022 sec.
['5706170__7167016__20210712']: Create X: 0.58672 sec.
['5716397__7179450__20210723']: Get Data: 0.00000 sec.
['5716397__7179450__20210723']: Parse Data: 0.03376 sec.
['5716397__7179450__20210723']: Create X: 0.50889 sec.
['5695070__7153434__20210629', '5695070__7153435__20210629']: Get Data: 0.00000 sec.
['5695070__7153434__20210629', '5695070__7153435__20210629']: Parse Data: 0.06218 sec.
['5695070__7153434__20210629', '5695070__7153435__20210629']: Create X: 0.53118 sec.
['5719288__7183020__20210726']: Get Data: 0.00000 sec.
['5719288__7183020__20210726']: Parse Data: 0.03270 sec.
['5719288__7183020__20210726']: Create X: 0.51188 sec.
['5717785__7181140__20210724']: Get Data: 0.00000 sec.
['5717785__7181140__20210724']: Parse Data: 0.03305 sec.

['5717785__7181140__20210724']: Create X: 0.50989 sec.
['5713040__7175367__20210719']: Get Data: 0.00000 sec.
['5713040__7175367__20210719']: Parse Data: 0.03272 sec.
['5713040__7175367__20210719']: Create X: 0.51097 sec.
['5714847__7177553__20210721']: Get Data: 0.00000 sec.
['5714847__7177553__20210721']: Parse Data: 0.03009 sec.
['5714847__7177553__20210721']: Create X: 0.58505 sec.
['5712088__7174212__20210717']: Get Data: 0.00000 sec.
['5712088__7174212__20210717']: Parse Data: 0.03328 sec.
['5712088__7174212__20210717']: Create X: 0.50914 sec.
['5715974__7178946__20210722', '5715974__7178947__20210722']: Get Data: 0.00000 sec.
['5715974__7178946__20210722', '5715974__7178947__20210722']: Parse Data: 0.12748 sec.
['5715974__7178946__20210722', '5715974__7178947__20210722']: Create X: 0.60624 sec.
['5708421__7169743__20210714', '5708421__7169744__20210714']: Get Data: 0.00000 sec.
['5708421__7169743__20210714', '5708421__7169744__20210714']: Parse Data: 0.06540 sec.
['5708421__7169743__20210714', '5708421__7169744__20210714']: Create X: 0.53283 sec.
['5711070__7172941__20210717']: Get Data: 0.00000 sec.
['5711070__7172941__20210717']: Parse Data: 0.02932 sec.
['5711070__7172941__20210717']: Create X: 0.59044 sec.
['5714864__7177574__20210721', '5714864__7177575__20210721']: Get Data: 0.00000 sec.
['5714864__7177574__20210721', '5714864__7177575__20210721']: Parse Data: 0.06768 sec.
['5714864__7177574__20210721', '5714864__7177575__20210721']: Create X: 0.53149 sec.
['5709398__7170916__20210715']: Get Data: 0.00000 sec.
['5709398__7170916__20210715']: Parse Data: 0.03491 sec.
['5709398__7170916__20210715']: Create X: 0.51268 sec.
['5714071__7176621__20210720']: Get Data: 0.00000 sec.
['5714071__7176621__20210720']: Parse Data: 0.03255 sec.
['5714071__7176621__20210720']: Create X: 0.51217 sec.
['5714987__7177729__20210721']: Get Data: 0.00000 sec.
['5714987__7177729__20210721']: Parse Data: 0.03335 sec.
['5714987__7177729__20210721']: Create X: 0.51203 sec.
['5696880__7155640__20210701']: Get Data: 0.00000 sec.
['5696880__7155640__20210701']: Parse Data: 0.10584 sec.
['5696880__7155640__20210701']: Create X: 0.51161 sec.
['5717506__7180798__20210724']: Get Data: 0.00000 sec.
['5717506__7180798__20210724']: Parse Data: 0.03305 sec.
['5717506__7180798__20210724']: Create X: 0.51133 sec.
['5709088__7170547__20210715']: Get Data: 0.00000 sec.
['5709088__7170547__20210715']: Parse Data: 0.02985 sec.
['5709088__7170547__20210715']: Create X: 0.58684 sec.
['5697900__7156884__20210702']: Get Data: 0.00000 sec.
['5697900__7156884__20210702']: Parse Data: 0.03356 sec.
['5697900__7156884__20210702']: Create X: 0.51259 sec.
['5716286__7179319__20210722']: Get Data: 0.00000 sec.
['5716286__7179319__20210722']: Parse Data: 0.03247 sec.
['5716286__7179319__20210722']: Create X: 0.51124 sec.
['5713585__7176035__20210720']: Get Data: 0.00000 sec.
['5713585__7176035__20210720']: Parse Data: 0.03335 sec.
['5713585__7176035__20210720']: Create X: 0.51102 sec.
['5714830__7177533__20210721']: Get Data: 0.00000 sec.
['5714830__7177533__20210721']: Parse Data: 0.03386 sec.
['5714830__7177533__20210721']: Create X: 0.51104 sec.
['5716209__7179221__20210722']: Get Data: 0.00000 sec.
['5716209__7179221__20210722']: Parse Data: 0.02954 sec.
['5716209__7179221__20210722']: Create X: 0.58767 sec.
['5716895__7180058__20210723']: Get Data: 0.00000 sec.
['5716895__7180058__20210723']: Parse Data: 0.03425 sec.
['5716895__7180058__20210723']: Create X: 0.51114 sec.
['5710018__7171669__20210716']: Get Data: 0.00000 sec.
['5710018__7171669__20210716']: Parse Data: 0.03444 sec.
['5710018__7171669__20210716']: Create X: 0.51127 sec.
['5720762__7184825__20210727']: Get Data: 0.00000 sec.
['5720762__7184825__20210727']: Parse Data: 0.03431 sec.
['5720762__7184825__20210727']: Create X: 0.51225 sec.
['5717595__7180908__20210724']: Get Data: 0.00000 sec.
['5717595__7180908__20210724']: Parse Data: 0.03272 sec.
['5717595__7180908__20210724']: Create X: 0.51251 sec.
['5712939__7175249__20210719', '5712939__7175285__20210719']: Get Data: 0.00000 sec.
['5712939__7175249__20210719', '5712939__7175285__20210719']: Parse Data: 0.14608 sec.
['5712939__7175249__20210719', '5712939__7175285__20210719']: Create X: 0.53253 sec.
['5712605__7174839__20210719']: Get Data: 0.00000 sec.
['5712605__7174839__20210719']: Parse Data: 0.03019 sec.
['5712605__7174839__20210719']: Create X: 0.58779 sec.
['5703249__7163465__20210708']: Get Data: 0.00000 sec.
['5703249__7163465__20210708']: Parse Data: 0.03357 sec.
['5703249__7163465__20210708']: Create X: 0.51238 sec.
['5718903__7182553__20210726']: Get Data: 0.00000 sec.
['5718903__7182553__20210726']: Parse Data: 0.02967 sec.
['5718903__7182553__20210726']: Create X: 0.58759 sec.
['5720241__7184194__20210727']: Get Data: 0.00000 sec.
['5720241__7184194__20210727']: Parse Data: 0.03401 sec.
['5720241__7184194__20210727']: Create X: 0.51170 sec.
['5710818__7172634__20210716']: Get Data: 0.00000 sec.
['5710818__7172634__20210716']: Parse Data: 0.02921 sec.
['5710818__7172634__20210716']: Create X: 0.58615 sec.
['5714707__7177383__20210721']: Get Data: 0.00000 sec.
['5714707__7177383__20210721']: Parse Data: 0.03366 sec.
['5714707__7177383__20210721']: Create X: 0.50985 sec.
['5704602__7165106__20210709']: Get Data: 0.00000 sec.
['5704602__7165106__20210709']: Parse Data: 0.03256 sec.
['5704602__7165106__20210709']: Create X: 0.51152 sec.
['5716795__7179927__20210723']: Get Data: 0.00000 sec.
['5716795__7179927__20210723']: Parse Data: 0.03487 sec.
['5716795__7179927__20210723']: Create X: 0.51140 sec.
['5718665__7182250__20210724']: Get Data: 0.00000 sec.
['5718665__7182250__20210724']: Parse Data: 0.03212 sec.
['5718665__7182250__20210724']: Create X: 0.51117 sec.
['5711751__7173782__20210717']: Get Data: 0.00000 sec.
['5711751__7173782__20210717']: Parse Data: 0.03317 sec.
['5711751__7173782__20210717']: Create X: 0.51096 sec.
['5719067__7182755__20210726', '5719067__7182756__20210726']: Get Data: 0.00000 sec.
['5719067__7182755__20210726', '5719067__7182756__20210726']: Parse Data: 0.15218 sec.
['5719067__7182755__20210726', '5719067__7182756__20210726']: Create X: 0.53411 sec.
['5718183__7181634__20210724', '5718183__7181635__20210724']: Get Data: 0.00000 sec.
['5718183__7181634__20210724', '5718183__7181635__20210724']: Parse Data: 0.06497 sec.
['5718183__7181634__20210724', '5718183__7181635__20210724']: Create X: 0.53371 sec.
['5712483__7174695__20210719']: Get Data: 0.00000 sec.
['5712483__7174695__20210719']: Parse Data: 0.03249 sec.
['5712483__7174695__20210719']: Create X: 0.51231 sec.
['5714824__7177525__20210721', '5714824__7177526__20210721']: Get Data: 0.00000 sec.
['5714824__7177525__20210721', '5714824__7177526__20210721']: Parse Data: 0.06210 sec.
['5714824__7177525__20210721', '5714824__7177526__20210721']: Create X: 0.53436 sec.
['5714542__7177185__20210721']: Get Data: 0.00000 sec.
['5714542__7177185__20210721']: Parse Data: 0.03272 sec.
['5714542__7177185__20210721']: Create X: 0.51183 sec.
['5712001__7174100__20210717', '5712001__7174101__20210717']: Get Data: 0.00000 sec.
['5712001__7174100__20210717', '5712001__7174101__20210717']: Parse Data: 0.06764 sec.
['5712001__7174100__20210717', '5712001__7174101__20210717']: Create X: 0.53274 sec.
['5720626__7184664__20210727', '5720626__7184665__20210727']: Get Data: 0.00000 sec.
['5720626__7184664__20210727', '5720626__7184665__20210727']: Parse Data: 0.06344 sec.
['5720626__7184664__20210727', '5720626__7184665__20210727']: Create X: 0.53712 sec.
['5707589__7168722__20210713']: Get Data: 0.00000 sec.
['5707589__7168722__20210713']: Parse Data: 0.03520 sec.
['5707589__7168722__20210713']: Create X: 0.51441 sec.
['5710198__7171879__20210716']: Get Data: 0.00000 sec.
['5710198__7171879__20210716']: Parse Data: 0.03247 sec.
['5710198__7171879__20210716']: Create X: 0.50967 sec.
['5717181__7180417__20210723']: Get Data: 0.00000 sec.
['5717181__7180417__20210723']: Parse Data: 0.02960 sec.
['5717181__7180417__20210723']: Create X: 0.58654 sec.
['5720326__7184297__20210727']: Get Data: 0.00000 sec.
['5720326__7184297__20210727']: Parse Data: 0.03053 sec.
['5720326__7184297__20210727']: Create X: 0.58844 sec.
['5715012__7177763__20210721']: Get Data: 0.00000 sec.
['5715012__7177763__20210721']: Parse Data: 0.13018 sec.

['5715012__7177763__20210721']: Create X: 0.51608 sec.
['5716145__7179144__20210722']: Get Data: 0.00000 sec.
['5716145__7179144__20210722']: Parse Data: 0.03404 sec.
['5716145__7179144__20210722']: Create X: 0.51170 sec.
['5721262__7185423__20210728']: Get Data: 0.00000 sec.
['5721262__7185423__20210728']: Parse Data: 0.03437 sec.
['5721262__7185423__20210728']: Create X: 0.51254 sec.
['5715716__7178627__20210722', '5715716__7178628__20210722']: Get Data: 0.00000 sec.
['5715716__7178627__20210722', '5715716__7178628__20210722']: Parse Data: 0.06520 sec.
['5715716__7178627__20210722', '5715716__7178628__20210722']: Create X: 0.53586 sec.
['5720007__7183907__20210727', '5720007__7183908__20210727']: Get Data: 0.00000 sec.
['5720007__7183907__20210727', '5720007__7183908__20210727']: Parse Data: 0.05931 sec.
['5720007__7183907__20210727', '5720007__7183908__20210727']: Create X: 0.60662 sec.
['5720091__7184009__20210727']: Get Data: 0.00000 sec.
['5720091__7184009__20210727']: Parse Data: 0.03361 sec.
['5720091__7184009__20210727']: Create X: 0.51268 sec.
['5716645__7179743__20210723', '5716645__7179744__20210723']: Get Data: 0.00000 sec.
['5716645__7179743__20210723', '5716645__7179744__20210723']: Parse Data: 0.06310 sec.
['5716645__7179743__20210723', '5716645__7179744__20210723']: Create X: 0.53549 sec.
['5706152__7166995__20210712']: Get Data: 0.00000 sec.
['5706152__7166995__20210712']: Parse Data: 0.02993 sec.
['5706152__7166995__20210712']: Create X: 0.58929 sec.
['5713490__7175919__20210720']: Get Data: 0.00000 sec.
['5713490__7175919__20210720']: Parse Data: 0.03311 sec.
['5713490__7175919__20210720']: Create X: 0.51166 sec.
['5713619__7176075__20210720', '5713619__7176076__20210720']: Get Data: 0.00000 sec.
['5713619__7176075__20210720', '5713619__7176076__20210720']: Parse Data: 0.06384 sec.
['5713619__7176075__20210720', '5713619__7176076__20210720']: Create X: 0.53485 sec.
Concatenating raw data...
Writing raw data to s3...

In [18]:
X_raw

,uniqueid__app,bigaccountid__app,bigdebtorid__app,bitdebtor__app,strcity__app,strname__app,strzipcode__app,applicationdate__app,bitapproved__app,bitsystemdecline__app,...,fltadvance__app,strvehicletype__app,bitgap__app,dealerstampcreation__app,RunningNetLoss,bitTarget24Months,target,bigAccountId,dtmFunded,BITDEBTOR
5714239__7176826__20210720,5714239__7176826__20210720,5714239,7176826,1,W VALLEY CITY,Utah,84119,NaN,True,nan,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5714239,2021-07-26,1
5711466__7173427__20210717,5711466__7173427__20210717,5711466,7173427,1,BRIERFIELD,Alabama,35035,NaN,True,nan,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5711466,2021-07-27,1
5702106__7162085__20210707,5702106__7162085__20210707,5702106,7162085,1,SACRAMENTO,California,95823,NaN,True,nan,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5702106,2021-07-27,1
5708876__7170291__20210714,5708876__7170291__20210714,5708876,7170291,1,MCFARLAND,Wisconsin,53558,NaN,True,nan,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5708876,2021-07-27,1
5708693__7170066__20210714,5708693__7170066__20210714,5708693,7170066,1,MATTESON,Illinois,60443,NaN,True,nan,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5708693,2021-07-27,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5716645__7179744__20210723,5716645__7179744__20210723,5716645,7179744,0,Rock Falls,Illinois,61071,NaN,True,nan,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5716645,2021-08-02,0
5706152__7166995__20210712,5706152__7166995__20210712,5706152,7166995,1,SAVAGE,Minnesota,55378,NaN,True,nan,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5706152,2021-08-02,1
5713490__7175919__20210720,5713490__7175919__20210720,5713490,7175919,1,MOORESVILLE,Indiana,46158,NaN,True,nan,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5713490,2021-08-02,1
5713619__7176075__20210720,5713619__7176075__20210720,5713619,7176075,1,COLORADO SPRINGS,Colorado,80920,NaN,True,nan,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5713619,2021-08-02,1
5713619__7176076__20210720,5713619__7176076__20210720,5713619,7176076,0,COLORADO SPRINGS,Colorado,80920,NaN,True,nan,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5713619,2021-08-02,0

In [19]:
list_ = list(X_raw.columns)
list_

['uniqueid__app',
 'bigaccountid__app',
 'bigdebtorid__app',
 'bitdebtor__app',
 'strcity__app',
 'strname__app',
 'strzipcode__app',
 'applicationdate__app',
 'bitapproved__app',
 'bitsystemdecline__app',
 'approvaldate__app',
 'bitfunded__app',
 'fundeddate__app',
 'dtmstampcreation__app',
 'dtmapproved__app',
 'dtmdeclined__app',
 'dtmfunded__app',
 'defaultdate__app',
 'chargeoffdate__app',
 'defaultamount__app',
 'chargeoffamount__app',
 'applicationmonth__app',
 'applicationquarter__app',
 'applicationdayofweek__app',
 'bigdealerid__app',
 'bitrolled__app',
 'bigdealertypeid__app',
 'dealerstate__app',
 'bitlhmgroup__app',
 'dealercity__app',
 'dealerzip__app',
 'bitdealerapplicantsamestate__app',
 'bitdealerapplicantsamecity__app',
 'bitdealerapplicantsamezip__app',
 'strdealershiptrackertype__app',
 'inttype__app',
 'fltacquisitionfee__app',
 'fltaddfee__app',
 'fltallowance__app',
 'fltamountfinanced__app',
 'fltapprovedapr_contract__app',
 'fltapproveddebttoincome__app',
 'fltapproveddowntotal__app',
 'fltapprovedloantovalue__app',
 'fltapprovedpayment__app',
 'fltapprovedpricewholesale__app',
 'fltapprovedservicecontract__app',
 'fltdocumentfee__app',
 'fltdowncash__app',
 'fltgapinsurance__app',
 'fltinsureddisabilityamount__app',
 'fltinsureddisabilitypremium__app',
 'fltinsuredlifeamount__app',
 'fltinsuredlifepremium__app',
 'fltinsuredunemploymentamount__app',
 'fltinsuredunemploymentpremium__app',
 'fltlicensefee__app',
 'fltservicecontract__app',
 'flttaxgrossreceipts__app',
 'intterm__app',
 'inttermbump__app',
 'bitdealertrack__app',
 'bitrouteone__app',
 'bitservicecontract__app',
 'intservicecontractterm__app',
 'intservicecontractmileage__app',
 'intservicecontractmileageaddon__app',
 'bitmaintenanceagreement__app',
 'fltmaintenanceagreement__app',
 'bittrade__app',
 'fltgrossmonthly__income_sum',
 'fltgrossmonthly__income_count',
 'uniqueid__ln',
 'biglnriskviewattributesv5id__ln',
 'bigaccountid__ln',
 'bigdebtorid__ln',
 'biglnriskviewscoreid__ln',
 'bitinvalid__ln',
 'dtmstampcreation__ln',
 'attribute_index__ln',
 'inputprovidedfirstname__ln',
 'inputprovidedlastname__ln',
 'inputprovidedstreetaddress__ln',
 'inputprovidedcity__ln',
 'inputprovidedstate__ln',
 'inputprovidedzipcode__ln',
 'inputprovidedssn__ln',
 'inputprovideddateofbirth__ln',
 'inputprovidedphone__ln',
 'inputprovidedlexid__ln',
 'subjectrecordtimeoldest__ln',
 'subjectrecordtimenewest__ln',
 'subjectnewestrecord12month__ln',
 'subjectactivityindex03month__ln',
 'subjectactivityindex06month__ln',
 'subjectactivityindex12month__ln',
 'subjectage__ln',
 'subjectdeceased__ln',
 'subjectssncount__ln',
 'subjectstabilityindex__ln',
 'subjectstabilityprimaryfactor__ln',
 'subjectabilityindex__ln',
 'subjectabilityprimaryfactor__ln',
 'subjectwillingnessindex__ln',
 'subjectwillingnessprimaryfactor__ln',
 'confirmationsubjectfound__ln',
 'confirmationinputname__ln',
 'confirmationinputdob__ln',
 'confirmationinputssn__ln',
 'confirmationinputaddress__ln',
 'sourcenonderogprofileindex__ln',
 'sourcenonderogcount__ln',
 'sourcenonderogcount03month__ln',
 'sourcenonderogcount06month__ln',
 'sourcenonderogcount12month__ln',
 'sourcecredheadertimeoldest__ln',
 'sourcecredheadertimenewest__ln',
 'sourcevoterregistration__ln',
 'educationattendance__ln',
 'educationevidence__ln',
 'educationprogramattended__ln',
 'educationinstitutionprivate__ln',
 'educationinstitutionrating__ln',
 'profliccount__ln',
 'proflictypecategory__ln',
 'businessassociation__ln',
 'businessassociationindex__ln',
 'businessassociationtimeoldest__ln',
 'businesstitleleadership__ln',
 'assetindex__ln',
 'assetindexprimaryfactor__ln',
 'assetownership__ln',
 'assetprop__ln',
 'assetpropindex__ln',
 'assetpropevercount__ln',
 'assetpropcurrentcount__ln',
 'assetpropcurrenttaxtotal__ln',
 'assetproppurchasecount12month__ln',
 'assetproppurchasetimeoldest__ln',
 'assetproppurchasetimenewest__ln',
 'assetpropnewestmortgagetype__ln',
 'assetpropeversoldcount__ln',
 'assetpropsoldcount12month__ln',
 'assetpropsaletimeoldest__ln',
 'assetpropsaletimenewest__ln',
 'assetpropnewestsaleprice__ln',
 'assetpropsalepurchaseratio__ln',
 'assetpersonal__ln',
 'assetpersonalcount__ln',
 'purchaseactivityindex__ln',
 'purchaseactivitycount__ln',
 'purchaseactivitydollartotal__ln',
 'derogseverityindex__ln',
 'derogcount__ln',
 'derogcount12month__ln',
 'derogtimenewest__ln',
 'criminalfelonycount__ln',
 'criminalfelonycount12month__ln',
 'criminalfelonytimenewest__ln',
 'criminalnonfelonycount__ln',
 'criminalnonfelonycount12month__ln',
 'criminalnonfelonytimenewest__ln',
 'evictioncount__ln',
 'evictioncount12month__ln',
 'evictiontimenewest__ln',
 'lienjudgmentseverityindex__ln',
 'lienjudgmentcount__ln',
 'lienjudgmentcount12month__ln',
 'lienjudgmentsmallclaimscount__ln',
 'lienjudgmentcourtcount__ln',
 'lienjudgmenttaxcount__ln',
 'lienjudgmentforeclosurecount__ln',
 'lienjudgmentothercount__ln',
 'lienjudgmenttimenewest__ln',
 'lienjudgmentdollartotal__ln',
 'bankruptcycount__ln',
 'bankruptcycount24month__ln',
 'bankruptcytimenewest__ln',
 'bankruptcychapter__ln',
 'bankruptcystatus__ln',
 'bankruptcydismissed24month__ln',
 'shorttermloanrequest__ln',
 'shorttermloanrequest12month__ln',
 'shorttermloanrequest24month__ln',
 'inquiryauto12month__ln',
 'inquirybanking12month__ln',
 'inquirytelcom12month__ln',
 'inquirynonshortterm12month__ln',
 'inquiryshortterm12month__ln',
 'inquirycollections12month__ln',
 'ssnsubjectcount__ln',
 'ssndeceased__ln',
 'ssndatelowissued__ln',
 'ssnproblems__ln',
 'addronfilecount__ln',
 'addronfilecorrectional__ln',
 'addronfilecollege__ln',
 'addronfilehighrisk__ln',
 'addrinputtimeoldest__ln',
 'addrinputtimenewest__ln',
 'addrinputlengthofres__ln',
 'addrinputsubjectcount__ln',
 'addrinputmatchindex__ln',
 'addrinputsubjectowned__ln',
 'addrinputdeedmailing__ln',
 'addrinputownershipindex__ln',
 'addrinputphoneservice__ln',
 'addrinputphonecount__ln',
 'addrinputdwelltype__ln',
 'addrinputdwelltypeindex__ln',
 'addrinputdelivery__ln',
 'addrinputtimelastsale__ln',
 'addrinputlastsaleprice__ln',
 'addrinputtaxvalue__ln',
 'addrinputtaxyr__ln',
 'addrinputtaxmarketvalue__ln',
 'addrinputavmvalue__ln',
 'addrinputavmvalue12month__ln',
 'addrinputavmratio12monthprior__ln',
 'addrinputavmvalue60month__ln',
 'addrinputavmratio60monthprior__ln',
 'addrinputcountyratio__ln',
 'addrinputtractratio__ln',
 'addrinputblockratio__ln',
 'addrinputproblems__ln',
 'addrcurrenttimeoldest__ln',
 'addrcurrenttimenewest__ln',
 'addrcurrentlengthofres__ln',
 'addrcurrentsubjectowned__ln',
 'addrcurrentdeedmailing__ln',
 'addrcurrentownershipindex__ln',
 'addrcurrentphoneservice__ln',
 'addrcurrentdwelltype__ln',
 'addrcurrentdwelltypeindex__ln',
 'addrcurrenttimelastsale__ln',
 'addrcurrentlastsalesprice__ln',
 'addrcurrenttaxvalue__ln',
 'addrcurrenttaxyr__ln',
 'addrcurrenttaxmarketvalue__ln',
 'addrcurrentavmvalue__ln',
 'addrcurrentavmvalue12month__ln',
 'addrcurrentavmratio12monthprior__ln',
 'addrcurrentavmvalue60month__ln',
 'addrcurrentavmratio60monthprior__ln',
 'addrcurrentcountyratio__ln',
 'addrcurrenttractratio__ln',
 'addrcurrentblockratio__ln',
 'addrcurrentcorrectional__ln',
 'addrprevioustimeoldest__ln',
 'addrprevioustimenewest__ln',
 'addrpreviouslengthofres__ln',
 'addrprevioussubjectowned__ln',
 'addrpreviousownershipindex__ln',
 'addrpreviousdwelltype__ln',
 'addrpreviousdwelltypeindex__ln',
 'addrpreviouscorrectional__ln',
 'addrstabilityindex__ln',
 'addrchangecount03month__ln',
 'addrchangecount06month__ln',
 'addrchangecount12month__ln',
 'addrchangecount24month__ln',
 'addrchangecount60month__ln',
 'addrlastmovetaxratiodiff__ln',
 'addrlastmoveecontrajectory__ln',
 'addrlastmoveecontrajectoryindex__ln',
 'phoneinputproblems__ln',
 'phoneinputsubjectcount__ln',
 'phoneinputmobile__ln',
 'alertregulatorycondition__ln',
 'at01s__tu',
 'at02s__tu',
 'at03s__tu',
 'at06s__tu',
 'at09s__tu',
 'at12s__tu',
 'at20s__tu',
 'at21s__tu',
 'at24s__tu',
 'at25s__tu',
 'at27s__tu',
 'at28a__tu',
 'at28b__tu',
 'at29s__tu',
 'at30s__tu',
 'at31s__tu',
 'at32s__tu',
 'at33a__tu',
 'at33b__tu',
 'at34a__tu',
 'at34b__tu',
 'at35a__tu',
 'at35b__tu',
 'at36s__tu',
 'at57s__tu',
 'at101s__tu',
 'at101b__tu',
 'at103s__tu',
 'at104s__tu',
 'au01s__tu',
 'au02s__tu',
 'au03s__tu',
 'au06s__tu',
 'au09s__tu',
 'au12s__tu',
 'au20s__tu',
 'au21s__tu',
 'au24s__tu',
 'au25s__tu',
 'au27s__tu',
 'au28s__tu',
 'au29s__tu',
 'au30s__tu',
 'au31s__tu',
 'au32s__tu',
 'au33s__tu',
 'au34s__tu',
 'au35s__tu',
 'au36s__tu',
 'au51a__tu',
 'au57s__tu',
 'au101s__tu',
 'bc01s__tu',
 'bc02s__tu',
 'bc03s__tu',
 'bc06s__tu',
 'bc09s__tu',
 'bc12s__tu',
 'bc20s__tu',
 'bc21s__tu',
 'bc24s__tu',
 'bc25s__tu',
 'bc27s__tu',
 'bc28s__tu',
 'bc29s__tu',
 'bc30s__tu',
 'bc31s__tu',
 'bc32s__tu',
 'bc33s__tu',
 'bc34s__tu',
 'bc35s__tu',
 'bc36s__tu',
 'bc57s__tu',
 'bc97a__tu',
 'bc97b__tu',
 'bc98a__tu',
 'bc101s__tu',
 'bc102s__tu',
 'bc103s__tu',
 'bc104s__tu',
 'bc106s__tu',
 'bc107s__tu',
 'bc108s__tu',
 'bc109s__tu',
 'bc110s__tu',
 'bi01s__tu',
 'bi02s__tu',
 'bi03s__tu',
 'bi06s__tu',
 'bi09s__tu',
 'bi12s__tu',
 'bi20s__tu',
 'bi21s__tu',
 'bi24s__tu',
 'bi25s__tu',
 'bi27s__tu',
 'bi28s__tu',
 'bi29s__tu',
 'bi30s__tu',
 'bi31s__tu',
 'bi32s__tu',
 'bi33s__tu',
 'bi34s__tu',
 'bi35s__tu',
 'bi36s__tu',
 'bi57s__tu',
 'bi101s__tu',
 'br01s__tu',
 'br02s__tu',
 'br03s__tu',
 'br06s__tu',
 'br09s__tu',
 'br12s__tu',
 'br20s__tu',
 'br21s__tu',
 'br24s__tu',
 'br25s__tu',
 'br27s__tu',
 'br28s__tu',
 'br29s__tu',
 'br30s__tu',
 'br31s__tu',
 'br32s__tu',
 'br33s__tu',
 'br34s__tu',
 'br35s__tu',
 'br36s__tu',
 'br57s__tu',
 'br101s__tu',
 'br109s__tu',
 'co01s__tu',
 'co02s__tu',
 'co03s__tu',
 'co04s__tu',
 'co05s__tu',
 'co06s__tu',
 'co07s__tu',
 'fc01s__tu',
 'fc02s__tu',
 'fc03s__tu',
 'fc04s__tu',
 'fc05s__tu',
 'fc06s__tu',
 'fc07s__tu',
 'fi01s__tu',
 'fi02s__tu',
 'fi03s__tu',
 'fi06s__tu',
 'fi09s__tu',
 'fi12s__tu',
 'fi20s__tu',
 'fi21s__tu',
 'fi24s__tu',
 'fi25s__tu',
 'fi27s__tu',
 'fi28s__tu',
 'fi29s__tu',
 'fi30s__tu',
 'fi31s__tu',
 'fi32s__tu',
 'fi33s__tu',
 'fi34s__tu',
 'fi35s__tu',
 'fi36s__tu',
 'fi57s__tu',
 'fi101s__tu',
 'fr01s__tu',
 'fr02s__tu',
 'fr03s__tu',
 'fr06s__tu',
 'fr09s__tu',
 'fr12s__tu',
 'fr20s__tu',
 'fr21s__tu',
 'fr24s__tu',
 'fr25s__tu',
 'fr27s__tu',
 'fr28s__tu',
 'fr29s__tu',
 'fr30s__tu',
 'fr31s__tu',
 'fr32s__tu',
 'fr33s__tu',
 'fr34s__tu',
 'fr35s__tu',
 'fr36s__tu',
 'fr57s__tu',
 'fr101s__tu',
 'g001s__tu',
 'g001b__tu',
 'g001c__tu',
 'g002s__tu',
 'g002b__tu',
 'g002c__tu',
 'g003s__tu',
 'g003c__tu',
 'g020s__tu',
 'g041s__tu',
 'g041c__tu',
 'g042s__tu',
 'g042c__tu',
 'g043s__tu',
 'g043c__tu',
 'g051s__tu',
 'g057s__tu',
 'g058s__tu',
 'g059s__tu',
 'g061s__tu',
 'g063s__tu',
 'g064s__tu',
 'g066s__tu',
 'g068s__tu',
 'g069s__tu',
 'g071s__tu',
 'g093s__tu',
 'g094s__tu',
 'g095s__tu',
 'g099s__tu',
 'g100s__tu',
 'g102s__tu',
 'g105s__tu',
 'g199s__tu',
 'g200s__tu',
 'g201a__tu',
 'g201b__tu',
 'g202a__tu',
 'g202b__tu',
 'g205s__tu',
 'g206s__tu',
 'g207s__tu',
 'g208s__tu',
 'g209s__tu',
 'g210s__tu',
 'g211s__tu',
 'g212s__tu',
 'g213a__tu',
 'g213b__tu',
 'g215a__tu',
 'g215b__tu',
 'g216s__tu',
 'g217s__tu',
 'g218a__tu',
 'g218b__tu',
 'g218c__tu',
 'g218d__tu',
 'g219a__tu',
 'g219b__tu',
 'g219c__tu',
 'g219d__tu',
 'g220a__tu',
 'g220b__tu',
 'g220c__tu',
 'g220d__tu',
 'g221a__tu',
 'g221b__tu',
 'g221c__tu',
 'g221d__tu',
 'g222s__tu',
 'g223s__tu',
 'g224a__tu',
 'g224b__tu',
 'g224c__tu',
 'g225s__tu',
 'g226s__tu',
 'g227s__tu',
 'g228s__tu',
 'g230s__tu',
 'g232s__tu',
 'g234s__tu',
 'g235s__tu',
 'g237s__tu',
 'g238s__tu',
 'g240s__tu',
 'g241s__tu',
 'g250a__tu',
 'g250b__tu',
 'g250c__tu',
 'g251a__tu',
 'g251b__tu',
 'g251c__tu',
 'g300s__tu',
 'g301s__tu',
 'g302s__tu',
 'g303s__tu',
 'g304s__tu',
 'g305s__tu',
 'g306s__tu',
 'g307s__tu',
 'g308s__tu',
 'g309s__tu',
 'g310s__tu',
 'g311s__tu',
 'g312s__tu',
 'g313s__tu',
 'g314s__tu',
 'g315s__tu',
 'g960s__tu',
 'g980s__tu',
 'g990s__tu',
 'hi01s__tu',
 'hi02s__tu',
 'hi03s__tu',
 'hi06s__tu',
 'hi09s__tu',
 'hi12s__tu',
 'hi20s__tu',
 'hi21s__tu',
 'hi24s__tu',
 'hi25s__tu',
 'hi27s__tu',
 'hi28s__tu',
 'hi29s__tu',
 'hi30s__tu',
 'hi31s__tu',
 'hi32s__tu',
 'hi33s__tu',
 'hi34s__tu',
 'hi35s__tu',
 'hi36s__tu',
 'hi57s__tu',
 'hi101s__tu',
 'hr01s__tu',
 'hr02s__tu',
 'hr03s__tu',
 'hr06s__tu',
 'hr09s__tu',
 'hr12s__tu',
 'hr20s__tu',
 'hr21s__tu',
 'hr24s__tu',
 'hr25s__tu',
 'hr27s__tu',
 'hr28s__tu',
 'hr29s__tu',
 'hr30s__tu',
 'hr31s__tu',
 'hr32s__tu',
 'hr33s__tu',
 'hr34s__tu',
 'hr35s__tu',
 'hr36s__tu',
 'hr57s__tu',
 'hr101s__tu',
 'in01s__tu',
 'in02s__tu',
 'in03s__tu',
 'in06s__tu',
 'in09s__tu',
 'in12s__tu',
 'in20s__tu',
 'in21s__tu',
 'in24s__tu',
 'in25s__tu',
 'in27s__tu',
 'in28s__tu',
 'in29s__tu',
 'in30s__tu',
 'in31s__tu',
 'in32s__tu',
 'in33s__tu',
 'in34s__tu',
 'in35s__tu',
 'in36s__tu',
 'in57s__tu',
 'in101s__tu',
 'lm01s__tu',
 'lm02s__tu',
 'lm03s__tu',
 'lm04s__tu',
 'lm05s__tu',
 'lm06s__tu',
 'lm07s__tu',
 'lm08s__tu',
 'lm09s__tu',
 'lm10s__tu',
 'lm11s__tu',
 'lm12s__tu',
 'lm13s__tu',
 'lm14s__tu',
 'lm15s__tu',
 'lm16s__tu',
 'lm17s__tu',
 'lm18s__tu',
 'lm19s__tu',
 'lm20s__tu',
 'lm21s__tu',
 'lm22s__tu',
 'lm23s__tu',
 'lm24s__tu',
 'lm25s__tu',
 'lm26s__tu',
 'lm27s__tu',
 'lm28s__tu',
 'lm29s__tu',
 'lm30s__tu',
 'lm31s__tu',
 'lm32s__tu',
 'lm33s__tu',
 'lm34s__tu',
 'lm35s__tu',
 'lm36s__tu',
 'lm37s__tu',
 'lm38s__tu',
 'lm39s__tu',
 'mt01s__tu',
 'mt02s__tu',
 'mt03s__tu',
 'mt06s__tu',
 'mt09s__tu',
 'mt12s__tu',
 'mt20s__tu',
 'mt21s__tu',
 'mt24s__tu',
 'mt25s__tu',
 'mt27s__tu',
 'mt28s__tu',
 'mt29s__tu',
 'mt30s__tu',
 'mt31s__tu',
 'mt32s__tu',
 'mt33s__tu',
 'mt34s__tu',
 'mt34b__tu',
 'mt34c__tu',
 'mt35s__tu',
 'mt36s__tu',
 'mt47s__tu',
 'mt57s__tu',
 'mt101s__tu',
 'md02s__tu',
 'md33s__tu',
 'md106s__tu',
 'of01s__tu',
 'of02s__tu',
 'of03s__tu',
 'of06s__tu',
 'of09s__tu',
 'of12s__tu',
 'of20s__tu',
 'of21s__tu',
 'of24s__tu',
 'of25s__tu',
 'of27s__tu',
 'of28s__tu',
 'of29s__tu',
 'of30s__tu',
 'of31s__tu',
 'of32s__tu',
 'of33s__tu',
 'of34s__tu',
 'of35s__tu',
 'of36s__tu',
 'of57s__tu',
 'of101s__tu',
 'pb01s__tu',
 'pb02s__tu',
 'pb03s__tu',
 'pb06s__tu',
 'pb09s__tu',
 'pb12s__tu',
 'pb20s__tu',
 'pb21s__tu',
 'pb24s__tu',
 'pb25s__tu',
 'pb27s__tu',
 'pb28s__tu',
 'pb29s__tu',
 'pb30s__tu',
 'pb31s__tu',
 'pb32s__tu',
 'pb33s__tu',
 'pb34s__tu',
 'pb35s__tu',
 'pb36s__tu',
 'pb57s__tu',
 'pb101s__tu',
 're01s__tu',
 're02s__tu',
 're03s__tu',
 're06s__tu',
 're09s__tu',
 're12s__tu',
 're20s__tu',
 're21s__tu',
 're24s__tu',
 're25s__tu',
 're27s__tu',
 're28s__tu',
 're29s__tu',
 're30s__tu',
 're31s__tu',
 're32s__tu',
 're33s__tu',
 're34s__tu',
 're35s__tu',
 're36s__tu',
 're57s__tu',
 're101s__tu',
 're102s__tu',
 'rp01s__tu',
 'rp02s__tu',
 'rp03s__tu',
 'rp04s__tu',
 'rp05s__tu',
 'rp06s__tu',
 'rp07s__tu',
 'rp08s__tu',
 'rt01s__tu',
 'rt02s__tu',
 'rt03s__tu',
 'rt06s__tu',
 'rt09s__tu',
 'rt12s__tu',
 'rt20s__tu',
 'rt21s__tu',
 'rt24s__tu',
 'rt25s__tu',
 'rt27s__tu',
 'rt28s__tu',
 'rt29s__tu',
 'rt30s__tu',
 'rt31s__tu',
 'rt32s__tu',
 'rt33s__tu',
 'rt34s__tu',
 'rt35s__tu',
 'rt36s__tu',
 'rt57s__tu',
 'rt101s__tu',
 'rt201s__tu',
 's004s__tu',
 's043s__tu',
 's061s__tu',
 's062s__tu',
 's064a__tu',
 's064b__tu',
 's068a__tu',
 's068b__tu',
 's071a__tu',
 's071b__tu',
 's073a__tu',
 's073b__tu',
 's114s__tu',
 'st01s__tu',
 'st02s__tu',
 'st03s__tu',
 'st05s__tu',
 'st06s__tu',
 'st09s__tu',
 'st12s__tu',
 'st20s__tu',
 'st21s__tu',
 'st24s__tu',
 'st25s__tu',
 'st27s__tu',
 'st28s__tu',
 'st29s__tu',
 'st30s__tu',
 'st31s__tu',
 'st32s__tu',
 'st33s__tu',
 'st34s__tu',
 'st35s__tu',
 'st36s__tu',
 'st45s__tu',
 'st50s__tu',
 'st57s__tu',
 'st60s__tu',
 'st99s__tu',
 'st101s__tu',
 'atap01__tu',
 'hiap01__tu',
 'hrap01__tu',
 'inap01__tu',
 'mtap01__tu',
 'reap01__tu',
 's063s__tu',
 's063a__tu',
 's208s__tu',
 's207s__tu',
 's207a__tu',
 'g106s__tu',
 'g099a__tu',
 's209s__tu',
 's209a__tu',
 's204s__tu',
 's204a__tu',
 'g242s__tu',
 'g242f__tu',
 'g243f__tu',
 'g244f__tu',
 'g242b__tu',
 'g243b__tu',
 'g244b__tu',
 'st102s__tu',
 'st103s__tu',
 'at01a__tu',
 'us01s__tu',
 'us02s__tu',
 'us03s__tu',
 'us06s__tu',
 'us09s__tu',
 'us12s__tu',
 'us20s__tu',
 'us21s__tu',
 'us24s__tu',
 'us25s__tu',
 'us27s__tu',
 'us28s__tu',
 'us29s__tu',
 'us30s__tu',
 'us31s__tu',
 'us32s__tu',
 'us33s__tu',
 'us34s__tu',
 'us35s__tu',
 'us36s__tu',
 'us57s__tu',
 'us101s__tu',
 'se01s__tu',
 'se02s__tu',
 'se03s__tu',
 'se06s__tu',
 'se09s__tu',
 'se12s__tu',
 'se20s__tu',
 'se21s__tu',
 'se24s__tu',
 'se25s__tu',
 'se27s__tu',
 'se28s__tu',
 'se29s__tu',
 'se30s__tu',
 'se31s__tu',
 'se32s__tu',
 'se33s__tu',
 'se34s__tu',
 'se35s__tu',
 'se36s__tu',
 'se57s__tu',
 'se101s__tu',
 'jt01s__tu',
 'jt02s__tu',
 'jt03s__tu',
 'jt20s__tu',
 'jt21s__tu',
 'jt28s__tu',
 'jt33s__tu',
 'jt34s__tu',
 'jt40s__tu',
 'jt41s__tu',
 'jt42s__tu',
 'jt44s__tu',
 'jt51s__tu',
 'jt53s__tu',
 'jt70s__tu',
 'jt75s__tu',
 'jt80s__tu',
 'au200s__tu',
 'au201s__tu',
 'au202s__tu',
 'au203s__tu',
 'au204s__tu',
 'au205s__tu',
 'au206s__tu',
 'au207s__tu',
 'g400s__tu',
 'g401s__tu',
 'g402s__tu',
 'g403s__tu',
 'g404s__tu',
 'g405s__tu',
 'g406s__tu',
 'g407s__tu',
 'g408s__tu',
 'g409s__tu',
 'g410s__tu',
 'g411s__tu',
 'g412s__tu',
 'g413s__tu',
 'g414s__tu',
 'g415s__tu',
 'g416s__tu',
 'g417s__tu',
 'g418s__tu',
 'us51a__tu',
 'hrap02__tu',
 'reap02__tu',
 'g199b__tu',
 'g200b__tu',
 'g205b__tu',
 'g206b__tu',
 'g207b__tu',
 'g208b__tu',
 'rvlr61__tu',
 'rvlr62__tu',
 'rvlr63__tu',
 'rvlr64__tu',
 'rvlr65__tu',
 'rvlr66__tu',
 'rvlr70__tu',
 'rvlr71__tu',
 'rvlr72__tu',
 'rvlr73__tu',
 'rvlr74__tu',
 'rvlr75__tu',
 'rvlr76__tu',
 'rvlr77__tu',
 'rvlr78__tu',
 'rvlr79__tu',
 'rvlr80__tu',
 'rvlr81__tu',
 'rets101__tu',
 'rets102__tu',
 'rets103__tu',
 'rets104__tu',
 'rets105__tu',
 'rets106__tu',
 'rets107__tu',
 'rets108__tu',
 'rets109__tu',
 'rets110__tu',
 'rets111__tu',
 'rets112__tu',
 'rets113__tu',
 'rets114__tu',
 'rets115__tu',
 'rets116__tu',
 'rets117__tu',
 'rets118__tu',
 'rets119__tu',
 ...]

In [20]:
list_tu = [col for col in X_raw.columns if '__tu' in col.lower()]
X_raw[list_tu]

,at01s__tu,at02s__tu,at03s__tu,at06s__tu,at09s__tu,at12s__tu,at20s__tu,at21s__tu,at24s__tu,at25s__tu,...,us934c__tu,us934d__tu,us934s__tu,us935b__tu,us935c__tu,us935d__tu,us935s__tu,score_bankcard__tu,score_cvpropensity__tu,finscore__tu
5714239__7176826__20210720,3,1,1,1,2,1,112,2,-6,-6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5711466__7173427__20210717,5,0,-3,0,0,-3,122,62,-3,-3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5702106__7162085__20210707,2,0,-3,0,0,-3,189,181,-3,-3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5708876__7170291__20210714,13,1,1,0,0,1,48,32,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5708693__7170066__20210714,3,2,2,0,2,2,136,14,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5716645__7179744__20210723,8,0,-3,0,2,-3,79,8,-3,-3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5706152__7166995__20210712,11,0,-3,0,0,-3,223,56,-3,-3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5713490__7175919__20210720,7,1,1,2,4,1,74,4,-6,-6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5713619__7176075__20210720,26,0,-3,0,2,-3,150,17,-3,-3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5713619__7176076__20210720,3,0,-3,0,0,-3,115,34,-3,-3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
list_ln = [col for col in X_raw.columns if '__ln' in col.lower()]
X_raw[list_ln]

,uniqueid__ln,biglnriskviewattributesv5id__ln,bigaccountid__ln,bigdebtorid__ln,biglnriskviewscoreid__ln,bitinvalid__ln,dtmstampcreation__ln,attribute_index__ln,inputprovidedfirstname__ln,inputprovidedlastname__ln,...,alert2__ln,alert3__ln,alert4__ln,alert5__ln,alert6__ln,alert7__ln,alert8__ln,alert9__ln,alert10__ln,intscore__ln
5714239__7176826__20210720,"5714239,7176826",0,5714239,7176826,0,False,2021-07-20T17:06:40,NaN,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5711466__7173427__20210717,"5711466,7173427",0,5711466,7173427,0,False,2021-07-17T11:00:51,NaN,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5702106__7162085__20210707,"5702106,7162085",0,5702106,7162085,0,False,2021-07-07T12:17:57,NaN,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5708876__7170291__20210714,"5708876,7170291",0,5708876,7170291,0,False,2021-07-14T17:50:30,NaN,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5708693__7170066__20210714,"5708693,7170066",0,5708693,7170066,0,False,2021-07-14T15:56:05,NaN,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5716645__7179744__20210723,"5716645,7179744",0,5716645,7179744,0,False,2021-07-23T11:42:57,NaN,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5706152__7166995__20210712,"5706152,7166995",0,5706152,7166995,0,False,2021-07-12T09:24:55,NaN,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5713490__7175919__20210720,"5713490,7175919",0,5713490,7175919,0,False,2021-07-20T08:34:21,NaN,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5713619__7176075__20210720,"5713619,7176075",0,5713619,7176075,0,False,2021-07-20T10:22:42,NaN,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5713619__7176076__20210720,"5713619,7176076",0,5713619,7176076,0,False,2021-07-20T10:22:44,NaN,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN