In [1]:
import os
import pandas as pd
import numpy as np
import pprint

## PD NOLEAKS PRE

#### Train noleaks pre

In [2]:
%%time

# import
str_filename = 'df_train_noleaks_pre.gzip'
str_uri = f's3://20231010-gen-xii/02_pricing_pd/02_model/00_preprocessing/02_make_dfs/{str_filename}'
# read from s3
df = pd.read_parquet(str_uri)
# replace
df.replace(['NaN','nan'], np.nan, inplace=True)

# show
df

CPU times: user 3.66 s, sys: 2.15 s, total: 5.81 s
Wall time: 13.8 s

,linkf060__tu,linkf045__tu,linkf185__tu,linkf105__tu,linkf193__tu,linkf195__tu,linkf032__tu,linkf212__tu,linkf076__tu,linkf084__tu,...,data_set,year,factor,ENG-applicationdate__app_month,ENG-applicationdate__app_quarter,ENG-payment_to_income,ENG-loan_to_value,ENG-vehicle_age,ENG-dealership_age,target
0,0.0,0.0,152.0,40.0,40.0,1141.0,n,0.000000,0.0,1.0,...,train,2013,1.256262,10,4,0.09,1.370370,4.0,1.284932,1
1,0.0,0.0,152.0,40.0,40.0,1141.0,n,0.000000,0.0,1.0,...,train,2013,1.256262,10,4,0.09,1.370370,4.0,1.284932,1
2,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,0.0,0.0,...,train,2013,1.256262,10,4,0.15,1.586207,2.0,1.569863,1
3,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,0.0,0.0,...,train,2013,1.256262,10,4,0.15,1.586207,2.0,1.569863,1
4,0.0,0.0,5.0,5.0,5.0,1802.0,n,806.645757,0.0,1.0,...,train,2013,1.256262,10,4,0.03,1.342857,1.0,3.961644,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74584,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,0.0,0.0,...,train,2016,0.000000,3,1,0.15,1.607143,3.0,8.498630,1
74585,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,0.0,0.0,...,train,2016,0.000000,3,1,0.15,1.607143,1.0,3.890411,0
74586,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,0.0,0.0,...,train,2016,0.000000,3,1,0.15,1.607143,1.0,3.890411,0
74587,0.0,0.0,1912.0,1613.0,1912.0,1948.0,n,0.000000,0.0,0.0,...,train,2016,0.000000,3,1,0.15,1.607143,5.0,4.030137,0
74588,0.0,0.0,1948.0,1948.0,1948.0,1948.0,n,0.000000,0.0,0.0,...,train,2016,0.000000,3,1,0.15,1.607143,3.0,4.049315,1

In [3]:
list_cols_check = [
'ENG-payment_to_income'
,'payment__app'
,'fltgrossmonthly__income_sum'
,'amtfinanced__app'
,'bookvalue__app'
,'ENG-loan_to_value'
,'ENG-vehicle_age'
,'vehicleyear__app'
,'ENG-dealership_age'
#,'dealerstampcreation__app'
,'intterm__app'
#,'ENG-applicationdate__app_month'
#,'ENG-applicationdate__app_quarter'
]

In [4]:
def check_no_variance(df, columns):
    result = {}
    for col in columns:
        variance = df[col].var()
        has_variance = variance != 0
        result[col] = not has_variance
    return result

In [5]:
result = check_no_variance(df, list_cols_check)
print(result)

{'ENG-payment_to_income': False, 'payment__app': False, 'fltgrossmonthly__income_sum': False, 'amtfinanced__app': False, 'bookvalue__app': False, 'ENG-loan_to_value': False, 'ENG-vehicle_age': False, 'vehicleyear__app': False, 'ENG-dealership_age': False, 'intterm__app': False}

#### Valid

In [6]:
%%time

# import
str_filename = 'df_valid_noleaks_pre.gzip'
str_uri = f's3://20231010-gen-xii/02_pricing_pd/02_model/00_preprocessing/02_make_dfs/{str_filename}'
# read from s3
df = pd.read_parquet(str_uri)
# replace
df.replace(['NaN','nan'], np.nan, inplace=True)

# show
df

CPU times: user 1.11 s, sys: 758 ms, total: 1.86 s
Wall time: 1.43 s

,linkf060__tu,linkf045__tu,linkf185__tu,linkf105__tu,linkf193__tu,linkf195__tu,linkf032__tu,linkf212__tu,linkf076__tu,linkf084__tu,...,data_set,year,factor,ENG-applicationdate__app_month,ENG-applicationdate__app_quarter,ENG-payment_to_income,ENG-loan_to_value,ENG-vehicle_age,ENG-dealership_age,target
74589,0.0,0.0,0.0,0.0,0.0,0.0,y,0.0,0.0,0.0,...,valid,2016,0.0,3,1,0.15,1.607143,4.0,1.709589,0
74590,0.0,0.0,362.0,362.0,362.0,1381.0,n,0.0,0.0,0.0,...,valid,2016,0.0,3,1,0.15,1.607143,1.0,3.893151,0
74591,0.0,0.0,362.0,362.0,362.0,1381.0,n,0.0,0.0,0.0,...,valid,2016,0.0,3,1,0.15,1.607143,1.0,3.893151,0
74592,0.0,0.0,1.0,1.0,1.0,287.0,n,0.0,0.0,1.0,...,valid,2016,0.0,3,1,0.15,1.607143,4.0,1.419178,1
74593,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,...,valid,2016,0.0,3,1,0.15,1.607143,4.0,9.090411,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99447,0.0,0.0,114.0,80.0,80.0,2488.0,n,0.0,0.0,0.0,...,valid,2016,0.0,11,4,0.15,1.607143,2.0,4.723288,0
99448,0.0,0.0,243.0,167.0,167.0,362.0,n,0.0,0.0,0.0,...,valid,2016,0.0,11,4,0.15,1.607143,1.0,4.046575,1
99449,0.0,0.0,503.0,503.0,503.0,2176.0,n,0.0,0.0,0.0,...,valid,2016,0.0,11,4,0.15,1.607143,1.0,4.046575,0
99450,0.0,0.0,503.0,503.0,503.0,2176.0,n,0.0,0.0,0.0,...,valid,2016,0.0,11,4,0.15,1.607143,1.0,4.046575,0
99451,0.0,0.0,67.0,67.0,67.0,652.0,n,0.0,0.0,0.0,...,valid,2016,0.0,11,4,0.15,1.607143,-1.0,0.753425,1

In [7]:
result = check_no_variance(df, list_cols_check)
print(result)

{'ENG-payment_to_income': False, 'payment__app': True, 'fltgrossmonthly__income_sum': True, 'amtfinanced__app': True, 'bookvalue__app': True, 'ENG-loan_to_value': False, 'ENG-vehicle_age': False, 'vehicleyear__app': False, 'ENG-dealership_age': False, 'intterm__app': False}

In [8]:
df['ENG-loan_to_value'].min()

1.6071428571428572

In [9]:
df['ENG-loan_to_value'].max()

1.6071428571428572

In [10]:
df['uniqueid'].value_counts()

uniqueid
2.668568e+14    2
2.575336e+14    2
2.810506e+14    2
2.575573e+14    2
2.810524e+14    2
               ..
2.637770e+14    1
2.637788e+14    1
2.637803e+14    1
2.637818e+14    1
2.867541e+14    1
Name: count, Length: 20314, dtype: int64

#### Test

In [11]:
%%time

# import
str_filename = 'df_test_noleaks_pre.gzip'
str_uri = f's3://20231010-gen-xii/02_pricing_pd/02_model/00_preprocessing/02_make_dfs/{str_filename}'
# read from s3
df = pd.read_parquet(str_uri)
# replace
df.replace(['NaN','nan'], np.nan, inplace=True)

# show
df

CPU times: user 1.14 s, sys: 748 ms, total: 1.89 s
Wall time: 2.39 s

,linkf060__tu,linkf045__tu,linkf185__tu,linkf105__tu,linkf193__tu,linkf195__tu,linkf032__tu,linkf212__tu,linkf076__tu,linkf084__tu,...,data_set,year,factor,ENG-applicationdate__app_month,ENG-applicationdate__app_quarter,ENG-payment_to_income,ENG-loan_to_value,ENG-vehicle_age,ENG-dealership_age,target
99452,0.0,0.0,67.0,67.0,67.0,652.0,n,0.000000,0.0,0.0,...,test,2016,0.000000,11,4,0.15,1.607143,-1.0,0.753425,1
99453,0.0,0.0,1193.0,1193.0,1193.0,1193.0,n,0.000000,0.0,0.0,...,test,2016,0.000000,11,4,0.15,1.607143,1.0,5.608219,0
99454,0.0,0.0,13.0,13.0,13.0,123.0,n,0.000000,0.0,6.0,...,test,2016,0.000000,11,4,0.15,1.607143,4.0,8.849315,1
99455,0.0,0.0,39.0,11.0,11.0,798.0,n,0.000000,0.0,2.0,...,test,2016,0.000000,11,4,0.15,1.607143,3.0,7.443836,1
99456,0.0,0.0,66.0,66.0,66.0,686.0,n,0.000000,0.0,0.0,...,test,2016,0.000000,11,4,0.15,1.607143,3.0,4.860274,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124312,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,0.0,0.0,...,test,2017,1.193925,10,4,0.09,1.016667,-1.0,7.249315,0
124311,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,0.0,0.0,...,test,2017,1.193925,10,4,0.09,1.016667,-1.0,7.249315,0
124313,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,0.0,0.0,...,test,2017,1.193925,10,4,0.06,1.500000,2.0,4.263014,0
124314,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.000000,0.0,0.0,...,test,2017,1.193925,10,4,0.15,1.366667,1.0,11.139726,1
124315,0.0,0.0,994.0,665.0,994.0,1722.0,n,196.997695,0.0,0.0,...,test,2017,1.193925,10,4,0.06,1.333333,2.0,10.504110,1

In [12]:
result = check_no_variance(df, list_cols_check)
print(result)

{'ENG-payment_to_income': False, 'payment__app': False, 'fltgrossmonthly__income_sum': False, 'amtfinanced__app': False, 'bookvalue__app': False, 'ENG-loan_to_value': False, 'ENG-vehicle_age': False, 'vehicleyear__app': False, 'ENG-dealership_age': False, 'intterm__app': False}

In [13]:
del df

## AD NO LEAKS NO PRE

#### Train

In [14]:
%%time

# import
str_filename = 'df_train_noleaks.gzip'
str_uri = f's3://20231010-gen-xii/01_ad/01_data_prep/05_leaky_features/04_write_dfs/{str_filename}'
# read from s3
df = pd.read_parquet(str_uri)
# replace
df.replace(['NaN','nan'], np.nan, inplace=True)

# show
df

CPU times: user 57.2 s, sys: 32 s, total: 1min 29s
Wall time: 2min 2s

,inttype__app,linkf060__tu,linkf045__tu,linkf079__tu,linkf185__tu,linkf195__tu,linkf193__tu,linkf105__tu,linkb012__tu,linkf032__tu,...,fltdowncash__app,fltallowance__app,bitdealerapplicantsamezip__app,bitdealerapplicantsamecity__app,bitdealerapplicantsamestate__app,uniqueid,applicationdate__app,target,year_month,data_set
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,None,...,0.0,0.0,0.0,1.0,1.0,1.337505e+14,2013-10-01,1,2013-10,train
430,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,...,0.0,0.0,0.0,0.0,1.0,1.338208e+14,2013-10-01,0,2013-10,train
431,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,...,0.0,0.0,0.0,0.0,1.0,1.338208e+14,2013-10-01,0,2013-10,train
432,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,None,...,0.0,0.0,0.0,0.0,1.0,1.338211e+14,2013-10-01,0,2013-10,train
433,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,...,0.0,0.0,0.0,1.0,1.0,1.338213e+14,2013-10-01,0,2013-10,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1260313,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,...,0.0,0.0,0.0,0.0,1.0,3.387656e+14,2017-10-21,0,2017-10,train
1260314,NaN,NaN,NaN,NaN,2444.0,2480.0,2444.0,2444.0,NaN,N,...,0.0,0.0,0.0,0.0,1.0,3.387658e+14,2017-10-21,0,2017-10,train
1260315,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,None,...,0.0,0.0,0.0,1.0,1.0,3.387661e+14,2017-10-21,0,2017-10,train
1260316,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,None,...,0.0,0.0,0.0,1.0,1.0,3.387661e+14,2017-10-21,0,2017-10,train
1260317,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,None,...,0.0,0.0,0.0,0.0,0.0,3.387663e+14,2017-10-21,0,2017-10,train

In [15]:
list_cols = [col for col in df.columns if '__app' in col]
list_cols

['inttype__app',
 'fltapprovedloantovalue__app',
 'fltapprovedservicecontract__app',
 'fltservicecontract__app',
 'fltinsuredlifeamount__app',
 'fltgapinsurance__app',
 'fltapprovedpricewholesale__app',
 'fltapproveddowntotal__app',
 'fltapprovedpayment__app',
 'strname__app',
 'fltamountfinanced__app',
 'intservicecontractmileageaddon__app',
 'strdealershiptrackertype__app',
 'dealerstate__app',
 'bigdealertypeid__app',
 'bitdebtor__app',
 'bitmaintenanceagreement__app',
 'bitservicecontract__app',
 'bitrouteone__app',
 'bitdealertrack__app',
 'intterm__app',
 'fltinsureddisabilityamount__app',
 'fltdowncash__app',
 'fltallowance__app',
 'bitdealerapplicantsamezip__app',
 'bitdealerapplicantsamecity__app',
 'bitdealerapplicantsamestate__app',
 'applicationdate__app']

In [16]:
list_cols_check = [
#'ENG-payment_to_income'
'fltapprovedpayment__app'
,'fltgrossmonthly__income_sum'
,'fltamountfinanced__app'
,'fltapprovedpricewholesale__app'
#,'ENG-loan_to_value'
#,'ENG-vehicle_age'
#,'vehicleyear__app'
#,'ENG-dealership_age'
#,'dealerstampcreation__app'
,'intterm__app'
#,'ENG-applicationdate__app_month'
#,'ENG-applicationdate__app_quarter'
]

In [17]:
result = check_no_variance(df, list_cols_check)
print(result)

{'fltapprovedpayment__app': False, 'fltgrossmonthly__income_sum': False, 'fltamountfinanced__app': False, 'fltapprovedpricewholesale__app': False, 'intterm__app': False}

In [18]:
del df

#### Valid no leak no pre

In [19]:
%%time

# import
str_filename = 'df_valid_noleaks.gzip'
str_uri = f's3://20231010-gen-xii/01_ad/01_data_prep/05_leaky_features/04_write_dfs/{str_filename}'
# read from s3
df = pd.read_parquet(str_uri)
# replace
df.replace(['NaN','nan'], np.nan, inplace=True)

# show
df

CPU times: user 19.3 s, sys: 10.3 s, total: 29.6 s
Wall time: 46.2 s

,inttype__app,linkf060__tu,linkf045__tu,linkf079__tu,linkf185__tu,linkf195__tu,linkf193__tu,linkf105__tu,linkb012__tu,linkf032__tu,...,fltdowncash__app,fltallowance__app,bitdealerapplicantsamezip__app,bitdealerapplicantsamecity__app,bitdealerapplicantsamestate__app,uniqueid,applicationdate__app,target,year_month,data_set
1260318,7.0,NaN,NaN,500.0,50.0,2463.0,50.0,50.0,0.0,N,...,0.0,0.0,0.0,0.0,0.0,3.387666e+14,2017-10-21,0,2017-10,valid
1260319,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,...,0.0,0.0,0.0,0.0,1.0,3.387670e+14,2017-10-21,0,2017-10,valid
1260320,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,...,0.0,0.0,0.0,1.0,1.0,3.387672e+14,2017-10-21,0,2017-10,valid
1260321,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,...,0.0,0.0,0.0,0.0,0.0,3.387673e+14,2017-10-21,1,2017-10,valid
1260322,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,...,1525.0,0.0,0.0,0.0,1.0,3.387675e+14,2017-10-21,0,2017-10,valid
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
431587,NaN,NaN,585.0,4190.0,81.0,1265.0,81.0,31.0,0.0,N,...,0.0,0.0,0.0,0.0,1.0,4.128014e+14,2019-02-08,0,2019-02,valid
7838,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,None,...,NaN,NaN,NaN,NaN,NaN,NaN,2019-02-08,0,2019-02,valid
246017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,None,...,0.0,0.0,0.0,1.0,1.0,4.127223e+14,2019-02-08,0,2019-02,valid
246016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,...,0.0,0.0,0.0,0.0,0.0,4.127245e+14,2019-02-08,0,2019-02,valid
246015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,None,...,0.0,0.0,0.0,0.0,1.0,4.127006e+14,2019-02-08,1,2019-02,valid

In [20]:
result = check_no_variance(df, list_cols_check)
print(result)

{'fltapprovedpayment__app': False, 'fltgrossmonthly__income_sum': False, 'fltamountfinanced__app': False, 'fltapprovedpricewholesale__app': False, 'intterm__app': False}

In [21]:
del df

#### Test no leak no pre

In [22]:
%%time

# import
str_filename = 'df_test_noleaks.gzip'
str_uri = f's3://20231010-gen-xii/01_ad/01_data_prep/05_leaky_features/04_write_dfs/{str_filename}'
# read from s3
df = pd.read_parquet(str_uri)
# replace
df.replace(['NaN','nan'], np.nan, inplace=True)

# show
df

CPU times: user 19.7 s, sys: 10.4 s, total: 30.1 s
Wall time: 45.2 s

,inttype__app,linkf060__tu,linkf045__tu,linkf079__tu,linkf185__tu,linkf195__tu,linkf193__tu,linkf105__tu,linkb012__tu,linkf032__tu,...,fltdowncash__app,fltallowance__app,bitdealerapplicantsamezip__app,bitdealerapplicantsamecity__app,bitdealerapplicantsamestate__app,uniqueid,applicationdate__app,target,year_month,data_set
246014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,...,0.0,0.0,0.0,1.0,1.0,4.127949e+14,2019-02-08,0,2019-02,test
246013,NaN,NaN,NaN,0.0,115.0,1330.0,115.0,94.0,NaN,N,...,0.0,0.0,0.0,0.0,1.0,4.127780e+14,2019-02-08,1,2019-02,test
246012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,...,0.0,0.0,0.0,0.0,1.0,4.127566e+14,2019-02-08,1,2019-02,test
246008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,...,0.0,0.0,0.0,0.0,1.0,4.126733e+14,2019-02-08,1,2019-02,test
7965,NaN,NaN,NaN,0.0,137.0,2418.0,137.0,137.0,0.0,N,...,NaN,NaN,NaN,NaN,NaN,NaN,2019-02-08,0,2019-02,test
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61490,NaN,NaN,NaN,875.0,65.0,2319.0,65.0,65.0,NaN,N,...,0.0,0.0,0.0,0.0,1.0,4.812562e+14,2019-12-31,1,2019-12,test
98385,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,...,0.0,0.0,0.0,0.0,1.0,4.812224e+14,2019-12-31,1,2019-12,test
98384,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,None,...,0.0,0.0,0.0,0.0,0.0,4.812529e+14,2019-12-31,1,2019-12,test
413531,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,...,0.0,0.0,0.0,0.0,1.0,4.811927e+14,2019-12-31,0,2019-12,test
10060,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,...,NaN,NaN,NaN,NaN,NaN,NaN,2019-12-31,0,2019-12,test

In [23]:
result = check_no_variance(df, list_cols_check)
print(result)

{'fltapprovedpayment__app': False, 'fltgrossmonthly__income_sum': False, 'fltamountfinanced__app': False, 'fltapprovedpricewholesale__app': False, 'intterm__app': False}

In [24]:
del df

## PD NOLEAKS NO PRE

#### train

In [28]:
list_cols_check = [
#'ENG-payment_to_income'
'payment__app'
,'fltgrossmonthly__income_sum'
,'amtfinanced__app'
,'bookvalue__app'
#,'ENG-loan_to_value'
#,'ENG-vehicle_age'
,'vehicleyear__app'
#,'ENG-dealership_age'
#,'dealerstampcreation__app'
,'intterm__app'
#,'ENG-applicationdate__app_month'
#,'ENG-applicationdate__app_quarter'
]

In [26]:
%%time

# import
str_filename = 'df_train_noleaks.gzip'
str_uri = f's3://20231010-gen-xii/02_pricing_pd/01_data_prep/05_leaky_features/04_write_dfs/{str_filename}'
# read from s3
df = pd.read_parquet(str_uri)
# replace
df.replace(['NaN','nan'], np.nan, inplace=True)

# show
df

CPU times: user 3.61 s, sys: 1.76 s, total: 5.37 s
Wall time: 8.05 s

,linkf060__tu,linkf045__tu,linkf185__tu,linkf105__tu,linkf193__tu,linkf195__tu,linkf032__tu,linkf212__tu,linkf076__tu,linkf084__tu,...,bitdealerapplicantsamezip__app,strdealershiptrackertype__app,fltallowance__app,fltinsureddisabilityamount__app,dealerstampcreation__app,uniqueid,applicationdate__app,target,year_month,data_set
0,0.0,0.0,152.0,40.0,40.0,1141.0,N,0.0,0.0,1.0,...,0.0,Franchise,0.0,0.0,2012-06-18 09:31:54.393,1.337511e+14,2013-10-01 07:28:54.833,1,2013-10,train
1,0.0,0.0,152.0,40.0,40.0,1141.0,N,0.0,0.0,1.0,...,0.0,Franchise,0.0,0.0,2012-06-18 09:31:54.393,1.337511e+14,2013-10-01 07:28:54.833,1,2013-10,train
2,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,...,0.0,Independent,0.0,0.0,2012-03-06 16:36:21.623,1.337528e+14,2013-10-01 08:25:39.117,1,2013-10,train
3,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,...,0.0,Independent,0.0,0.0,2012-03-06 16:36:21.623,1.337528e+14,2013-10-01 08:25:39.117,1,2013-10,train
4,NaN,0.0,5.0,5.0,5.0,1802.0,N,642.1,0.0,1.0,...,0.0,Independent,0.0,0.0,2009-10-15 16:06:40.767,1.337539e+14,2013-10-01 08:39:13.390,1,2013-10,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74584,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,...,0.0,Franchise,0.0,0.0,2007-09-18 17:16:17.027,2.493958e+14,2016-03-17 16:04:47.077,1,2016-03,train
74585,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,...,1.0,Franchise,0.0,0.0,2012-04-26 16:31:49.550,2.493969e+14,2016-03-17 16:07:54.870,0,2016-03,train
74586,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,...,1.0,Franchise,0.0,0.0,2012-04-26 16:31:49.550,2.493969e+14,2016-03-17 16:07:54.870,0,2016-03,train
74587,NaN,NaN,1912.0,1613.0,1912.0,1948.0,N,0.0,0.0,0.0,...,0.0,Independent,0.0,0.0,2012-03-06 16:36:21.623,2.493994e+14,2016-03-17 16:17:35.020,0,2016-03,train
74588,0.0,0.0,1948.0,1948.0,1948.0,1948.0,N,0.0,0.0,0.0,...,0.0,Franchise,0.0,0.0,2012-02-29 10:24:35.673,2.494006e+14,2016-03-17 16:21:03.933,1,2016-03,train

In [29]:
result = check_no_variance(df, list_cols_check)
print(result)

{'payment__app': False, 'fltgrossmonthly__income_sum': False, 'amtfinanced__app': False, 'bookvalue__app': False, 'vehicleyear__app': False, 'intterm__app': False}

#### Valid

In [30]:
%%time

# import
str_filename = 'df_valid_noleaks.gzip'
str_uri = f's3://20231010-gen-xii/02_pricing_pd/01_data_prep/05_leaky_features/04_write_dfs/{str_filename}'
# read from s3
df = pd.read_parquet(str_uri)
# replace
df.replace(['NaN','nan'], np.nan, inplace=True)

# show
df

CPU times: user 1.37 s, sys: 635 ms, total: 2 s
Wall time: 2.57 s

,linkf060__tu,linkf045__tu,linkf185__tu,linkf105__tu,linkf193__tu,linkf195__tu,linkf032__tu,linkf212__tu,linkf076__tu,linkf084__tu,...,bitdealerapplicantsamezip__app,strdealershiptrackertype__app,fltallowance__app,fltinsureddisabilityamount__app,dealerstampcreation__app,uniqueid,applicationdate__app,target,year_month,data_set
74589,NaN,NaN,NaN,NaN,NaN,NaN,Y,0.00,0.0,0.0,...,0.0,Franchise,0.0,0.0,2014-07-02 15:52:35.527,2.494009e+14,2016-03-17 16:21:40.237,0,2016-03,valid
74590,NaN,NaN,362.0,362.0,362.0,1381.0,N,187.20,0.0,0.0,...,0.0,Franchise,0.0,0.0,2012-04-25 16:45:11.587,2.494046e+14,2016-03-17 16:37:56.250,0,2016-03,valid
74591,NaN,NaN,362.0,362.0,362.0,1381.0,N,187.20,0.0,0.0,...,0.0,Franchise,0.0,0.0,2012-04-25 16:45:11.587,2.494046e+14,2016-03-17 16:37:56.250,0,2016-03,valid
74592,0.0,0.0,1.0,1.0,1.0,287.0,N,0.00,0.0,1.0,...,0.0,Franchise,0.0,0.0,2014-10-16 15:31:26.623,2.494095e+14,2016-03-17 16:55:00.627,1,2016-03,valid
74593,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,...,0.0,Franchise,0.0,0.0,2007-02-15 09:05:41.530,2.494180e+14,2016-03-17 17:31:35.613,0,2016-03,valid
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99447,NaN,NaN,114.0,80.0,80.0,2488.0,N,125.00,0.0,0.0,...,0.0,Franchise,0.0,0.0,2012-02-29 10:24:35.673,2.867502e+14,2016-11-18 16:54:20.863,0,2016-11,valid
99448,0.0,0.0,243.0,167.0,167.0,362.0,N,0.00,0.0,0.0,...,0.0,Franchise,0.0,0.0,2012-11-02 16:17:10.707,2.867505e+14,2016-11-18 16:55:44.713,1,2016-11,valid
99449,NaN,NaN,503.0,503.0,503.0,2176.0,N,363.66,0.0,0.0,...,0.0,Franchise,0.0,0.0,2012-11-02 16:17:10.707,2.867509e+14,2016-11-18 16:56:58.190,0,2016-11,valid
99450,NaN,NaN,503.0,503.0,503.0,2176.0,N,363.66,0.0,0.0,...,0.0,Franchise,0.0,0.0,2012-11-02 16:17:10.707,2.867509e+14,2016-11-18 16:56:58.190,0,2016-11,valid
99451,0.0,0.0,67.0,67.0,67.0,652.0,N,0.00,0.0,0.0,...,0.0,Franchise,0.0,0.0,2016-02-17 12:47:19.233,2.867541e+14,2016-11-18 17:12:48.527,1,2016-11,valid

In [31]:
result = check_no_variance(df, list_cols_check)
print(result)

{'payment__app': False, 'fltgrossmonthly__income_sum': False, 'amtfinanced__app': False, 'bookvalue__app': False, 'vehicleyear__app': False, 'intterm__app': False}

#### Test

In [32]:
%%time

# import
str_filename = 'df_test_noleaks.gzip'
str_uri = f's3://20231010-gen-xii/02_pricing_pd/01_data_prep/05_leaky_features/04_write_dfs/{str_filename}'
# read from s3
df = pd.read_parquet(str_uri)
# replace
df.replace(['NaN','nan'], np.nan, inplace=True)

# show
df

CPU times: user 1.42 s, sys: 572 ms, total: 1.99 s
Wall time: 2.27 s

,linkf060__tu,linkf045__tu,linkf185__tu,linkf105__tu,linkf193__tu,linkf195__tu,linkf032__tu,linkf212__tu,linkf076__tu,linkf084__tu,...,bitdealerapplicantsamezip__app,strdealershiptrackertype__app,fltallowance__app,fltinsureddisabilityamount__app,dealerstampcreation__app,uniqueid,applicationdate__app,target,year_month,data_set
99452,0.0,0.0,67.0,67.0,67.0,652.0,N,0.0,0.0,0.0,...,0.0,Franchise,0.0,0.0,2016-02-17 12:47:19.233,2.867541e+14,2016-11-18 17:12:48.527,1,2016-11,test
99453,0.0,0.0,1193.0,1193.0,1193.0,1193.0,N,0.0,0.0,0.0,...,0.0,Franchise,0.0,0.0,2011-04-12 13:36:22.680,2.867543e+14,2016-11-18 17:13:32.410,0,2016-11,test
99454,0.0,0.0,13.0,13.0,13.0,123.0,N,0.0,0.0,6.0,...,0.0,Franchise,0.0,0.0,2008-01-15 08:53:13.480,2.867556e+14,2016-11-18 17:18:24.817,1,2016-11,test
99455,0.0,0.0,39.0,11.0,11.0,798.0,N,0.0,0.0,2.0,...,0.0,Franchise,0.0,0.0,2009-06-11 17:08:59.937,2.867569e+14,2016-11-18 17:24:38.703,1,2016-11,test
99456,NaN,NaN,66.0,66.0,66.0,686.0,N,1163.0,0.0,0.0,...,0.0,Independent,0.0,0.0,2012-01-10 16:05:32.420,2.867589e+14,2016-11-18 17:30:58.610,1,2016-11,test
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124312,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,...,0.0,Franchise,0.0,0.0,2010-07-30 13:50:37.207,3.397156e+14,2017-10-28 08:39:20.483,0,2017-10,test
124311,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,...,0.0,Franchise,0.0,0.0,2010-07-30 13:50:37.207,3.397156e+14,2017-10-28 08:39:20.483,0,2017-10,test
124313,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,...,0.0,Franchise,0.0,0.0,2013-07-24 10:29:42.193,3.397435e+14,2017-10-28 10:07:56.663,0,2017-10,test
124314,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,...,0.0,Franchise,0.0,0.0,2006-09-09 11:59:48.000,3.397518e+14,2017-10-28 10:30:35.503,1,2017-10,test
124315,NaN,NaN,994.0,665.0,994.0,1722.0,N,165.0,0.0,0.0,...,0.0,Franchise,0.0,0.0,2007-04-30 08:49:27.647,3.397773e+14,2017-10-28 11:35:40.970,1,2017-10,test

In [33]:
result = check_no_variance(df, list_cols_check)
print(result)

{'payment__app': False, 'fltgrossmonthly__income_sum': False, 'amtfinanced__app': False, 'bookvalue__app': False, 'vehicleyear__app': False, 'intterm__app': False}

In [ ]:
del df