In [48]:
import pandas as pd
import os
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.exceptions import NotFittedError

# Constants

In [49]:
str_project = os.getcwd().split('\\')[4]
print(f'Project: {str_project}')
str_task = os.getcwd().split('\\')[5]
print(f'Task: {str_task}')
str_subtask = os.getcwd().split('\\')[6]
print(f'Subtask: {str_subtask}')

str_dirname_output = './output'

Project: 06_ml_in_python
Task: 01_home_credit_model
Subtask: 03_preprocessing

In [50]:
os.getcwd()

'M:\\Risk Management\\Bridger Hyde\\20240521_bridger_internship\\06_ml_in_python\\01_home_credit_model\\03_preprocessing'

In [51]:
try:
    os.mkdir(str_dirname_output)
except FileExistsError:
    pass

# Pull In Training Csv

In [75]:
df = pd.read_csv('M:\\Risk Management\\Bridger Hyde\\20240521_bridger_internship\\06_ml_in_python\\01_home_credit_model\\02_exploratory_data_analysis\\output\\training.csv')
df

,rownum,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,FONDKAPREMONT_MODE,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,0,396902,0,Cash loans,F,Y,Y,0,121500,835380,40320.0,675000.0,Unaccompanied,Working,Higher education,Separated,House / apartment,0.035792,-16647,-283,-611.0,-184,10.0,1,1,1,1,0,0,Core staff,1.0,2,2,SUNDAY,11,0,0,0,0,0,0,Restaurant,0.642816,0.606592,0.646330,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-770.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,4.0
1,1,112096,0,Cash loans,F,N,Y,0,202500,516069,26478.0,445500.0,Unaccompanied,Pensioner,Secondary / secondary special,Widow,House / apartment,0.011657,-22237,365243,-34.0,-4878,NaN,1,0,0,1,0,0,NaN,1.0,1,1,WEDNESDAY,10,0,0,0,0,0,0,XNA,NaN,0.172095,0.360613,0.1227,0.1213,0.9762,0.6736,0.1901,0.00,0.2069,0.1667,0.0417,0.0476,0.1000,0.0941,0.0000,0.1375,0.1250,0.1259,0.9762,0.6864,0.1918,0.0000,0.2069,0.1667,0.0417,0.0487,0.1093,0.0981,0.0000,0.1456,0.1239,0.1213,0.9762,0.6780,0.1913,0.00,0.2069,0.1667,0.0417,0.0485,0.1018,0.0958,0.0000,0.1404,reg oper spec account,block of flats,0.1039,"Stone, brick",No,1.0,1.0,1.0,1.0,-1069.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,6.0
2,2,285821,1,Cash loans,M,Y,Y,1,180000,284400,22469.0,225000.0,"Spouse, partner",Working,Secondary / secondary special,Married,House / apartment,0.028663,-11399,-508,-1500.0,-920,16.0,1,1,0,1,0,0,Laborers,3.0,2,2,SUNDAY,11,0,1,1,0,1,1,Construction,0.446722,0.465626,0.106156,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,0.0,7.0,0.0,-933.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
3,3,376901,0,Cash loans,F,N,Y,0,90000,265536,13685.0,180000.0,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.031329,-20074,-221,-1264.0,-3559,NaN,1,1,0,1,0,0,Medicine staff,2.0,2,2,FRIDAY,10,0,0,0,0,0,0,Kindergarten,NaN,0.662464,0.266457,0.1320,0.0460,0.9856,0.8028,0.0375,0.08,0.0345,0.6250,0.6667,0.0116,0.1067,0.1327,0.0039,0.0011,0.1345,0.0478,0.9856,0.8105,0.0378,0.0806,0.0345,0.6250,0.6667,0.0119,0.1166,0.1382,0.0039,0.0011,0.1332,0.0460,0.9856,0.8054,0.0377,0.08,0.0345,0.6250,0.6667,0.0118,0.1086,0.1351,0.0039,0.0011,reg oper account,block of flats,0.1251,Monolithic,No,0.0,0.0,0.0,0.0,-1428.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
4,4,325138,0,Cash loans,F,Y,Y,0,94500,755190,30078.0,675000.0,Unaccompanied,Pensioner,Secondary / secondary special,Single / not married,House / apartment,0.019689,-20691,365243,-2277.0,-703,10.0,1,0,0,1,0,0,NaN,1.0,2,2,THURSDAY,12,0,0,0,0,0,0,XNA,NaN,0.054296,NaN,0.0082,0.0216,0.9722,NaN,NaN,0.00,0.0345,0.0417,NaN,0.0038,NaN,0.0095,NaN,0.0000,0.0084,0.0225,0.9722,NaN,NaN,0.0000,0.0345,0.0417,NaN,0.0039,NaN,0.0099,NaN,0.0000,0.0083,0.0216,0.9722,NaN,NaN,0.00,0.0345,0.0417,NaN,0.0039,NaN,0.0096,NaN,0.0000,NaN,block of flats,0.0074,"Stone, brick",No,0.0,0.0,0.0,0.0,-695.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124995,124995,217133,0,Revolving loans,M,Y,Y,0,54000,157500,7875.0,157500.0,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.019101,-21089,-1412,-10474.0,-3965,17.0,1,1,1,1,1,0,Laborers,2.0,2,2,THURSDAY,12,0,0,0,0,0,0,Business Entity Type 3,NaN,0.626477,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,1.0,0.0,-696.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
124996,124996,169482,0,Cash loans,F,N,N,0,180000,661500,17577.0,661500.0,Unaccompanied,Commercial associate,Secondary / secondary special,Married,House / apartment,0.018209,-14074,-483,-1890.0,-5047,NaN,1,1,0,1,0,0,NaN,2.0,3,3,TUESDAY,15,0,0,0,0,0,0,Business Entity Type 3,0.636386,0.552308,0.579727,0.0990,0.1075,0.9826,0.7620,NaN,0.00,0.2759,0.1667,0.0417,0.0935,NaN,0.0747,NaN,0.1435,0.1008,0.1115,0.9826,0.7713,NaN,0.0000,0.2759,0.1667,0.0417,0.0956,NaN,0.0779,NaN,0.1519,0.0999,0.1075,0.9826,0.7652,NaN,0.00,0.2759,0.1667,0.0417,0.0951,NaN,0.0761,NaN,0.1465,reg oper account,block of flats,0.1183,"Stone, brick",No,0.0,0.0,0.0,0.0,-2136.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,2.0,0.0,2.0
124997,124997,333982,0,Cash loans,F,N,Y,0,90000,239850,24705.0,225000.0,Unaccompanied,Working,Secondary / secondary special,Civil marriage,House / apartment,0.024610,-24545,-135,-11583.0,-4579,NaN,1,1,0,1,1,0,Cleaning staff,2.0,2,2,WEDNESDAY,15,0,0,0,0,0,0,Kindergarten,NaN,0.361526,0.840667,0.0082,0.0000,0.9717,NaN,NaN,0.00,0.0345,0.0417,NaN,0.0052,NaN,0.0079,NaN,0.0000,0.0084,0.0000,0.9717,NaN,NaN,0.0000,0.0345,0.0417,NaN,0.0053,NaN,0.0082,NaN,0.0000,0.0083,0.0000,0.9717,NaN,NaN,0.00,0.0345,0.0417,NaN,0.0053,NaN,0.0080,NaN,0.0000,NaN,block of flats,0.0062,Wooden,Yes,0.0,0.0,0.0,0.0,-633.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
124998,124998,249620,0,Revolving loans,M,N,Y,0,76500,180000,9000.0,180000.0,Unaccompanied,Commercial associate,Higher education,Single / not married,House / apartment,0.025164,-9074,-317,-9033.0,-1610,NaN,1,1,0,1,0,0,Core staff,1.0,2,2,FRIDAY,12,0,0,0,0,0,0,Police,0.429235,0.598695,0.337673,0.0660,0.0078,0.9627,0.4900,0.0421,0.00,0.2069,0.1250,0.1667,0.1062,0.0530,0.0587,0.0039,0.0044,0.0672,0.0081,0.9628,0.5100,0.0425,0.0000,0.2069,0.1250,0.1667,0.1086,0.0579,0.0612,0.0039,0.0046,0.0666,0.0078,0.9627,0.4968,0.0424,0.00,0.2069,0.1250,0.1667,0.1081,0.0539,0.0598,0.0039,0.0044,reg oper account,block of flats,0.0702,"Stone, brick",No,0.0,0.0,0.0,0.0,-426.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,2.0,0.0
124999,124999,320235,0,Cash loans,M,Y,N,0,81000,306000,24305.0,306000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,With parents,0.018850,-10662,-674,-829.0,-3312,7.0,1,1,1,1,1,0,Low-skill Laborers,1.0,2,2,FRIDAY,12,0,0,0,0,0,0,Housing,0.136291,0.502877,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-755.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

# Clean Data Before Splitting

In [76]:
missing = df.isnull().mean() * 100
print(missing[missing > 0])
cols_to_remove = missing[missing > 65].index
dfclean = df.drop(columns=cols_to_remove)
numcols = dfclean.select_dtypes(include=['float64','int64']).columns
catcols = dfclean.select_dtypes(include=['object']).columns
dfclean[numcols] = dfclean[numcols].fillna(0)
dfclean[catcols] = dfclean[catcols].fillna('Unknown')

AMT_ANNUITY                    0.0024
AMT_GOODS_PRICE                0.1056
NAME_TYPE_SUITE                0.4488
OWN_CAR_AGE                   65.9352
OCCUPATION_TYPE               31.4336
                               ...
AMT_REQ_CREDIT_BUREAU_DAY     13.4040
AMT_REQ_CREDIT_BUREAU_WEEK    13.4040
AMT_REQ_CREDIT_BUREAU_MON     13.4040
AMT_REQ_CREDIT_BUREAU_QRT     13.4040
AMT_REQ_CREDIT_BUREAU_YEAR    13.4040
Length: 66, dtype: float64

In [77]:
# Locate Text columns and search for outliers
text_columns = dfclean.select_dtypes(include=['category', 'object'])

count_results = {}

for column in text_columns.columns:
    value_counts = text_columns[column].value_counts()
    count_results[column] = value_counts

for column, counts in count_results.items():
    print(f"Counts for Column: {column}")
    for value, count in counts.items():  
        print(f"{value}: {count}")
    print("\n" + "--"*40 + "\n")

Counts for Column: NAME_CONTRACT_TYPE
Cash loans: 113034
Revolving loans: 11966

--------------------------------------------------------------------------------

Counts for Column: CODE_GENDER
F: 82209
M: 42790
XNA: 1

--------------------------------------------------------------------------------

Counts for Column: FLAG_OWN_CAR
N: 82416
Y: 42584

--------------------------------------------------------------------------------

Counts for Column: FLAG_OWN_REALTY
Y: 86804
N: 38196

--------------------------------------------------------------------------------

Counts for Column: NAME_TYPE_SUITE
Unaccompanied: 100814
Family: 16406
Spouse, partner: 4739
Children: 1340
Other_B: 711
Unknown: 561
Other_A: 315
Group of people: 114

--------------------------------------------------------------------------------

Counts for Column: NAME_INCOME_TYPE
Working: 64354
Commercial associate: 29285
Pensioner: 22535
State servant: 8802
Unemployed: 10
Student: 6
Businessman: 6
Maternity leave: 2

--------------------------------------------------------------------------------

Counts for Column: NAME_EDUCATION_TYPE
Secondary / secondary special: 88596
Higher education: 30574
Incomplete higher: 4155
Lower secondary: 1605
Academic degree: 70

--------------------------------------------------------------------------------

Counts for Column: NAME_FAMILY_STATUS
Married: 79907
Single / not married: 18334
Civil marriage: 12179
Separated: 8059
Widow: 6520
Unknown: 1

--------------------------------------------------------------------------------

Counts for Column: NAME_HOUSING_TYPE
House / apartment: 110943
With parents: 5978
Municipal apartment: 4595
Rented apartment: 1946
Office apartment: 1069
Co-op apartment: 469

--------------------------------------------------------------------------------

Counts for Column: OCCUPATION_TYPE
Unknown: 39292
Laborers: 22366
Sales staff: 13020
Core staff: 11223
Managers: 8661
Drivers: 7590
High skill tech staff: 4707
Accountants: 4036
Medicine staff: 3430
Security staff: 2671
Cooking staff: 2402
Cleaning staff: 1848
Private service staff: 1073
Low-skill Laborers: 847
Secretaries: 544
Waiters/barmen staff: 518
Realty agents: 312
HR staff: 233
IT staff: 227

--------------------------------------------------------------------------------

Counts for Column: WEEKDAY_APPR_PROCESS_START
TUESDAY: 22012
WEDNESDAY: 21054
MONDAY: 20795
THURSDAY: 20645
FRIDAY: 20323
SATURDAY: 13639
SUNDAY: 6532

--------------------------------------------------------------------------------

Counts for Column: ORGANIZATION_TYPE
Business Entity Type 3: 27798
XNA: 22543
Self-employed: 15596
Other: 6699
Medicine: 4552
Business Entity Type 2: 4261
Government: 4215
School: 3590
Trade: type 7: 3216
Kindergarten: 2694
Construction: 2674
Business Entity Type 1: 2420
Transport: type 4: 2205
Trade: type 3: 1407
Industry: type 9: 1402
Industry: type 3: 1376
Security: 1275
Housing: 1215
Military: 1122
Industry: type 11: 1064
Bank: 1004
Agriculture: 983
Police: 973
Transport: type 2: 898
Postal: 897
Security Ministries: 788
Trade: type 2: 772
Restaurant: 745
Services: 614
University: 546
Industry: type 7: 542
Transport: type 3: 488
Industry: type 1: 429
Electricity: 384
Hotel: 379
Industry: type 4: 345
Trade: type 6: 240
Industry: type 5: 238
Insurance: 236
Telecom: 231
Emergency: 231
Industry: type 2: 201
Culture: 178
Realtor: 176
Industry: type 12: 165
Advertising: 161
Mobile: 141
Trade: type 1: 140
Legal Services: 126
Cleaning: 100
Transport: type 1: 87
Industry: type 10: 56
Industry: type 6: 48
Religion: 39
Industry: type 13: 33
Trade: type 4: 32
Trade: type 5: 18
Industry: type 8: 12

--------------------------------------------------------------------------------

Counts for Column: HOUSETYPE_MODE
Unknown: 62770
block of flats: 61203
specific housing: 571
terraced house: 456

--------------------------------------------------------------------------------

Counts for Column: WALLSMATERIAL_MODE
Unknown: 63568
Panel: 26842
Stone, brick: 26311
Block: 3761
Wooden: 2176
Mixed: 906
Monolithic: 740
Others: 696

--------------------------------------------------------------------------------

Counts for Column: EMERGENCYSTATE_MODE
No: 64769
Unknown: 59292
Yes: 939

--------------------------------------------------------------------------------

In [78]:

dfwho = dfclean[dfclean['CODE_GENDER'] == 'XNA']
print(dfwho)

       rownum  SK_ID_CURR  TARGET NAME_CONTRACT_TYPE CODE_GENDER FLAG_OWN_CAR  \
56092   56092      144669       0    Revolving loans         XNA            N

      FLAG_OWN_REALTY  CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  \
56092               Y             2            157500      270000

       AMT_ANNUITY  AMT_GOODS_PRICE NAME_TYPE_SUITE NAME_INCOME_TYPE  \
56092      13500.0         225000.0          Family          Working

                 NAME_EDUCATION_TYPE NAME_FAMILY_STATUS  NAME_HOUSING_TYPE  \
56092  Secondary / secondary special            Married  House / apartment

       REGION_POPULATION_RELATIVE  DAYS_BIRTH  DAYS_EMPLOYED  \
56092                    0.026392      -13717          -2797

       DAYS_REGISTRATION  DAYS_ID_PUBLISH  FLAG_MOBIL  FLAG_EMP_PHONE  \
56092            -2241.0            -4659           1               1

       FLAG_WORK_PHONE  FLAG_CONT_MOBILE  FLAG_PHONE  FLAG_EMAIL  \
56092                1                 1           1           0

          OCCUPATION_TYPE  CNT_FAM_MEMBERS  REGION_RATING_CLIENT  \
56092  Low-skill Laborers              4.0                     2

       REGION_RATING_CLIENT_W_CITY WEEKDAY_APPR_PROCESS_START  \
56092                            2                     FRIDAY

       HOUR_APPR_PROCESS_START  REG_REGION_NOT_LIVE_REGION  \
56092                       16                           0

       REG_REGION_NOT_WORK_REGION  LIVE_REGION_NOT_WORK_REGION  \
56092                           0                            0

       REG_CITY_NOT_LIVE_CITY  REG_CITY_NOT_WORK_CITY  \
56092                       0                       0

       LIVE_CITY_NOT_WORK_CITY ORGANIZATION_TYPE  EXT_SOURCE_1  EXT_SOURCE_2  \
56092                        0  Industry: type 3           0.0      0.709205

       EXT_SOURCE_3  APARTMENTS_AVG  BASEMENTAREA_AVG  \
56092      0.310818          0.0165            0.0368

       YEARS_BEGINEXPLUATATION_AVG  ELEVATORS_AVG  ENTRANCES_AVG  \
56092                       0.9811            0.0          0.069

       FLOORSMAX_AVG  LANDAREA_AVG  LIVINGAREA_AVG  NONLIVINGAREA_AVG  \
56092         0.0417        0.0233          0.0115                0.0

       APARTMENTS_MODE  BASEMENTAREA_MODE  YEARS_BEGINEXPLUATATION_MODE  \
56092           0.0168             0.0382                        0.9811

       ELEVATORS_MODE  ENTRANCES_MODE  FLOORSMAX_MODE  LANDAREA_MODE  \
56092             0.0           0.069          0.0417         0.0238

       LIVINGAREA_MODE  NONLIVINGAREA_MODE  APARTMENTS_MEDI  \
56092            0.012                 0.0           0.0167

       BASEMENTAREA_MEDI  YEARS_BEGINEXPLUATATION_MEDI  ELEVATORS_MEDI  \
56092             0.0368                        0.9811             0.0

       ENTRANCES_MEDI  FLOORSMAX_MEDI  LANDAREA_MEDI  LIVINGAREA_MEDI  \
56092           0.069          0.0417         0.0237           0.0117

       NONLIVINGAREA_MEDI  HOUSETYPE_MODE  TOTALAREA_MODE WALLSMATERIAL_MODE  \
56092                 0.0  block of flats           0.009       Stone, brick

      EMERGENCYSTATE_MODE  OBS_30_CNT_SOCIAL_CIRCLE  DEF_30_CNT_SOCIAL_CIRCLE  \
56092                  No                       0.0                       0.0

       OBS_60_CNT_SOCIAL_CIRCLE  DEF_60_CNT_SOCIAL_CIRCLE  \
56092                       0.0                       0.0

       DAYS_LAST_PHONE_CHANGE  FLAG_DOCUMENT_2  FLAG_DOCUMENT_3  \
56092                  -493.0                0                0

       FLAG_DOCUMENT_4  FLAG_DOCUMENT_5  FLAG_DOCUMENT_6  FLAG_DOCUMENT_7  \
56092                0                0                0                0

       FLAG_DOCUMENT_8  FLAG_DOCUMENT_9  FLAG_DOCUMENT_10  FLAG_DOCUMENT_11  \
56092                0                0                 0                 0

       FLAG_DOCUMENT_12  FLAG_DOCUMENT_13  FLAG_DOCUMENT_14  FLAG_DOCUMENT_15  \
56092                 0                 0                 0                 0

       FLAG_DOCUMENT_16  FLAG_DOCUMENT_17  FLAG_DOCUMENT_18  FLAG_DOCUMENT_19  \
56092                 0                 0                 0                 0

       FLAG_DOCUMENT_20  FLAG_DOCUMENT_21  AMT_REQ_CREDIT_BUREAU_HOUR  \
56092                 0                 0                         0.0

       AMT_REQ_CREDIT_BUREAU_DAY  AMT_REQ_CREDIT_BUREAU_WEEK  \
56092                        0.0                         0.0

       AMT_REQ_CREDIT_BUREAU_MON  AMT_REQ_CREDIT_BUREAU_QRT  \
56092                        3.0                        0.0

       AMT_REQ_CREDIT_BUREAU_YEAR
56092                         4.0

In [79]:
# change outlier to average 
dfclean.loc[56092, 'CODE_GENDER'] = 'F'

In [80]:
dfwho = dfclean[dfclean['NAME_FAMILY_STATUS'] == 'Unknown']
print(dfwho)

      rownum  SK_ID_CURR  TARGET NAME_CONTRACT_TYPE CODE_GENDER FLAG_OWN_CAR  \
1497    1497      317181       0    Revolving loans           F            N

     FLAG_OWN_REALTY  CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  AMT_ANNUITY  \
1497               Y             0            202500      585000      29250.0

      AMT_GOODS_PRICE NAME_TYPE_SUITE      NAME_INCOME_TYPE  \
1497              0.0         Unknown  Commercial associate

     NAME_EDUCATION_TYPE NAME_FAMILY_STATUS  NAME_HOUSING_TYPE  \
1497    Higher education            Unknown  House / apartment

      REGION_POPULATION_RELATIVE  DAYS_BIRTH  DAYS_EMPLOYED  \
1497                    0.031329      -12844           -232

      DAYS_REGISTRATION  DAYS_ID_PUBLISH  FLAG_MOBIL  FLAG_EMP_PHONE  \
1497            -1597.0            -1571           1               1

      FLAG_WORK_PHONE  FLAG_CONT_MOBILE  FLAG_PHONE  FLAG_EMAIL  \
1497                0                 1           0           0

     OCCUPATION_TYPE  CNT_FAM_MEMBERS  REGION_RATING_CLIENT  \
1497     Accountants              0.0                     2

      REGION_RATING_CLIENT_W_CITY WEEKDAY_APPR_PROCESS_START  \
1497                            2                     FRIDAY

      HOUR_APPR_PROCESS_START  REG_REGION_NOT_LIVE_REGION  \
1497                       14                           0

      REG_REGION_NOT_WORK_REGION  LIVE_REGION_NOT_WORK_REGION  \
1497                           0                            0

      REG_CITY_NOT_LIVE_CITY  REG_CITY_NOT_WORK_CITY  LIVE_CITY_NOT_WORK_CITY  \
1497                       0                       0                        0

           ORGANIZATION_TYPE  EXT_SOURCE_1  EXT_SOURCE_2  EXT_SOURCE_3  \
1497  Business Entity Type 2           0.0      0.645168      0.670652

      APARTMENTS_AVG  BASEMENTAREA_AVG  YEARS_BEGINEXPLUATATION_AVG  \
1497          0.1031            0.0467                        0.997

      ELEVATORS_AVG  ENTRANCES_AVG  FLOORSMAX_AVG  LANDAREA_AVG  \
1497           0.08          0.069          0.375           0.0

      LIVINGAREA_AVG  NONLIVINGAREA_AVG  APARTMENTS_MODE  BASEMENTAREA_MODE  \
1497           0.088                0.0            0.105             0.0485

      YEARS_BEGINEXPLUATATION_MODE  ELEVATORS_MODE  ENTRANCES_MODE  \
1497                         0.997          0.0806           0.069

      FLOORSMAX_MODE  LANDAREA_MODE  LIVINGAREA_MODE  NONLIVINGAREA_MODE  \
1497           0.375            0.0           0.0917                 0.0

      APARTMENTS_MEDI  BASEMENTAREA_MEDI  YEARS_BEGINEXPLUATATION_MEDI  \
1497           0.1041             0.0467                         0.997

      ELEVATORS_MEDI  ENTRANCES_MEDI  FLOORSMAX_MEDI  LANDAREA_MEDI  \
1497            0.08           0.069           0.375            0.0

      LIVINGAREA_MEDI  NONLIVINGAREA_MEDI  HOUSETYPE_MODE  TOTALAREA_MODE  \
1497           0.0896                 0.0  block of flats          0.0791

     WALLSMATERIAL_MODE EMERGENCYSTATE_MODE  OBS_30_CNT_SOCIAL_CIRCLE  \
1497              Panel                  No                       1.0

      DEF_30_CNT_SOCIAL_CIRCLE  OBS_60_CNT_SOCIAL_CIRCLE  \
1497                       0.0                       1.0

      DEF_60_CNT_SOCIAL_CIRCLE  DAYS_LAST_PHONE_CHANGE  FLAG_DOCUMENT_2  \
1497                       0.0                  -654.0                0

      FLAG_DOCUMENT_3  FLAG_DOCUMENT_4  FLAG_DOCUMENT_5  FLAG_DOCUMENT_6  \
1497                0                0                0                0

      FLAG_DOCUMENT_7  FLAG_DOCUMENT_8  FLAG_DOCUMENT_9  FLAG_DOCUMENT_10  \
1497                1                0                0                 0

      FLAG_DOCUMENT_11  FLAG_DOCUMENT_12  FLAG_DOCUMENT_13  FLAG_DOCUMENT_14  \
1497                 0                 0                 0                 0

      FLAG_DOCUMENT_15  FLAG_DOCUMENT_16  FLAG_DOCUMENT_17  FLAG_DOCUMENT_18  \
1497                 0                 0                 0                 0

      FLAG_DOCUMENT_19  FLAG_DOCUMENT_20  FLAG_DOCUMENT_21  \
1497                 0                 0                 0

      AMT_REQ_CREDIT_BUREAU_HOUR  AMT_REQ_CREDIT_BUREAU_DAY  \
1497                         0.0                        0.0

      AMT_REQ_CREDIT_BUREAU_WEEK  AMT_REQ_CREDIT_BUREAU_MON  \
1497                         0.0                        0.0

      AMT_REQ_CREDIT_BUREAU_QRT  AMT_REQ_CREDIT_BUREAU_YEAR
1497                        0.0                         1.0

In [81]:
dfclean.loc[1497, 'NAME_FAMILY_STATUS'] = 'Single / not married'

In [82]:
#adjust odd Income #
dfclean.loc[13804, 'AMT_INCOME_TOTAL'] = 1170000

# remove uneeded columns

In [83]:
#all Values are 1 (uneeded)
dfclean.drop(columns=['FLAG_MOBIL'], inplace=True)

In [84]:
# all but 2 values are 0
dfclean.drop(columns=['FLAG_DOCUMENT_2'], inplace=True)

In [85]:
# all but 10 values are 0
dfclean.drop(columns=['FLAG_DOCUMENT_4'], inplace=True)

In [86]:
# all but 28 values are 0
dfclean.drop(columns=['FLAG_DOCUMENT_7'], inplace=True)

In [87]:
# Will test these to see if all or none are needed

# Split Data Into 3 Sets

In [88]:
df_train = dfclean.query('0 <= rownum < 87500')
df_train

,rownum,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,LANDAREA_AVG,LIVINGAREA_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,LANDAREA_MODE,LIVINGAREA_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,LANDAREA_MEDI,LIVINGAREA_MEDI,NONLIVINGAREA_MEDI,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_3,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,0,396902,0,Cash loans,F,Y,Y,0,121500,835380,40320.0,675000.0,Unaccompanied,Working,Higher education,Separated,House / apartment,0.035792,-16647,-283,-611.0,-184,1,1,1,0,0,Core staff,1.0,2,2,SUNDAY,11,0,0,0,0,0,0,Restaurant,0.642816,0.606592,0.646330,0.0000,0.0000,0.0000,0.00,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.00,0.0000,0.0000,0.0000,0.0000,0.0000,Unknown,0.0000,Unknown,Unknown,0.0,0.0,0.0,0.0,-770.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,4.0
1,1,112096,0,Cash loans,F,N,Y,0,202500,516069,26478.0,445500.0,Unaccompanied,Pensioner,Secondary / secondary special,Widow,House / apartment,0.011657,-22237,365243,-34.0,-4878,0,0,1,0,0,Unknown,1.0,1,1,WEDNESDAY,10,0,0,0,0,0,0,XNA,0.000000,0.172095,0.360613,0.1227,0.1213,0.9762,0.00,0.2069,0.1667,0.0476,0.0941,0.1375,0.1250,0.1259,0.9762,0.0000,0.2069,0.1667,0.0487,0.0981,0.1456,0.1239,0.1213,0.9762,0.00,0.2069,0.1667,0.0485,0.0958,0.1404,block of flats,0.1039,"Stone, brick",No,1.0,1.0,1.0,1.0,-1069.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,6.0
2,2,285821,1,Cash loans,M,Y,Y,1,180000,284400,22469.0,225000.0,"Spouse, partner",Working,Secondary / secondary special,Married,House / apartment,0.028663,-11399,-508,-1500.0,-920,1,0,1,0,0,Laborers,3.0,2,2,SUNDAY,11,0,1,1,0,1,1,Construction,0.446722,0.465626,0.106156,0.0000,0.0000,0.0000,0.00,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.00,0.0000,0.0000,0.0000,0.0000,0.0000,Unknown,0.0000,Unknown,Unknown,7.0,0.0,7.0,0.0,-933.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
3,3,376901,0,Cash loans,F,N,Y,0,90000,265536,13685.0,180000.0,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.031329,-20074,-221,-1264.0,-3559,1,0,1,0,0,Medicine staff,2.0,2,2,FRIDAY,10,0,0,0,0,0,0,Kindergarten,0.000000,0.662464,0.266457,0.1320,0.0460,0.9856,0.08,0.0345,0.6250,0.0116,0.1327,0.0011,0.1345,0.0478,0.9856,0.0806,0.0345,0.6250,0.0119,0.1382,0.0011,0.1332,0.0460,0.9856,0.08,0.0345,0.6250,0.0118,0.1351,0.0011,block of flats,0.1251,Monolithic,No,0.0,0.0,0.0,0.0,-1428.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
4,4,325138,0,Cash loans,F,Y,Y,0,94500,755190,30078.0,675000.0,Unaccompanied,Pensioner,Secondary / secondary special,Single / not married,House / apartment,0.019689,-20691,365243,-2277.0,-703,0,0,1,0,0,Unknown,1.0,2,2,THURSDAY,12,0,0,0,0,0,0,XNA,0.000000,0.054296,0.000000,0.0082,0.0216,0.9722,0.00,0.0345,0.0417,0.0038,0.0095,0.0000,0.0084,0.0225,0.9722,0.0000,0.0345,0.0417,0.0039,0.0099,0.0000,0.0083,0.0216,0.9722,0.00,0.0345,0.0417,0.0039,0.0096,0.0000,block of flats,0.0074,"Stone, brick",No,0.0,0.0,0.0,0.0,-695.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87495,87495,347233,1,Cash loans,M,Y,Y,1,202500,436500,29300.0,436500.0,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.018209,-10646,-1311,-4200.0,-1779,1,0,1,0,0,Drivers,3.0,3,3,TUESDAY,7,0,0,0,0,0,0,Transport: type 3,0.127830,0.446274,0.397946,0.0000,0.0000,0.0000,0.00,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.00,0.0000,0.0000,0.0000,0.0000,0.0000,Unknown,0.0000,Unknown,Unknown,0.0,0.0,0.0,0.0,-1290.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,1.0,3.0
87496,87496,415155,0,Cash loans,F,N,Y,1,90000,325908,17195.0,247500.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.031329,-14857,-153,-6155.0,-4074,1,0,1,0,0,Laborers,2.0,2,2,FRIDAY,16,0,0,0,0,1,1,Business Entity Type 3,0.000000,0.595655,0.000000,0.2216,0.1082,0.9781,0.24,0.2069,0.3333,0.0956,0.1338,0.0000,0.2258,0.1123,0.9782,0.2417,0.2069,0.3333,0.0978,0.1394,0.0000,0.2238,0.1082,0.9781,0.24,0.2069,0.3333,0.0973,0.1362,0.0000,block of flats,0.1627,Panel,No,0.0,0.0,0.0,0.0,-1.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
87497,87497,452814,0,Cash loans,M,Y,Y,1,270000,971280,54234.0,900000.0,Unaccompanied,Working,Higher education,Separated,House / apartment,0.046220,-14522,-2041,-8607.0,-4142,1,1,1,0,0,Sales staff,2.0,1,1,MONDAY,11,0,1,1,0,1,1,Business Entity Type 3,0.637490,0.789869,0.000000,0.1041,0.0000,0.9955,0.16,0.0345,0.9167,0.0000,0.0000,0.0000,0.1061,0.0000,0.9955,0.1611,0.0345,0.9167,0.0000,0.0000,0.0000,0.1051,0.0000,0.9955,0.16,0.0345,0.9167,0.0000,0.0000,0.0000,block of flats,0.0390,"Stone, brick",No,0.0,0.0,0.0,0.0,-1874.0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,2.0,0.0,0.0,2.0
87498,87498,346541,0,Cash loans,F,N,Y,0,135000,640080,31262.0,450000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,Municipal apartment,0.072508,-10507,-1451,-5318.0,-3186,1,0,1,0,0,Medicine staff,1.0,1,1,WEDNESDAY,18,0,0,0,0,0,0,Security Ministries,0.538142,0.093427,0.251239,0.1982,0.1043,0.9796,0.32,0.1379,0.4583,0.0000,0.2025,0.0026,0.2017,0.1051,0.9796,0.3222,0.1379,0.4583,0.0000,0.2029,0.0011,0.1999,0.1043,0.9796,0.32,0.1379,0.4583,0.0000,0.2077,0.0026,block of flats,0.1603,Panel,No,0.0,0.0,0.0,0.0,0.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
87499,87499,340871,0,Cash loans,F,N,Y,2,157500,936909,30222.0,782060.0,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.025164,-9690,-2020,-9677.0,-714,1,0,1,0,1,Sales staff,4.0,2,2,THURSDAY,12,0,0,0,0,0,0,Self-employed,0.423547,0.365325,0.000000,0.0742,0.0436,0.9861,0.08,0.0690,0.3333,0.0285,0.0623,0.0789,0.0756,0.0452,0.9861,0.0806,0.0690,0.3333,0.0292,0.0649,0.0835,0.0749,0.0436,0.9861,0.08,0.0690,0.3333,0.0290,0.0634,0.0805,block of flats,0.0662,Panel,No,3.0,0.0,3.0,0.0,-312.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

In [89]:
df_valid = dfclean.query('87500 <= rownum < 106250')
df_valid

,rownum,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,LANDAREA_AVG,LIVINGAREA_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,LANDAREA_MODE,LIVINGAREA_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,LANDAREA_MEDI,LIVINGAREA_MEDI,NONLIVINGAREA_MEDI,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_3,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
87500,87500,356241,1,Cash loans,M,N,Y,0,220500,816660,26474.0,585000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.011657,-17048,-1481,-9656.0,-606,1,0,1,0,0,Security staff,1.0,1,1,FRIDAY,11,0,0,0,0,0,0,Business Entity Type 3,0.000000,0.483689,0.401407,0.2588,0.1887,0.9801,0.2,0.1724,0.3333,0.0000,0.2222,0.1514,0.2637,0.1958,0.9801,0.2014,0.1724,0.3333,0.0000,0.2315,0.1603,0.2613,0.1887,0.9801,0.2,0.1724,0.3333,0.0000,0.2261,0.1546,block of flats,0.2419,"Stone, brick",No,0.0,0.0,0.0,0.0,0.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0
87501,87501,443823,0,Cash loans,F,N,N,0,220500,1535553,42224.0,1372500.0,Unaccompanied,Working,Secondary / secondary special,Separated,House / apartment,0.046220,-14906,-6526,-8813.0,-4668,1,1,1,0,0,Unknown,1.0,1,1,FRIDAY,16,0,0,0,0,1,1,Military,0.717817,0.405276,0.683269,0.0000,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,Unknown,0.0000,Unknown,Unknown,4.0,0.0,4.0,0.0,-1470.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
87502,87502,401657,0,Cash loans,M,Y,Y,1,315000,857169,25191.0,715500.0,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.007274,-12112,-2126,-6273.0,-4575,1,0,1,0,0,Drivers,3.0,2,2,FRIDAY,18,0,1,1,0,1,1,Business Entity Type 3,0.202459,0.630704,0.572683,0.0247,0.0358,0.9806,0.0,0.0690,0.0833,0.0000,0.0217,0.0000,0.0252,0.0372,0.9806,0.0000,0.0690,0.0833,0.0000,0.0227,0.0000,0.0250,0.0358,0.9806,0.0,0.0690,0.0833,0.0000,0.0221,0.0000,block of flats,0.0171,"Stone, brick",No,0.0,0.0,0.0,0.0,-2412.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
87503,87503,145013,0,Cash loans,F,Y,Y,1,112500,697500,27662.0,697500.0,Unaccompanied,Commercial associate,Secondary / secondary special,Married,House / apartment,0.018850,-13950,-4777,-4543.0,-4714,1,1,1,0,0,Managers,3.0,2,2,TUESDAY,15,0,0,0,0,0,0,Self-employed,0.000000,0.281361,0.729567,0.0000,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,Unknown,0.0000,Unknown,Unknown,0.0,0.0,0.0,0.0,-1414.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
87504,87504,231633,0,Cash loans,M,Y,N,1,225000,805536,32076.0,720000.0,Family,Working,Secondary / secondary special,Married,House / apartment,0.009657,-14719,-4277,-2030.0,-4407,1,0,1,0,0,Unknown,3.0,2,2,TUESDAY,10,0,0,0,0,0,0,Transport: type 4,0.000000,0.495065,0.743559,0.0000,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,Unknown,0.0000,Unknown,Unknown,1.0,0.0,1.0,0.0,-1876.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106245,106245,140745,0,Cash loans,F,N,N,1,157500,942300,30528.0,675000.0,Unaccompanied,Commercial associate,Secondary / secondary special,Married,Municipal apartment,0.003818,-15690,-1463,-9028.0,-3203,1,0,1,0,0,Cleaning staff,3.0,2,2,WEDNESDAY,8,0,0,0,0,0,0,Self-employed,0.158220,0.587179,0.786267,0.0000,0.0000,0.9757,0.0,0.0345,0.0417,0.0048,0.0048,0.0000,0.0000,0.0000,0.9757,0.0000,0.0345,0.0417,0.0049,0.0050,0.0000,0.0000,0.0000,0.9757,0.0,0.0345,0.0417,0.0049,0.0049,0.0000,block of flats,0.0048,Wooden,Yes,0.0,0.0,0.0,0.0,-2084.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
106246,106246,155170,1,Cash loans,F,N,Y,2,81000,418500,20484.0,418500.0,"Spouse, partner",Commercial associate,Secondary / secondary special,Married,House / apartment,0.014520,-11804,-475,-1757.0,-270,1,0,1,0,0,High skill tech staff,4.0,2,2,WEDNESDAY,10,0,0,0,1,1,0,Business Entity Type 1,0.329686,0.634171,0.167408,0.0000,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,Unknown,0.0000,Unknown,Unknown,8.0,1.0,8.0,1.0,-332.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
106247,106247,139134,0,Cash loans,F,N,Y,0,112500,1139846,48425.0,1048500.0,"Spouse, partner",Working,Secondary / secondary special,Married,House / apartment,0.004960,-15548,-879,-8052.0,-4488,1,0,1,0,0,Cleaning staff,2.0,2,2,FRIDAY,16,0,0,0,0,1,1,Industry: type 8,0.542351,0.530273,0.576209,0.0000,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,Unknown,0.0000,Unknown,Unknown,3.0,0.0,3.0,0.0,-829.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
106248,106248,188087,0,Cash loans,F,Y,Y,0,166500,472500,47817.0,454500.0,Family,Working,Secondary / secondary special,Married,House / apartment,0.025164,-17108,-4124,-249.0,-633,1,0,1,0,0,Sales staff,2.0,2,2,FRIDAY,10,0,0,0,0,0,0,Trade: type 7,0.000000,0.682884,0.000000,0.1052,0.0137,0.9821,0.0,0.2759,0.2083,0.0695,0.1030,0.0620,0.1071,0.0142,0.9821,0.0000,0.2759,0.2083,0.0711,0.1073,0.0656,0.1062,0.0137,0.9821,0.0,0.2759,0.2083,0.0707,0.1048,0.0633,block of flats,0.1051,"Stone, brick",No,0.0,0.0,0.0,0.0,-528.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
106249,106249,353189,0,Cash loans,F,N,Y,2,99000,755190,36459.0,675000.0,Unaccompanied,State servant,Secondary / secondary special,Married,House / apartment,0.025164,-12779,-3517,-3034.0,-4285,1,1,1,0,0,Cleaning staff,4.0,2,2,SATURDAY,9,0,0,0,0,0,0,School,0.000000,0.017458,0.291097,0.0000,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,Unknown,0.0000,Unknown,Unknown,2.0,1.0,2.0,0.0,0.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

In [90]:
df_test = dfclean.query('rownum >= 106250')
df_test

,rownum,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,LANDAREA_AVG,LIVINGAREA_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,LANDAREA_MODE,LIVINGAREA_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,LANDAREA_MEDI,LIVINGAREA_MEDI,NONLIVINGAREA_MEDI,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_3,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
106250,106250,349548,1,Cash loans,F,Y,Y,1,112500,545040,26640.0,450000.0,Family,Working,Secondary / secondary special,Married,House / apartment,0.020246,-15311,-293,-15.0,-4928,1,0,1,0,0,Sales staff,3.0,3,3,TUESDAY,9,0,0,0,0,0,0,Self-employed,0.189391,0.421384,0.102782,0.0371,0.0179,1.0000,0.0,0.1034,0.0417,0.0136,0.0316,0.0141,0.0378,0.0185,1.0000,0.0,0.1034,0.0417,0.0139,0.0330,0.0150,0.0375,0.0179,1.0000,0.0,0.1034,0.0417,0.0138,0.0322,0.0144,block of flats,0.0311,"Stone, brick",No,2.0,1.0,2.0,0.0,0.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,1.0,3.0
106251,106251,115330,1,Cash loans,F,N,Y,1,112500,553806,28404.0,495000.0,Unaccompanied,Commercial associate,Secondary / secondary special,Married,House / apartment,0.006008,-10435,-2435,-2860.0,-550,1,1,1,0,0,Laborers,3.0,2,2,MONDAY,14,0,0,0,0,0,0,Business Entity Type 3,0.553823,0.539190,0.000000,0.0000,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,Unknown,0.0000,Unknown,Unknown,7.0,0.0,7.0,0.0,-1064.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
106252,106252,156518,0,Cash loans,M,N,Y,0,126000,269982,29205.0,238500.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.010147,-11543,-4348,-6186.0,-2845,1,0,1,0,0,Laborers,1.0,2,2,MONDAY,14,0,0,0,0,1,1,Business Entity Type 2,0.317241,0.120314,0.614414,0.0000,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,Unknown,0.0000,Unknown,Unknown,5.0,0.0,5.0,0.0,-1253.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0
106253,106253,391420,0,Cash loans,F,Y,Y,0,135000,526491,32337.0,454500.0,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.018801,-9995,-1523,-2026.0,-2649,1,0,1,0,0,Sales staff,2.0,2,2,SUNDAY,10,0,0,0,0,0,0,Self-employed,0.177603,0.340971,0.728141,0.0000,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,Unknown,0.0000,Unknown,Unknown,0.0,0.0,0.0,0.0,0.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
106254,106254,351610,0,Cash loans,F,N,Y,2,126000,331632,35186.0,315000.0,Family,Working,Higher education,Married,House / apartment,0.006207,-10876,-196,-983.0,-2143,1,1,1,0,0,Unknown,4.0,2,2,SATURDAY,16,0,0,0,0,0,0,Business Entity Type 1,0.168585,0.207979,0.662638,0.0000,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,Unknown,0.0000,Unknown,Unknown,0.0,0.0,0.0,0.0,-1907.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124995,124995,217133,0,Revolving loans,M,Y,Y,0,54000,157500,7875.0,157500.0,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.019101,-21089,-1412,-10474.0,-3965,1,1,1,1,0,Laborers,2.0,2,2,THURSDAY,12,0,0,0,0,0,0,Business Entity Type 3,0.000000,0.626477,0.000000,0.0000,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,Unknown,0.0000,Unknown,Unknown,1.0,0.0,1.0,0.0,-696.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
124996,124996,169482,0,Cash loans,F,N,N,0,180000,661500,17577.0,661500.0,Unaccompanied,Commercial associate,Secondary / secondary special,Married,House / apartment,0.018209,-14074,-483,-1890.0,-5047,1,0,1,0,0,Unknown,2.0,3,3,TUESDAY,15,0,0,0,0,0,0,Business Entity Type 3,0.636386,0.552308,0.579727,0.0990,0.1075,0.9826,0.0,0.2759,0.1667,0.0935,0.0747,0.1435,0.1008,0.1115,0.9826,0.0,0.2759,0.1667,0.0956,0.0779,0.1519,0.0999,0.1075,0.9826,0.0,0.2759,0.1667,0.0951,0.0761,0.1465,block of flats,0.1183,"Stone, brick",No,0.0,0.0,0.0,0.0,-2136.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,2.0,0.0,2.0
124997,124997,333982,0,Cash loans,F,N,Y,0,90000,239850,24705.0,225000.0,Unaccompanied,Working,Secondary / secondary special,Civil marriage,House / apartment,0.024610,-24545,-135,-11583.0,-4579,1,0,1,1,0,Cleaning staff,2.0,2,2,WEDNESDAY,15,0,0,0,0,0,0,Kindergarten,0.000000,0.361526,0.840667,0.0082,0.0000,0.9717,0.0,0.0345,0.0417,0.0052,0.0079,0.0000,0.0084,0.0000,0.9717,0.0,0.0345,0.0417,0.0053,0.0082,0.0000,0.0083,0.0000,0.9717,0.0,0.0345,0.0417,0.0053,0.0080,0.0000,block of flats,0.0062,Wooden,Yes,0.0,0.0,0.0,0.0,-633.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
124998,124998,249620,0,Revolving loans,M,N,Y,0,76500,180000,9000.0,180000.0,Unaccompanied,Commercial associate,Higher education,Single / not married,House / apartment,0.025164,-9074,-317,-9033.0,-1610,1,0,1,0,0,Core staff,1.0,2,2,FRIDAY,12,0,0,0,0,0,0,Police,0.429235,0.598695,0.337673,0.0660,0.0078,0.9627,0.0,0.2069,0.1250,0.1062,0.0587,0.0044,0.0672,0.0081,0.9628,0.0,0.2069,0.1250,0.1086,0.0612,0.0046,0.0666,0.0078,0.9627,0.0,0.2069,0.1250,0.1081,0.0598,0.0044,block of flats,0.0702,"Stone, brick",No,0.0,0.0,0.0,0.0,-426.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,2.0,0.0
124999,124999,320235,0,Cash loans,M,Y,N,0,81000,306000,24305.0,306000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,With parents,0.018850,-10662,-674,-829.0,-3312,1,1,1,1,0,Low-skill Laborers,1.0,2,2,FRIDAY,12,0,0,0,0,0,0,Housing,0.136291,0.502877,0.000000,0.0000,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,Unknown,0.0000,Unknown,Unknown,0.0,0.0,0.0,0.0,-755.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

# Save 3 datasets for model creation

In [91]:
df_train.to_csv('./output/df_train.csv', index=False)

In [92]:
df_valid.to_csv('./output/df_valid.csv', index=False)

In [93]:
df_test.to_csv('./output/df_test.csv', index=False)