In [1]:
import pandas as pd
import os
import matplotlib.pyplot as plt
import pyodbc
import numpy as np
import pickle

## Constants

In [2]:
str_project = os.getcwd().split('\\')[3]
print(f'Project: {str_project}')

str_task = os.getcwd().split('\\')[4]
print(f'Task: {str_task}')

str_subtask = os.getcwd().split('\\')[5]
print(f'Subtask: {str_subtask}')

str_dirname_output = 'output'

Project: 20240521_bridger_internship
Task: 04_flask
Subtask: notebooks

In [3]:
try:
    os.mkdir(str_dirname_output)
except FileExistsError:
    pass

## Functions

In [3]:
class GetData:
    def __init__(self):
        pass
    def read_sql_script(self, str_local_path):
        str_query = open(str_local_path, 'r').read()
        # save to object
        self.str_query = str_query
        # return object
        return self
    def pull_data_from_sql(self, conn, bool_close_conn=True):
        df = pd.read_sql_query(
            sql=self.str_query,
            con=conn,
        )
        if bool_close_conn:
            conn.close()
        else:
            pass
        return df

## Pull  DEALER Data

In [16]:
# initialize class 
cls_get_data = GetData()

#read query
str_filename = 'dealerquery.sql'
str_local_path = f'./sql/{str_filename}'
cls_get_data.read_sql_script(
    str_local_path=str_local_path,
)
# pull data
conn = pyodbc.connect(
    'Driver={SQL Server};'
    'Server=electra;'
    'Database=pfsdb;'
    'Trusted_connection=yes;'
)
df = cls_get_data.pull_data_from_sql(
    conn=conn,
    bool_close_conn=True,
)
df

C:\Users\bhyde\AppData\Local\Temp\ipykernel_7704\3525508220.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(

,strName,YTDApplicationcount,YTDApprovedCount,YTDFundedCount
0,"MCCLUSKEY CHEVROLET, INC. - KINGS",7635,1966,117
1,RIDE TIME AUTO FINANCE,4853,911,166
2,SMART BUY AUTO FINANCE INC,4755,495,151
3,BOBB SAYS YES,4266,607,57
4,JIMMY THE BOXER AUTO MALL,4115,887,106
5,DIRECT AUTO,4113,482,68
6,SHERMAN DODGE,3612,467,119
7,OLE BEN FRANKLIN MOTORS,3393,467,57
8,NORTHWEST INDIANA AUTO FINANCE,3019,637,92
9,WORLD HYUNDAI MATTESON,2720,281,67

In [24]:
# pull applications amounts from df
dfdealerapps = df[['strName','YTDApplicationcount']]
print(dfdealerapps)
# save output
str_filename = 'dealerapps.gzip'
dfdealerapps.to_parquet(f'./output/{str_filename}')
# save memory
del dfdealerapps

                             strName  YTDApplicationcount
0  MCCLUSKEY CHEVROLET, INC. - KINGS                 7635
1             RIDE TIME AUTO FINANCE                 4853
2         SMART BUY AUTO FINANCE INC                 4755
3                      BOBB SAYS YES                 4266
4          JIMMY THE BOXER AUTO MALL                 4115
5                        DIRECT AUTO                 4113
6                      SHERMAN DODGE                 3612
7            OLE BEN FRANKLIN MOTORS                 3393
8     NORTHWEST INDIANA AUTO FINANCE                 3019
9             WORLD HYUNDAI MATTESON                 2720

In [25]:
# pull approved amounts from df
dfdealerapproved = df[['strName','YTDApprovedCount']]
print(dfdealerapproved)
# save output
str_filename = 'dealerapproved.gzip'
dfdealerapproved.to_parquet(f'./output/{str_filename}')
# save memory
del dfdealerapproved

                             strName  YTDApprovedCount
0  MCCLUSKEY CHEVROLET, INC. - KINGS              1966
1             RIDE TIME AUTO FINANCE               911
2         SMART BUY AUTO FINANCE INC               495
3                      BOBB SAYS YES               607
4          JIMMY THE BOXER AUTO MALL               887
5                        DIRECT AUTO               482
6                      SHERMAN DODGE               467
7            OLE BEN FRANKLIN MOTORS               467
8     NORTHWEST INDIANA AUTO FINANCE               637
9             WORLD HYUNDAI MATTESON               281

In [27]:
# pull funded amounts from df
dfdealerfunded = df[['strName','YTDFundedCount']]
print(dfdealerfunded)
# save output
str_filename = 'dealerfunded.gzip'
dfdealerfunded.to_parquet(f'./output/{str_filename}')
# save memory
del dfdealerfunded

                             strName  YTDFundedCount
0  MCCLUSKEY CHEVROLET, INC. - KINGS             117
1             RIDE TIME AUTO FINANCE             166
2         SMART BUY AUTO FINANCE INC             151
3                      BOBB SAYS YES              57
4          JIMMY THE BOXER AUTO MALL             106
5                        DIRECT AUTO              68
6                      SHERMAN DODGE             119
7            OLE BEN FRANKLIN MOTORS              57
8     NORTHWEST INDIANA AUTO FINANCE              92
9             WORLD HYUNDAI MATTESON              67

## PULL TIERS DATA FOR 2024

In [9]:
# initialize class To create dftier
cls_get_data = GetData()

#read query
str_filename = 'TiersTempStaticPool2024.sql'
str_local_path = f'./sql/{str_filename}'
cls_get_data.read_sql_script(
    str_local_path=str_local_path,
)
# pull data
conn = pyodbc.connect(
    'Driver={SQL Server};'
    'Server=electra;'
    'Database=pfsdb;'
    'Trusted_connection=yes;'
)
dftier = cls_get_data.pull_data_from_sql(
    conn=conn,
    bool_close_conn=True,
)
dftier

C:\Users\bhyde\AppData\Local\Temp\ipykernel_9920\3525508220.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(

  Tiers  Amount
0     A    1099
1    A1     953
2     B    6531
3     C    2207
4     D    1480

In [10]:
str_filename = 'dftier2024.gzip'
# Save Tier Information To gzip
dftier.to_parquet(f'./output/{str_filename}', compression = 'gzip')
# Save memory
del dftier

## PULL TIER DATA 2023 - 2024

In [12]:
# initialize class To create dftier
cls_get_data = GetData()

#read query
str_filename = 'TiersTempStaticPool2023.sql'
str_local_path = f'./sql/{str_filename}'
cls_get_data.read_sql_script(
    str_local_path=str_local_path,
)
# pull data
conn = pyodbc.connect(
    'Driver={SQL Server};'
    'Server=electra;'
    'Database=pfsdb;'
    'Trusted_connection=yes;'
)
dftier = cls_get_data.pull_data_from_sql(
    conn=conn,
    bool_close_conn=True,
)
dftier

C:\Users\bhyde\AppData\Local\Temp\ipykernel_9920\3525508220.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(

  Tiers  Amount
0     A    3571
1    A1    4660
2     B   10852
3     C    3094
4     D    2342

In [13]:
str_filename = 'dftier2023.gzip'
# save data to gzip
dftier.to_parquet(f'./output/{str_filename}', compression = 'gzip')
# save memeory
del dftier

## PULL TIER DATA 2022 - 2023

In [14]:
# initialize class To create dftier
cls_get_data = GetData()

#read query
str_filename = 'TiersTempStaticPool2022.sql'
str_local_path = f'./sql/{str_filename}'
cls_get_data.read_sql_script(
    str_local_path=str_local_path,
)
# pull data
conn = pyodbc.connect(
    'Driver={SQL Server};'
    'Server=electra;'
    'Database=pfsdb;'
    'Trusted_connection=yes;'
)
dftier = cls_get_data.pull_data_from_sql(
    conn=conn,
    bool_close_conn=True,
)
dftier

C:\Users\bhyde\AppData\Local\Temp\ipykernel_9920\3525508220.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(

  Tiers  Amount
0     A    4390
1    A1    2259
2     B   10822
3     C    5568
4     D    3202

In [15]:
str_filename = 'dftier2022.gzip'
# save data to gzip
dftier.to_parquet(f'./output/{str_filename}', compression = 'gzip')
# save memeory
del dftier

## PULL TIER DATA 2021 - 2022

In [16]:
# initialize class To create dftier
cls_get_data = GetData()

#read query
str_filename = 'TiersTempStaticPool2021.sql'
str_local_path = f'./sql/{str_filename}'
cls_get_data.read_sql_script(
    str_local_path=str_local_path,
)
# pull data
conn = pyodbc.connect(
    'Driver={SQL Server};'
    'Server=electra;'
    'Database=pfsdb;'
    'Trusted_connection=yes;'
)
dftier = cls_get_data.pull_data_from_sql(
    conn=conn,
    bool_close_conn=True,
)
dftier

C:\Users\bhyde\AppData\Local\Temp\ipykernel_9920\3525508220.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(

  Tiers  Amount
0     A    2331
1    A1    1964
2     B    5047
3     C    3140
4     D    1394

In [17]:
str_filename = 'dftier2021.gzip'
# save data to gzip
dftier.to_parquet(f'./output/{str_filename}', compression = 'gzip')
# save memeory
del dftier

## PULL TIER DATA 2020 - 2021

In [18]:
# initialize class To create dftier
cls_get_data = GetData()

#read query
str_filename = 'TiersTempStaticPool2020.sql'
str_local_path = f'./sql/{str_filename}'
cls_get_data.read_sql_script(
    str_local_path=str_local_path,
)
# pull data
conn = pyodbc.connect(
    'Driver={SQL Server};'
    'Server=electra;'
    'Database=pfsdb;'
    'Trusted_connection=yes;'
)
dftier = cls_get_data.pull_data_from_sql(
    conn=conn,
    bool_close_conn=True,
)
dftier

C:\Users\bhyde\AppData\Local\Temp\ipykernel_9920\3525508220.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(

  Tiers  Amount
0     A    2460
1    A1    2360
2     B    3560
3     C    2845
4     D    1263

In [19]:
str_filename = 'dftier2020.gzip'
# save data to gzip
dftier.to_parquet(f'./output/{str_filename}', compression = 'gzip')
# save memeory
del dftier

## PULL TIER DATA 2020 - CURRENT

In [20]:
# initialize class To create dftier
cls_get_data = GetData()

#read query
str_filename = 'TiersTempStaticPool2020-current.sql'
str_local_path = f'./sql/{str_filename}'
cls_get_data.read_sql_script(
    str_local_path=str_local_path,
)
# pull data
conn = pyodbc.connect(
    'Driver={SQL Server};'
    'Server=electra;'
    'Database=pfsdb;'
    'Trusted_connection=yes;'
)
dftier = cls_get_data.pull_data_from_sql(
    conn=conn,
    bool_close_conn=True,
)
dftier

C:\Users\bhyde\AppData\Local\Temp\ipykernel_9920\3525508220.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(

  Tiers  Amount
0     A   13851
1    A1   12196
2     B   36812
3     C   16854
4     D    9681

In [21]:
str_filename = 'dftier2020-current.gzip'
# save data to gzip
dftier.to_parquet(f'./output/{str_filename}', compression = 'gzip')
# save memeory
del dftier

## Gen Scores Table

In [4]:
# initialize class 
cls_get_data = GetData()

#read query
str_filename = 'GenScoresTable2024Revamp.sql'
str_local_path = f'./sql/{str_filename}'
cls_get_data.read_sql_script(
    str_local_path=str_local_path,
)
# pull data
conn = pyodbc.connect(
    'Driver={SQL Server};'
    'Server=electra;'
    'Database=pfsdb;'
    'Trusted_connection=yes;'
)
df = cls_get_data.pull_data_from_sql(
    conn=conn,
    bool_close_conn=True,
)
df

C:\Users\bhyde\AppData\Local\Temp\ipykernel_14076\3525508220.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(

,bigAccountId,bigDealerId,dtmStampCreation,dtmFunded,intTerm,intOpenBKType,strTier,AmtFinanced,OriginalInterestRate,MaxFico,Gen 11,Gen 12,Gen
0,7148408,2222,2023-10-02 10:46:59.683,2024-01-10,72,13.0,A,28369.14,19.74,542.0,0.055039,0.126122,Gen11
1,7171803,5948,2023-10-07 10:48:33.760,2024-01-22,72,7.0,B,23322.44,25.00,519.0,0.139163,0.311783,Gen11
2,7221580,6703,2023-10-16 09:32:06.757,2024-02-02,60,13.0,A1,21807.24,18.00,580.0,0.009565,0.025141,Gen11
3,7228265,6159,2023-10-18 14:25:13.170,2024-02-07,72,NaN,B,13281.06,26.74,574.0,0.120231,0.241734,Gen11
4,7254327,929,2023-10-20 15:26:45.807,2024-01-16,72,13.0,A,24286.22,19.99,537.0,0.040068,0.029945,Gen11
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12368,8030819,2408,2024-07-27 09:56:10.757,2024-07-29,72,NaN,D,21361.76,27.60,469.0,0.183660,0.353340,Gen11
12369,8031085,2602,2024-07-27 10:41:16.653,2024-07-29,72,7.0,B,23496.95,22.74,591.0,0.153108,NaN,Gen12
12370,8031357,8009,2024-07-27 11:31:37.137,2024-07-29,72,NaN,B,18222.88,22.28,504.0,0.077574,0.191827,Gen11
12371,8031596,4824,2024-07-27 12:09:55.253,2024-07-29,72,NaN,B,34892.26,23.59,552.0,0.080854,0.764019,Gen11
12372,8033867,4788,2024-07-29 09:40:56.557,2024-07-29,63,NaN,B,21506.86,22.82,NaN,0.079114,0.531994,Gen11

In [5]:
str_filename = 'genscores2024.gzip'
df.to_parquet(f'./output/{str_filename}', compression = 'gzip')
del df