In [1]:
import os
import pandas as pd
import numpy as np
import boto3
import datetime as dt
from tqdm import tqdm
import time

try:
    import xmltodict
except:
    ! pip install xmltodict

from parse_payload import PayloadToDataFrame

In [2]:
print(f'Latest run date: {dt.datetime.today()}')

Latest run date: 2025-02-04 22:32:22.647364

#### Constants

In [3]:
# project
str_project = os.getcwd().split('/')[4].replace('_','-')
print(f'Project: {str_project}')

# task
str_task = os.getcwd().split('/')[5]
print(f'Task: {str_task}')

# subtask
str_subtask = os.getcwd().split('/')[6]
print(f'Subtask: {str_subtask}')

# output
str_dirname_output = './output'

int_n_payloads = 10000

Project: 20241112-simple-model-test
Task: parse_all_apps
Subtask: 02_parse_payloads

#### Output directory

In [4]:
try:
    os.mkdir(str_dirname_output)
except FileExistsError:
    pass

#### Import data

In [5]:
str_filename = 'df_payloads.gzip'
str_uri = f's3://{str_project}/{str_task}/01_pull_data/{str_filename}'
df = pd.read_parquet(str_uri)

# show
df

/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/fsspec/registry.py:283: UserWarning: Your installed version of s3fs is very old and known to cause
severe performance issues, see also https://github.com/dask/dask/issues/10276

To fix, you should specify a lower version bound on s3fs, or
update the current installation.

  warnings.warn(s3_msg)

,FILE_NAME,ACCOUNTID,REQUEST_DATETIME,FILE_VALUE,REQUEST_JSON,RESPONSE_JSON,REQUEST_ID,RESPONSE_MODEL_NAME,RESPONSE_MODEL_VERSION,RN
0,8544966/x3QS-2025-01-06-14:38:36,8544966,2025-01-06 21:38:36+00:00,"{\n ""request"": {\n ""request_id"": ""85449668...","{\n ""request_id"": ""8544966884627"",\n ""rows"":...","{\n ""Response"": [\n {\n ""CounterOffer...",8544966884627,PRESTIGE-GEN-XII,V1,1
1,8506900/Z92q-2024-12-18-19:14:55,8506900,2024-12-19 02:14:55+00:00,"{\n ""request"": {\n ""request_id"": ""85069004...","{\n ""request_id"": ""8506900413352"",\n ""rows"":...","{\n ""Response"": [\n {\n ""CounterOffer...",8506900413352,PRESTIGE-GEN-XII,V1,1
2,8561362/4Ln9-2025-01-13-18:49:00,8561362,2025-01-14 01:49:00+00:00,"{\n ""request"": {\n ""request_id"": ""85613627...","{\n ""request_id"": ""85613627021"",\n ""rows"": [...","{\n ""Response"": [\n {\n ""CounterOffer...",85613627021,PRESTIGE-GEN-XII,V1,1
3,8474876/Nsi8-2024-12-09-21:37:38,8474876,2024-12-10 04:37:38+00:00,"{\n ""request"": {\n ""request_id"": ""84748766...","{\n ""request_id"": ""8474876689953"",\n ""rows"":...","{\n ""Response"": [\n {\n ""CounterOffer...",8474876689953,PRESTIGE-GEN-XII,V1,1
4,8465170/c69Z-2024-12-05-17:24:35,8465170,2024-12-06 00:24:35+00:00,"{\n ""request"": {\n ""request_id"": ""84651705...","{\n ""request_id"": ""8465170579834"",\n ""rows"":...","{\n ""Response"": [\n {\n ""CounterOffer...",8465170579834,PRESTIGE-GEN-XII,V1,1
...,...,...,...,...,...,...,...,...,...,...
88657,8469056/3lgV-2024-12-06-21:30:33,8469056,2024-12-07 04:30:33+00:00,"{\n ""request"": {\n ""request_id"": ""84690563...","{\n ""request_id"": ""8469056369541"",\n ""rows"":...","{\n ""Response"": [\n {\n ""CounterOffer...",8469056369541,PRESTIGE-GEN-XII,V1,1
88658,8560281/i571-2025-01-11-22:30:42,8560281,2025-01-12 05:30:42+00:00,"{\n ""request"": {\n ""request_id"": ""85602816...","{\n ""request_id"": ""8560281603978"",\n ""rows"":...","{\n ""Response"": [\n {\n ""CounterOffer...",8560281603978,PRESTIGE-GEN-XII,V1,1
88659,8506082/Gy54-2024-12-18-15:59:13,8506082,2024-12-18 22:59:13+00:00,"{\n ""request"": {\n ""request_id"": ""85060823...","{\n ""request_id"": ""8506082398019"",\n ""rows"":...","{\n ""Response"": [\n {\n ""CounterOffer...",8506082398019,PRESTIGE-GEN-XII,V1,1
88660,8554968/8FHE-2025-01-09-23:57:37,8554968,2025-01-10 06:57:37+00:00,"{\n ""request"": {\n ""request_id"": ""85549685...","{\n ""request_id"": ""8554968590809"",\n ""rows"":...","{\n ""Response"": [\n {\n ""CounterOffer...",8554968590809,PRESTIGE-GEN-XII,V1,1
88661,8514463/09Ks-2024-12-21-17:15:52,8514463,2024-12-22 00:15:52+00:00,"{\n ""request"": {\n ""request_id"": ""85144639...","{\n ""request_id"": ""8514463925259"",\n ""rows"":...","{\n ""Response"": [\n {\n ""CounterOffer...",8514463925259,PRESTIGE-GEN-XII,V1,1

#### Get sample

In [6]:
# get sample
df = df.sample(
    n=int_n_payloads,
    random_state=42,
)

# show
df

,FILE_NAME,ACCOUNTID,REQUEST_DATETIME,FILE_VALUE,REQUEST_JSON,RESPONSE_JSON,REQUEST_ID,RESPONSE_MODEL_NAME,RESPONSE_MODEL_VERSION,RN
70891,8439574/i1aJ-2024-12-03-01:40:04,8439574,2024-12-03 08:40:04+00:00,"{\n ""request"": {\n ""request_id"": ""84395748...","{\n ""request_id"": ""8439574819805"",\n ""rows"":...","{\n ""Response"": [\n {\n ""CounterOffer...",8439574819805,PRESTIGE-GEN-XII,V1,1
29223,8564134/WCm0-2025-01-14-00:37:54,8564134,2025-01-14 07:37:54+00:00,"{\n ""request"": {\n ""request_id"": ""85641345...","{\n ""request_id"": ""8564134535361"",\n ""rows"":...","{\n ""Response"": [\n {\n ""CounterOffer...",8564134535361,PRESTIGE-GEN-XII,V1,1
74094,8489707/Hszr-2024-12-14-23:08:17,8489707,2024-12-15 06:08:17+00:00,"{\n ""request"": {\n ""request_id"": ""84897077...","{\n ""request_id"": ""8489707737695"",\n ""rows"":...","{\n ""Response"": [\n {\n ""CounterOffer...",8489707737695,PRESTIGE-GEN-XII,V1,1
43647,8554640/tyE2-2025-01-09-22:31:51,8554640,2025-01-10 05:31:51+00:00,"{\n ""request"": {\n ""request_id"": ""85546409...","{\n ""request_id"": ""8554640976543"",\n ""rows"":...","{\n ""Response"": [\n {\n ""CounterOffer...",8554640976543,PRESTIGE-GEN-XII,V1,1
16802,8425624/jJ6Y-2024-11-26-15:41:51,8425624,2024-11-26 22:41:51+00:00,"{\n ""request"": {\n ""request_id"": ""84256246...","{\n ""request_id"": ""8425624613996"",\n ""rows"":...","{\n ""Response"": [\n {\n ""CounterOffer...",8425624613996,PRESTIGE-GEN-XII,V1,1
...,...,...,...,...,...,...,...,...,...,...
44316,8528424/4fPr-2024-12-28-20:56:45,8528424,2024-12-29 03:56:45+00:00,"{\n ""request"": {\n ""request_id"": ""85284247...","{\n ""request_id"": ""8528424729288"",\n ""rows"":...","{\n ""Response"": [\n {\n ""CounterOffer...",8528424729288,PRESTIGE-GEN-XII,V1,1
61479,8574699/63fa-2025-01-17-19:42:42,8574699,2025-01-18 02:42:42+00:00,"{\n ""request"": {\n ""request_id"": ""85746994...","{\n ""request_id"": ""8574699430507"",\n ""rows"":...","{\n ""Response"": [\n {\n ""CounterOffer...",8574699430507,PRESTIGE-GEN-XII,V1,1
27823,8528513/9KQ3-2024-12-28-21:14:24,8528513,2024-12-29 04:14:24+00:00,"{\n ""request"": {\n ""request_id"": ""85285131...","{\n ""request_id"": ""8528513172500"",\n ""rows"":...","{\n ""Response"": [\n {\n ""CounterOffer...",8528513172500,PRESTIGE-GEN-XII,V1,1
65772,8506878/Plr6-2024-12-18-19:10:09,8506878,2024-12-19 02:10:09+00:00,"{\n ""request"": {\n ""request_id"": ""85068784...","{\n ""request_id"": ""8506878435714"",\n ""rows"":...","{\n ""Response"": [\n {\n ""CounterOffer...",8506878435714,PRESTIGE-GEN-XII,V1,1
22135,8436878/0qgd-2024-12-02-02:36:31,8436878,2024-12-02 09:36:31+00:00,"{\n ""request"": {\n ""request_id"": ""84368788...","{\n ""request_id"": ""8436878896797"",\n ""rows"":...","{\n ""Response"": [\n {\n ""CounterOffer...",8436878896797,PRESTIGE-GEN-XII,V1,1

#### Iterate and parse

In [7]:
list_df_tmp = []
a = 0
for str_request in tqdm(df['REQUEST_JSON']):
    # replace NaN
    time_start = time.perf_counter()
    
    # init
    cls_parse_payload = PayloadToDataFrame()

    # get data
    df_tmp = cls_parse_payload.get_data(
        str_request=str_request,
    )

    # make copy
    df_tmp = df_tmp.copy()

    # assign
    df_tmp['ACCOUNTID'] = df['ACCOUNTID'].iloc[a]
    df_tmp['REQUEST_DATETIME'] = df['REQUEST_DATETIME'].iloc[a]
    df_tmp['RESPONSE_MODEL_NAME'] = df['RESPONSE_MODEL_NAME'].iloc[a]
    df_tmp['FILE_NAME'] = df['FILE_NAME'].iloc[a]
    
    # get number of rows
    int_nrows = df_tmp.shape[0]

    # logic
    if int_nrows == 1:
        list_bitdebtor = [1]
    else:
        list_bitdebtor = [1, 0]

    # assign
    df_tmp['BITDEBTOR'] = list_bitdebtor

    # reorder
    list_cols_id = [
        'ACCOUNTID',
        'REQUEST_DATETIME',
        'RESPONSE_MODEL_NAME',
        'FILE_NAME',
        'BITDEBTOR',
    ]
    list_cols = [col for col in df_tmp.columns if col not in list_cols_id]
    list_cols = list_cols_id + list_cols
    df_tmp = df_tmp[list_cols].copy()

    # end time
    time_end = time.perf_counter()
    # sec
    flt_sec = time_end - time_start

    # assign
    df_tmp['flt_sec'] = flt_sec

    # append
    list_df_tmp.append(df_tmp)
    # increase counter
    a += 1

# save memory
del df

100%|██████████| 10000/10000 [24:15<00:00,  6.87it/s]

#### Create df

In [8]:
%%time

df = pd.concat(list_df_tmp)
# save memory
del list_df_tmp
# lower
list_cols = [col.lower() for col in df.columns]
df.columns = list_cols

# show
df

CPU times: user 2min 13s, sys: 2.05 s, total: 2min 15s
Wall time: 2min 15s

,accountid,request_datetime,response_model_name,file_name,bitdebtor,uniqueid__app,bigaccountid__app,bigdebtorid__app,bitdebtor__app,dealerstate__app,...,linkf206__tu,linkf207__tu,linkf208__tu,linkf209__tu,linkf210__tu,linkf211__tu,linkf212__tu,linkf213__tu,totalincome__app,totaldebt__app
0,8439574,2024-12-03 08:40:04+00:00,PRESTIGE-GEN-XII,8439574/i1aJ-2024-12-03-01:40:04,1,8439574104198171,8439574,10419817,1,Illinois,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,8564134,2025-01-14 07:37:54+00:00,PRESTIGE-GEN-XII,8564134/WCm0-2025-01-14-00:37:54,1,8564134105623331,8564134,10562333,1,Utah,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
0,8489707,2024-12-15 06:08:17+00:00,PRESTIGE-GEN-XII,8489707/Hszr-2024-12-14-23:08:17,1,8489707104756971,8489707,10475697,1,California,...,0.0,235.0,0.0,4.0,0.0,1005.0,0.0,0.48,NaN,NaN
0,8554640,2025-01-10 05:31:51+00:00,PRESTIGE-GEN-XII,8554640/tyE2-2025-01-09-22:31:51,1,8554640105510811,8554640,10551081,1,Indiana,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,8425624,2024-11-26 22:41:51+00:00,PRESTIGE-GEN-XII,8425624/jJ6Y-2024-11-26-15:41:51,1,8425624104031221,8425624,10403122,1,Wisconsin,...,0.0,0.0,0.0,0.0,7.0,0.0,1166.0,0.95,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,8574699,2025-01-18 02:42:42+00:00,PRESTIGE-GEN-XII,8574699/63fa-2025-01-17-19:42:42,1,8574699105747531,8574699,10574753,1,Oklahoma,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,5560.0,2742.65
0,8574699,2025-01-18 02:42:42+00:00,PRESTIGE-GEN-XII,8574699/63fa-2025-01-17-19:42:42,0,8574699105747540,8574699,10574754,0,Oklahoma,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,5560.0,2742.65
0,8528513,2024-12-29 04:14:24+00:00,PRESTIGE-GEN-XII,8528513/9KQ3-2024-12-28-21:14:24,1,8528513105200701,8528513,10520070,1,Maryland,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
0,8506878,2024-12-19 02:10:09+00:00,PRESTIGE-GEN-XII,8506878/Plr6-2024-12-18-19:10:09,1,8506878104941931,8506878,10494193,1,Ohio,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,8436878,2024-12-02 09:36:31+00:00,PRESTIGE-GEN-XII,8436878/0qgd-2024-12-02-02:36:31,1,8436878104166651,8436878,10416665,1,Oregon,...,0.0,0.0,0.0,0.0,2.0,0.0,228.0,1.62,NaN,NaN

#### Convert non-numeric to string

In [9]:
for col in tqdm(df.columns):
    # get dtype
    str_dtype = df[col].dtype
    # logic
    if str_dtype not in ['int64','float64']:
        # convert to str
        df[col] = df[col].astype(str)
    else:
        pass

100%|██████████| 2603/2603 [00:00<00:00, 2917.56it/s]

#### Write to s3

In [10]:
%%time

str_filename = 'df.gzip'
str_uri = f's3://{str_project}/{str_task}/{str_subtask}/{str_filename}'
df.to_parquet(str_uri, compression='gzip')

CPU times: user 6.17 s, sys: 39.7 ms, total: 6.21 s
Wall time: 6.83 s